### ISSUE TITLE
Incorrect Bdr/Face Transformations

### ISSUE THREAD

**Issue by mlstowell** [mfem/mfem#1000]
The comments at lines 
https://github.com/mfem/mfem/blob/40795c21c6a70a381395265f7069afc83af51f99/mesh/mesh.cpp#L464
and
https://github.com/mfem/mfem/blob/40795c21c6a70a381395265f7069afc83af51f99/mesh/mesh.cpp#L527
are not actually correct and, consequently, the calls to `GetVectorValues` produce incorrect results.  The trouble is that the `Nodes` grid function is evaluated in the element `Transformation::ElementNo` but we don't know which element this is.  We should set this to be the `elem_id` identified earlier in these methods but this will overwrite the current `ElementNo`.  Since the `Mesh::Transformation` data member is not documented we cannot be sure if we need to preserve its contents or not.

I know this is a very simple thing to fix but I want to be sure that we can treat `Mesh::Transformation` as a temporary variable.

**Comment by v-dobrev** [comment]
@mlstowell, you are right -- this is a bug in `Mesh::GetFaceTransformation` that was copied to `Mesh::GetBdrElementTransformation`.

It is interesting that the original use case (DG methods on periodic meshes) actually works correctly since `Mesh::GetFaceTransformation` is called from `Mesh::GetFaceElementTransformations` where `Mesh::Transformation::ElementNo` already has the correct value.

To fix this, it is probably best to replace `Mesh::Transformation` with `Mesh::FaceElemTr.Loc1.Transf` which is already used by these methods as a temporary. We can just set its `ElementNo` entry to `elem_id` -- the rest of the structure is not needed/used for the case of scalar FEs which is what the FEs used by `Nodes` should be.

I wonder how this implementation of `Mesh::GetBdrElementTransformation` seemed to actually work fine when introduced in #811. Buggy code finds mysterious ways to work correctly. 😁

**Comment by mlstowell** [comment]
Sounds good.  Thanks, @v-dobrev !
