### ISSUE TITLE
mfem@develop build via spack/xsdk breaks.

### ISSUE THREAD

**Issue by balay** [mfem/mfem#1024]
This build is for:
-- linux-centos7-x86_64 / intel@18.0.2 --------------------------
with:
      cflags:  "-O3 -fp-model fast -xMIC-AVX512"

Note: this is from xsdk testing for xsdk-0.5.0 release preparation

[spack-build-out.txt](https://github.com/mfem/mfem/files/3461981/spack-build-out.txt)

**Comment by v-dobrev** [comment]
The spack mfem package has not been updated for the latest mfem release (4.0) and, in particular, `mfem@develop` is broken as of now. I think this is an issue only when `cxxflags` is not empty (I assume `cxxflags` is initialized from `cflags` if the former is not explicitly given). This fix is not too hard -- I think we just need to add the c++11 flag (e.g. `-std=c++11`) which is now required.

We are planning on updating the mfem spack package soon. There is already a PR in spack (https://github.com/spack/spack/pull/11880) which adds the new version but does not address the above issue at the moment.

**Comment by balay** [comment]
@v-dobrev Thanks for looking into this.

I'm interested in xsdk@0.5.0 - so whatever mfem version you [i.e @tzanio ] is targeting for this  release is the one I should be checking on. If that's 4.0 - I'll use that in my xsdk testing.

**Comment by tzanio** [comment]
@balay, if that breaks your testing please use 4.0 for now.

Our intention is to have a new release/tag for xsdk-0.5 which will include support for Sundials 5.0 and updated Spack package.

cc: @acfisher

**Comment by balay** [comment]
@v-dobrev, If I understand the comments - 4.0 version also has this issue. So perhaps the following fix?

This works for me with mfem@develop on this build.

```
bash-4.2$ git diff var/spack/repos/builtin/packages/mfem/package.py
diff --git a/var/spack/repos/builtin/packages/mfem/package.py b/var/spack/repos/builtin/packages/mfem/package.py
index 16a977d..767e059 100644
--- a/var/spack/repos/builtin/packages/mfem/package.py
+++ b/var/spack/repos/builtin/packages/mfem/package.py
@@ -262,6 +262,9 @@ class Mfem(Package):
             'MFEM_USE_CONDUIT=%s' % yes_no('+conduit')]
 
         cxxflags = spec.compiler_flags['cxxflags']
+        if self.spec.satisfies('@4.0:'):
+            cxxflags.append(self.compiler.cxx11_flag)
+
         if cxxflags:
             # The cxxflags are set by the spack c++ compiler wrapper. We also
             # set CXXFLAGS explicitly, for clarity, and to properly export the

```
@tzanio,  will this new release with Sundials 5.0 be off mfem master brach? If so - I'll continue to use mfem@develop - until a branch or  release/tag for this new mfem version is created.

**Comment by tzanio** [comment]
> @tzanio, will this new release with Sundials 5.0 be off mfem master branch? 

Yes

**Comment by acfisher** [comment]
@balay Yes we will need that change from 4.0 on since C++11 is needed after that.  Do you want to add that change to your spack xsdk branch for now.  I plan to hammer on the mfem spack build this week and I can get that change pulled in with any other changes.

**Comment by balay** [comment]
Yeah - I have this change in `balay/xsdk-0.5.0` branch at https://github.com/spack/spack/commits/5c952a15a9a47c05f0860733b30a5a08dba23146

[I'll be rebasing this branch as needed]

**Comment by goxberry** [comment]
@acfisher I think most of the work for mfem 4.0 on Spack is pretty trivial for someone who knows the version requirements for dependencies. As @v-dobrev mentioned earlier in the thread, I started a PR for mfem 4.0 in spack a while ago at https://github.com/spack/spack/pull/11880.

To really get a Spack package "right" requires knowing what versions of dependencies are required; I requested this information in https://github.com/mfem/mfem/issues/989 and have done some of the detective work myself, but more work is needed, and that information needs to be somewhere in the mfem documentation (see also https://github.com/mfem/mfem/pull/990).

As far as I know, the following other issues germane to packaging are:

- https://github.com/mfem/mfem/issues/983 from @jandrej, which should probably be documented as a `conflict` in the spack formula when configuring with hypre 2.16.0 and SuperLU-Dist 6.1.1 and/or backported to maintenance versions of mfem for use in spack
- https://github.com/mfem/mfem/issues/1002, which notes that linking will fail for certain combinations of operating systems and compilers (e.g., macOS + Intel). One possible fix for the issue in mfem is in https://github.com/mfem/mfem/pull/1006. As for the Spack package, I think it would be worth noting at least once architecture/OS/compiler tuple where linking fails due to the assumed Fortran name mangling convention so that other power users can add similar conflicts as they encounter them. An exhaustive listing is probably impractical, but at least one example would probably help other users reduce the amount of time required to diagnose this bug in the event that they encounter it.

**Comment by acfisher** [comment]
Yes, unfortunately it's a moving target, We are working with other teams to resolve the conflicts.  I'll grab onto your spack PR and work in there.
