### ISSUE TITLE
Cannot use gmsh files with provided examples

### ISSUE THREAD

**Issue by CallMeJohnSeven** [mfem/mfem#1061]
I am using gmsh-4.1.0-Windows64 to generate a tetrahedral mesh for a sphere using just the default options in gmsh, but I am getting the following error. I am exporting the msh format to ASCII version 2.2. 

MFEM abort: Non-positive element attribute in Gmsh mesh!
 ... in function: void mfem::Mesh::ReadGmshMesh(std::istream&)
 ... in file: mesh/mesh_readers.cpp:1172

What settings would I need to create a mesh that doesn't get this error? I can provide the file if people are interested.

**Comment by mlstowell** [comment]
Hi, @CallMeJohnSeven ,

The issue here is that Gmsh allows tags to be numbered with integers starting from 0 while MFEM requires tag numbering to start at 1.  I don't use Gmsh myself so I don't know how to set these tag numbers but it may be related to the "physical group" number associated with the spherical volume.

Best wishes,
Mark

**Comment by pazner** [comment]
To follow up on @mlstowell's remark, gmsh will by default assign a "physical tag" of zero to your elements. You will need to specify a nonzero physical tag in your `.geo` file by adding a line like
```
Physical Volume(1) = {vol_id};
```
where `vol_id` is the number associated with the volume of your sphere (it should correspond to a line like `Volume(vol_id) = {...};` in your `.geo` file.

**Comment by CallMeJohnSeven** [comment]
@mlstowell @pazner 
Thanks for the help. That was able to resolve my issue.
