### ISSUE TITLE
Getting vertex coordinates from high-order meshes

### ISSUE THREAD

**Issue by junkudo** [mfem/mfem#1062]
Hey,

I'm trying to query the coordinates given a vertex id for a mesh with high-order coordinates.  Is there a straight forward way to do this?  It seems like currently I'd need to find an element attached to the vertex, get the integration point corresponding to that vertex, and then evaluate that point with the grid function that represents the high-order coordinates.

Thanks!
Jun

**Comment by tzanio** [comment]
Are you interested in only the vertices or all the high-order nodes? In the latter case, you can just project the function (x,y,z) on the `FiniteElementSpace` for the nodes...

**Comment by junkudo** [comment]
I don't remember exactly why I wanted this anymore but I think I wanted the coordinates at a given vertex and not at all that high order node points.

**Comment by kennyweiss** [comment]
@junkudo -- I think the following should work for both low order or high order meshes:

```cpp
double* coords[3];
mesh->GetNode( vertex_id, coords);
```

**Comment by junkudo** [comment]
It certainly looks like it will work. Thanks. The semantics are a little
confusing here to me. I was under the impression the 'GetNodes' interface
takes in a node id and not a vertex id.

**Comment by tzanio** [comment]
> The semantics are a little confusing here to me. I was under the impression the 'GetNodes' interface takes in a node id and not a vertex id.

You are correct -- `GetNodes` returns the coordinates of the i'th node (for high-order meshes) or i'th vertex (for low-order meshes), see https://github.com/mfem/mfem/blob/master/mesh/mesh.cpp#L5786-L5803.

However, the vertices are numbered first in the high-order `Nodes`, so the same function will continue to work :).

Since you don't need this anymore I will close the issue now. Feel free to reopen if you have any further questions.

**Comment by junkudo** [comment]
Oh I understand why that happens to work.  Thank @tzanio @kennyweiss !
