### ISSUE TITLE
Using serial mesh with parallel solvers like Hypre's BoomerAMG

### ISSUE THREAD

**Issue by QikLiang** [mfem/mfem#1069]
Hi all,
For my application (electrostatics), I have experimentally determined BoomerAMG to produce the fasted performance on solving the linear system (which seems to be the consensus). All the examples that I have encountered requires using a `ParMesh` when using any of the Hypre solvers, but that is not feasible for me because
1. `ParMesh` does not support refining a 3D non-conforming anisotropic mesh
2. I intend to run multiple instances of my solver in parallel, so the additional parallelism used by `ParMesh` would only add unnecessary overhead

Is there a way to use a serial mesh with BoomerAMG? Looking through the documentation,
`HypreParMatrix (MPI_Comm comm, HYPRE_Int *row_starts, HYPRE_Int *col_starts, SparseMatrix *a)` seems to be my best option. Guidance will be appreciated if anyone knows how to work around this limitation.

**Comment by mlstowell** [comment]
Hi, @QikLiang ,

The class `HypreParVector` inherits from `Vector` so, at least in theory, you could use `HypreParVector` anywhere that requires a `Vector`.  The primary danger should be methods that resize vectors because they are unlikely to update `HypreParVector`s properly.  You have at least two options.  First, you could use `Vector`s for the `x` and `b` arguments to `BilinearForm::FormLinearSystem` and `HypreParVector`s for the `X` and `B` arguments.  This might work except for the resizing of these vectors that happens within this method.  A safer option might be to use `Vector`s for all four arguments to `BilinearForm::FormLinearSystem` and then create `HypreParVector`s which are only wrappers around the data arrays stored in `X` and `B`.  These wrappers can then be passed to the `Mult` method of `BoomerAMG`.  To form these wrappers you use the following constructor:
https://github.com/mfem/mfem/blob/3f1adff17d8865061ef643cabb11d7a49c5fd53c/linalg/hypre.hpp#L105
This constructor will require some of the same arguments that will be needed to create the `HypreParMatrix`.

Best wishes,
Mark

**Comment by jakubcerveny** [comment]
Hi @QikLiang, I'm working on the parallel anisotropic refinement feature right now. It's kind of tricky. But it's good to hear there is demand for this. I'll try my best.

**Comment by QikLiang** [comment]
@mlstowell 
I have confirmed that passing `HypreparVector` into `BilinearForm::FormLinearSystem` indeed results in a crash (not immediately, but in `HyprePCG::Mult`). I was able to get it working by first using `Vector` for`BilinearForm::FormLinearSystem` and the converting them into `HypreparVector` for `HyprePCG::Mult`. For others interested, the following is a cleaned up version of what worked for me:

```
GridFunction *x = SetupBoundaryCondition();
GridFunction *b = SetupRHS();

SparseMatrix A;

Vector X(fes->GetVDim());
Vector B(fes->GetVDim());

biliform->FormLinearSystem(ess_bdr_tdofs_, *x, *b, A, X, B);

// convert Vector into HypreParVector
int x_row_idx[2] = {0, X.Size()};
int b_row_idx[2] = {0, B.Size()};
HypreParVector hypre_x(MPI_COMM_SELF, X.Size(), X.GetData(), x_row_idx);
HypreParVector hypre_b(MPI_COMM_SELF, B.Size(), B.GetData(), b_row_idx);

const int mat_size = A.Height();
int mat_row_idx[2] = {0, mat_size};
/* This constructor assumes input SparseMatrix is always square,
* which should be true for stiffness matrices */
HypreParMatrix hypre_A(MPI_COMM_SELF, mat_size, mat_row_idx, &A);
HypreBoomerAMG precond(hypre_A);

HyprePCG solver(hypre_A);
solver.SetTol(relative_tolerance);
solver.SetMaxIter(lin_sol_max_it);
solver.SetPreconditioner(precond);
// Hypre solvers print directly to std::cout instead of
// mfem::out, so print level needs to be adjusted with out.IsEnabled
solver.SetPrintLevel(out.IsEnabled() ? print_level : 0);

solver.Mult(hypre_b, hypre_x);

biliform->RecoverFEMSolution(hypre_x, *b, *x);
```



@jakubcerveny 
Thank you for your efforts. As someone who has only recently been learning about finite element, not knowing what combinations of commands would give an error before running it has been a major source of frustration. In addition to removing a technical limitation, adding this feature would also make it easier for people who are new to the library or finite element in general.
