### ISSUE TITLE
Update GridFunction and GridFunctionCoefficient

### ISSUE THREAD

**Issue by fanronghong** [mfem/mfem#1084]
Hi all,

I want to implement below functionality. But I don't find any solution. Thanks in advance!

```
#include "mfem.hpp"
using namespace mfem;
using namespace std;

int main()
{
    Mesh mesh(10, 10, Element::TRIANGLE, 1.0, 1.0, 1.0);

    H1_FECollection h1_fec(1, 1);
    FiniteElementSpace h1_space(&mesh, &h1_fec);

    GridFunction u_gf(&h1_space);
    ConstantCoefficient one(1.0);
    u_gf.ProjectCoefficient(one);
    
    GridFunctionCoefficient u_coeff(&u_gf);
    
    int max_iter = 10;
    int iter = 1;
    while (iter < max_iter)
    {
        // After some computing, I get a new u_gf.
        // Now I want to compute L2 error norm of new u_gf and u_coeff
        u_gf.ComputeL2Error(u_coeff); // always 0.0

        // And then I want to update the u_coeff
        u_coeff.SetGridFunction(&u_gf); // here the u_gf is new
    }    
    // But the u_gf are always binding with u_coeff
}
```

**Comment by mlstowell** [comment]
Hi, @fanronghong ,
A `GridFunctionCoefficient` is just a wrapper around a `GridFunction` object that allows it to easily be evaluated at points in physical space.  Consequently, as soon as you update `u_gf` the corresponding coefficient will produce different values.  I believe you will need two separate `GridFunction` objects so that you can compare values from the updated one with the older one.
Best wishes,
Mark

**Comment by fanronghong** [comment]
Thanks @mlstowell ,

Yes, I just need two `GridFunction`s.
