### ISSUE TITLE
Interior face integrator

### ISSUE THREAD

**Issue by fanronghong** [mfem/mfem#1096]
Hi all,

I want to implement a `LinearFormIntegrator` only on selected interior (not boundary) faces (for 3D mesh).

For `BilinearForm blf`, I can 
```
blf.AddDomainIntegrator(),
blf.AddInteriorFaceIntegrator(),
blf.AddBdrFaceIntegrator(),
```

But for `LinearForm lf`, it only has
```
lf.AddDomainIntegrator(),
lf.AddBoundaryIntegrator(),
lf.AddBdrFaceIntegrator().
```
There is no `lf.AddInteriorFaceIntegrator`, right?

Thanks in advance!

**Comment by vikramsg** [comment]
Yes, LinearForm does not have an InteriorFaceIntegrator. You will have to implement it yourself.

**Comment by fanronghong** [comment]
Thanks @vikramsg for your reply,
Did you implement this before? Or can you give some suggestions? I just don't know how and where to start.

**Comment by vikramsg** [comment]
Yes, I did implement it some time ago. Essentially you need to copy what is done for the BoundaryFaceIntegrator in linearform.cpp/hpp and that should be good. However, in lininteg.cpp it will be slightly different since the integrator itself will require faceElementTransformation for both right and left hand side unlike the boundary integrator which requires this on only one side.

**Comment by fanronghong** [comment]
Hi @vikramsg ,

Sorry to disturb you again. Which MFEM edition do you use? I could not find `BoundaryFaceIntegrator` in linearform.cpp/hpp. And could you please provide more info about implementing? Thanks a lot.

**Comment by vikramsg** [comment]
You can find the function
```
void AddBdrFaceIntegrator(LinearFormIntegrator *lfi,
                             Array<int> &bdr_attr_marker);
```
in ```linearform.hpp```.

It can be taken as a template for how you should implement ```InteriorFaceIntegrator```. 

Regarding implementation the integrator itself, you can get ideas from ```bilinteg.cpp``` such as say ```void DGDiffusionIntegrator::AssembleFaceMatrix(
   const FiniteElement &el1, const FiniteElement &el2,
   FaceElementTransformations &Trans, DenseMatrix &elmat)```.

What you need to do is replace the ```DenseMatrix &elmat``` with ```Vector &elvec```, since finally you are going to be sending back a vector of values. Of course the linear integration itself will depend on what you are trying to do.

**Comment by fanronghong** [comment]
Thanks @vikramsg a lot.

I think I understand your detailed explanation, but I must take some time to try it. Thanks again.

**Comment by fanronghong** [comment]
Hi @vikramsg ,

Sorry to disturb you again. I finished by your explanation, but the result is not right. So I opened another issue [Face Integral](https://github.com/mfem/mfem/issues/1122#issue-509136700). Could you please take a look if you have some time?
