### ISSUE TITLE
Convergence on Magnetostatics with Nedelec Elements

### ISSUE THREAD

**Issue by garobed1** [mfem/mfem#1120]
Hello,

I have been trying to perform a convergence test for a magnetostatics problem with a manufactured solution, but I have not been achieving appropriate convergence with respect to the order of Nedelec element I am using. The A field solution fails to converge, and even produces more error for more dense meshes. The B field solution, on the other hand, produces no better than 1st order convergence regardless of element order. I solve for the A and B fields in the same way as the Tesla miniapp and compare them to the manufactured solution. The problem is as such:

The domain is a 3D 'unit square', centered on the origin, with some thickness in Z. The half that is negative in y is'Region 1', and the half that is positive in y is 'Region 2', each having a separate constant permeability mu1 and mu2. Any properties associated with the regions are denoted by a 1 or a 2.

The magnetostatic equation, Curl ((1/mu)Curl A) = J

The manufactured solution is A1 = (0 0 y^2), A2 = (0 0 -y^2). As a result, B1 = (2y 0 0), B2 = (-2y 0 0), J1 = (0 0 -2/mu1), J2 = (0 0 2/mu2).

My domain is a cuboid with x y z side lengths of (1, 1, .1), for which I generate a structured tetrahedral mesh using the Make3D method. I fix the number of elements in x and z directions to 20 and 5, respectively, and refine only in the direction of y such that there are 4, 8, 16, 32, 64, and 128 elements in that direction.

As in the Tesla miniapp, I create two bilinear forms using a Nedelec FE space, one with a `CurlCurlIntegrator` and one with an `hCurlMassInteg` (for computing the dual of J). I define the same `curl_` operator as in Tesla as well. I solve for A on the domain, then apply the curl operator to get B.

I impose the tangential components of the analytic solution for A on every face of the boundary. Therefore, the 'thin' faces match the analytic solution for A. I impose permeability and J on the domain using function coefficients. I solve the resulting system using GMRES, and compute the L2 error norms for both A and B.

I checked for convergence on the domain as I doubled the number of elements, using orders 1, 2, and 3 elements. The accuracy of A stagnates with refinement. B, on the other hand, shows first order convergence for all element orders, and does not improve as expected for orders 2 and 3.

I can provide Paraview visualizations for this problem as well as L2 error data. I would appreciate if you could shed some light on why this issue might arise.

I had another issue when I tried using a mesh with 1 element thickness in the z direction (as suggested by @mlstowell in https://github.com/mfem/mfem/issues/1089), but this produced large spikes in B magnitude only at the interface, causing lack of convergence. This does not occur with more elements in z, but the problem is essentially 2D, so I'm not sure why this would happen.

**Comment by mlstowell** [comment]
Hi, @garobed1 ,

Are you also using the `DivergenceFreeProjector` to prepare J?  If not, this may be the issue.  Because the curl curl operator is not full rank is it crucial that the right hand side of the linear system be in the range of the curl curl operator otherwise a solution may not exist.  In such cases the solver will stall as you are seeing.

Another smaller issue that I see is due to the discontinuity in J.  When you project your exact J onto a Nedelec `GridFunction` which value do you choose along the surface of discontinuity?  Choosing one value or the other will lead to different answers and either choice may reduce the accuracy near the discontinuity.  There are a few different ways to handle this if it becomes an issue.  The simplest is to use the average of the two values when evaluating very near the interface.  A more accurate option is to compute the dual of J using a `ParLinearForm` and then solve for J using a Nedelec mass matrix (then use the `DivergenceFreeProjector` and finally multiply by the Nedelec mass matrix again).  This last scheme essentially computes a weighted average for the values of J on the discontinuity and is more robust when using irregular meshes.

Best wishes,
Mark

**Comment by garobed1** [comment]
Hello,

Thanks for the response. I should clarify. The solver does not stall, it will converge to an answer with the boundary conditions I describe. The problem is in convergence of accuracy through h-refinement. That being said, I am using the `DivergenceFreeProjector` to prepare J as well.

Regarding discontinuity in J, I have been setting its value at the interface to 0. This is the average for two materials with the same permeability. I will try averaging them for different permeabilities, this may help resolve another problem. However, the accuracy convergence tests I have been performing so far have been using the same permeability for both regions, so there still lies the issue of lack of accuracy convergence through h-refinement.

As an example, I performed a test with 2nd order Nedelec elements, both regions with a permeability of 1. For the number of tetrahedral elements blocks in the y direction going from 16 to 32 (essentially doubling the number of elements), I see the L2 error norms for A and B go from (A: 0.00329334, B: 0.000475185) to (A: 0.00365934, B: 0.000211212). The accuracy of A essentially stagnates while the accuracy of B converges at approximately 1st order, despite using 2nd order Nedelec elements. Orders 1 and 3 Nedelec elements show this same pattern. I've attached a line plot comparing the A and B solutions to the analytic solutions parallel to the y-axis at an arbitrary point in the domain, as an example for a typical solution (sol_Z refers to A, solb_magnitude refers to B).
![o2y16](https://user-images.githubusercontent.com/43361579/67038928-562a3480-f0ee-11e9-915e-81a4c780f6a0.png)

I believe there may be some issue with my application of Dirichlet BC's on A, here are plots of the solution at a line on the left and right boundaries of the domain (x = 0,1).

x = 0:
![leftbound](https://user-images.githubusercontent.com/43361579/67039339-1dd72600-f0ef-11e9-90f3-5903d070c45c.png)

x = 1:
![rightbound](https://user-images.githubusercontent.com/43361579/67039345-229bda00-f0ef-11e9-82c7-1c767d0ab48f.png)

The A solution should be exact for both, but somehow it is poor for one and exact for the other. I'm confused as to why this could be the case.

**Comment by mlstowell** [comment]
Hi, @garobed1 ,

I was able to confirm the lack of convergence that you're seeing.  I used a modified version of the `tesla` mini app on a hexahedral mesh.  The following plot shows the L2 error in A for basis function orders 1 and 2 for a sequence of meshes as you described.

![image](https://user-images.githubusercontent.com/6109571/67122561-f04bb480-f1a2-11e9-89a5-8ed6efcb9a61.png)

I've got one or two ideas about what might be causing this but I'll need to investigate further.  Thanks for pointing this out.

Best wishes,
Mark

**Comment by garobed1** [comment]
Thank you for looking into it. I'll respond in kind with my own convergence plot for A, which seems to be a little different. For 4, 8, 16 elements, some expected convergence shows for order 1, but all other results seem inconsistent with expectations.
![conv](https://user-images.githubusercontent.com/43361579/67126348-d3c07400-f1c4-11e9-9945-e4c27c10685e.png)

**Comment by mlstowell** [comment]
Hi, @garobed1 ,

I've only come up with a partial answer.  Part of the problem is that the AMS preconditioner can produce solutions with non-zero divergence.  If we add one more step to the solution process and use the `DivFreeProj_` on the solution `a_` the result will more closely match the expected solution.  However, this only seems to improve the convergence rate a little and, in my tests, all orders from 2 upwards converged with essentially the same rate.  I think this is consistent with your observation that B converges with first order.

I don't know why this is the case.  I suspected the discontinuity in the material and/or the right hand side so I setup the equivalent 2D problem to test this.  Interestingly, the solution was essentially exact for orders above 1 as you might expect since the exact solution is a 2nd degree polynomial.  I'm not sure why the curl curl version of the problem is restricted to lower order convergence.  Perhaps @tzanio can offer his insights.  He has studied this problem much more deeply than I have.

Best wishes,
Mark

**Comment by garobed1** [comment]
I'll give that method a shot and see what happens on my end. I'm primarily interested in trying to observe the proper convergence and solve magnetostatics on a larger 3D problem. I'm not sure how else to proceed myself, but I'll otherwise work around this issue and see what other insights I can get.

**Comment by tzanio** [comment]
@garobed1 -- were you able to resolve this?

@mlstowell -- is the convergence questions about the curl curl A = rhs problem?

**Comment by tzanio** [comment]
We discussed this with @mlstowell and the issue could be the smoothness of A -- its second derivative is discontinuous. Can you try  `A1 = (0 0 y^p), A2 = (0 0 -y^p)` with `p = 3, 4, ...`?

**Comment by garobed1** [comment]
Hello,

I sincerely apologize for bringing this back up so late after failing to respond to your last suggestion in a timely manner due to other work, but I did eventually try a manufactured solution for p=3. My error norm results don't show a meaningful difference for A; it still fails to converge. B does converge somewhat as expected, though.

A summary of my results:
h = 10, 20, 40 in y-direction

O1:

A: 0.00248227, 0.00163546, 0.00154945
B: 0.012817, 0.00638264, 0.00318682

O2:

A: 0.00196998, 0.00223559, 0.00270343
B: 0.0009282, 0.000377241, 0.000175032

O3:

A: 0.0022681, 0.00266416
B: 2.90799e-05, 6.84125e-06

I'll edit or follow up this post with plots, and perhaps results for p=4, when I get the chance, but these results still don't seem to show expected convergence for A. I am still using the exact manufactured solution as the boundary condition for A, so it should be scaled properly. I can only suspect the non-uniqueness of A, even with the given boundary conditions, prevents meaningful convergence study, but B is still useful.
