### ISSUE TITLE
Complex numbers

### ISSUE THREAD

**Issue by alexgribenko** [mfem/mfem#1125]
Is there a plan to have support for complex numbers? Thanks, AG

**Comment by tzanio** [comment]
There is no plan to add direct complex numbers support in the near future, mostly because large-scale preconditioners, such as the BoomerAMG solver in *hypre* do not support them.

However, you can solve complex problems by reformulating them in a block 2 x 2 form (for the real and imaginary form). Several folks, e.g. @sshiraiwa and @mlstowell have done that and may be able to help. See also https://github.com/mfem/mfem/blob/master/linalg/complex_operator.hpp.

Hope this helps,
Tzanio
