### ISSUE TITLE
Inconsistent behavior with Solver::SetPreconditioner

### ISSUE THREAD

**Issue by juan42** [mfem/mfem#113]
Let us assume two simple cases
```
CGSolver M_solver(M.GetComm());
HypreParaSails M_prec(M);

M_solver.SetPreconditioner(M_prec);
M_solver.SetOperator(M);
```
does not work. While
```
CGSolver M_solver(M.GetComm());
HypreParaSails M_prec(M);

M_solver.SetOperator(M);
M_solver.SetPreconditioner(M_prec);
```
works. It is necessary for e.g. HypreSmoother to set the preconditioner before setting the operator (first case). This is inconsistent behavior, because you get an error if you set a preconditioner which does not support SetOperator (illustrated in the second case).

**Comment by v-dobrev** [comment]
Hi @juan42,

Yes, we are aware of the inconsistency you describe. This affects all classes derived from `HypreSolver` except `HypreBoomerAMG`.

Since the first approach works fine, it has not been a big priority for us to fix this. Do you have a specific use case, where you need to use the second approach?

Veselin

**Comment by juan42** [comment]
Not a specific use case, just an inconvenience while testing some configurations. I thought it could be misleading for new users.
