### ISSUE TITLE
No linear form in Tesla miniapp?

### ISSUE THREAD

**Issue by tuckerbabcock** [mfem/mfem#1132]
I'm looking at the Tesla miniapp, and I notice that the current source term is not treated with a linear form object, but instead through these code snippets:
```
BilinearFormIntegrator * hCurlMassInteg = new VectorFEMassIntegrator;
hCurlMassInteg->SetIntRule(ir);
hCurlMass_      = new ParBilinearForm(HCurlFESpace_);
hCurlMass_->AddDomainIntegrator(hCurlMassInteg);
```

```
jr_->ProjectCoefficient(*jCoef_);

// Compute the discretely divergence-free portion of jr_
DivFreeProj_->Mult(*jr_, *j_);

// Compute the dual of j_
hCurlMass_->AddMult(*j_, *jd_);
```

Is this process equivalent to using a `VectorFEDomainLFIntegrator` constructed with the coefficient `jCoef`?
If it is equivalent, is there no way to ensure that the current source is divergence free using the `VectorFEDomainLFIntegrator`, and thats why this approach is taken?

**Comment by mlstowell** [comment]
Hi, @tuckerbabcock ,
Using the `VectorFEDomainLFIntegrator` with a `LinearForm` object would be equivalent to projecting a coefficient onto a `GridFunction` object and then multiplying this object by a mass matrix.  As you suspect, making the linear form divergence free is the crucial step here and does require an approach like this.  The reason is that the divergence free projection requires a global solve and `LinearForm` objects only compute integrals locally within each element.

Best wishes,
Mark

**Comment by tuckerbabcock** [comment]
Hi Mark, 

Thanks for the reply, that make sense.

Thanks!

**Comment by tuckerbabcock** [comment]
Hi @mlstowell,
I had another question related to this I thought you could help with. My goal is to use this divergence free current vector with a nonlinear curl-curl integrator I wrote and Newton's method to solve the nonlinear problem. I tried accomplishing this with `newton_solver.Mult(*current_vec, *A);` where `current_vec` is the divergence free current vector, and `A` is my grid function for the magnetic vector potential, and I've set `newton_solver`'s operator to be the nonlinear form. I've also told the nonlinear form about the essential degrees of freedom by:
```
ess_bdr.SetSize(mesh->bdr_attributes.Max());
ess_bdr = 1;
Array<int> ess_tdof_list;
h_curl_space->GetEssentialTrueDofs(ess_bdr, ess_tdof_list);
res->SetEssentialTrueDofs(ess_tdof_list);
```
where res is the `NonlinearForm`, which I think is straightforward.

I realized that nowhere have I set/accounted for the essential degrees of freedom for the current vector, and I'm not sure where/how I can do it. 
I believe that the `BilinearForm::FormLinearSystem` method would to handle this for a bilinear form, (as done by the Tesla miniapp), but since I have a nonlinear form I don't see an obvious analog. Do you know how to best proceed?

Thanks, 

Tucker

**Comment by mlstowell** [comment]
Hi, @tuckerbabcock ,
I'm not as familiar with our `NonlinearForms` but you raise an excellent question.  The `NewtonSolver` takes a linear algebra based view point so it knows nothing of boundary conditions.  It simply solves a sequence of linearized problems.  Setting essential boundary conditions alters the rhs vector using the boundary values and matrix entries so the rhs vector becomes a function of the matrix which in turn has some nonlinear dependance on the field.  This suggests that the rhs vector becomes part of the non-linear form.

I would suggest that you incorporate the `current_vec` into your `NonlinearForm` so that the `Mult` method computes `F(A)=Curl(mu^{-1}CurlA) - J` and the `NewtonSolver` solves `F(A)=0`.  In this setup the `NonlinearForm::GetGradient` method can create the curl curl matrix and apply essential BCs to both the matrix and its internal copy of `current_vec`.  I'm not entirely sure this will work because the essential BCs will somehow need to be enforced within the `NonlinearForm::Mult` method but I think we're on the right track.

I think @jamiebramwell has had much more experience with these issues than I have.  Perhaps she can offer her insights.

Best wishes,
Mark

**Comment by rcarson3** [comment]
So, if you look at the ```NonlinearForm::Mult``` and ```NonlinearForm::GetGradient``` they enforce the essential boundary conditions that are located at the locations supplied by ```res->SetEssentialTrueDofs(ess_tdof_list);``` .

You can find the specific lines for ```Mult``` here: https://github.com/mfem/mfem/blob/master/fem/nonlinearform.cpp#L221-L230 and then ```GetGradient``` here: https://github.com/mfem/mfem/blob/master/fem/nonlinearform.cpp#L359-L371 . It appears that the ```BilinearForm``` does something similar when it set-up the linear system of equations to solve.

```ParNonlinearForm``` also has similar lines of codes in the ```Mult``` and ```GetGradient``` definitions as well.

I don't have too much experience of using the ```NonlinearForm``` and enforcing the essential boundary conditions outside of my uses in ```ExaConstit```. However, I know that in there we also make sure to apply the boundary conditions before starting our Newton Raphson solve for a given time step. Other that we don't have to do anything to make sure they're getting properly enforced outside of the original call of ```SetEssentialBC``` on our ```ParNonlinearForm``` object.

**Comment by v-dobrev** [comment]
The `NonlinearForm::Mult` method sets the essential dofs on the output vector to zero, so for the Newton solve `newton_solver.Mult(*current_vec, *A);` you just need to zero-out the essential dofs in the r.h.s. vector, `*current_vec`, e.g. using `Vector::SetSubVector(const Array<int> &dofs, const double value)`. On the other hand, the essential dofs in the input vector of `NonlinearForm::Mult` are important and have to be set appropriately. For the Newton solver, this means that the initial guess, `*A`, has to contain the correct essential dofs - this can be done with a method like `GridFunction::ProjectBdrCoefficent`.

Does this answer your question?

**Comment by tuckerbabcock** [comment]
Thanks @mlstowell, @rcarson3, and @v-dobrev. I think that answers my question. I have also found the method `NonlinearForm::SetEssentialBC(const Array<int> &bdr_attr_is_ess, Vector *rhs)`, which I believe performs the equivalent of using `Vector::SetSubVector(const Array<int> &dofs, const double value)` to zero-out the r.h.s. vector, `*current_vec`, and seems to be the most straightforward way to handle this, is that correct @v-dobrev?

Thanks so much,

Tucker

**Comment by v-dobrev** [comment]
Yes, `NonlinearForm::SetEssentialBC` with a given r.h.s. vector should work too.

**Comment by tuckerbabcock** [comment]
Thank you for the help.

**Comment by tuckerbabcock** [comment]
Hi @v-dobrev, 

I'm still struggling to enforce boundary conditions for this nonlinear magnetostatics problem. I've tried all the approaches suggested in the above discussion, but none of them allow me to specify non-zero tangential boundary conditions on the A field. All of the above approaches gave me the exact same answer, with A always tangentially zero even when I used `GridFunction::ProjectBdrCoefficent` to project the non-zero boundary coefficient. Given that my right hand side vector is a `ParGridFunction` from the divergence free projection of the current, do I need to do something different? Or is there something special I need to do since I'm using Nedelec elements?

Potentially related, I don't really understand the difference between `FiniteElementSpace::GetEssentialVDofs` and `FiniteElementSpace::GetEssentialTrueVDofs`. Which should I be using here to specify the Dirichlet boundary condition degrees of freedom? 

Thanks for your help,

Tucker

**Comment by v-dobrev** [comment]
If you have a Nedelec `GridFunction` you should use `GridFunction::ProjectBdrCoefficientTangent` instead of `GridFunction::ProjectBdrCoefficient`. However, I'm not sure this will resolve your issue with the b.c. always being zero.

Regarding the use  of `FiniteElementSpace::GetEssentialVDofs` or `FiniteElementSpace::GetEssentialTrueDofs`: the right choice depends on which method you will use the resulting `Array<int>` with. For example, if you want to use `NonlinearForm::SetEssentialTrueDofs` then you need to use `FiniteElementSpace::GetEssentialTrueDofs`.

**Comment by tuckerbabcock** [comment]
Hi @v-dobrev, thanks for your response.

My code looks like this...
```
ess_bdr.SetSize(mesh->bdr_attributes.Max());
ess_bdr = 1;
Array<int> ess_tdof_list;
h_curl_space->GetEssentialTrueDofs(ess_bdr, ess_tdof_list); // the parfiniteelementspace
res->SetEssentialTrueDofs(ess_tdof_list); // the parnonlinear form
current_vec->SetSubVector(ess_tdof_list, 0.0);

bc_coef.reset(new VectorFunctionCoefficient(3, a_exact)); // bc_coef is a std::unique_ptr<mfem::VectorCoefficient>

A->ProjectBdrCoefficientTangent(*bc_coef, ess_bdr);

// and eventually 
newton_solver.Mult(*current_vec, *A);
```
I've printed the grid function `A` before and after the call to `ProjectBdrCoefficientTangent`, and it does set values. However, if I print `A` **AFTER** the newton solve, the dofs that had been set by `ProjectBdrCoefficientTangent` are now all zero. Do you have any thoughts on why that might happen?

**Comment by v-dobrev** [comment]
Are you by any chance setting `newton_solver.iterative_mode` to false?

**Comment by tuckerbabcock** [comment]
I am, should I not?

**Comment by tuckerbabcock** [comment]
Setting `newton_solver.iterative_mode` to true seems to have resolved my boundary condition issue. Thank you so much for you help.

**Comment by v-dobrev** [comment]
Yes, you should keep `newton_solver.iterative_mode`  equal to `true` (which is the default value).

When set to `false`, the first thing the `Mult` method of the `newton_solver` will do is to initialize the output vector (the `*A` vector in your case) with zeroes.

One thing to keep in mind is that with `iterative_mode == true`, one has to initialize all entries of the output vector. In your case, you probably need to do `*A = 0.0;` before calling `ProjectBdrCoefficientTangent` since the latter will only modify entries on the boundary that correspond to boundary attributes marked in the `ess_bdr` array. In particular, the interior DOFs will not be touched.
