### ISSUE TITLE
Confusion about finite element space DOFs

### ISSUE THREAD

**Issue by termi-official** [mfem/mfem#1157]
Hi folks,

I am not sure about the concepts behind DOFs used in the finite element space class implementations (serial/parallel).

I started [here](https://mfem.org/pri-dual-vec/) and then went into the code. From my understanding there is
1. _NDofs_ := the total number of unique nodes, resulting from the finite element base nodes over all elements of the mesh.
1. _VSize_ := the total number of unknowns, resulting from the finite element bases over all elements of the mesh in combination with the solution space.
1. _True Dofs_ := the number of local unique nodes (as before) in a partitioned mesh, excluding slave nodes.
1. _True VSize_ := the number of local unknowns (as before) in a partitioned mesh, excluding slave unknowns.

With these definitions in mind I spotted some differences in the serial and parallel implementations of the FE spaces (taking the current dev branch for reference).

For the parallel implementation we have:

https://github.com/mfem/mfem/blob/beb8ead90767c0e3e328374f7070fcf256ffc573/fem/pfespace.hpp#L256

While in the serial offers:

https://github.com/mfem/mfem/blob/beb8ead90767c0e3e328374f7070fcf256ffc573/fem/fespace.hpp#L353

with the corresponding call to:

https://github.com/mfem/mfem/blob/beb8ead90767c0e3e328374f7070fcf256ffc573/fem/fespace.hpp#L359

Further, in the parallel implementation the non-conforming DOFs seem to be counted separately:

https://github.com/mfem/mfem/blob/beb8ead90767c0e3e328374f7070fcf256ffc573/fem/pfespace.hpp#L48

for which I could not find an analogon in the serial implementation. 

I feel like I overlook something major. Could someone shed light on this?

**Comment by tzanio** [comment]
Hi @termi-official, thanks for the good questions.

Starting from the diagram, we distinguish between the _finite element world_ on the left and the _linear algebra world_ on the right. There are two corresponding concepts of degrees of freedom: **all dofs** a.k.a. **dofs** in the finite element world, and **true dofs** a.k.a. **tdofs** in the linear algebra world.

The **tdofs** are the ones that you ultimately solving a linear system for. They are the minimal set of unknowns that describe the problem. In parallel, they do not include copies of the same shared value on different MPI ranks. On non-conforming meshes, they do not include hanging nodes. You can't perform finite element operations (e.g. norm computation) on  **tdofs**  you have to first convert them to **dofs** via the *conforming prolongation matrix* `P`.

The **dofs** are just the degrees of freedom in the finite element space which is decoupled in parallel (each MPI rank essentially has its own mesh and space, as if it was not part of a parallel computation) and also in the non-conforming case (the mesh is "cut" on the coarse-fine interfaces). So in your notation, *NDofs* is just the number of degrees of freedom on the local mesh.  There is a similar function for the global size, `ParFiniteElementSpace::GlobalVSize()`. The *vector dimension* a.k.a. *vdim* and denoted with *VSize* just signifies that we have a space that is a Cartesian product of a vector space, e.g. when we solve for the displacement in linear elasticity, the finite element space for the solution has `vdim=3` in 3D because the solution is a vector field, each component of which is discretized in the same (H1-type) scalar finite element space.

Does this make sense?
Tzanio

**Comment by termi-official** [comment]
Hi Tzanio,

thanks for the detailed explanation! That clarified it for me.

**Comment by termi-official** [comment]
I got a follow up question about the conforming prolongation operator P.
In the following I will stick to the example 1 (parallel version) in this repository. Basically, I want to update the nodal values after computing the finite element solution, called X as in the code sample. If I understand everything correctly then I obtain the nodal values with the action of P, i.e. x_nodal = P X. After updating these I can move these back to the linear algebra world by X = P^T x_nodal. 

Now, if I have this setup in a parallel implementation, the P projects the true dofs onto the dofs of the local partition of my mesh. So in this direction adjacent processes obtain the same true dofs at the shared edges and faces, right? From my understanding in parallel implementations, we also need master and slave nodes at these shared faces and edges, so one process actually owns a shared node. So at this point my expectation is that the action of P^T on the locally modified value at the dof of the respective owning process determines the corresponding true dof's value. But actually, the values of the local modifications are _added_.

To have a small example just paste the following code in [ex1p between step 13 and 14](https://github.com/mfem/mfem/blob/beb8ead90767c0e3e328374f7070fcf256ffc573/examples/ex1p.cpp#L222).

```cpp
  // Setup DOF map
  fespace->BuildDofToArrays();

  // Get prolongation operator P
  const Operator &P = *fespace->GetProlongationMatrix();

  // Allocate a vector for the local dof values
  Vector x_nodal(P.Height());

  // Project linear algebra solution onto local dofs.
  P.Mult(X,x_nodal);

  // Set a fixed value at dofs with material of type "1".
  for (int i = 0; i < x_nodal.Size(); i++) 
  {
    auto element_id = fespace->GetElementForDof(i);
    if (fespace->GetAttribute(element_id) == 1) 
    {
      x_nodal[i] = 10.0;
    }
  }

  // Move the updated values for the true dof back to the linear algebra space
  P.MultTranspose(x_nodal, X);
```

I run this example with 7 processes and the This gives me the following result.

![bar-prolongation](https://user-images.githubusercontent.com/9196588/70484106-09118000-1aeb-11ea-8160-b60468fec9ea.png)

It somewhat makes sense that the values are added when applying P^T, when thinking about it as a matrix. This leads me to several questions.

1. Is there an operator pair like P and P^T, which projects the linear algebra solution onto the owning dofs (and back)? If not, what is the intended way to do this?
1. When moving a step further to non-conforming meshes, is there a recipe how hanging nodes should be handled? And what is right the prolongation operator in this case?

Best regards and thanks for your time,
Dennis

**Comment by v-dobrev** [comment]
In the last step, instead of `P^T` you should use the restriction matrix `R` returned by `fespace->GetRestrictionMatrix()`.

For non-conforming meshes, the same snippet should still work -- in this case the action of `P` communicates shared master dofs and computes the dependent/slave dofs; the restriction `R` will drop the dependent/slave dofs as well as the shared master dofs that are not owned by the local processor.

**Comment by termi-official** [comment]
Well, sorry. I totally missed this one. For completeness [I leave the link here again](https://mfem.org/pri-dual-vec/), where these operators and the corresponding spaces are described, just in case someone else also runs into this problem.
 
Thanks for pointing this one out!

**Comment by tzanio** [comment]
See also Section 5.2 in https://arxiv.org/pdf/1911.09220.pdf.
