### ISSUE TITLE
ParMesh attributes are not uniform across processors

### ISSUE THREAD

**Issue by mlstowell** [mfem/mfem#1178]
We (@psocratis and I) recently ran into trouble with the `Volta` mini app while parsing boundary attributes from the command line.  In parallel each processor only records attributes that occur in its subset of local elements (via the `Mesh::SetAttributes()` method).  Consequently, `ParMesh::attribute.Max()`  and `ParMesh::bdr_attribute.Max()` can return different results on different processors.

Many of our classes require marker arrays indicating active portions of the boundary and these arrays can have different lengths (based on the above calls to `Array::Max()`) if the highest numbered attributes are not present on some processors.  Therefore, you need to check to see if the attribute you need to mark is included in the local portion of the mesh.

On the other hand methods like `ParGridFunction::ProjectBdrCoefficient` involve collective communication so these must be called on all processors even when attribute in question is not present on the local portion of the mesh.

I would like to propose that we implement a `ParMesh::SetAttributes()` method, or otherwise alter `Mesh::SetAttributes()`, so that each processor will contain a copy of the global list of attributes.

**Comment by rcarson3** [comment]
It sounds to me @mlstowell, based on your comments, that there should be another function added that finds the global set of attributes and stores those in another class variable rather than changing the ```Mesh::SetAttributes()``` function and attribute variable.

**Comment by mlstowell** [comment]
Hi, @rcarson3, that is certainly a possibility and I almost proposed this.  However, I'm wondering if we need the shorter list of locally represented attributes.  They might provide an opportunity for avoiding looping through elements checking their attributes but we don't take advantage of this as far as I know.

**Comment by rcarson3** [comment]
So, I'm not sure about within the MFEM library itself, but I will say that I am working on a parallel reduction class within my app ```ExaConstit``` for some post-processing operations where at least that shorter list is useful during the initial set-up of the class in figuring out which processors are communicating with who for certain operations. Granted, I could also loop through all of the local elements to figure out the unique attributes within the local mesh as well. So, it wouldn't be the worst thing for me personally if this were to change. However, I can't speak for other MFEM users.

**Comment by v-dobrev** [comment]
Hi @mlstowell, this looks like a bug somewhere in the code. The intended behavior is for the arrays `Mesh::attributes` and `Mesh::bdr_attributes` to contain lists of all attributes from all processors.

Do you have an example that reproduces this bug? There must be some method in `ParMesh` that breaks this since the `ParMesh` constructor simply copies these arrays from the serial `Mesh`, as seen e.g. here: https://github.com/mfem/mfem/blob/b6d50d0b4bb5ea4cd393edf384ef5c291be95cfe/mesh/pmesh.cpp#L166-L167

**Comment by mlstowell** [comment]
Hi, @v-dobrev, the error occurs when `Mesh::SetAttributes()` is called because this method creates or recreates the attribute arrays by looping over the local elements.  I believe this method is being called via the `Mesh::Finalize*Mesh()` methods.

You should be able to reproduce it by running the following (with MFEM_DEBUG set to YES in your build):
```mpirun -np 4 volta -m ../../data/square-disc.mesh -dbcs '1 2 3 4 5 6 7 8' -dbcv '0 0 0 0 1 1 1 1'
```

**Comment by v-dobrev** [comment]
@mlstowell, I think you forgot to paste the command line in your last comment.

**Comment by mlstowell** [comment]
@v-dobrev , I used too many back ticks so it was invisible...

**Comment by v-dobrev** [comment]
It looks like in `volta.cpp` the problem comes from the call: https://github.com/mfem/mfem/blob/b6d50d0b4bb5ea4cd393edf384ef5c291be95cfe/miniapps/electromagnetics/volta.cpp#L222-L223

which calls `Mesh::Finalize()` `->` `Mesh::FinalizeTopology()` `->` `Mesh::SetAttributes()`.

One option is to make the method `SetAttributes()` **virtual** and re-implement it for `ParMesh`. This has the drawback that it will always need to communicate even when we really do not need to re-compute the attribute lists. However, in some cases, a true parallel `SetAttributes()` will be useful, e.g here: https://github.com/mfem/mfem/blob/b6d50d0b4bb5ea4cd393edf384ef5c291be95cfe/mesh/pmesh.cpp#L1055

What do you think of this approach?

**Comment by tzanio** [comment]
@mlstowell, any updates on this issue?

**Comment by mlstowell** [comment]
No, I haven't had a chance to get back to this.  I do like @v-dobrev 's approach though.

**Comment by tzanio** [comment]
Discussion continued in #1222
