### ISSUE TITLE
Possible conservation error when using periodic-hexagon.mesh

### ISSUE THREAD

**Issue by HennesHajduk** [mfem/mfem#1224]
In ex9, I've included

```c++
Vector LumpedMassMat;
BilinearForm ml(&fes);
ml.AddDomainIntegrator(new LumpedIntegrator(new MassIntegrator));
ml.Assemble();
ml.Finalize();
ml.SpMat().GetDiag(LumpedMassMat);
const double InitialMass = LumpedMassMat * u;
```

before the time stepping loop, so after time stepping is completed I check the mass error, by
`cout << "Difference in solution mass: " << abs(InitialMass - LumpedMassMat * u) << endl;`

If I run this on periodic-hexagon.mesh, I get a mass error in the order of machine precision for the configuration -p 0 (translation), but if I rotate instead (-p 1) it is about 10^-5.

Due to the periodic mesh, there is no mass change over domain boundaries, i.e. mass errors should not occur as long as the velocity is exactly divergence free (in the case of rotation, the integrals seem to be integrated accurately).

**Comment by vladotomov** [comment]
Hi Hennes,

I think what happens at the end is that the rowsums of the advection matrix approximate
integral [div(v) phi_i]
over the mesh, see the derivation in Section 2.1 of [this paper](https://www.sciencedirect.com/science/article/pii/S0021999116306854?via%3Dihub). The integrals written there are generally not an exact approximation, it's up to the order of the FE. I noticed that under refinement this mass error drops with order k+1. I'm not quite sure why you get it at machine precision for the uniform mesh, but it can probably be derived.

Vladimir

**Comment by HennesHajduk** [comment]
Hi Vladimir,

Yes it seems that integration is inexact, but I don't quite understand why, I checked the integrals and believe, that the quadrature orders are of high enough to compute both volume and boundary integrals accurately on this mesh as long as the velocity is at most linear. I tried increasing the quadrature order significantly, but that didn't change it. So there has to be some specific reason, why constant velocity is integrated accurately and linear velocity can not.

Anyway, I don't know if this is of significant interest  to you guys, I just wanted to point it out, it's something that transcends to Remhos as well.

Thanks
Hennes

**Comment by vladotomov** [comment]
Hi Hennes,

We looked more closely at this with Veselin. We believe the issue for this particular test (periodic-hexagon with rotation) is that while the mesh is periodic, the rotating velocity field is not consistent with the periodicity of the mesh. In other words, the velocity points at different directions when taken from both sides of a periodic face. This causes a kind of velocity discontinuity in the integrals and mass gets modified. Since the solution converges to zero around the boundary, this mass perturbation converges under refinement too.

So yes, this setup of mesh+velocity is not very consistent for transport, but the operators are ok.

Thanks,
Vladimir

**Comment by HennesHajduk** [comment]
Thanks, I appreciate you looking into this!
