### ISSUE TITLE
Arbitrary prolongation matrix

### ISSUE THREAD

**Issue by geyan3566** [mfem/mfem#1235]
Hi,

I'm wondering that without constructing a new `FiniteElementSpace`, is there a way to build an arbitrary prolongation matrix independent of the mesh?

Thanks,
Ge

**Comment by v-dobrev** [comment]
I don't understand your question: what is the prolongation matrix that you want to build? The ones created by MFEM do not make sense without a FE space and a mesh.

I suppose you can build an arbitrary prolongation matrix as a `SparseMatrix` (for example) but then what do you want to do with it with MFEM?

**Comment by geyan3566** [comment]
> I don't understand your question: what is the prolongation matrix that you want to build? The ones created by MFEM do not make sense without an FE space and a mesh.
> 
> I suppose you can build an arbitrary prolongation matrix as a `SparseMatrix` (for example) but then what do you want to do with it with MFEM?

Sorry for the confusion. I'm using conforming mesh but at the same time, I'd like to project dofs to other locations using the prolongation matrix. So my question is more close to Is there a way to construct the prolongation matrix within the finiteelementspace even with the conforming mesh?

**Comment by tzanio** [comment]
Can you clarify further: what is the input and output for the action of this prolongation matrix?

We create for example prolongation matrices that map coarse to fine dofs after refinement, or true to all dofs in parallel settings.

**Comment by geyan3566** [comment]
> Can you clarify further: what is the input and output for the action of this prolongation matrix?
> 
> We create for example prolongation matrices that map coarse to fine dofs after refinement, or true to all dofs in parallel settings.

I want to create the prolongation matrix used in a reduced-order model such that it prolongate the dofs from reduced-order space to the real dofs. So in this situation, can I build a prolongation matrix even with a conforming mesh?

**Comment by tzanio** [comment]
@dylan-copeland may be able to provide more specific advice about reduced-order modeling with MFEM, but in general the answer to your question is that MFEM doesn't provide any direct way to do that. 

You can of course always construct a `SparseMatrix` whose columns represent the ROM basis in the finite element space and apply it appropriately.

**Comment by dylan-copeland** [comment]
If I understand the question correctly, you would like to construct a subspace of the finite element space, defined as the span of some set of basis vectors in the finite element space. The question is then how to "prolongate" from coefficients in the subspace to a coefficient vector in the full finite element space.

As @tzanio mentioned, in serial the ROM basis vectors would be the columns of a SparseMatrix, which defines the prolongation. In parallel, it could be represented by a HypreParMatrix.

This is not a very informative answer, because mfem does not have ROM capabilities for generating a basis and doing the prolongation and restriction. Instead, the user must define the basis somehow, perhaps by using another library (I have used libROM https://github.com/LLNL/libROM). Then the user can define the necessary mappings via the mfem linear algebra in serial or parallel.

**Comment by goxberry** [comment]
Building upon @dylan-copeland's comment, it depends heavily on the reduced order model you're using.  If you're using Galerkin- or Petrov-Galerkin-based reduced order models, presumably you know not only the restriction operator, via a basis, to construct your reduced order model, but you also know a prolongation operator as well.

My graduate work was in Petrov-Galerkin-based reduced order modeling, and most of the methods I'm aware of are essentially algebraic -- the operators are mesh-oblivious and do not explicitly consider any geometric structure. For these methods, a `FiniteElementSpace` appears to be an inappropriate abstraction because your space is no longer defined by nodal basis functions -- it's defined by some "modal" basis constructed via linear combinations of nodal basis functions -- and so concepts of vertex, edge, and face dofs don't really apply to the reduced order model basis. Like @dylan-copeland, I'd use a `SparseMatrix` or `HypreParMatrix` to construct the prolongation operator. I don't think it makes sense to implement these methods natively in MFEM at the moment because of their geometry-oblivious nature -- that's why we use libROM in conjunction with MFEM. If native reduced order modeling support were on the MFEM roadmap, I think it would make sense to implement it only after implementing better support for modal bases.

**Comment by geyan3566** [comment]
Thanks for all the answers.
The ROM in my work is derived from the Galerkin Difference method, which does not require POD to get the basis, so my current solution is to construct a derived class from `FiniteElementSpace` and build the prolongation matrix there.
