### ISSUE TITLE
Multiple attributes

### ISSUE THREAD

**Issue by thorvath12** [mfem/mfem#1298]
Hi,

Is there a possibility to have a list of attributes (instead of a single one) of a mesh element? As far as I can see, it is not possible right now. Am I right?

If it is not possible, is there any initiative to change that?

Any help would be appreciated.

Tamas

**Comment by tzanio** [comment]
I believe @mlstowell was working on something that could allow this, but currently this is not possible in master.

One way to get around it could be to define a piecewise-constant field for each attribute and query that when necessary.

**Comment by mlstowell** [comment]
Hi, @thorvath12 ,
I'm curious about the use case you have in mind.  How were you hoping to use multiple element attributes?

As you noticed, MFEM assigns exactly one attribute label to each mesh element.  These are used primarily to determine material coefficients.  So, each attribute can be associated with one set of materials and these materials can be analytic functions or lookup tables, etc..  The point is that we can use different schemes to determine material coefficients in different regions and these regions are labeled with different attribute numbers.

The other scheme I've been working on, which @tzanio mentioned, is a notion I'm calling "Entity Sets".  These are relatively small groups of elements, faces, edges, or points.  Any given element could belong to any number of different sets which could then be used for a variety of purposes.  For example, we could define a source term or boundary condition on a small set of edges.  Another use case would be post processing.  For example, computing a path integral along a set of edges or a volume integral on an element set.  The important point is that these sets are small so that it makes more sense to loop over the set rather than looping over the entire mesh searching for the elements you're interested in.

Best wishes,
Mark

**Comment by thorvath12** [comment]
Hi @mlstowell ,

I need one attribute to identify parts of the domain, but I also need another one, because of the discretization I am using.  I was hoping to be able to define a set of attributes, so something like this in the mesh file

`<no of element attributes> <attribute 1> ... <attribute k> <geometry type> <vertex index 1> ... <vertex index m>`

Do you think something like that would be possible?

@tzanio that is a nice workaround, nicer than the one I have right now, I'll think about it.

Best,
Tamas

**Comment by mlstowell** [comment]
Hi, @thorvath12 ,
Anything's possible but multiple attributes would require extensive changes inside MFEM.  Would it be practical to encode your attributes into a single integer?

Best wishes,
Mark
