### ISSUE TITLE
Different number of non-zeros in coefficient matrix with and without lapack library in ex2

### ISSUE THREAD

**Issue by davidherreroperez** [mfem/mfem#1418]
Hi there,

I found that ex2 with and without lapack library (3.7.1) assembles a coefficient matrix with different number of non-zeros in some cases. By replacing

https://github.com/mfem/mfem/blob/278a27db5ed1ccc58253c604024d8388f4bde7a8/examples/ex2.cpp#L194

with

```
   cout << "Size of linear system: " << A.Height() << endl;
   cout << "NumNonZeroElems: " << A.NumNonZeroElems () << endl;
   cout << "MaxNorm: " << A.MaxNorm () << endl;
   cout << "CountSmallElems: " << A.CountSmallElems (1e-18) << endl;
```
Running for example ex2 with beam-hex.mesh

```
./ex2 -m ../data/beam-hex.mesh
```

I obtain the following output with lapack

```
Size of linear system: 15795
NumNonZeroElems: 1085621
MaxNorm: 27.7778
CountSmallElems: 29244
```

and without lapack library

```
Size of linear system: 15795
NumNonZeroElems: 1085617
MaxNorm: 27.7778
CountSmallElems: 30487
```

This also happens in the parallel implementation ex2p generating different matrix transfer operators in the AMG solver.

**Comment by v-dobrev** [comment]
This can be expected: the element matrices can have round-off differences with and without lapack. Since entries that are exactly 0 are not added to the sparse matrix (with the default parameter of `BilinearForm::Assemble(skip_zeros = 1)`) then an entry that is 0 with lapack and, say, 1e-16 without lapack will result in different number of nonzeros. If you want to ensure you get the exact same sparsity pattern, you can use `a->Assemble(0)` in the example.

By the way, you can print similar sparse matrix stats with the method `SparseMatrix::PrintInfo` which also shows how many entries are exactly 0.

**Comment by davidherreroperez** [comment]
Thank you for your response. Another question concerns the small differences in symmetric coefficients. Are they attributed to round-off error during the assembly?

**Comment by davidherreroperez** [comment]
Sorry, I have checked the symmetric coefficients and they seem ok. Thank you again for your response.
