### ISSUE TITLE
use BoundaryNormalLFIntegrator for Neumann boundary conditions

### ISSUE THREAD

**Issue by fanronghong** [mfem/mfem#1441]
Hi all,

I want to test a simple non-zero Neumann and non-zero Dirichlet boundary condition for Poisson problem.
I know I can use `BoundaryLFIntegrator` if `du/dn = g` is known. But here I want to use analytic solution for the Neumann bdc, like `du/dn = grad(u) \cdot n`. So I use `BoundaryNormalLFIntegrator`. 
But I don't get the right convergence rate. I don't know where is wrong and how to fix it. I have seen discussions [here](https://github.com/mfem/mfem/issues/708#issue-394233025) and [here](https://github.com/mfem/mfem/issues/1117#issue-507203795)

Below is MWE
```
/* Solve -Delta u = f  in \Omega,
 *                u = u_D  on \Gamma_D,
 * grad(u) \cdot n = grad(ue) \cdot n  on \Gamma_N,
 * Analytic solution ue = sin(x)sin(y)
 * */
#include <fstream>
#include "mfem.hpp"
using namespace mfem;
using namespace std;

double f(const Vector& x)
{
    return 2*sin(x[0]) * sin(x[1]);
}
double ue(const Vector& x)
{
    return sin(x[0]) * sin(x[1]);
}

int main()
{
    Mesh mesh(4, 4, 4,Element::TETRAHEDRON, true, 1.0, 1.0, 1.0);
    {
        ofstream mesh_file("demo.mesh");
        mesh.Print(mesh_file);
    }
    for (int i=0; i<1; ++i) mesh.UniformRefinement();

    H1_FECollection h1_fec(1, mesh.Dimension());
    FiniteElementSpace h1_space(&mesh, &h1_fec);

    int size = mesh.bdr_attributes.Max();
    Array<int> Neumann(size), Dirichlet(size), ess_tdof_list;
    {
        Neumann        = 0;
        Neumann[2 - 1] = 1;
        Neumann[3 - 1] = 1;
        Neumann[4 - 1] = 1;
        Neumann[5 - 1] = 1;
        Dirichlet        = 0;
        Dirichlet[1 - 1] = 1; // bottom
        Dirichlet[6 - 1] = 1; // top
        h1_space.GetEssentialTrueDofs(Dirichlet, ess_tdof_list);
    }

    FunctionCoefficient ue_coeff(ue);

    GridFunction ue_gf(&h1_space);
//    ue_gf.ProjectCoefficient(ue_coeff); // use this or below ?
    ue_gf.ProjectBdrCoefficient(ue_coeff, Dirichlet);

    BilinearForm blf(&h1_space);
    blf.AddDomainIntegrator(new DiffusionIntegrator);
    blf.Assemble();

    LinearForm lf(&h1_space);
    FunctionCoefficient f_coeff(f);
    lf.AddDomainIntegrator(new DomainLFIntegrator(f_coeff)); // (f, v)_{\Omega}
    // use analytic solution to construct Neumann bdc
    GradientGridFunctionCoefficient grad_ue_coeff(&ue_gf);
    lf.AddBoundaryIntegrator(new BoundaryNormalLFIntegrator(grad_ue_coeff), Neumann); // (grad(u_e) \cdot n, v)_{\Gamma_N}
    // here I can only use BoundaryNormalLFIntegrator, instead of BoundaryLFIntegrator
    lf.Assemble();

    GridFunction uh(&h1_space);
    uh.ProjectBdrCoefficient(ue_coeff, Dirichlet);

    SparseMatrix A;
    Vector x, b;
    blf.FormLinearSystem(ess_tdof_list, uh, lf, A, x, b);

    IterativeSolver* solver;
    Solver* smoother;
    {
        smoother = new GSSmoother(A);
        solver = new MINRESSolver;
        solver->SetAbsTol(1.0e-10);
        solver->SetRelTol(1.0e-8);
        solver->SetMaxIter(1000);
        solver->SetPreconditioner(*smoother);
        solver->SetPrintLevel(0);
        solver->SetOperator(A);
    }

    solver->Mult(b, x);
    blf.RecoverFEMSolution(x, lf, uh);

    if (solver->GetConverged() == 1) cout << "Converged by iterating " << endl;
    else MFEM_ABORT("Not Converge");

    cout << "l2 error norm of |u_h - u_e|: " << uh.ComputeL2Error(ue_coeff) << endl;
}
```

**Comment by mlstowell** [comment]
Hello, @fanronghong ,
I'm curious if you're working in a branch of MFEM or some other modified source.  When I try your example in MFEM's master branch it crashes rather quickly because the `Gridfunction::GetGradient` method, used by `GradientGridFunctionCoefficient`, is not designed to work on the boundary of a domain.

We are currently reviewing a pull request, PR #1194, which addresses a similar issue with the `GridFunction::GetValue` method.  I may be able to put together a solution based on this PR which  will work for `Gridfunction::GetGradient`.  I was planning to work on these methods in any case but I can expedite this one since you need it.

A possible work-around is to compute the gradient on the entire domain and use the resulting `GridFunction` in a `VectorGridFunctionCoefficient`.  This would require some care but I can try to help you with that if you need a solution right away.

Best wishes,
Mark

**Comment by mlstowell** [comment]
Hi, @fanronghong ,

I just committed a branch which implements `GridFunction::GetGradient` correctly on boundaries.  It's called `gf-getgradient-dev`, if you want to have a look.  While testing this implementation I noticed a small bug in your test driver.  When projecting onto `ue_gf` you were using the `Dirichlet` portion of the boundary rather than the `Neumann` portion.  However, you should in fact project onto the entire domain (using the commented line) so that the normal component of the gradient will be correct.  Also, it's good practice to initialize `uh` to zero before setting its boundary values.  The interior values can be copied to `x` by `FormLinearSystem` and some iterative solvers will use these uninitialized values as an initial guess.

Best wishes,
Mark
