### ISSUE TITLE
Orientation of boundary faces

### ISSUE THREAD

**Issue by mlstowell** [mfem/mfem#1446]
While expanding tests related to PR #1194 I noticed an inconsistency in the ordering of integration points on boundary faces.  If we perform a boundary integral using `GetBdrElementTransformation` we traverse the face in a certain order but if we use `GetBdrFaceTransformations` the order is different.  Each method is internally consistent but they cannot be mixed.  For example, integrating a `GridFunctionCoefficient` based on an H1 field over the boundary in a DG context produces the wrong results.  This is because the face `Elements` stored in the `faces` array have a different orientation relative to those in the `boundary` array.

We can probably use the orientation information returned from `Mesh::GetBdrElementFace` to resolve this but I'm not sure how best to accomplish this.  Suggestions would be most welcome.

**Comment by mlstowell** [comment]
The following test code can be used to see that the two types of transformations are incompatible.
```
#include <iostream>
#include "mfem.hpp"
using namespace mfem;

int main(int argc, char ** argv)
{
   int n = 1;
   int type = (int)Element::TETRAHEDRON;
   int order = 1;

   Mesh mesh(n, n, n, (Element::Type)type, 1, 2.0, 3.0, 5.0);

   Vector x(3), y(3);

   for (int be = 0; be < mesh.GetNBE(); be++)
   {
      ElementTransformation      *BET = mesh.GetBdrElementTransformation(be);
      FaceElementTransformations *FET = mesh.GetBdrFaceTransformations(be);

      const IntegrationRule &ir = IntRules.Get(BET->GetGeometryType(),
                                               2*order + 2);

      std::cout << "Boundary Element: " << be << std::endl;
      for (int j=0; j<ir.GetNPoints(); j++)
      {
         const IntegrationPoint &ip = ir.IntPoint(j);

         BET->SetIntPoint(&ip);
         BET->Transform(ip, x);

         FET->Face->SetIntPoint(&ip);
         FET->Face->Transform(ip, y);

         std::cout << "(" << x[0] << "," << x[1] << "," << x[2] << ") vs "
                   << "(" << y[0] << "," << y[1] << "," << y[2] << ")\n";
      }
      std::cout << std::endl;
   }
}
```

**Comment by v-dobrev** [comment]
Yes, a boundary element and its corresponding face element can have differently ordered vertices -- one is obtained from the other by rotation.

So, yes, you don't want to mix the boundary transformation with the face transformation. Do you have a specific need to mix the two?

**Comment by mlstowell** [comment]
Yes, I do have a specific need unfortunately.  In the plasma physics project I'm working on the electric field boundary condition depends on the plasma density and energy just inside the boundary.  The electric field uses Nedelec basis functions whereas the density and energy use DG.  We haven't thought much about coupling the electric field into the fluid equations but there may be coupling issues there as well.

**Comment by v-dobrev** [comment]
I don't quite understand if you need a mixed bilinear form on the boundary or simply a linear form, so here are a few possible solutions:

1. If you have boundary terms coupling DG + Nedelec, in a bilinear form integrator, you can override this method:
```c++
void BilinearFormIntegrator::AssembleFaceMatrix(
   const FiniteElement &trial_face_fe, const FiniteElement &test_fe1,
   const FiniteElement &test_fe2, FaceElementTransformations &Trans,
   DenseMatrix &elmat)
```
and then add it to the `MixedBilinearForm` with
```c++
void MixedBilinearForm::AddBdrTraceFaceIntegrator(BilinearFormIntegrator *bfi);
```

2. If you have just a linear form on the Nedelec space and you want to evaluate DG fields on the boundary as part of it, you can override the method
```c++
void LinearFormIntegrator::AssembleRHSElementVect(
   const FiniteElement &el, FaceElementTransformations &Tr, Vector &elvect)
```
and then add it with
```c++
void LinearForm::AddBdrFaceIntegrator(LinearFormIntegrator * lfi);
```

3. Of course, you can evaluate the DG fields through `GridFunctionCoefficient`s and then #1194 should take care of that. If a DG `GridFunctionCoefficient` is evaluated through a boundary `ElementTransformation` then the `IntegrationPoint` will have to be mapped to the (volume) element using
```c++
void Mesh::GetBdrElementAdjacentElement(int bdr_el, int &el, int &info) const
```
followed by
```c++
void Mesh::GetLocalFaceTransformation(
   int face_type, int elem_type, IsoparametricTransformation &Transf, int info);
```
This is currently done in `master` here: https://github.com/mfem/mfem/blob/7690eca85041e0b69afe81a063c71015184e82a3/fem/coefficient.cpp#L182-L194

This approach is not optimal since the repeated calls to `Mesh::GetBdrElementAdjacentElement` and `Mesh::GetLocalFaceTransformation` can be avoided, e.g. using approach 2.

Generally speaking, the methods that use `FaceElementTransformations` can do more than the ones using `ElementTransformation`s for the boundary faces, so there should be no need to mix them.

**Comment by mlstowell** [comment]
I believe I found a solution by checking the orientation, and handling it, in `GridFunction::GetValue` and similar methods.
