### ISSUE TITLE
Attributes and physical groups setting, some parmesh and metis bug

### ISSUE THREAD

**Issue by skarden18** [mfem/mfem#1475]
Dear developers,

I have just started to use mfem for electromagnetism (wave equation in frequency domain is what i need). I try to simulate 3D optical fiber which is consist of core and cladding volumes with different refractive index. Geometry consist of two coaxial cylinders of different radius.
In Gmsh I specified 5 physical domains:
1) core
2) cladding
3) surface of cladding (i need it for boundary conditions)
4 and 5) two ports on the base of cylinders (i need it for boundary conditions) 

I try to use ex3 as a solver and ex2 as an example how to work with physical domains, but i still do not understand many things.
A)
Am I right that in mfem physical domains are called attributes? I called

`mesh->attributes.Max()`

but it said I have only 1, but in .msh file I have 5 physical domains. (attachment)
How can I set boundary conditions?

B)
I tested parallel version for my .msh file and it gives Metis error. Glvis visualize .msh file correct.

`METIS Error: A contiguous partition is requested for a non-contiguous input graph.

Mesh::GeneratePartitioning:  error in METIS_PartGraphKway!
`
Could you please give me advice about it.

BR,
Denis
[mesh.tar.gz](https://github.com/mfem/mfem/files/4609719/mesh.tar.gz)

**Comment by pazner** [comment]
Hi Denis,

It looks like the file `2cylinders.step` is missing, and is required to define the geometry in Gmsh. This means I can't regenerate your mesh with different physical domains to debug, so I can only speculate about the issues.

(A) Yes, the concept of "physical domains" in Gmsh maps to "attributes" in MFEM. Note that the attribute numbers in MFEM have to be strictly positive, and by default Gmsh starts numbering from zero, so this can cause issues.

I would suggest assigning specific numbers to the domains in Gmsh, e.g.
```
Physical Volume("core", 1) = {1};
Physical Volume("cladding", 2) = {2};
```
(the names you assign will not be used in MFEM).

This should result in the "core" mesh elements having attribute 1, and the "cladding" mesh elements having attribute 2.

For boundary conditions, instead of `mesh->attributes`, you should look at `mesh->bdr_attributes`, which are the attributes assigned to the boundary elements. You should be able to do something like
```
Physical Surface("port1", 1) = {5};
Physical Surface("port2", 2) = {6};
Physical Surface("side", 3) = {4};
```
This should give different boundary attributes to the boundary elements in the different physical domains.

(B) Again, I can only speculate about this error. Could it be that your mesh is not contiguous i.e. perhaps two of the domains are not topologically connected?

**Comment by skarden18** [comment]
Hi pazner,

thank you, now become more clear.

Please find .step file in attachment.

I did not understand why it could be topologically not connected.

Denis
[mesh.tar.gz](https://github.com/mfem/mfem/files/4611274/mesh.tar.gz)
[Uploading mesh.tar.gz…]()

**Comment by pazner** [comment]
I still can't generate the mesh (using the latest version of gmsh). However, it does look like the mesh isn't properly connected. The meshes of the two cylinders do not match. See the attached screenshot. It looks like the resulting mesh consists of two intersecting cylinders, which are topologically not contiguous.

![mesh](https://user-images.githubusercontent.com/11493037/81596352-c6ddba80-9378-11ea-9a24-b8201fb74832.png)

**Comment by skarden18** [comment]
Application created two independent meshes for two cylinders?
I have not found topology setting, could you please explain how can I fix it?

**Comment by sshiraiwa** [comment]
As @pazner noted, METIS_PartGraphKway error means that the mesh are not all connected together as one piece. 

The STEP file has two cylinders. The inner one is just sitting inside the outer one position-wise, but there is no relationship between them. In other words, the cladding and core are not sharing the surface. 
For such a geometry, GMSH makes a two mesh one for each cylinder without connecting them. 

One way to fix it is to take the boolean fragmentation of geometry in GMSH. Here is an example to do the job using GMSH Python interface.
```
import gmsh

gmsh.initialize()

# make text output to Terminal
gmsh.option.setNumber("General.Terminal", 1)    

# load STEP and synchronize
gmsh.model.occ.importShapes('2cylinders.step')  
gmsh.model.occ.synchronize()                    
ents = gmsh.model.getEntities()
print("entities", ents)

# Fragmentation to split goemetry and transfer
ent3D = gmsh.model.getEntities(3)
gmsh.model.occ.fragment(ent3D[:1], ent3D[1:],
                        removeObject=True, removeTool=True)
gmsh.model.occ.synchronize()      

gmsh.model.setVisibility(ents, True, recursive = True)

# Make physcal groups
for k, dimtag in enumerate(gmsh.model.getEntities(3)):
    value = gmsh.model.addPhysicalGroup(3, [dimtag[1]], tag=dimtag[1])
    gmsh.model.setPhysicalName(3, value, 'volume'+str(value))
                  
for k, dimtag in enumerate(gmsh.model.getEntities(2)):
    value = gmsh.model.addPhysicalGroup(2, [dimtag[1]], tag=dimtag[1])
    gmsh.model.setPhysicalName(2, value, 'surface'+str(value))

# Set mesh size    
gmsh.option.setNumber("Mesh.CharacteristicLengthMax", 0.1)
gmsh.option.setNumber("Mesh.CharacteristicLengthMin", 0.05)
gmsh.option.setNumber("Mesh.CharacteristicLengthExtendFromBoundary", 1)                
    
gmsh.model.mesh.generate(1)
gmsh.model.mesh.generate(2)
gmsh.model.mesh.generate(3)

# Save file in 2.2 format, although new MFEM may read a newer format
gmsh.option.setNumber("Mesh.MshFileVersion", 2.2)
gmsh.write('out.msh')
```

**Comment by skarden18** [comment]
Thank you very much sshiraiwa,

great, it works!
