### ISSUE TITLE
Why is current density in H(curl) in Tesla Miniapp

### ISSUE THREAD

**Issue by tuckerbabcock** [mfem/mfem#1488]
Hi All,

I'm wondering why the current density source term is projected onto an H(curl) function space (instead of an H(div) space), as I believe the current density should be in the same space as the magnetic flux density (although I can't seem to find a reference for that right now)? It seems like the current coefficient doesn't adhere to the continuity enforced by Nedelec elements, as there will be a tangential discontinuity in the current density on the interface between conducting regions and non-conducting regions.

Thanks,

Tucker

**Comment by mlstowell** [comment]
HI, @tuckerbabcock ,

You are correct, of course, J should be in H(Div).  However, the `j_` that appears in the Tesla miniapp is not the same J.  There are two ways to make sense of this.

First, consider the FEM approach; the PDE we are trying to solve is `Curl(mu^{-1}Curl A)=J` with `A` in H(Curl).  `A` must be in H(Curl) so that we can compute its curl.  To build the weak form we need to take the inner product of this PDE with some function.  That function must also be in H(Curl) because we need to move the outermost `Curl` operator onto it.  This is also the only way to ensure we have a square linear system which we will be able to solve.  So, the weak form is `(mu^{-1}Curl A, Curl W) = (J, W)` with `W` in H(Curl).  The `j_` appearing in Tesla is actually `(J,W)` which is not in H(Curl), although it has the same dimension as H(Curl).  I believe it's in the topological dual space of H(Curl) called H(Curl)*.

The other approach is to take a closer look at the PDE in the language of differential forms.  In this language `A` is a 1-form and its natural derivative `d`, in 3D, is the curl operator.  The result of `dA` is a 2-form `B=dA`.  To connect this with the FEM approach note that 1-forms are in H(Curl) and 2-forms are in H(Div).  A 2-form's natural derivative is the divergence but this is not what we want.  We need to take a co-differential `delta` of `B` which, in 3D, is again the curl operator.  Specifically,  `delta B = *d*(mu)B = *J` (where the innermost Hodge star incorporates the appropraite factor of mu^{-1}).  Putting this together yields `*d*(mu)dA=*J`.  Hidden within this are the two relations; `H=*(mu)B` (or H = mu^{-1}B) where `B` is a 2-form and `H` is a 1-form, and `dH=J` where `J` is a 2-form.  The important thing to note is that while `J=Curl H` is in H(Div), the thing appearing on the right hand side of the PDE is actually `*J` which is the Hodge dual of `J` and this is in H(Curl).

I hope this didn't just confuse the issue more...

Best wishes,
Mark

**Comment by tuckerbabcock** [comment]
Hi Mark,

Thanks for the response, I think that helps to clear things up. I've got a follow up question about the coefficient that defines the current source. The coefficient `jCoef_` is projected to the grid function `jr_`, where `jr_` is in H(curl). For the coefficient used in the Tesla miniapp, the current discontinuously jumps from some value to zero along the interface of the annulus. Since an H(curl) space requires tangential continuity between interfaces, and the interface of the annulus would be tangent to the current (as defined by the coefficient) can't the H(curl) space not represent this coefficient?

Looking at `GridFunction::ProjectCoefficient`, the use of `SetSubVector` makes it seem like the values in the resulting `GridFunction` are dependent upon the ordering of the mesh.

Thanks,

Tucker

**Comment by mlstowell** [comment]
Hi, @tuckerbabcock ,

Yes, the procedure implemented in Tesla can have trouble with discontinuous coefficients.  These troubles will diminish as the mesh is resolved so I think this procedure is acceptable for these purposes.

In a realistic simulation one would build a mesh which conforms to the current source and it would exhibit the continuity issues that you describe.  There are two, at least, suitable procedures to overcome these issues.

Method 1:
i: Project` jCoef` onto an H(Div) field, `j2`.   
ii: Multiply this by a rectangular mass matrix, `M21`, built with H(Div) and H(Curl) basis functions.
iii: Solve for an H(Curl) representation of the current density, `M1 j1 = M12 j2`.
iv: Perform divergence cleaning to get `jr` from `j1`.
v: Compute right hand side as `M1 jr`.

Method 2:
i: Compute an H(Curl) linear form using `jCoef` and call this `J1` for example.
ii: Solve for an H(Curl) representation of the current density, `M1 j1 = J1`.
iii: Perform divergence cleaning to get `jr` from `j1`.
iv: Compute right hand side as `M1 jr`.

Method 1 avoid the discontinuity by projecting into the proper H(Div) space.  Method 2 avoids the discontinuity by integrating over the interior of the elements where the current density is continuous.  The `j1` field, computed in steps iii or ii in the two methods, is a properly averaged approximation of `jCoef` in H(Curl).  Visualizing this field would show the expected current density away from the surface of the annulus.  Near the surface this field would show a transition from the interior value to zero in the exterior.  Normally this blurring of the interface is not a problem.

Best wishes,
Mark

**Comment by tuckerbabcock** [comment]
Hi Mark,

Thank you for explaining it, both of those methods sound like they'll work for me. One final question is what to do about boundary conditions when solving the linear system in 2.ii or 1.iii, can you help elaborate on what I might use for boundary conditions for those solves (if anything)?

Lastly, do you have any good references you could recommend for me to learn more about dealing with mixed spaces/dual forms/Hodge operators?

Thanks so much for your help,

Tucker

**Comment by mlstowell** [comment]
Hi, @tuckerbabcock ,

Generally speaking, no boundary conditions are required in this case.  However, if your `jCoef` has a non-trivial tangential component near the boundary and you're using method 1 you can see odd behavior near the boundary (because the H(Div) field, `j2`, doesn't represent the tangential components accurately enough).  So, in method 1 you can use `jCoef` to set a Dirichlet BC in solve 1.iii.

Unfortunately, I don't know of a suitable reference.  Perhaps someone else on the MFEM team will have a suggestion.  This is something that we should add to the documentation on MFEM.org.

Best wishes,
Mark

**Comment by tuckerbabcock** [comment]
Hi Mark,

Thank you so much for taking the time to explain this all to me, you've helped me out greatly.

Tucker
