### ISSUE TITLE
VectorDeltaCoefficient / AssembleDeltaElementVect

### ISSUE THREAD

**Issue by NikolayYavich** [mfem/mfem#1504]
Dear All,

While exercising with vector delta function
I received an unexpected result.

I checked **local** right-hand sides corresponding to
a single vector delta function. Interestingly,
all of them are non-zero (see example below), while
I expect them to be all zeros except the one corresponding
to the element with the delta function. 

Could you please comment on this?
Thanks a lot!

```C++
int main(int argc, char *argv[])
{
   int num_procs, myid;
   MPI_Init(&argc, &argv);
   MPI_Comm_size(MPI_COMM_WORLD, &num_procs);
   MPI_Comm_rank(MPI_COMM_WORLD, &myid);

   Mesh *mesh = new Mesh(2, 2, 2, Element::TETRAHEDRON, true, 1.0, 1.0, 1.0);

   ParMesh *pmesh = new ParMesh(MPI_COMM_WORLD, *mesh);
   delete mesh;

   const int dim = pmesh->Dimension();
   const int nEl = pmesh->GetNE();
   const int nFaces = pmesh->GetNFaces();

   pmesh->PrintCharacteristics();

   const int order =  0;

   FiniteElementCollection *hdiv_coll(new RT_FECollection(order, dim));
   ParFiniteElementSpace *R_space = new ParFiniteElementSpace(pmesh, hdiv_coll);

   Vector dir(3), loc(3);
   dir(0) = 0.0; dir(1) = 0.0; dir(2) = 1.0;
   loc(0) = 0.0; loc(1) = 0.0; loc(2) = 0.567;

   VectorDeltaCoefficient dipole(dir, loc(0), loc(1), loc(2), 1.0);

   VectorFEDomainLFIntegrator *vector_rhs_int(new VectorFEDomainLFIntegrator(dipole));

   Vector local_f(4);
   ElementTransformation *eltrans;

   for (int i = 0; i < nEl; i++)
   {
      eltrans = R_space->GetElementTransformation (i);
      vector_rhs_int->AssembleDeltaElementVect(*R_space->GetFE(i), *eltrans,   local_f);
      cout << "element " << i << "  local rhs  norm " << local_f.Norml2() << "\n";
   }
   MPI_Finalize();

   delete R_space;
   delete hdiv_coll;
   delete pmesh;

   return 0;
}           
```
The code produces:

```bash
...
element 0  local rhs norm 3.4641
element 1  local rhs norm 3.4641
element 2  local rhs norm 3.4641
element 3  local rhs norm 3.4641
element 4  local rhs norm 3.4641
element 5  local rhs norm 3.4641
element 6  local rhs norm 3.4641
element 7  local rhs norm 3.4641
element 8  local rhs norm 3.4641
element 9  local rhs norm 3.4641
...
```

**Comment by stefanozampini** [comment]
```
vector_rhs_int->AssembleDeltaElementVect(*R_space->GetFE(i), *eltrans,   local_f);
```

This is not the intended usage. Here you are using the integrator while instead you should assemble the linear form. By design, MFEM integrators do not know anything about the element id,  so they cannot distinguish if the delta belongs to that element or not.
Instead, when invoked, they just evaluate the basis functions https://github.com/mfem/mfem/blob/master/fem/lininteg.cpp#L57
The element transformation should carry the information of the point where the quadrature term is evaluated (and this is missing from your code).
Here is how the assembly of the delta terms is actually performed https://github.com/mfem/mfem/blob/master/fem/linearform.cpp#L206

**Comment by NikolayYavich** [comment]
Thanks a lot for your detailed explanation!
