### ISSUE TITLE
FindPointsGSLIB does not return right element indices for tets

### ISSUE THREAD

**Issue by rcarson3** [mfem/mfem#1508]
I was recently working on a side project that makes use of linear tets where I needed to find what elements a set of points belonged within. I first made use of ```FindPointsGSLIB``` and found that a few of the elements were outside of the range for how many the mesh contained. I have a feeling this might be due to the fact that the tet mesh is converted over to a hex mesh, and then later on the element numbers aren't mapped back to the original elements. 

I found that ```Mesh::FindPoints``` does work for my needs but is significantly slower. 

I've included what should be a minimal working example that should reproduce the problem.

[min_ex.zip](https://github.com/mfem/mfem/files/4679711/min_ex.zip)

**Comment by kmittal2** [comment]
Yes, the current version of the master does not return the right element number for simplices because of conversion to a quad/hex mesh. I am working on an update to FindPointsGSLIB where I have added this functionality of mapping the element number for simplices ([here](https://github.com/mfem/mfem/blob/findpts-crystalrouter/fem/gslib.cpp#L492)). Note that this function also maps the reference space coordinates from [-1, 1] (output by GSLIB) to [0, 1] (for MFEM).

**Comment by rcarson3** [comment]
@kmittal2 thanks for the quick feedback. I look forward to seeing this update brought into master :)

**Comment by kmittal2** [comment]
@rcarson3 I am closing this issue for now but feel free to reopen it if you have any further questions.
