### ISSUE TITLE
Net normal flux of a vector-function

### ISSUE THREAD

**Issue by NikolayYavich** [mfem/mfem#1533]
Dear MFEM team,

I am trying check three ways to compute the net normal flux 
of a vector-function g represented
in the RT0 space, i.e. 
![\displaystyle\int_{\partial \Omega}\vec{g} \cdot \vec{n} dS](https://render.githubusercontent.com/render/math?math=%5Cdisplaystyle%5Cint_%7B%5Cpartial%20%5COmega%7D%5Cvec%7Bg%7D%20%5Ccdot%20%5Cvec%7Bn%7D%20dS)

This could be achieved at least in the following ways:
1. Linear form of unity acting on vector-function g.
2. Linear form of g acting on unity.
3. Simply sum up boundary face DOFs of g.

Below are three pieces of my code that attempt to do this.
However, they all result in different answers.

Could you please comment on if these methods are correct/wrong/accurate.
Thanks a lot!
```C
   FiniteElementCollection *hdiv_coll(new RT_FECollection(0, 3));
   ParFiniteElementSpace *R_space = new ParFiniteElementSpace(pmesh, hdiv_coll);

   FiniteElementCollection *h1_coll( new H1_FECollection(1, 3));
   ParFiniteElementSpace *H1_space = new ParFiniteElementSpace(pmesh, h1_coll);

   ParGridFunction g(R_space);
   g.ProjectCoefficient(dgr);  // dgr is a VectorCoefficient

    // Method 1
   {
     ParLinearForm lf_bdr(R_space);
     ConstantCoefficient ones(1.0);
     lf_bdr.AddBoundaryIntegrator(new VectorFEBoundaryFluxLFIntegrator(ones), ess_bdr);
     lf_bdr.Assemble();

     cout << "1: surface integral "<< lf_bdr(g) << "\n";
  }
  // Method 2
  {
     ParLinearForm lf_bdr(H1_space);
     lf_bdr.AddBoundaryIntegrator(new  BoundaryNormalLFIntegrator(dgr), ess_bdr);
     lf_bdr.Assemble();

     ParGridFunction ones(H1_space);
     ones = 1.0;

     cout << "2: surface integral "<< lf_bdr(ones) << "\n";
  }
  // Method 3
   {
      double net_flux = 0.0;
      for (int k = 0; k < nFaces ; k++)
         if ( ! pmesh->FaceIsInterior( k  ) )
               net_flux += g[k];

      cout << "3: surface integral "<< net_flux << "\n";
   }
```

**Comment by mlstowell** [comment]
Hi, @NikolayYavich ,
This is an excellent question.  We need more examples that illustrate these issues.  I believe all three methods are correct although method 3 is clearly specialized to the RT0 case as you know.  As the mesh is refined they should all converge to the correct answer.

For this basis the degrees of freedom are computed (during projection) by evaluating the `dgr` function at a single point in the middle of each face.  This will limit the accuracy of methods 1 and 3.  If your boundary is curved, method 1 may be more accurate than method 3 because it will more accurately compute the area of the curved face.  Method 2 has the potential to be more accurate than the other two because it is integrating `dgr` over each boundary face and this integration uses 4 points per quadrilateral face if I'm not mistaken.  So clearly, method 2 has more information at its disposal.

Best wishes,
Mark

**Comment by NikolayYavich** [comment]
Hi Mark,

Thank you for your detailed answer.

Here is an example.
The domain is a ball of radius 0.09, ![\displaystyle\vec{g} = \frac{\vec{r}}{r^3}](https://render.githubusercontent.com/render/math?math=%5Cdisplaystyle%5Cvec%7Bg%7D%20%3D%20%5Cfrac%7B%5Cvec%7Br%7D%7D%7Br%5E3%7D). 
So the exact value for the integral is 4*pi = 12.56637.

I use a tetrahedral grid refine somewhat refined near the boundary.
```bash
Number of vertices : 146062
Number of edges    : 1025599
Number of faces    : 1750585  --  1750585 Triangle(s)
Number of elements : 871047  --  871047 Tetrahedron(s)
Number of bdr elem : 16982  --  16982 Triangle(s)
h_min              : 0.000680866
h_max              : 0.0203502
```
The results I receive
```bash
1: surface integral 12.5695
2: surface integral 12.5664
3: surface integral 25.1389
```

In fact, the method 2 is most accurate. 
Why the method 3 gives a twice larger value than the method 1? 

Thanks again,
Nikolay

**Comment by mlstowell** [comment]
Hi, @NikolayYavich ,
That surprises me as well.  Apparently, we define our RT degrees of freedom on triangular faces differently than I expected.  Of course, we are free to do so as long a as we remain consistent. Unfortunately, this means that method 3 comes with more caveats.  We cannot simply sum the degrees of freedom in this manner.  We need to keep track of the face type and use the appropriate scale factor.  For hexahedral and tetrahedral meshes this is easy but for mixed meshes (with wedges for example) the scale factor could change from one entry to the next.

Best wishes,
Mark

**Comment by tzanio** [comment]
Hmmm, I wonder if this is due to orientation of parallelization issues -- for the summation to work, all normals should point in the right direction and you should truly be looking at boundary faces, not faces shared between processors.

Do you still get incorrect results if you run on 1 MPI task, on a mesh like `inline-hex.mesh` without any refinement?

**Comment by mlstowell** [comment]
Yes, it fails on a single processor.  The issue is that the DoFs are computed as the function value at the interpolation point times the adjugate of the Jacobian.  There is no scaling by 1/2 for triangular faces so this sum ends up being twice as large.

**Comment by sshiraiwa** [comment]
May I ask somewhat relevant question? I am doing similar integration on the internal boundaries.
What I noticed is that even if I am taking the integration on a single boundary, meaning that the domain index of two sides of faces are all the same pair, the order is random. In other words, on some surface, the face normal is orienting one direction, say from domain 1 to domain 2,  and on the other surface, it orients oppositely. I am wondering if this is how it is supposed to be?

**Comment by mlstowell** [comment]
Hi, @sshiraiwa ,
I believe the face orientations for a single element are defined so that surface normals point outwards from the element.  Faces are defined by looping over the elements and then the faces within each element.  For each element's face there is a check to see if that face has already been encountered.  If not, a new face is created with orientation derived from that face's orientation with respect to that element i.e. outward from the first element that touches that face.

So, with this scheme the face orientations depend on the order in which the elements are traversed. If it is desired to have a consistent surface normal on the interface between two domains then the mesh elements would need to be reordered so that the elements of domain 1 are listed first followed by those of domain 2, etc.. The alternative is to define a vector field which can be used to determine a consistent surface normal and incorporate this into the flux computation.

Best wishes,
Mark

**Comment by sshiraiwa** [comment]
Hi @mlstowell, 
Thank you for the detailed explanation. This explains well what I observed. Sounds like what I should do is to define a surface vector orienting to a given domain attribute, although rearranging the element order in the input is interesting approach.
