### ISSUE TITLE
Non linear mechanical behaviours, bilinear form integrators and linear form integrator

### ISSUE THREAD

**Issue by thelfer** [mfem/mfem#1537]
Dear all,

In most mechanical solvers, the behaviour integration allows updating the stiffness matrix and the the inner forces simultaneously.

If I translate this in the `mfem` context, that would mean that the result of the behaviour integration shall be used both in a bilinear form integrator (for the assembly of the stiffness matrix) and in a linear form integrator (for the inner forces).

I am not sure how I shall do this efficiently because I don't want:

1. perform two times the behaviour integration, one in the bilinear form integrator and one in the linear form integrator.
2. perform the behaviour integration before the calls to the bilinear form integrator and linear form integrator because I would imply storrin the stresses and the consistent tangent operator (the equivalent of the stiffness matrix) at all integration steps.

Is there a mechanism in `mfem` that would allow me to solve my problem ? I really wish to have something that would be naturally integrated in the `Newton` solver.

Thanks for any help.

**Comment by rcarson3** [comment]
So, it sounds to me that one solution would be to build a class off of the ```NonlinearForm``` [link](http://mfem.github.io/doxygen/html/classmfem_1_1NonlinearForm.html) and ```NonlinearFormIntegrator``` class. Within the ```NonlinearForm``` based class you would want to combine the ```GetGradient``` and ```Mult``` functions into one. Then within the ```NonlinearFormIntegrator``` based class you would want to combine the ```AssembleElementGrad``` and ```AssembleElementVector``` functions into one.

This is the best thing I can think of based on your desire to avoid storing the tangent stiffness tensor at each quadrature point.

**Comment by thelfer** [comment]
@rcarson3 Thanks. That kind of advices are extremly useful for a new user as I am. This allows me explore `mfem` much more effectively.
May I ask how you do in `ExaConstit` ?

**Comment by rcarson3** [comment]
Within ```ExaConstit```, we have a set-up phase where we compute all of the necessary state/history variables, stresses, and tangent stiffness matrices at every quadrature points. We need to keep track of the state variables and stress at every quadrature point anyways, so it's not really an issue for us to have to keep track of theses values for only our current and previous time step values. Then we have classes based off the ```NonlinearForm``` and ```NonlinearFormIntegrator``` classes that help perform the necessary operations to compute either our RHS side or our matrix if we're doing a full assembly of everything. In order to make use of the GPU, we also have constructed partial-assembly variations that are matrix free versions of the above. If you're unfamiliar with partial assembly methods here's a brief [overview](https://mfem.org/performance/#performance-and-partial-assembly).

**Comment by thelfer** [comment]
@rcarson3 Indeed the only memory overhead that can be avoided is the storage of the tangent operator. It is good to know that a setup phase (at the beginning of every Newton step, right ?) can be set up. Thanks for the link.

**Comment by thelfer** [comment]
@rcarson3 BTW, is the behaviour integration also perform on the GPU ?

**Comment by rcarson3** [comment]
@thelfer yes the set-up phase is only performed once per newton iteration. Also, yes the RHS is also calculated on the GPU as well.

**Comment by thelfer** [comment]
@rcarson3 I am impressed. For the moment I only saw behaviour integration on the GPU only in pretty simple cases. Have you published something about it ?

**Comment by rcarson3** [comment]
We have not published anything on it, but our RHS side currently is only the div(stress) term which is pretty simple to compute. However, I'm pretty sure a lot of the work done within MFEM would make porting more complicated RHS over to the GPU fairly simple.
