### ISSUE TITLE
BlockILU for systems of PDEs

### ISSUE THREAD

**Issue by jehicken** [mfem/mfem#1554]
Hi Will @pazner,

I had a quick look at the `BlockILU` class.  How difficult would it be to adapt this to continuous-Galerkin-type discretizations, where the blocks are based on the conservative variables, for example?  Also, does it use non-overlapping additive Schwarz in parallel, or something else?

Thanks in advance,
Jason

**Comment by pazner** [comment]
Hi @jehicken,

If I understand correctly, you would like to do block ILU, where the blocks correspond to all the conservative variables at a single node? The easiest way to achieve this would be to use the ordering of degrees of freedom `Ordering::byVDIM` so that all the components for a single node appear consecutively. Then, setting the block size to the number of components should have the desired effect.

In parallel it is currently non-overlapping additive Schwarz, simply for ease of implementation. I'm sure we would be open to something more sophisticated.

Hope this helps,
Will

**Comment by jehicken** [comment]
Yes, I would like all the conservative variables at a single node, so the block CSR storage would use  5x5 block matrices in 3D.  We were already using `Ordering::byVDIM`, so hopefully it will be a simple swap of the preconditioner.

Thanks!
