### ISSUE TITLE
Essential BCs for Complex Operator with PA

### ISSUE THREAD

**Issue by stefanhenneking** [mfem/mfem#1556]
Consider a `SesquilinearForm` or `ParSesquilinearForm` for which we want to do partial assembly with essential boundary conditions (with real and/or imaginary component). 

In the full assembly case, the functions `SesquilinearForm::FormLinearSystem` and `ParSesquilinearForm::FormLinearSystem` use the `DiagonalPolicy` (or overwrite the diagonal manually) to adjust for either assembling the real matrix block ('1' on the diagonal) or the imaginary matrix block ('0' on the diagonal).

In the partial assembly case, these methods call `Operator::FormLinearSystem` which calls `Operator::FormConstrainedSystemOperator` where essential BCs are treated but without using any diagonal policy, thus as far as I understand the (imaginary) operator/rhs is not correctly modified in this case.

@dylan-copeland 
@psocratis 
@mlstowell

**Comment by v-dobrev** [comment]
We can certainly extend the class `ConstrainedOperator` to support different diagonal policies -- right now it just implements the matrix-free version of using ones on the eliminated block-diagonal.

**Comment by psocratis** [comment]
I think there is a way we can do this and keep the diagonal entries to be 1 even in the off-diagonal blocks (the imag part of the operator) by modifying accordingly the RHS. If I remember correctly that was how it was originally implemented by @mlstowell for SparseMatrix/HyperParMatrix. Basically instead of enforcing the essential dofs with  the equations

 `1 * x_r + 0 * x_i = b_r`
 `0 * x_r + 1 * x_i = b_i`

you can use these:

 `1 * x_r + 1 * x_i =  b_r + b_i `  
 `1  * x_r - 1 * x_i =  b_r - b_i `

In any case, I think extending the class `ConstrainedOperator`  to support other diagonal policies would be the preferred solution. 

@stefanhenneking I think we can move this to a private discussion and work on it together if you want.  

Socratis

**Comment by stefanhenneking** [comment]
I'm closing this issue (discussion can be continued in #1563).
