### ISSUE TITLE
Easy way to get vertices on the boundary?

### ISSUE THREAD

**Issue by izaid** [mfem/mfem#1599]
Hi all,

I've written a little extrusion program for a mesh, which works by extruding boundary faces. I know there is a way to get the number of boundary elements of a mesh (`mesh->GetNBE()`), but is there an easy way to get the number of vertices on the boundary and / or the list of vertices on the boundary?

What I am doing now is looping through all the boundary elements, adding their vertices to a big list, and removing duplicates. Is this basically the solution?

Thanks!

**Comment by v-dobrev** [comment]
There are currently no methods that return this information. What you are doing seems to be a good solution.

One indirect method to get a list of all boundary vertices is to define a linear FE space on the mesh and then construct the `ess_tdof_list` as in `ex1`/`ex1p`. Since for a linear space the dofs correspond to the vertices, the `ess_tdof_list` will contain exactly the list of all boundary vertices.

**Comment by izaid** [comment]
Thanks, @v-dobrev! I didn't think of the linear FE solution you proposed, but that's interesting. For now I'll just stick to what I'm doing, I think.
