### ISSUE TITLE
Electromagnetic problem examples

### ISSUE THREAD

**Issue by anjirom** [mfem/mfem#1617]
Hi everyone.

I am starting a new project and I would like to know if with MFEM it would be possible to carry out.

I would like to perform the electromagnetic simulation of a high frequency transformer winding (in 2D and 3D) and change the frequency of the current to evaluate the effects and their losses (skin effect and proximity effect).
Is this possible with MFEM?

In that case, what example do you recommend taking my first steps in MFEM?

Thank you very much.

**Comment by mlstowell** [comment]
Hi, @anjirom ,

MFEM is probably capable of simulating your problem of interest but I'd need to see more details before knowing what hurdles you might face.  Of course, MFEM is quite extensible so I expect any necessary features could be added if they aren't already in the library.

The best place to start is always example 1, [ex1p](https://github.com/mfem/mfem/blob/master/examples/ex1p.cpp).  This is only a Laplace solver but it gives a good introduction to MFEM's problem setup procedures.  Next you may want to look at example 3, [ex3p](https://github.com/mfem/mfem/blob/master/examples/ex3p.cpp).  This demonstrates using H(Curl), a.k.a. Nedelec, basis functions which are commonly used for electromagnetic simulations.

After that you can look at our electromagnetic miniapps, [Volta](https://github.com/mfem/mfem/blob/master/miniapps/electromagnetics/volta.cpp), [Tesla](https://github.com/mfem/mfem/blob/master/miniapps/electromagnetics/tesla.cpp), and [Joule](https://github.com/mfem/mfem/blob/master/miniapps/electromagnetics/joule.cpp) which solve electrostatic, magnetostatic, and eddy current problems respectively.  If you're planning to work in the time domain, Joule may be an excellent starting point for developing your own application.  This mini app solves the Maxwell equations in the limit where the displacement current can be ignored.  This reduces the full electromagnetic wave equation to a vector diffusion equation.  Joule also approximates the electromagnetic energy losses due to thermal heating in metal structures.

If you are planning to work in the frequency domain we don't currently have an example in MFEM's master branch which demonstrates this but you can look at a prototype code in a development branch called `hertz-dev`.  The code you may want to look at is [Hertz](https://github.com/mfem/mfem/blob/hertz-dev/miniapps/electromagnetics/hertz.cpp).  The main reason this is not yet in `master` is its reliance on sparse direct solvers which are not included in MFEM by default.  This miniapp should work well with SuperLU or STRUMPACK.  Our collaborators have also recommended using MUMPS through MFEM's PETSc interface.

I'd be happy to offer more targeted advice if you want to discuss specifics.

Best wishes,
Mark

**Comment by anjirom** [comment]
Hi and thanks for your answer.

My goal is to perform the full simulation of a high frequency transformer. I begin to study example 1 and I will follow the order that you have indicated to me to try carry out my project.

Thank you very much.

**Comment by tzanio** [comment]
Closing this for now. Feel free to reopen if you have additional questions.
