### ISSUE TITLE
Metis unavailable on appveyor and Travis

### ISSUE THREAD

**Issue by IdoAkkerman** [mfem/mfem#1631]
Both the appveyor and Travis seem to fail to connect to the glacos website when attempting to download metis. Perhaps just a glitch on their side?

**Comment by tzanio** [comment]
Unfortunately this seems to happen [periodically](https://github.com/mfem/mfem/issues/948).

@v-dobrev and @adrienbernede what do you think about moving the internal `tpls` repo to `mfem/tpls` or maybe `mfem/external` and use that in the CI runs on GitHub?

**Comment by adrienbernede** [comment]
I think it is important to host a mirror of the tarballs we need, especially since they don’t change very often.

Hosting 'tpls' on GitHub is an option.

**Comment by v-dobrev** [comment]
I was thinking we may be able to use the new spack public mirror (https://github.com/spack/spack/pull/17077) but I'm not sure if the older version of metis is mirrored. Also, it looks like the mirrored source files are stored by their hash, so it is not obvious what to download in general.

Since the main problem is the metis website, we can just mirror the two metis versions we use -- 4.0.3 used in travis and 5.1.0 used in appveyor. Another option for the repo name is `mfem/mirrors`.
