### ISSUE TITLE
Computing outer normal

### ISSUE THREAD

**Issue by J-Pi** [mfem/mfem#1639]
Hi, I have a problem with computing the outer normal in a boudary element (on a 2D mesh). I found out, that I can do this with the ElementTransformation and the CalcOrtho-Function. IIf I do this one time it works fine. Since I need the outer normal for every boundary element, I tried to do this in a loop. Now the problem is, that for the first iteration everything works fine, but from the second iteration on I always get the same result as in the first iteration. Here is the code I am using for this:

Working (BdrElement 4 as an example, works with every BdrElement):
`Vector nor(dim);`
`ElementTransformation *Trans = fespace->GetBdrElementTransformation(4);`
`CalcOrtho(Trans->Jacobian(), nor); [...]`
In this case `nor` is the outer normal of the BdrElement, if the element is part of a different boundary segment, `nor` changes.

Not Working (Compute Outer Normal for every BdrElement):
`for (int it = 0; it < fespace->GetNBE(); it++){`
`Vector nor(dim);`
`ElementTransformation *Trans = fespace->GetBdrElementTransformation(it);`
`CalcOrtho(Trans->Jacobian(), nor);`
`[...]}`
In this case `nor` is the same in every iteration, but from my understanding it should change, when the current BdrElement is part of a different segemnt of the boundary.

Is there any way to fix this? I am grateful for any reply.

**Comment by mlstowell** [comment]
Hello, @J-Pi ,

Jacobians are relatively expensive to compute so the element transformation object tries to reuse the last Jacobian whenever possible.  The behavior you're seeing is clearly a consequence of this.  The easiest way to overcome this is to specify at which point you want the Jacobian computed each time you request it.  The Jacobian is often a function of the position within the element so setting the position will instruct the element transformation object to recompute the Jacobian the next time it's requested.  One way to do this is to add this line before `CalcOrtho`:
```
Trans->SetIntPoint(&Geometries.GetCenter(Trans->GetGeometryType()));
```

Best wishes,
Mark

Note to other developers: perhaps we should add another mechanism for resetting the `EvalState` in `ElementTransformation` objects so that altering the point matrix will also result in resetting its state.

**Comment by J-Pi** [comment]
Hi Mark,

thank you for the fast answere. It was really helpful and my problem is solved.

Wishes,

JP
