### ISSUE TITLE
SidreDataCollection produces runtime warning from Axom

### ISSUE THREAD

**Issue by joshessman-llnl** [mfem/mfem#1640]
`SidreDataCollection::addVectorBasedGridFunction` and `SidreDataCollection::addScalarBasedGridFunction` both check for corresponding internal buffers, and use externally managed memory otherwise.  This check is a null check of the return value from a Sidre function that will display a warning before returning a null pointer, which is potentially misleading to the user and can clutter user output.

I am happy to submit a PR with a proposed solution, if appropriate.

The following was observed when using the binary output option in MFEM's example 9 (`./ex9 -visit -binary`):
```
***********************************
LEVEL=WARNING
MESSAGE=Failed Check: !intpath.empty() && group->hasChildView(intpath)
[Group: 'Example9/named_buffers'] No View with name 'mesh_nodes'
FILE=axom/src/axom/sidre/core/Group.cpp
LINE=122
***********************************

***********************************
LEVEL=WARNING
MESSAGE=Failed Check: !intpath.empty() && group->hasChildView(intpath)
[Group: 'Example9/named_buffers'] No View with name 'solution'
FILE=axom/src/axom/sidre/core/Group.cpp
LINE=122
***********************************
```

**Comment by v-dobrev** [comment]
Yes, I don't quite understand why this warning is generated -- my interpretation of the documented behavior for `getView()` that "If no such View exists, nullptr is returned" is that such case is normal (i.e. no warning will be generated).

In any case, we can certainly check explicitly if the view exists with `hasView()` to avoid the warning.

A PR to resolve this issue will be welcome. Thank you.

**Comment by kennyweiss** [comment]
Correct -- in addition to returning `nullptr`, `sidre` also produces a warning if you try to access a view that is not present.
So, to avoid a warning, one would want to first check if `group->hasView()` before calling `group->getView()`.
My understanding is that this is because the assumption is that codes know which views should be available, so this warning is meant to help them / prevent against typos.

In an application that uses `SidreDataCollection`, we have a function that performs such this check.
(Something to the effect of `getOrCreateView(name)` )

In addition to the fix here, we should probably also update the documentation for `getView()` to indicate that it will produce a warning.

**Comment by tzanio** [comment]
@joshessman-llnl, what is the status of this? Were you able to resolve it?

**Comment by tzanio** [comment]
ping: @joshessman-llnl

**Comment by joshessman-llnl** [comment]
SidreDataCollection is in the process of being moved to Axom (see https://github.com/LLNL/axom/pull/318), so this is no longer a concern.
