### ISSUE TITLE
Stress output: integration points, element nodal, averaged nodal

### ISSUE THREAD

**Issue by benzwick** [mfem/mfem#1676]
How can I output the following in the elasticity example (ex2.cpp):

1. Stress at integration points.

2. Element nodal stress: the stress computed at the quadrature points extrapolated to the nodes of the element. This is a piecewise function of one degree less than the displacements.

3. Averaged nodal stress: the element nodal stress from step 2 averaged at each node. This is a continuous function of the same degree as the displacements.

The reason for using these quantities is that I would like to compare my results with other software such as Abaqus. Later, I want to use the averaged nodal stress to computed derived quantities such as principal stresses and invariants such as von Mises stress. This can be done as a post-processing step outside of MFEM although it would be nicer to have everything in the same place and do it at the same time as the above.

In Abaqus, the above corresponds to the following keyword options:

1. `*EL PRINT, POSITION=INTEGRATION POINTS`

2. `*EL PRINT, POSITION=NODES`

3. `*EL PRINT, POSITION=AVERAGED AT NODES`

I am trying to do this in FEniCS as well as described in this [question](https://fenicsproject.discourse.group/t/average-nodal-stress-and-principal-stress-convert-tensor-function-from-dg1-to-cg2/3872).

Also, what would be the best file format to use for this in MFEM? Currently I am using ParaView for visualization.
Does MFEM support higher order data as described [here](https://www.paraview.org/Wiki/ParaView_Release_Notes#Arbitrary-order_Lagrange_finite_element_support)?

**Comment by rcarson3** [comment]
@benzwick you should be able to output the quadrature points if they're ```QuadratureFunction``` using the ```VisitDataCollection``` using the ```RegisterQField``` function. 

Now if you're quadrature points lie at the same points as those in an ```L2_FECollection``` you can just make use of either the 
```VectorQuadratureFunctionCoefficient``` or ```QuadratureFunctionCoefficient``` class and project those values onto the L2 ```GridFunction```. Here's a snippet of how to do that:
```C++
      VectorQuadratureFunctionCoefficient qfvc(*qf);
      gf.ProjectDiscCoefficient(qfvc, mfem::GridFunction::ARITHMETIC);
```
You might also find some interest in the PR it was introduced in as well #1281 .

I believe you might be able to then use the ```GridFunction::ProjectGridFunction``` to get the last quantity. However, I've never really messed with this one too much, so I could definitely be wrong here. Alternatively, you might be able to make use of some of the code I wrote for #1281 that we decided was best to leave out for that PR found here: https://github.com/mfem/mfem/blob/quadrature-project-dev/fem/field_interpolant.hpp#L69-L76 . The set of functions I've linked to there perform the classical L2 projection method described here: https://doi.org/10.1016/0168-874X(94)00054-J at Eq 13. 

I've personally tested the first two methods in my application ```ExaConstit```.  I've found that when working with the L2 FESpace gridfunctions that if I'm working with non-negative quantities such as the von Mises stress the values outputted to the files can be wrong in that negative values can be present. I can't really fault the MFEM functions here, since they aren't aware of the non-negative restriction. So, you'll probably want to make use of the built in calculators in either ParaView or VisIT to perform these derived calculations.

Also, yes MFEM does support higher-order data in the ```ParaViewDataCollection``` http://mfem.github.io/doxygen/html/classmfem_1_1ParaViewDataCollection.html#a187f58b706c21521b4cee42e3c3821a5

**Comment by benzwick** [comment]
Thanks @rcarson3, that is extremely helpful!

> edit: I just realized I forgot that you were asking about example 2 for the above. The below response is more related to how you might do the above in general.

It doesn't necessarily have to be about example 2 (more general is probably better). I've used a lot of code from example 17 as well so it's probably closer to that one now anyway.

As a summary, and to confirm that I have understood correctly, for the above steps I should use:

1. `quad_stress.ProjectCoefficient(stress_coef);`

2. `disc_stress.ProjectCoefficient(stress_coef);`

3. `cont_stress.ProjectDiscCoefficient(stress_coef, mfem::GridFunction::ARITHMETIC);`

where `stress_coef` is the `StressCoefficient` from example 17, `quad_stress` is a `QuadratureFunction`, `disc_stress` is a `GridFunction` on a L2 (degree n-1) FE space, and `cont_stress` is a `GridFunction` on a H1 (degree n) FE space. However, I don't understand what is the difference between `Coefficient`, `QuadratureFunctionCoefficient` and the `StressCoefficient` defined in example 17?

So far I tried steps 2 and 3 which seem to give me the same results as element nodal and averaged nodal stress in  Abaqus (at least for linear elements).

> you should be able to output the quadrature points if they're `QuadratureFunction` using the `VisitDataCollection` using the `RegisterQField` function.

It seems there is some support for integration points in ParaView as well but it might require a user provided reader for the integration point data:
- https://gitlab.kitware.com/vtk/vtk/-/issues/17124
- https://vtk.org/Wiki/VTK/VTK_integration_point_support
- https://www.paraview.org/Wiki/ParaView/Users_Guide/List_of_filters#Generate_Quadrature_Points

Is it possible to output the integration point positions, quadrature scheme, and the field values at those points so I can use the quadrature points filter to read these into ParaView? Or do you recommed using Visit instead?

> Alternatively, you might be able to make use of some of the code I wrote for #1281 that we decided was best to leave out for that PR found here: https://github.com/mfem/mfem/blob/quadrature-project-dev/fem/field_interpolant.hpp#L69-L76 . The set of functions I've linked to there perform the classical L2 projection method described here: https://doi.org/10.1016/0168-874X(94)00054-J at Eq 13.

Do you think it would be worth adding those functions in a new PR? A built-in way to perform the L2 projection sounds quite useful.

> I've found that when working with the L2 FESpace gridfunctions that if I'm working with non-negative quantities such as the von Mises stress the values outputted to the files can be wrong in that negative values can be present.

I don't understand why this would happen. Do you compute von Mises stress at the quadrature points then project onto the nodes or the other way around?

**Comment by rcarson3** [comment]
@benzwick so I will say I'm not as familiar with ex17 just because I work with CG methods, so when I started off I looked at ex10 and ex19.

If we look at the ```QuadratureFunction``` [class](http://mfem.github.io/doxygen/html/classmfem_1_1QuadratureFunction.html) we can see it's built off the vector class, so the first method won't work. However, if you set up your ```QuadratureFunction``` to be of the same order as your L2 GridFunction you should just be able to copy over the values from that variable to the QF. The other two methods look fine to me if you're making use of that ```StressCoefficient```.

>However, I don't understand what is the difference between Coefficient, QuadratureFunctionCoefficient and the StressCoefficient defined in example 17?

So, the ```Coefficient``` class is pretty much our base class for describing these other coefficient classes. The ```StressCoefficient``` in this example evaluates a function at a given integration point in an element and returns that to the value to the user. A ```QuadratureFunctionCoefficient``` simply holds a ```QuadratureFunction``` with a vdim of 1 and when given an integration point for an element it simply returns the value associated with that within the ```QuadratureFunction```.

>It seems there is some support for integration points in ParaView as well but it might require a user provided reader for the integration point data
>
> * https://gitlab.kitware.com/vtk/vtk/-/issues/17124
> * https://vtk.org/Wiki/VTK/VTK_integration_point_support
> * https://www.paraview.org/Wiki/ParaView/Users_Guide/List_of_filters#Generate_Quadrature_Points
>
>Is it possible to output the integration point positions, quadrature scheme, and the field values at those points so I can use the quadrature points filter to read these into ParaView? Or do you recommed using Visit instead?` 

So, if you wanted to output the quadrature data to ParaView you would need to add that functionality to the ```ParaViewDataCollection```, since it's currently not supported. Now the VisitDataCollection will output the quadrature point data as of #1513 . However, another PR is needed on the VisIT side of things in order to actually visualize the data. So, I'm not too sure I can really one over the other. The only thing I can say is at least with using the VisitDataCollection you can output the quadrature point data and then investigate it that data with something like python.

>Do you think it would be worth adding those functions in a new PR? A built-in way to perform the L2 projection sounds quite useful.

So, we do have plans of eventually providing these functionalities in a new PR. However, it was decided at the time that more design work would be needed for that work.

>I don't understand why this would happen. Do you compute von Mises stress at the quadrature points then project onto the nodes or the other way around?

I'm computing my von Mises stress values at the quadrature points and transferring them over to an L2 FES gridfunction, since the points for both in my case were the exact same place. So, it's when that gridfunction is saved off to that things are projected to where the mesh nodes are located which is what causes the problem. I go into this a bit more here https://github.com/mfem/mfem/pull/1281#issuecomment-619308399

Hope this helps clarify at least some of your questions.

**Comment by benzwick** [comment]
Thanks @rcarson3, that answers most of my questions.

Regarding the alternative methods, how difficult would it be to implement the "superconvergent patch recovery" (SPR) method described in the paper by Zienkiewicz and Zhu (and references therein) that you mentioned previously? It requires the neighboring elements and associated nodal variables (Fig 4 in the paper). I'm interested in comparing different stress recovery methods and SPR appears to be the most accurate (but may not be straightforward to apply) compared to nodal averages, L2 local projection and L2 global projection.

**Comment by rcarson3** [comment]
>Regarding the alternative methods, how difficult would it be to implement the "superconvergent patch recovery" (SPR) method described in the paper by Zienkiewicz and Zhu (and references therein) that you mentioned previously? It requires the neighboring elements and associated nodal variables (Fig 4 in the paper). I'm interested in comparing different stress recovery methods and SPR appears to be the most accurate (but may not be straightforward to apply) compared to nodal averages, L2 local projection and L2 global projection.

@benzwick so I remember @v-dobrev talking about ways to do take into account only local variations when doing these sort of projections. So, he'd probably be better able to respond to your comment about implementing the SPR method than me.
