### ISSUE TITLE
How to use GetElementAverages for set of variables?

### ISSUE THREAD

**Issue by vkorchagova** [mfem/mfem#1715]
Good evening,

I want to add the slope limiter functionality to the code for DG compressible Euler equations. I need to compute cell average values for all conservative variables. I try to use `GridFunction::GetElementAverages(GridFunction& avgs) `, but this function gives me average values only for the 1st conservative variable (density); the other values are equal to nan. 

My code is the following:
```c++
   DG_FECollection fec(order, dim);
   FiniteElementSpace fes(&mesh, &fec);
   FiniteElementSpace dfes(&mesh, &fec, dim, Ordering::byNODES);
   FiniteElementSpace vfes(&mesh, &fec, num_equation, Ordering::byNODES);

   // The solution u has components {density, x-momentum, y-momentum, energy}.
   // These are stored contiguously in the BlockVector u_block.
   Array<int> offsets(num_equation + 1);
   for (int k = 0; k <= num_equation; k++) { offsets[k] = k * vfes.GetNDofs(); }
   BlockVector u_block(offsets);
   // Initialize the state.
   VectorFunctionCoefficient u0(num_equation, InitialCondition);
   GridFunction sol(&vfes, u_block.GetData());
   sol.ProjectCoefficient(u0);
   // prepare for averages
   DG_FECollection fec_avg(0, dim);
   FiniteElementSpace fes_avg(&mesh, &fec_avg, num_equation);
   BlockVector u_block_avg(offsets);
   GridFunction avgs(&fes_avg, u_block_avg.GetData());
   sol.GetElementAverages(avgs); 
```
... and I have the following output (this is the 2-cells 2D quadrilateral mesh, density is the linear function just for test, momentum and density are the constant functions):
```
sol size =  32; sol =0.12764156 0.13485844 0.12764156 0.13485844 0.14014156 0.14735844 0.14014156 0.14735844
0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0
0.25 0.25 0.25 0.25 0.25 0.25 0.25 0.25
avgs size =  8
FiniteElementSpace
FiniteElementCollection: L2_2D_P0
VDim: 4
Ordering: 0

0.13125
0.14375
-nan
-nan
-nan
-nan
-nan
-nan
```
How to use GetElementAverages for the set of conservative variables correctly?

--
Many thanks,
Victoria

_Originally posted by @vkorchagova in https://github.com/mfem/mfem/issues/673#issuecomment-677761643_

**Comment by vladotomov** [comment]
Hi Victoria,

The call  `sol.GetElementAverages(avgs)` would work only if `sol` and `avgs` were scalar functions (as specified in the documentation). You can still use the function, but you would have to loop over the variables and reference each component, something like this:
```
FiniteElementSpace fes_avg_scalar(&mesh, &fec_avg);
for (int i = 0, i < num_equations; i++)
{
   GridFunction sol_i, avgs_i;  
   sol_i.MakeRef(&fes, sol, offset_sol[i]);
   avgs_i.MakeRef(&fes_avg_scalar, avgs, offset_avgs[i]);
   sol_i.GetElementAverages(avgs_i);
}
```

I also noticed that `BlockVector u_block_avg(offsets);` might be wrong, because `offsets` are sized by `vfes`, instead of `fes_avg`.

Also, currently your `sol` only contains the velocity components. An example of similar BlockVector construction can be found in [Laghos](https://github.com/CEED/Laghos/blob/e9e215b59577a3b1842defdfacf11ea799db09e3/laghos.cpp#L458-#L480).

**Comment by vkorchagova** [comment]
Dear @vladotomov,
it works! Many thanks for your reply!
