### ISSUE TITLE
Local absorbing (scattering) boundary condition with tangent derivative?

### ISSUE THREAD

**Issue by izaid** [mfem/mfem#1725]
Hi all,

I'm solving some wave scattering problems in H1, basically the scalar Helmholtz equation. I'm trying to simulate an approximately infinite space, where the actual infinite version of the problem satisfies the Sommerfeld radiation condition in the far field. I've implemented PML, similar to Example 25 (very useful!), but I'd very much like to compare with a local absorbing condition. In particular, I'd like to implement the following

<img width="312" alt="Screen Shot 2020-08-26 at 6 26 51 PM" src="https://user-images.githubusercontent.com/482179/91336753-4d07fa80-e7ca-11ea-8dd2-aa0af49cde7d.png">

where u is the field I'm solving for, omega is some constant, n is the normal to the boundary, and s is the *tangent* to the boundary. This boundary condition is available, for instance, in COMSOL.

Is such a boundary condition possible in MFEM? The first term seems like it might be possible with DGDiffusionIntegrator, the second term is just BoundaryMassIntegrator, and I have no idea about the third term! Am I missing something or is this possible?

Thanks!

**Comment by psocratis** [comment]
Hi @izaid , 

I am glad you found the PML example useful. 

Regarding you question here is my take. 
Just to clarify... you wouldn't need the first term above, since it would be replaced by the other two, right?  
Then, the second term is indeed `BoundaryMassIntegrator`. So without the third term you would have the usual impedance (Robin or first-order scattering) condition. 

Unfortunately, there is no integrator right now that would compute the third term in MFEM. However, you/we might be able to put it together. 

Do you need this for 2D or 3D (or both) problems? 

Best, 

Socratis
