### ISSUE TITLE
Assign a Vector to a ParGridFunction 

### ISSUE THREAD

**Issue by chang-yiyi** [mfem/mfem#1739]
Hi all,

I want to know what differences the below operations 1 and 2 are in parallel programming.
```
Vector vec;
ParGridFunction pgf;

pgf.SetFromTrueDofs(vec); // 1
pgf = vec; // 2
```
Thanks.

**Comment by tzanio** [comment]
There is no difference. 

They both set the `pgf` grid function values from the true degrees of freedom in `vec`. 

This corresponds to `pgf = P vec` in https://mfem.org/pri-dual-vec/.

**Comment by chang-yiyi** [comment]
Hi @tzanio , thanks for reply.

For `pgf = vec`, I see it will call the below function eventually.
```
Vector &Vector::operator=(const Vector &v)
{
#if 0
   SetSize(v.Size(), v.data.GetMemoryType());
   data.CopyFrom(v.data, v.Size());
   UseDevice(v.UseDevice());
#else
   SetSize(v.Size());
   const bool use_dev = UseDevice() || v.UseDevice();
   v.UseDevice(use_dev);
   // keep 'data' where it is, unless 'use_dev' is true
   if (use_dev) { Write(); }
   data.CopyFrom(v.data, v.Size());
#endif
   return *this;
}
```
It seems that `pgf = vec` just copy `data` of `vec` to `data`(because `pgf` is an object of `Vector` as well, there is a `Memory<double> data` in it) of `pgf`.

But `pgf.SetFromTrueDofs(vec)` will call 
```
void ParGridFunction::Distribute(const Vector *tv)
{
   const Operator *prolong = pfes->GetProlongationMatrix();
   prolong->Mult(*tv, *this);
}
```

**Comment by tzanio** [comment]
Sorry, I didn't check carefully.

I assumed `vec` is a `HypreParVector` in the second call, in which case the two are identical because both call `Distribute`. The prolongation matrix is generally not identity but a rectangular matrix with more rows than columns. Given "true" i.e. globally unique degrees of freedom, it computes the local degrees of freedom, which could be just communicating values in parallel, or actual interpolation with AMR.

When `vec` is a `Vector`, you are correct that `pgf = vec` just copies the values. Note that in that case, the size of `vec` is the local size of `pgf` the local "all dofs" number. That is not what `pgf.SetFromTrueDofs(vec)` -- for that call, `vec` should be of the size of local "true dofs".

Regarding 3 and 4: `MakeRef()` just identifies a subvector as a grid function. In particular, `x` is a block vector of grid functions, one after the other, all of them on their "all dofs". In contrast, `trueX` is a vector on the unique "true dofs" and so each of its components is smaller.  This is hopefully explained better in https://mfem.org/pri-dual-vec/.

Hope this helps,
Tzanio

**Comment by chang-yiyi** [comment]
Thanks @tzanio , your explanation is so clear.
