### ISSUE TITLE
Adjoint curl, Nedelec elements, Delaunay-Voronoi meshes?

### ISSUE THREAD

**Issue by Marshdweller** [mfem/mfem#1747]
Dear MFEM developers

I would like to compute the adjoint curl of a vector field expanded into Nedelec basis functions, is that possible ?

Basically, I solve the Diriclet problem like this one,

(1) curl curl E - k^2 E=F

with the lowest order Nedelec elements. Then  I compute the magnetic field as 

H=Const*curl E =Const * Q * A^{-1} * F = S * F,

where 
Q is the matrix of curl operator,
A is the system matrix arising in (1),
S=Const * Q * A^{-1}.

Now, given some Y, I need to compute the following quantity

(2) X= adj(S) * Y = adj(Const) * adj(A^{-1}) * adj(Q) * Y,

where 'adj' stands for Hermitian conjugate.

My question is: how to compute adj(Q)=adj(curl) ? 
I suspect that I will have to build the dual (Voronoi) mesh, is it correct ?

Thank you very much!

**Comment by v-dobrev** [comment]
If I understand your question correctly, all the operators you have are real, so adj(Q)=Q^T. To apply the action of the transpose matrix you can use the method `MultTranspose`.

**Comment by Marshdweller** [comment]
> If I understand your question correctly, all the operators you have are real, so adj(Q)=Q^T. To apply the action of the transpose matrix you can use the method `MultTranspose`.

@v-dobrev
Thank you for your time!

I would like to clarify my question. Operation H=curl E can be seen as the application of a rectangular matrix Q to E, i.e. H=Q*E. I need to compute A=Q^T *B, such that <Qx,y>=<x,Q^T y> holds for any pair x,y (with proper dimension).

It seems that you recommended to modify Vector::GetCurl by transposing the shape matrix. So I outlined the function as follows. Could you please have a look at it ?



```
//Computing A = Q^T * B, where Q^T is the matrix of adjoint curl
//For simplicity, B is assumed real-valued

class MyGridFunction: public GridFunction
{
...
	Vector A; //<-- vector of length equal to the number of DoFs (edges)

	Vector B_x; //<-- vector of length equal to number of elements (tets)
	Vector B_y; //<-- vector of length equal to number of elements (tets)
	Vector B_z; //<-- vector of length equal to number of elements (tets)
...
	void MyGridFunction::GetCurlAdjoint(ElementTransformation &tr);
};


void MyGridFunction::GetCurlAdjoint(ElementTransformation &tr)
{

	int elNo = tr.ElementNo;
	const FiniteElement *FElem = fes->GetFE(elNo);
	
	// Assuming ND-type space with FElem->GetDim()=3
	
	Array<int> dofs;
	fes->GetElementDofs(elNo, dofs);
	DenseMatrix curl_shape(FElem->GetDof(), FElem->GetDim());
	FElem->CalcCurlShape(tr.GetIntPoint(), curl_shape);
	
	Vector B_loc   (FElem->GetDim());  //x,y,z
	Vector JT_B_loc(FElem->GetDim());
		
	//The following code contributes to all DoFs (==edges) assigned to this element

	//Extract values of 3D physical vector corresponding 
	//to this element (i.e. attached to this tetrahedron)
	B_loc(0) = B_x(elNo);
	B_loc(1) = B_y(elNo);
	B_loc(2) = B_z(elNo);
	
	tr.Jacobian().MultTranspose(B_loc, JT_B_loc);
	
	Vector result(FElem->GetDof());
	curl_shape.Mult(JT_B_loc, result);
	result /= tr.Weight();
	
	//Adding contribution to A
	A.AddElementVector(dofs,1.0,result);

       //Complex-valued B requires some modifications
}
```

**Comment by mlstowell** [comment]
Hi, @Marshdweller ,

The `Q` operator that @v-dobrev is referring to is computed using the [CurlInterpolator](https://github.com/mfem/mfem/blob/a40523a7cfe6bb0037311cd46200e2a5eddfc180/fem/bilininteg.hpp#L2906).  Such an operator is defined on the entire domain not just a single element.  Normally this is used to compute the curl of an H(Curl) field (i.e. expressed in terms of the Nedelec basis) and produce a result in H(Div) (i.e. expressed in terms of the Raviart-Thomas basis).  This works in a particularly nice manner because the curls of the Nedelec basis functions are contained in the space of Raviart-Thomas basis functions.

If your angle bracket notation is referring to the Euclidean inner product on an n-dimensional real space then clearly <Qx,y>=<x,Q^Ty> for all x and y of the appropriate dimensions.  However, such an inner product has no physical meaning because it ignores the relative weights associated with the different degrees of freedom due the variations in element sizes.

We'd be happy to offer more advice but I don't think we really understand what you're trying to accomplish.

Best wishes,
Mark

**Comment by Marshdweller** [comment]
Dear @mlstowell and @v-dobrev 

Thank you. Perhaps this is what I wanted (?). I will try this out.

"Such an operator is defined on the entire domain, not just a single element," - sure. 
"...produce a result in H(Div) (i.e. expressed in terms of the Raviart-Thomas basis)" - this makes perfect sense for me
"I don't think we really understand what you're trying to accomplish" - this is a very classical task in the context of coefficient inverse problems, although FEM complicates things.

Say, we have a forward solver,
rot rot E - k*E=F,   (1)
which is formally expressed as E=F_e(k), F_e : k->E (a forward-problem operator).
Then we compute H as follows,
H=rotE,    (2)
which is formally expressed as H=F_h(k), Fh : k->H. Clearly Fh=Q(Fe).

What I am trying to do is to compute product y=adjoint(J)*x needed for optimization. 
Here J=d Fh / d k (Jacobian of Fh with respect to coefficient k).
It turns out, to compute y for given x I need not only solve the adjoint of problem (1), but also to compute operator adj(Q).  This is a direct consequence of the fact that I optimize H, but the forward solver produces E (for some reason).

Regards,
M

**Comment by mlstowell** [comment]
Hi, @Marshdweller ,

Thank you.  I see now.  We have a few people here working on adjoint methods for optimization problems including @bslazarov and @jamiebramwell who may be interested as well.

Presumably you're interested in optimizing some functional  `G(H(k))` which can probably be expresses as a linear or non-linear function of `H`.  For simplicity let's assume it's linear so that we can represent `G` as a `LinearForm`.  In this case `G` is just a vector of the same length as `H` and your `J = d Fh / d k` would just be given by `Q d Fe / d k`.  This implies that `adjoint(J) = adjoint(d Fe / d k) transpose(Q)` so you'l be computing `(rot rot - k)^{-1} Q^T G`.  There are at least three different ways to compute `Q^T G` but @v-dobrev 's suggestion of using `Q.MultTranspose(G, QG)` is certainly the easiest.

Best wishes,
Mark

**Comment by Marshdweller** [comment]
@mlstowell , it is just like you wrote. I have checked  CurlInterpolator as per @v-dobrev , and it works. Thank you so much !

The minimal working example is given below for reference. I just wonder what is the other out of  the "three different ways to compute `Q^T G`" mentioned by Mark?

```
		const char * mesh_file = "../spherical_shell.mesh";
		Mesh *mesh = new Mesh(mesh_file, 1,0);

		int dim  = mesh->Dimension();
		mesh->SetAttributes(); 

		int nd_order = 1;//The lowest order ND elements
		int rt_order = 0;//The lowest order RT elements
		FiniteElementCollection *nd_coll = new ND_FECollection(nd_order, dim); 
		FiniteElementCollection *rt_coll = new RT_FECollection(rt_order, dim); 

		FiniteElementSpace *nd_fes 	= new FiniteElementSpace(mesh, nd_coll,dim );
		FiniteElementSpace *rt_fes 	= new FiniteElementSpace(mesh, rt_coll,dim );
		
		DiscreteLinearOperator * dlo = new DiscreteLinearOperator(nd_fes,rt_fes);

		DiscreteInterpolator * di = new CurlInterpolator;
		dlo->AddDomainInterpolator(di);
		dlo->Assemble();
		
		SparseMatrix &Q(dlo->SpMat());

		GridFunction x(nd_fes);
		GridFunction y(rt_fes);
		
		x.Randomize();
		y.Randomize();

		GridFunction Qx(rt_fes);
		GridFunction QTy(nd_fes);

		//Qx=Q*x
		Q.Mult(y,Qx);

		//QTy=Q^T * y
		Q.MultTranspose(y,QTy);
		
		// <Q*x,y> == <x,Q^T*y>
		double L = Qx*y;
		double R = QTy*x;

		printf("L = %.3e, R = %.3e, rerr= %.3e\n",L,R,fabs((L-R)/L));
```

which produces 
`L = 5.331e+02, R = 5.331e+02, rerr= 5.758e-15`

**Comment by mlstowell** [comment]
Hi, @Marshdweller ,

The three possibilities are:
1) `Q->MultTranspose(...);`
2) Build transpose of `Q` from `Q`.
```
   SparseMatrix * QT = Transpose(Q);
   QT->Mult(...);
```
3) Build transpose of `Q` directly
```
   DiscreteInterpolator * di = new CurlInterpolator;
   TransposeInterpolator *ti = new TransposeInterpolator(*di);
   dlo->AddDomainInterpolator(ti);
   dlo->Assemble();
```
Note that the `TransposeInterpolator` class does not yet exist but it should be trivial to implement based on the [`TransposeIntegrator`](https://github.com/mfem/mfem/blob/a40523a7cfe6bb0037311cd46200e2a5eddfc180/fem/bilininteg.hpp#L214) class.

Option 2 is, I think, what @v-dobrev was suggesting.  This option will probably be the most efficient if you need to use both `Q` and `QT` repeatedly within your optimization loop.  If you only need `QT` then option 3 would probably be most efficient and use less memory.  Option 1 is the easiest to implement and it uses less memory than option 2 but it will likely be more computationally expensive.

Best wishes,
Mark
