### ISSUE TITLE
Difference between H1_FECollection space nodes and DG_FECollection space ?

### ISSUE THREAD

**Issue by LeilaSalomon** [mfem/mfem#1796]
Hello everybody !  

H1_FECollection is a finite element space where the solutions are solved on the nodes of the mesh, that's right ?
If I understood correctly, on the DG_FECollection space, solutions are solved on different nodes, they are no longer located on the nodes of the mesh, but inside each element ?

Regards,

Leïla

**Comment by pazner** [comment]
With DG, the default nodal points are Gauss-Legendre points (lying in the interior of the elements). However, it is still possible to use Gauss-Lobatto points (same as the default for H1) like this:
```c++
DG_FECollection fec(order, dim, BasisType::GaussLobatto);
```
I find this is often a better choice than Gauss-Legendre, since it can be useful to have the same nodes as H1, take advantage of nodes on the element faces, etc.

**Comment by LeilaSalomon** [comment]
Hello,

Thank you very much for your reply, you were of great help !
