### ISSUE TITLE
Derefine strategy

### ISSUE THREAD

**Issue by tangqi** [mfem/mfem#1810]
I noticed in my application that derefiner is very inefficient. I think the reason is the refining strategy and derefining strategy we have in mfem are actually different. The refiner relies on a combination of relative value and absolute value with respect to element errors, while the derefiner only uses an absolute value compared to a threshold.  

I simply try something like
```c++
   const double total_err = GetNorm(local_err, mesh);
   const double true_threshold = std::max(total_err * total_fraction, threshold);
   bool derefs = mesh.DerefineByError(local_err, true_threshold, nc_limit, op);
```
Derefiner becomes much more efficient. 

So I am curious why such a strategy was not implemented by default. Is there something I am missing? I believe this strategy is common in practice. 

Qi

**Comment by tangqi** [comment]
ping @jakubcerveny

**Comment by jakubcerveny** [comment]
Sorry for the late answer. I think at the moment, ThresholdDerefiner is just a simple wrapper around Mesh::DerefineByError, and may need extending based on practical requirements. I think nobody just got around to doing that yet, that's all.

On a more philosophical note, I personally prefer to use the low-level functions (Mesh::GeneralRefinement, Mesh::DerefineByError), just like you did above, and have not been a huge fan of the fancy Refiner/Derefiner classes, which are confusing to me. The different refinement strategies are nice, but I would prefer them packaged in discrete building blocks that the users connect themselves (estimate errors -> select elements -> refine/derefine), instead of having these steps hidden inside an opaque class.
