### ISSUE TITLE
How to use ComputeElementFlux and ComputeFluxEnergy?

### ISSUE THREAD

**Issue by nghiakvnvsd** [mfem/mfem#1839]
Hi everyone! I am a newbie using MFEM. I have some problem when I try to compute Energy of elasticity equation.  I think I do not know how to use ComputeElementFlux and ComputeFluxEnergy function to calculate. More specifically, I want to apply into the examples 2 to calculate the Energy. May you guys help me by performing calculation for ex2

Thank you!

**Comment by chang-yiyi** [comment]
Hi @nghiakvnvsd ,

Sorry I'm not familiar with elasticity equation. Could you please provide linear form or bilinear form to compute energy?

**Comment by nghiakvnvsd** [comment]
> Hi @nghiakvnvsd ,
> 
> Sorry I'm not familiar with elasticity equation. Could you please provide linear form or bilinear form to compute energy?
Thanks for replying! I want to apply into the example 2 (https://github.com/mfem/mfem/blob/master/examples/ex2.cpp). You can see the bilinear form and linear form in it.

**Comment by nghiakvnvsd** [comment]
Actually, MFEM provides a function to compute it. But I do not know how to use it (http://mfem.github.io/doxygen/html/classmfem_1_1ElasticityIntegrator.html)

**Comment by v-dobrev** [comment]
Hi @nghiakvnvsd,

The methods `ComputeElementFlux` and `ComputeFluxEnergy` are typically used for the Zienkiewicz-Zhu error estimator. If that is what you are interested in, see Example 21/21p which illustrates their use for a linear elasticity problem.

If you just want to compute the energy from the FE formulation, `E(u) = (1/2) a(u,u) - b(u)` then you can use the methods `BilinearForm::FullInnerProduct` and `LinearForm::operator()(const GridFunction &)`. Since the `LinearForm` is typically modified when eliminating boundary conditions, then it will be easier to copy the `LinearForm` to a `Vector` after assembly but before elimination of b.c. and then later compute `b(u)` by using the `InnerProduct` with the solution `GridFunction`.
