### ISSUE TITLE
MFEM mesh v1.0

### ISSUE THREAD

**Issue by zahurullah123** [mfem/mfem#1844]
Hello
This may be very basic questions. 
How can we create this file? I tried it with Gmsh but no success. 
I want to create a mesh for the elasticity problem, Ex2. 
Regards 
Zahur

**Comment by bslazarov** [comment]
Hi,

To better understand the MFEM mesh format you can try to create the mesh description by hand.  

Since you have experience in using GMSH, I would suggest mesh generation with GMSH (it will generate mesh in format different than the MFEM native mesh format). Make sure that you dump the GMSH mesh in the older format 2.2.  You can add the following line in your *.geo file:

Mesh.MshFileVersion = 2.2;

Define 2 physical volumes/surfaces (depending if the mesh is in 3D or 2D) for the two material regions, and in addition two boundary surfaces/curves (3D/2D) for the boundaries. Let me know if you need an example of .geo file. 

Best regards, Boyan

**Comment by zahurullah123** [comment]
Hello Boyan
I have created the *.geo and *.msh file. I have included Mesh.MshFileVersion = 2.2; in the *.geo file. This is the *.geo file: 
`// Gmsh project created on Tue Oct 27 21:01:25 2020
SetFactory("OpenCASCADE");
Mesh.MshFileVersion = 2.2;
//+
h1=5;
Point(1) = {0, 0, 0, h1};
Point(2) = {5, 0, 0, h1};
Point(3) = {10, 0, 0, h1};
Point(4) = {0, 1, 0, h1};
Point(5) = {5, 1, 0,  h1};
Point(6) = {10, 1, 0, h1};
//+
Line(1) = {1, 2};
Line(2) = {2, 5};
Line(3) = {5, 4};
Line(4) = {4, 1};
Line(5) = {5, 6};
Line(6) = {6, 3};
Line(7) = {3, 2};
//+
Curve Loop(1) = {4, 1, 2, 3};
Plane Surface(1) = {1};
//+
Curve Loop(2) = {5, 6, 7, 2};
Plane Surface(2) = {2};
//+
Physical Surface("Mat_left") = {1};
Physical Surface("Mat_right") = {2};
Physical Curve("left") = {4};
Physical Curve("right") = {6};`

and this is the *.msh file

`$MeshFormat
2.2 0 8
$EndMeshFormat
$PhysicalNames
4
1 3 "left"
1 4 "right"
2 1 "Mat_left"
2 2 "Mat_right"
$EndPhysicalNames
$Nodes
6
1 0 0 0
2 5 0 0
3 10 0 0
4 0 1 0
5 5 1 0
6 10 1 0
$EndNodes
$Elements
17
1 15 2 0 1 1
2 15 2 0 2 2
3 15 2 0 3 3
4 15 2 0 4 4
5 15 2 0 5 5
6 15 2 0 6 6
7 1 2 0 1 1 2
8 1 2 0 2 2 5
9 1 2 0 3 5 4
10 1 2 0 4 4 1
11 1 2 0 5 5 6
12 1 2 0 6 6 3
13 1 2 0 7 3 2
14 2 2 0 1 1 2 5
15 2 2 0 1 1 5 4
16 2 2 0 2 3 2 5
17 2 2 0 2 6 3 5
$EndElements`

when I run this *.msh file with the ex2, I get this error: 
`Options used:
   --mesh /Users/zahurullah/Desktop/MFEM/Gmsh/geom.msh
   --order 1
   --no-static-condensation
   --visualization


MFEM abort: Non-positive element attribute in Gmsh mesh!
 ... in function: void mfem::Mesh::ReadGmshMesh(std::istream &)
 ... in file: mesh/mesh_readers.cpp:1172

Abort trap: 6`

**Comment by bslazarov** [comment]
Hi,

I modified a bit the geo file:

// Gmsh project created on Tue Oct 27 21:01:25 2020
SetFactory("OpenCASCADE");
Mesh.MshFileVersion = 2.2;
//+
h1=5;
Point(1) = {0, 0, 0, h1};
Point(2) = {5, 0, 0, h1};
Point(3) = {10, 0, 0, h1};
Point(4) = {0, 1, 0, h1};
Point(5) = {5, 1, 0,  h1};
Point(6) = {10, 1, 0, h1};
//+
Line(1) = {1, 2};
Line(2) = {2, 5};
Line(3) = {5, 4};
Line(4) = {4, 1};
Line(5) = {5, 6};
Line(6) = {6, 3};
Line(7) = {3, 2};
//+
Curve Loop(1) = {4, 1, 2, 3};
Plane Surface(1) = {1};
//+
Curve Loop(2) = {5, 6, 7, 2};
Plane Surface(2) = {2};
//+
Physical Surface(1) = {1};
Physical Surface(2) = {2};
Physical Curve(1) = {4};
Physical Curve(2) = {6};


The section:
$PhysicalNames
4
1 3 "left"
1 4 "right"
2 1 "Mat_left"
2 2 "Mat_right"
$EndPhysicalNames

is not compatible with MFEM. The code expects to see tags 1 and 2 for the domain and 1 and 2 for the boundary segments. 

Best regards, Boyan

**Comment by zahurullah123** [comment]
Hello @bslazarov 
This is the new *.msh file but produced the same error: 

```
$MeshFormat
2.2 0 8
$EndMeshFormat
$Nodes
6
1 0 0 0
2 5 0 0
3 10 0 0
4 0 1 0
5 5 1 0
6 10 1 0
$EndNodes
$Elements
17
1 15 2 0 1 1
2 15 2 0 2 2
3 15 2 0 3 3
4 15 2 0 4 4
5 15 2 0 5 5
6 15 2 0 6 6
7 1 2 0 1 1 2
8 1 2 0 2 2 5
9 1 2 0 3 5 4
10 1 2 0 4 4 1
11 1 2 0 5 5 6
12 1 2 0 6 6 3
13 1 2 0 7 3 2
14 2 2 0 1 1 2 5
15 2 2 0 1 1 5 4
16 2 2 0 2 3 2 5
17 2 2 0 2 6 3 5
$EndElements

```

**Comment by bslazarov** [comment]
Hi,

You have saved all mesh entries without physical tag. My mesh file is much shorter:
$MeshFormat
2.2 0 8
$EndMeshFormat
$Nodes
6
1 0 0 0
2 5 0 0
3 10 0 0
4 0 1 0
5 5 1 0
6 10 1 0
$EndNodes
$Elements
6
1 1 2 1 4 4 1
2 1 2 2 6 6 3
3 2 2 1 1 1 2 5
4 2 2 1 1 1 5 4
5 2 2 2 2 3 2 6
6 2 2 2 2 6 2 5
$EndElements
~                    
It seems that you do not have any physical tags defined in your mesh file. You should dump out only the physical entries in mesh files, otherwise the associated tags will be zero and MFEM will complain. 

Best regards, Boyan

**Comment by zahurullah123** [comment]
Thanks @bslazarov 
It is working now. In the Gmsh, I have to 

`File -> Export... -> Version 2 ASCII and uncheck all options `
