### ISSUE TITLE
Generate coefficient for BilinearForm using LFIntegrators ?

### ISSUE THREAD

**Issue by brightzhang91** [mfem/mfem#1859]
Hi
Thanks for the very useful discussions in #1533 , I have a question which requires producing normal vectors as well.
I want to produce normal vectors as VectorCoefficient acting on LHS to generate the normal component of the Bilinearform (Curl A) on a internal interface between two subdomains, A is in ND space. I wonder if I can make use of BoundaryNormalLFIntegrator or VectorFEBoundaryFluxLFIntegrator to produce this normal coefficient ?
such as :

```
 ParLinearForm lf_bdr (RT_space);
 ConstantCoefficient ones(1.0);
 lf_bdr.AddBoundaryIntegrator(new VectorFEBoundaryFluxLFIntegrator(ones), ess_bdr);
 lf_bdr.Assemble();
 VectorGridFunctionCoefficient normal_coef(lf_bdr);
 ParBilinearForm *A = new ParBilinearForm(ND_space);
 A.AddBdrFaceIntegrator(VectorFECurlIntegrator(normal_coef), ess_bdr);
```
Do you think this is a viable method? If not, how could I obtain the normal components of the Bilinearforms on a surface? Thanks very much !

Bright

**Comment by mlstowell** [comment]
Hello, @brightzhang91 ,

Unfortunately, this method will not work.  The `VectorFECurlIntegrator` requires a scalar coefficient rather than a `VectorCoefficient` and the `VectorGridFunctionCoefficient` requires a `GridFunction` and not a `LinearForm`.

I gather that your mesh has an internal surface marked with a particular boundary attribute and you need to compute `n.Curl A` on this surface but you don't have a simple function describing the normal so you're hoping MFEM can compute it for you.  This is a reasonable expectation but it's not something MFEM currently offers.  We tend to compute surface normals inside integrators in ad hoc ways.

Perhaps if you give us more information about the operator you're hoping to compute I can help you find a work-around.

Best wishes,
Mark

**Comment by brightzhang91** [comment]
> I gather that your mesh has an internal surface marked with a particular boundary attribute and you need to compute `n.Curl A` on this surface but you don't have a simple function describing the normal so you're hoping MFEM can compute it for you. This is a reasonable expectation but it's not something MFEM currently offers. We tend to compute surface normals inside integrators in ad hoc ways.
> 
Hi Mark 
Thanks for the explanation. Yes, I'm seeking to produce the surface normal `n.Curl A ` on the internal interface to generate a matrix , which will be a part of the BlockOperator to impose a constraint on field A, as discussed  #1579 . I found the LFIntegrator had the function to compute normal vectors so I wonder how could I produce the normal vectors on LHS.  Do I need to implement a new class of `VectorFECurlIntegrator` to add the normal vector ? Any advice would be appreciated.

Thanks !
Bright

**Comment by mlstowell** [comment]
Hi, @brightzhang91 ,

Take a look at the following prototype example: [ex_surf_int_p.cpp](https://github.com/mfem/mfem/blob/surf-int-dev/examples/ex_surf_int_p.cpp).  We may not have any example meshes with internal boundaries so I created a simple one alongside this example named `star-int.mesh`. This mesh has an internal boundary edge extending from (0,0) to (0.5,0).

This uses a `ParLinearform` to compute a flux integral similar to the one you mentioned in #1579.  If you wanted to apply a Lagrange constraint to fix the flux integral `n.Curl A` you would need to add a single row (and column) to your block operator.  This row would be given by the transpose of `curl^T.b` where `b` is a `ParLinearForm` like those in the example shown above and `curl` is a discrete linear curl operator like the one defined [here](https://github.com/mfem/mfem/blob/3bb3974bcb60883b47e00bdf8cd6015f50a6cd30/miniapps/common/pfem_extras.hpp#L101).

Note that the new linear for integrator is a slightly modified version of `BoundaryNormalLFIntegrator`.  Essentially it ignores the magnitude of its `VectorCoefficient` and only checks to see which direction it pierces the face.  It then uses this information to determine if this face's contribution should be added to or subtracted from the total flux.

Best wishes,
Mark

**Comment by brightzhang91** [comment]
> This uses a ParLinearform to compute a flux integral similar to the one you mentioned in #1579. If you wanted to apply a Lagrange constraint to fix the flux integral n.Curl A you would need to add a single row (and column) to your block operator. This row would be given by the transpose of curl^T.b where b is a ParLinearForm like those in the example shown above and curl is a discrete linear curl operator like the one defined here.

Hi Mark
Thanks very much for the help !
However I don't  understand the use  of  `ParLinearForm`  and a `DiscreteLinearOperator` to generate the one-row constraint matrix. My understanding is that the one-row matrix should be in BilinearForm with products of basis functions from both domain and range, such as suggested in  #1579 by performing column sum of the matrix generated by `VectorFECurlIntegrator`.  `DiscreteLinearOperator` behaves similarly to `BilinearForm/MixedBilinearForm` and `curl^T.b` should be a` Linearform` as well? Can it be used as a constraint matrix on LHS ?

Thanks
Bright

**Comment by mlstowell** [comment]
Hi, @brightzhang91 ,

There are different types of constraints.  Perhaps I am thinking of something different than you are.  When constraining a surface integral there are at least two ways to do this.  First, you might consider the flux through the surface as a function of position on that surface and you might want to constrain the values of that function at each point.  This type of constraint would indeed require a bilinear form where you integrate the basis functions of the field against basis functions describing the flux through the surface.  This would constrain individual degrees of freedom of the field to produce the desired flux locally in each face making up the surface.  The second option is to constrain the total flux through the surface with no regard for its variation at different points on that surface.  This type of constraint is much more loose and does not constrain individual degrees of freedom at all.  It is only concerned with the sum of all the fluxes through the surface and such a sum would be computed as a linear form.  The second scheme is what I had in mind.

I'm not aware of any MFEM examples which demonstrate these schemes for enforcing constraints and I don't think we have any classes to accomplish these in a user friendly manner.  Unfortunately this leaves you trying to put something together on your own for your particular needs.  For example I might suggest that you create a custom `Operator` which contains a linear form for computing the flux integral or possibly both the linear form and the `DiscreteLinearOperator` for computing the curl.  You would then need to implement "Mult" and "TransposeMult" functions which make use of the linear form and curl operator internally to compute the desired output.

Regarding issue #1579, I don't think it would be appropriate to simply sum rows or columns of bilinear forms.  You could certainly do this and obtain an operator with the correct dimensions but I doubt it would produce a meaningful result.

Best wishes,
Mark

**Comment by brightzhang91** [comment]
Hi Mark, thanks a lot for the quick reply and detailed explanation.

Yes, the second type of constraint is what I 'm seeking, a loose constraint just on the total flux through the surface, but not on each DoF of the field. Your suggestion is to make use of the linear form to compute the flux (and its surface integral) and a `DiscreteLinearOperator` to add the curl operation. What confuses me is the one-row matrix generated with a linear form and the`DiscreteLinearOperator` is also in linear form, rather than bilinear form. I thought only a bilinear form one-row matrix can be added into the block operator to impose the Lagrange multiplier. Am I incorrect with this issue ?

Thanks
Bright

**Comment by mlstowell** [comment]
Hi, @brightzhang91 ,

Actually, the `BlockOperator` class is a linear algebra class which knows nothing about `BilinearForm` objects.  What `BlockOperator` requires are pointers to `Operator` objects.  `Operator` objects basically have a number of rows and columns and a `Mult` method.  They can also have several optional methods such as `MultTranspose`.  You just need to create a class which inherits from `Operator`, make sure you set its `height` and `width` data members and define a `Mult` method.  Once you have those things you should be able to pass it to `BlockOperator`.

Best wishes,
Mark

**Comment by brightzhang91** [comment]
> This uses a ParLinearform to compute a flux integral similar to the one you mentioned in #1579. If you wanted to apply a Lagrange constraint to fix the flux integral n.Curl A you would need to add a single row (and column) to your block operator. This row would be given by the transpose of curl^T.b where b is a ParLinearForm like those in the example shown above and curl is a discrete linear curl operator like the one defined here.

Dear Mark 
Thanks very much for this advice and I think now I understand the use of the linearform and a Linear Interpolator (it took me some time to understand the face orientation issue). Thanks for making a new specialized boundary LF integrator ! 
However, the new class `SurfaceFluxLFIntegrator` [ ex_surf_int_p.cpp](https://github.com/mfem/mfem/blob/surf-int-dev/examples/ex_surf_int_p.cpp) is in RT space.  And  `ParDiscreteCurlOperator` calls `CurlInterpolator` which is only defined with ND space domain and  RT space range, while here `curl^T.b` is the opposite.  And I assume the one-row matrix `curl^T.b` should be in ND space as my unknown `A` is in ND space?
Sorry I just realized this issue after a while.

thanks
Bright

**Comment by mlstowell** [comment]
Hi, @brightzhang91 ,

Perhaps `curl^T.b` is a bad choice of notation which could have led to confusion.  This object would have the same dimensions as an ND vector.  The `b` is a `LinearForm` object build using the RT space so it does have the same dimensions as an RT vector.  The `curl` operator is rectangular with the same number of rows as an RT vector and same number of columns as an ND vector.  Consequently, the product `curl^T.b` has the same dimension as an ND vector because the RT dimensions are summed over when computing the product.  In order to use this in a `BlockOperator` you would need to create a custom class (or two) derived from `mfem::Operator` which computes `b^T.curl` and its transpose.

Best wishes,
Mark

**Comment by brightzhang91** [comment]
Thanks Mark ! I think now I understand how to produce the constraint matrix. I'll be back to update it when it works.

Best regards
Bright

**Comment by brightzhang91** [comment]
Hi Mark, thanks again for your support.
I encounters a new question which confuses me a lot.
Following your suggestions, I have produced the` Operator` class for the constraints.
One issue I don't understand is how MFEM distributes the BlockOperator and BlockVector in multiple processors, especially when the sub-blocks have different dimensions.
I have a blocked system with matrices B and Bt used as constraints (Lagrange Multiplier), which are non-square with only a few rows, e.g. A(n,n) B(3,n) and Bt(n,3).
[A Bt]
[B D]
I created an Operator class with this blockmatrix and implemented my Mult() and GetGradient(). This Operator is taken by the PetscNonlinearSolver .
My confusion is with the parallelism, if all sub-blocks are square matrices of the same dimension ( Operator size is 2*FESpace()->TrueVSize()) , my Mult() is like :

void H_Operator::Mult(const Vector &k, Vector &Residual) const
{ 
   int sc = height/2;
   Vector k1(k.GetData() +  0, sc);
   Vector k2(k.GetData() +  sc, sc);
   Vector y1(Residual.GetData() +  0, sc);
   Vector y2(Residual.GetData() +  sc, sc);
   
   L_nonlinear->Mult(k1, y1);  
   L_linear->TrueAddMult(k1, y1, 1.0);
   L_mass->TrueAddMult(k1, y1, 1.0/dt);    
   y1.SetSubVector(ess_tdof_list, 0.0);   
   y2 = k2;
   constraint_.AddMult(k1, y2,1.0);// constraint_ is the subblock  for Lagrange multiplier 
}
If my constraint_ is non-square with only 3 rows (then the Operator size is FESpace()->TrueVSize()+3), how do I know the size of k1 and k2 on each processor ?

Thanks very much.
Bright

**Comment by mlstowell** [comment]
Hi @brightzhang91, 

In general the rows of a `BlockOperator` or `BlockVector` are interleaved. For example if you have a 2x2 block system:
```
/A B\
\C D/
```
 distributed on 3 processors the full matrix would be:
```
/A_1 B_1\
|C_1 D_1|
|A_2 B_2|
|C_2 D_2|
|A_3 B_3|
\C_3 D_3/
```
Where `A_1` is the matrix of rows stored on processor 1, `A_2` are from processor 2, etc..

In your situation:
```
/A Bt\
\B  D/
```
`B` has so few rows that you probably want to keep them all on a single processor (it shouldn't matter which one). This will produce blocks which have height or width of zero on most processors. To be honest this might cause a problem with `BlockOperator` and/or `BlockVector` but let's hope for the best (if it fails create an issue and we'll try to fix it).

If your constraint is computed using `ParLinearForm` objects (or `Vectors` of length num-true-dofs) then you'll be computing vector inner products in parallel you'll either use our functions to do this or you'll do the communication on your own. Either way you'll only need the results on whichever processor you choose to own the rows of `B`. On the other processors you'll either ignore the parallel inner product results or simply not gather them (if you're doing the parallel communication yourself).

The sizes of things will need to match the sizes of the operators being used. These sizes are passed into the `BlockOperator` and/or `BlockVector` in the `offsets` array (the sizes are the differences of consecutive entries of this array). The size of `k1` will always need to match the `L_*` operators. The size of k2 will either be 0 or 3 depending on which processor you're on. Note that to compute `Bt * k2` you'll need to scatter (using MPI) the values from `k2` on whichever processor owns `B` to all other processors.

Best wishes,
Mark

**Comment by brightzhang91** [comment]
Thanks very much Mark !
 I now understand the  the vectors and matrices are interleaved.  Your recommendation is to specify a processor only for the the constraint multiplication.  My understanding is on that specific processor, the height of the Operator is 3, while the size of solution vector `k` should still be `FESpace()->TrueVSize()`. And the inner product of `ParLinearForm` and `k` is calculated on that processor. 
I don't know how that can be achieved in MFEM.  It seems both `k` and `ParLinearForm` are automatically partitioned and  distributed to different processors. How do I specify one processor and make it receive the non-partitioned `k` and `ParLinearForm` ?

Can you suggest an example to with the assignment of processors for specific operations ? Thanks !

Best regards
Bright

**Comment by mlstowell** [comment]
Hello, Bright,

There are many ways to do this but the one that might work best is:
```
Vector v(FESpace()->TrueVSize());
constraint_row.ParallelAssemble(v);
double vk = InnerProduct(FESpace->GetComm(), v, k);
```
Where `contraint_row` is a `ParLinearForm` making up one row of your constraint operator.

In `InnerProduct` calculation occurs on every processor. Each processor computes its local portion of the inner product and then the local results must be added together to get the complete inner product. You'll need to choose one processor to "own" this row of the constraint matrix. On that chosen processor the result `vk` will be stored in the local portion of `y2`. On all of the other processor the value of `vk` is still computed but it can be ignored. I don't think there are any MFEM examples that make such a choice so, unfortunately, I cannot give you an example to look at for guidance. This choice will be entirely within your code and it just comes down to ignoring the `vk` results on most processors.

The other place where this choice will matter is in the computation of `y1 += Bt * k2`. To make this work every processor needs to know `k2` so that they can properly update their local portion of `y1` with values from the local portion of `Bt`. Then processor which has been chosen to "own" the constraints will need to broadcast the three values from `k2` to all other processors.

Best wishes,
Mark

P.S. This is making me think that it would be useful to create an operator class in MFEM which mimics this sort of long and skinny matrix made up of individual vectors. It's a simple concept but it's not obvious how to describe how to implement it.

**Comment by brightzhang91** [comment]
Thanks Mark.

Actually I don't know how to finish the following in MFEM :

>  "choose one processor to "own" this row of the constraint matrix"
when constructing the `H_Operator::Mult` and `H_Operator::GetGradient()` of an `Operator`, taken by a `PetscNonlinearSolver`  or `NewtonSolver` . It seems the assignment of the processors is completed within  `PetscNonlinearSolver` or `NewtonSolver`.

Do you know any examples of choosing one specific processor to do some specific tasks?

> This is making me think that it would be useful to create an operator class in MFEM which mimics this sort of long and skinny matrix made up of individual vectors. It's a simple concept but it's not obvious how to describe how to implement it.
That will be fantastic ! I think Lagrange Multiplier are very likely to be non-square matrices. I have been struggling with the non-square constraints which cannot be produced with `Bilinearform`. This makes imposing multi-point constraints pretty difficult for non-experts.

Best
Bright

**Comment by rcarson3** [comment]
@brightzhang91 so I saw this pop up on my feed and have only glanced over what's being discussed briefly. However, it looks like you might be interested what was done in this PR: https://github.com/mfem/mfem/pull/1842 . It introduced a number of ways to deal with constrained systems granted they were largely to deal with certain types of boundary conditions, but the logic or classes might be of interest to your problem.

**Comment by mlstowell** [comment]
Hello, Bright,

I'm sorry if I've been creating confusion. There is no way to do this "in MFEM". Using a `ParLinearform` object as a row of an `Operator` is not a standard MFEM procedure. This is something you need to implement in your code.

It may seem overly simplistic but an example of what I mean by choosing one specific processor to do something is as simple as the following (taken from [ex1p.cpp](https://github.com/mfem/mfem/blob/5dda4c89ee9b9e91d59df8257a5d99b1b7ee74c7/examples/ex1p.cpp#L175)):
```
if (myid == 0)
{
   cout << "Number of finite element unknowns: " << size << endl;
}
```
Here one specific processor, processor 0 in this case, was chosen to print this output. That's all I mean.

So, in your `H_Operator::Mult` you will need something like:
```
Vector v(FESpace()->TrueVSize());
constraint_row.ParallelAssemble(v);
double vk = InnerProduct(FESpace->GetComm(), v, k1);
if (myid == 0)
{
   y2[0] = vk;
}
```
Here all processors are involved in computing `vk` because they each contribute something to the result. However, processor 0, the "chosen" processor in this case, needs to store that result in `y2`. The other processors can ignore the value of `vk` because they don't "own" that row of the operator. You can write whatever "if" statements you like to effectively choose which processors will "own" which rows of your constraint operator. All the rows could be on processor 0, or on the last processor, or one row on each processor (this would be complicated if you run out of rows or processors), whatever you choose. MFEM currently has no way to automate this as far as I know.

The code to compute the transpose of these rows is a bit more complicated and you'll need to use MPI functions to send the information in `k2` to all processors. There are many ways to do that and it may not be appropriate to go into those details here. There are probably many good MPI resources online.

Best wishes,
Mark

**Comment by brightzhang91** [comment]
Understood. Thanks Mark. 
I know I'll need to produce the row-matrix with `ParLinearform` by myself. I was not sure how to make one processor receive the whole vector (and `ParLinearform`) without partitioning. It seems ParLinearform. ParallelAssemble was doing the job, so is ParBilinearform. ParallelAssemble for the global matrix. 
Actually I can make Bt a zero matrix in my problem, so that perhaps I can skip the process of computing the transpose.
I'll update my developments later when I have more progresses. Thanks very much for your support !

Best
Bright
