### ISSUE TITLE
How to improve integrators precision?

### ISSUE THREAD

**Issue by chang-yiyi** [mfem/mfem#1869]
Hi all,

I have two very general questions. In my application, I have defined many `LinearFormIntegrator`s and `BilinearFormIntegrator`s by myself, like 
```
    Q*(u, grad(v)),
    q<u_D, v grad(w).n>,
    q <{u grad(w).n}, [v]>,
    <{h^{-1} q} [u], [v]>,
    ......
```
So my questions are

1. How do I know myself-defined integrators do the right thing? Are there good ways to "unit test" them?
2. How to guarantee integrators to have enough calculation precision?

**Comment by tzanio** [comment]
Hi @chang-yiyi,

You should think of ways to test the integrators as you write them, but here are some suggestions:

- For integrators with differential operators such as `Q*(u, grad(v))` you can check that without boundary conditions you get zero (e.g. in the local element matrices) when you set `v=1`
- If the integrator is symmetric -- test the element and global matrix for symmetry
- Test that you can recover a solution that belongs to the trial finite element space
- Test the convergence rate for a smooth solution that doesn't belong to the trial finite element space

Regarding 2, you should check what the transformed integral for your integrator looks in reference space and pick a quadrature rule that is exact for the corresponding integrand. Note that in some cases it is not possible to be "exact" because the integrand is not a polynomial, but it could be sufficient to have accuracy comparable to the approximation order.

Hope this helps,
Tzanio

**Comment by chang-yiyi** [comment]
Thanks @tzanio ,

It's a good idea.
