### ISSUE TITLE
Vectorized evaluation of FunctionCoefficients

### ISSUE THREAD

**Issue by varchasgopalaswamy** [mfem/mfem#1897]
Hi,

Based on feedback I got on https://github.com/mfem/mfem/issues/1838, I tried writing analytic solutions to test problems as `FunctionCoefficient`s and it seems I've hit upon a performance issue.  As an example, what I have right now is 

```
auto rho_soln = [pid = problem_id, t=time](const mfem::Vector& x) -> double {
              return rho_analytic(x, pid,t);
};
mfem::FunctionCoefficient rho_coeff(rho_soln);
analytic_gridfunction.ProjectCoefficient(rho_coeff);
double error = solver_gridfunction->ComputeL2Error(rho_coeff);
``` 
where `rho_analytic` has a signature like `double rho_analytic(const mfem::Vector& x, int pid, double time)` 

Which works, and gives me an error estimate I can refer to at a glance, and allows me to register the evaluated analytic solution in a DataCollection to view alongside the simulation's solution, take lineouts, etc. However, I guess `FunctionCoefficient` is doing a pointwise evaluation, because it is rather slow to evaluate certain analytic solutions, and ends up totally dominating the runtime of the simulation. I think this is because some of the analytic solutions have substantial overhead, which it ends up repeating for each pointwise evaluation (the versions of these analytic solvers that act on arrays are quite fast). 

Is there any way to make this process more efficient?  My analytic solvers can be (and originally were) formulated to take in an array of initial points and return an array of the solution at that point, which would probably be more efficient. Is there perhaps some way to initialize the `GridFunction` from a `Vector` that has been evaluated at the DOFs of the FE space of that `GridFunction`?

**Comment by wcdawn** [comment]
A first thought: if the problem is recalculating values, could you implement some caching within a container object (or many global variables)? Something like calculate the reused values once and then check some logical condition to see if they need to be computed or if they can simply be used.

Just looking at your code snippet, you could save half of the evaluations, but introduce some discretization error, by doing something like the following.
```
auto rho_soln = [pid = problem_id, t=time](const mfem::Vector& x) -> double {
              return rho_analytic(x, pid,t);
};
mfem::FunctionCoefficient rho_coeff(rho_soln);
analytic_gridfunction.ProjectCoefficient(rho_coeff);
mfem::GridFunctionCoefficient analytic_gridfunction_coeff(analytic_gridfunction);
double error = solver_gridfunction->ComputeL2Error(analytic_gridfunction_coeff);
```
This may be acceptable if you're only using it for a relative metric but would no longer be the true error.

**Comment by tzanio** [comment]
Hi @varchasgopalaswamy,

As @wcdawn pointed out, if `analytic_gridfunction` is acceptable approximation to `rho_func` you a `Coefficient` based off that in `ComputeL2Error`.

Alternatively, you can use a `QuadratureFunctionCoefficient` for which you directly fill in all values in all quadrature points with your existing functions. You should just coordinate that with the integration rule you pass to `ComputeL2Error`. (For visualization purposes it may be easier to use an L2 grid function instead of quadrature function).

Hope this helps,
Tzanio


Can you clarify which line is slow, is it `analytic_gridfunction.ProjectCoefficient(rho_coeff);`?

If

**Comment by varchasgopalaswamy** [comment]
@tzanio, @wcdawn, thanks for the ideas. I decided to go with @tzanio's suggestion because even half the execution time was painfully long! 

Long story short, I got it to work well (I think) . In case anyone in the future comes across this, the following snippet should provide a solution: 
```
// Important to get the integration order directly from the FE space you'll eventually project to
const int intOrder= analytic_rho->FESpace()->GetOrder(0); 
mfem::QuadratureSpace rho_space(&mesh, 2 * intOrder+ 1); 
mfem::QuadratureFunction rho_func(&rho_space, 1);

// Get the int rule and # quad points from the QuadSpace so it stays in sync 
auto ir = rho_func.GetSpace()->GetElementIntRule(0);
int nqpts = ir.GetNPoints();

mfem::Vector X(n_elements*nqpts*n_space_dim); 
X = mesh->GetGeometricFactors(ir, mfem::GeometricFactors::COORDINATES)->X; 
mfem::Vector rho_data(n_elements*nqpts); 

// Fill rho_data with the analytic solution 
some_expensive_function(X,rho_data) 
// Transfer solution back 
{
    for (int i = 0; i < n_elements; i++)
    {
        for (int j = 0; j < nqpts; j++)
        {
        rho_func((i * nqpts) + j) = rho_data((i * nqpts) + j);
        }
    }
}
// Project solution onto GridFunction for visualization, error analysis, etc. 
mfem::QuadratureFunctionCoefficient rho_coeff(rho_func);
analytic_rho->ProjectCoefficient(rho_coeff);
double error = simulation_rho->ComputeL2Error(rho_coeff);
```

- Varchas
