### ISSUE TITLE
Boundary face integrator for MixedBilinearForm

### ISSUE THREAD

**Issue by tangqi** [mfem/mfem#1974]
I am trying to implement a special boundary face integrator, <curl u, n x grad v>, as a mixed bilinear form (trial is H^1 vector and test is H^1 scalar). 

Here is my implementation
```
void CurlNormalCrossGradIntegrator::AssembleFaceMatrix(
   const FiniteElement &trial_el, const FiniteElement &test_el, const FiniteElement &test_dummy,
   FaceElementTransformations &Trans, DenseMatrix &elmat){
...
   order = 2*Trans.OrderGrad(&test_el);
   const IntegrationRule *ir = &IntRules.Get(Trans.FaceGeom, order);

   for (int p = 0; p < ir->GetNPoints(); p++)
   {
      const IntegrationPoint &ip = ir->IntPoint(p);
      IntegrationPoint eip1;
      Trans.Loc1.Transform(ip, eip1);
      Trans.Elem1->SetIntPoint(&eip1);

      trial_el.CalcDShape(eip1, dshape_trial);
      w = Trans.Elem1->Weight();
      Mult(dshape_trial, Trans.Elem1->AdjugateJacobian(), dshapedxt_trial); 
      dshapedxt_trial*=(1./w);
      dshapedxt_trial.GradToCurl(curl_trial);

      ...
  }
```
When I test the integrator using the unit tests, w can be 0 when element (it is TETRAHEDRON). So I think I must misunderstand something. Is there any obvious error? Is that because certain Face is not on the boundary?

Qi

**Comment by mlstowell** [comment]
HI, @tangqi ,

I don't see an obvious error but it may be that the `FaceElementTransformations` object has not been fully configured.  Can you add a call to `FaceElementTransformations::GetConfigurationMask()` and print out the results?  I would expect `w` to be non-zero if the mask has a value of 5, 21, or 31. 

Best wishes,
Mark

**Comment by tangqi** [comment]
Thanks a lot for the suggestion, Mark. I think weights are right after I play a bit more based on your suggestion, but I believe my memory got messed up, so it gives me some strange weights in the later iteration. 

I found at least one issue: I normally add `AssembleFaceMatrix` through `BilinearForm::AddBdrFaceIntegrator` for a boundary integral like this. However, since I cannot find the same operator in `MixedBilinearForm`, I used `AddBdrTraceFaceIntegrator`. This seems wrong since "Trace" here refers to skeleton, gives me one dimensional lower than I want in the integral. I get the dimension through `dim = trial_el.GetDim()`, which is 2 in the 3D test. 

So what would be the right way to assemble this operator in the mixed form? 

Qi

**Comment by mlstowell** [comment]
Hi, @tangqi ,

As I understand it, the `AssembleFaceMatrix` methods and the related `BilinearForm::AddBdrFaceIntegrator` etc. methods are meant to be used with Discontinuous Galerkin Methods so your proposal is a bit unconventional.   That being said, it may still be possible to make this work.

I guess the trouble here is that the trial space is interpreted as a 2D "trace" space so you don't have access to the normal derivative of `u` which you need to build its curl.  One way around this would be to use an intermediate field `F=curl u` where `F` is in H(Curl) (using a Nedelec finite element space).  The advantage of this is that the trace of an H(Curl) field will give you access to the tangential components of `curl u`.  The disadvantage is that you will need to compute `F=curl u` on the entire domain rather than just on the boundary.  Another issue is that we don't seem to have the necessary curl operator so you'll need to write one (perhaps using `VectorCurlCurlIntegrator` and `VectorDivergenceIntegrator` as guides).  Another advantage of this approach is that you could use the more standard `MixedBilinearForm::AddBoundaryIntegrator` since you would not need access to data from neighboring 3D elements.

Best wishes,
Mark

**Comment by tangqi** [comment]
Mark,
Let's take one step back. I guess I use the wrong assemble operator. You indicate if I use `AddBoundaryIntegrator` in a BilinearForm, I should be able to implement operator like <du/dn, v> as a BilinearForm (u, v are H1 scalar). Inside its `AssembleElementMatrix`, I would be able to access to its 3D normal. Am I right?

Based on that, I should be able to directly implement operator like <curl u, n x grad v> using `MixedBilinearForm::AddBoundaryIntegrator`. Then I will be able to compute its gradient or curl just on the boundary without doing a global reconstruction as you said. What do you think?

Thanks,
Qi

**Comment by tangqi** [comment]
Hi @mlstowell 
I see the issue with `AddBoundaryIntegrator` now. It only uses the boundary element but I need the curl of the volume element. The approach you suggested should work, but it is not clear to me how to assemble a matrix operator for <curl u, n x grad v>. Ideally, I would like to further explore some preconditioning strategy. 

I can see two other approaches: 
(1) since I am doing component-by-component, I can split  <curl u, n x grad v> into components. That makes it possible to use `BilinearForm::AddBdrFaceIntegrator` So maybe an easy work-around would be first assemble component-by-component and then merge it as a block operator, which would be used as one block of another block operator. Will that be possible? Are there any other functions I can use to glue HyperParMatrix together? In principle, the small matrices should have the consistent partitioning with the full matrix operator.
(2) I could add `AddBdrFaceIntegrator` into MixedBilinearForm. I checked briefly in `assemble`. I did not see the obvious obstacle to add it into `MixedBilinearForm`. But maybe there is a reason that `AddBdrFaceIntegrator` is not implemented.

I know this is not conventional. But I would greatly appreciate it if you have any suggestions. 

Qi

**Comment by mlstowell** [comment]
Hi, @tangqi ,

I think the component-by-component approach would lead to the same difficulty since you would not be able to compute the normal derivative of `u` within a boundary integrator.

The matrix for <curl u, n x grad v> would need to be built as a `BlockOperator`.  One row of this operator would compute the curl of u using <curl u, w> - <F, w> = 0 where `w` and `F` are in HCurl.  The other row would contain <F, n x grad v>.  I believe the <curl u, w> integrator would need to be implemented but <F, w> is just a `VectorFEMassIntegrator`. The <F, n x grad v> operator may also need to be implemented.

I'd be happy to help you build a prototype code to test this implementation.  How would this operator fit into your larger code? Is it part of a larger bilinear form that you need to solve, is it a contribution to the right hand side, or is it a post processing step?  Or perhaps something else entirely?

Best wishes,
Mark

P.S. It may also be useful to reconsider representing `u` in a vector H1 basis.  I'm always skeptical of taking the curl of a vector H1 field.  Perhaps it would make sense to use HCurl or HDiv for `u`.

**Comment by tangqi** [comment]
@mlstowell 
I understand what you mean with that block operator of <curl u, n x grad v> and I can likely build it by myself. It is not too hard. But I greatly appreciate your kind help. 

I still hope to achieve this through the component-by-component approach, since (1) I have successfully build an operator of <du/dn, v> using the interface `AddBdrFaceIntegrator`, in which I need to first compute full gradient of u and then multiply a 3D normal by myself, (2) it is much cheaper than that global reconstruction. I suspect I can build  <curl u, n x grad v> through the same approach (each term is just a combination of grad u, n and grad v, and yes, it is going to be ugly). But perhaps I am still missing something?

I am trying to build it as a part of a large bilinear form. I have tried to move this term to RHS, which is much easier. This kind of boundary coupling can raise in some FSI coupling problems. I am just doing some initial experiment now.

It is also interesting to hear your comments on vector H1 basis. Perhaps we should chat on that. We are thinking about using H(curl) and H(div) to build a MHD solver as a separate effort. So it would be nice to hear your experience. 

Qi

**Comment by tangqi** [comment]
I will explore JFNK to implement the same operator instead. This should be a lot easier. Thanks for the suggestion. I will close it for now.
