### ISSUE TITLE
CPARDISO interface should use a MPI_Fint

### ISSUE THREAD

**Issue by adam-sim-dev** [mfem/mfem#1990]
Hello,

CPARDISO interface should use a MPI_Fint, see https://gitlab.com/petsc/petsc/-/issues/640

To reproduce this issue, if I remember correctly, I use g++, mkl and openmpi?
To fix this bug,  call `MPI_Comm_c2f(comm_)` before call `cluster_sparse_solver`.

About the `MKL_MPI_WRAPPER` in `defaults.mk` and `config.mk`,  I think, it should be "mkl_blacs_intelmpi_lp64" if we use Intel MPI. So how to handle this based on the MPI vendor should be fixed.

Best,
Adam

**Comment by tzanio** [comment]
If I understand correctly, the proposed solution is to replace

1. in https://github.com/mfem/mfem/blob/master/linalg/cpardiso.hpp#L86

   ```c++
   MPI_Comm comm_;
   ```
   with
   ```c++
   MPI_Fint comm_;
   ```

2. in https://github.com/mfem/mfem/blob/master/linalg/cpardiso.cpp#L12-L13

   ```c++
   CPardisoSolver::CPardisoSolver(MPI_Comm comm) : comm_(comm)
   {
   ```
   with
   ```c++
   CPardisoSolver::CPardisoSolver(MPI_Comm comm)
   {
      comm_ = MPI_Comm_c2f(comm);
   ```

This seems reasonable to me. @jandrej what do you think?

Has the communicator always been `MPI_Fint` or is this a change since a particular version of CPardiso?

**Comment by tzanio** [comment]
Discussion continued in @2090.
