### ISSUE TITLE
Modeling Eddy-Current Problem with Anisotropic Electric Conductivity (Tensor)

### ISSUE THREAD

**Issue by Maatinski** [mfem/mfem#2008]
Hi all,
I initially posted this to my previous topic on modeling induced eddy-currents in anatomical body models from time-varying magnetic fields (https://github.com/mfem/mfem/issues/1432) but maybe this question deserves it's own topic:

Is there any way to implement an-isotropic conductivities in the eddy-current simulation? For some biological tissues (e.g., muscle and nerve) the electric conductivity is much greater along the fiber direction (up to 5x) than orthogonal to the fibers. We were wondering if there is a mechanism in MFEM to implement this.
Of course this would require additional inputs, as every mesh element would be associated with a conductivity tensor that varies even within a single tissue class. The question would be how this information can then be incorporated in the FE system matrix assembly.

We are also currently testing this with a commercial FEM solver to see how big of a difference it makes, but I wanted to maybe get some feedback on this from the MFEM community.

As always thanks a lot and warm regards
Maatinski

**Comment by mlstowell** [comment]
Hi, @Maatinski ,

Yes, this can be done but a realistic simulation would be non-trivial, as you might expect.  The conductivity in the eddy current problem appears in a `VectorFEMassIntegrator` and this integrator will accept rank 2 tensor-valued coefficients i.e. MFEM's `MatrixCoefficient`.  All you need to do is supply an appropriate `MatrixCoefficient` and your existing code should work just fine.  The hard part is forming a realistic tensor-valued conductivity.

For initial tests you can create a `MatrixConstantCoefficient` using any positive-definite 3x3 `DenseMatrix` of conductivities.  A next step might be to use different `MatrixConstantCoefficient` values in different regions of your domain tagged using the element attributes of the mesh.  For a realistic simulation you'll probably need a vector field which follows your tissue fibers.  You can then build a customized `MatrixCoefficient` which exhibits the necessary anisotropy.  A simple example would have a unit vector field `u` and two conductivities `sigma_perp` and `sigma_para`.  You then construct a tensor as follows:
```
sigma = sigma_para u^T u + sigma_perp (I - u^T u)
```
In order to be sure your linear system is non-singular you'll need to ensure that your `sigma` coefficient remains positive definite.  The trick to this is correctly handling the cases where your vector field goes to zero.  You'll need to determine a reasonable isotropic value for `sigma` in such cases and make sure your anisotropic tensor transitions smoothly to this isotropic value.  Failure to do this can lead to lack of convergence or, more commonly, non-physical charge buildup because `Div(sigma E)` is poorly behaved.

Best wishes,
Mark

P.S. I'll tag @jamiebramwell here because I happen know she has had experience with muscle fiber modeling and I'm sure she'll be interested in your simulations.

**Comment by adam-sim-dev** [comment]
> A next step might be to use different MatrixConstantCoefficient values in different regions of your domain tagged using the element attributes of the mesh.

Hi Mark, @mlstowell , is it possible to implement a `PWMatrixConstantCoefficient` (I don't know if this is a proper name) like `PWConstCoefficient`? This will provide more convenience.

**Comment by tzanio** [comment]
@adam-sim-dev, we can add this, but it should also be relatively easy to add it yourself. `Coefficient` is a simple object and the intention is that users can add their own as needed.

**Comment by Maatinski** [comment]
Hi everybody, thanks a lot for the helpful comments!
Looks like it shouldn't be too complicated to implement this, and I agree with @mlstowell that the more difficult part is probably generating the vector field characterizing the fiber directions (although we do have some ideas to do this). 
I will do some more testing in another software package to get an idea how much the anisotropy affects the total electric field, and then decide if we'll give it a shot...

Thanks and warm regards
Maatinski

**Comment by tzanio** [comment]
ping: @jamiebramwell

**Comment by jamiebramwell** [comment]
@Maatinski , we also did some cardiac modeling in MFEM for the [cardioid project](https://github.com/LLNL/cardioid). Included is a [mini-app for determining fiber directions](https://github.com/LLNL/cardioid/tree/master/fibers). I was mostly involved in the mechanical deformation part of the code, but I used the fiber orientations generated in an MFEM integrator [here](https://github.com/LLNL/cardioid/blob/59c07b714d8b066b4f84eb50487c36f6eadf634c/mech/cardiac_integrators.cpp#L47). Hopefully this helps! I would be happy to answer any questions you have, although you may have more luck with the principal developer @rblake-llnl.

**Comment by rblake-llnl** [comment]
Hi @Maatinski, I actually have an MFEM version of cardiac electrics that implements anisotropic diffusion on either a per-node or per-element basis.  The code can be found here: https://github.com/LLNL/cardioid/blob/59c07b714d8b066b4f84eb50487c36f6eadf634c/hack/MatrixElementPiecewiseCoefficient.cpp#L41

The process is pretty simple-- I define a 3D vector grid function that contains the x,y,z components of the quaternions for the fiber orientations. By doing this, I can use either nodal quaternion basis functions (H1) or per-element quaternion basis functions (L2).  Quaternions are used because linear interpolation in quaternion space is MUCH better for interpolating rotations than doing tensor interpolation.  The w component of the quaternion is calculated assuming unit quaternions.

After I have the rotation for the gauss point, I calculate the raw tensor using R*D*R', where D is a diagonal positive matrix that has the fiber, sheet, and transverse conductivities.

As far as where to get the raw data for the fiber anatomies, we can have a longer discussion about that over email.  In general DTMRI data is the gold standard, but it can return erroneous results at organ boundaries. I have a cool trick to generate accurate fiber orientations for human ventricles, but for things like the atria are harder to come by because the atria are so thin. Embedding 1D nerve fibers in a 3D medium presents it's own challenges.  As far as the rest of the torso goes, most people assume isotropic conductivities when doing the rest of the organs.  I have the isotropic conductivities for all the torso organs somewhere-- it's not too hard to find with a literature search.

**Comment by tzanio** [comment]
Hi @Maatinski,

Were you able to resolve this? Anything we can do to help?

Tzanio

**Comment by Maatinski** [comment]
Hi all,
apologies for not getting back to you earlier! Thanks for the helpful comments @jamiebramwell and @rblake-llnl , this definitely looks like something we could build upon. MRI (which is what we're working on anyway) is definitely a great choice, although we're working with somewhat of an artificial human model, so that might involve some manual labor.
At the moment, the idea of including anisotropy in our models got pushed in the background, as some more urgent stuff came up lately. I would love to revisit this at some point in the near future (and would love to chat more when this becomes relevant again).
Again, thanks a lot for the insightful comments!
Maatinski

**Comment by tzanio** [comment]
Hi @Maatinski, 

I am closing this for now, but please feel free to reopen any time.

Tzanio

**Comment by mdavids-cfs** [comment]
Hi all,
just reopened this (same person as @Maatinski but using different account). 

I am revisiting this point but for a slightly different application. I am still trying to solve an electrostatic problem and trying to define conductivity tensors pretty much for each element individually. For some materials, these will have to be interpolated from a vector field (could easily store this in a `VectorGridFunction`, for example) and for other materials it's going to be just uniform conductivity (but still material dependent).

I assume @rblake-llnl 's approach would be a feasible solution, but I would love to stick to purely MFEM internal functionalities (especially since I am using the 'PyMFEM' interface, which by the way is a **game changer** for integrating MFEM into some of our workflows).

Any thoughts on how this could be implemented most easily? @tzanio @mlstowell 
Big thanks for any helpful comments!
Mathias

**Comment by mlstowell** [comment]
Hi, @mdavids-cfs,

Of course, there are probably many ways to accomplish this task in MFEM but few if any would be able to stick purely with internal functionalities. Deriving from MFEM's coefficient classes is one of the most common and powerful ways to extend MFEM's capability. I think @rblake-llnl's scheme for producing anisotropic material properties is an excellent example of this type of extension. I imagine any scheme to produce your conductivity tensors will involve a mixture of existing coefficient classes and new custom classes. The trick is to make this mixture efficient and robust.

How are the elements with tensor conductivities distinguished from those with isotropic conductivities? If this can be done using element attributes then perhaps your operators could process groups of elements with common attributes in batches using the same integrators and  coefficient classes etc.. If they can only be distinguished by location or field values or similar data then such a determination would probably need to be done within a custom `MatrixCoefficient` class which sometimes returns isotropic tensors.

Either approach has pros and cons with regard to code complexity and efficiency.

Best wishes,
Mark
