### ISSUE TITLE
Lorentz coupling in 2D incompressible MHD

### ISSUE THREAD

**Issue by F3dR19** [mfem/mfem#2019]
Hi there,

I'm trying to set-up an incompressible magnetohydrodynamics problem in 2D, using a vector-potential formulation for the magnetic field. The coupling between velocity and magnetic field is given by Lorentz force, which in my formulation can be translated as an extra non-linear term
`(\div\grad(Az)) \grad(Az)`,
in the velocity equation, where Az is a scalar function, representing the z-component of the vector potential.
I plan on using Newton iterations to tackle the non-linearity: after linearisation (around Cz), we get the two bilinear forms
`((\div\grad(Cz)) \grad(Az), v)`, and `((\div\grad(Az)) \grad(Cz), v)`,
where v is the test function of the velocity space.

I need to explicitly assemble the corresponding Finite Element matrices, since I'll need them elsewhere in the code: my question is: what's the best way to do this?

I'm trying to write my own integrators for this purpose:
- For the first term, `((\div\grad(Cz)) \grad(Az), v)`, I need to compute the Laplacian of a fixed scalar function Cz. I'm thinking of storing Cz as a `GridFunction`, and invoking its method `GetLaplacians`. Then, I could simply reuse the code form `MixedVectorGradientIntegrator`: does it make sense, as a strategy?
- The second term, `((\div\grad(Az)) \grad(Cz), v)`, seems trickier instead, as I'd need to compute the Laplacian of the trial function Az, and I can't find example codes to start from. An alternative would be integrating by parts: after some manipulations, that would spit out a `\grad\grad(Cz)` term, which maybe is more tractable, since it doesn't involve the trial function? It seems to me like I'm just shifting the problem, though. Any ideas on how to go on about this?

Thank you in advance for looking into this: any hint is very welcome!
Fede

**Comment by mlstowell** [comment]
Hi, @F3dR19 ,

As a general rule we try to avoid taking more than one spatial derivative of a `GridFunction` because the accuracy drops off rapidly.

The standard way to avoid this loss of accuracy is to introduce an auxiliary field and add a new equation to your system of equations.  In this case you probably want to introduce `J=Curl(Curl(A))`.  This means that your non-linear iteration will need to expand `Jz` as well as `Az` so, for example you might have a `Kz` satisfying `Kz=Curl(Curl(Cz))`.

This should lead to a pair of terms resembling `(Kz grad(Az), v)` and `(grad(Cz) Jz, v)`.  The first term would use the `MixedVectorGradientIntegrator` as you mentioned, and the second term could use the `MixedVectorProductIntegrator`.

Best wishes,
Mark

**Comment by tangqi** [comment]
I agree it is not a good idea to take derivative directly on the solution. The auxiliary variable is likely necessary. I first compute J=Laplace(psi) in my incompressible MHD code, and then use it in B.grad(J) where B is curl_perp(psi). 

You may want to check this branch, I think most pieces you need are already there: https://github.com/mfem/mfem/tree/tds-mhd-dev/miniapps/mhd

Qi

**Comment by F3dR19** [comment]
Amazing! Thanks to you both, Mark and Qi, for the useful suggestions!
I'll give it a shot straight away, and eventually re-open the issue if some problem arises.

Thanks again,
Fede
