### ISSUE TITLE
Time-dependent source term in heat equation

### ISSUE THREAD

**Issue by raphaelzanella** [mfem/mfem#2024]
Hello,

I am interested in solving the following equation:
pd(u)/pdt + a.grad(u) - div (nu*grad(u)) = f,
where f is a given function of space and time.

Following example 9, I was able to implement a time-independent source term on the rhs. I create a ParLinearForm (from a function defining f), which is assembled into a HypreParVector, which is used to create the FE_Evolution object adv.

It seems that the source term cannot be time-dependent as the solver is. Is there a way to modify the solver so that it would be possible? Or should my approach be different?

If there is an example / miniapp that solves a similar problem, that would be great.

**Comment by barker29** [comment]
I think `ex15` will point you in the right direction. You probably already use the `FunctionCoefficient` object, which can be constructed with either a time-dependent or time-independent function. The function `rhs_func` in `ex15` is used to construct the coefficient `rhs` which is used in the `LinearForm` `b`, analagous to your `f` in the equation above.

Does this make sense?

**Comment by raphaelzanella** [comment]
It does and I think I got that part. My `FunctionCoefficient` object `f` is constructed from a time-dependent function. `f` is used for the `ParLinearForm` object which is then assembled into a `HypreParVector` object, etc.

The thing is that the code behaves as if the source term was time-independent. The solution is the same as if the source term took its value at *t = 0* all along.

I guess I am missing something. The rhs should be updated at every time step somehow.

I see that example 15 does not use an `ODESolver` object as exemple 9. I was looking for an example that does (and with a time-dependent source term) if there is.

**Comment by barker29** [comment]
You are right, this is a bit more complicated than I originally thought, and I don't think we have an example for this case.

I think what you want to do is change the `FE_Evolution` constructor so its third argument is `ParLinearForm` instead of `Vector`, and then you will construct this object with `b` instead of `B`. Then in both `FE_Evolution::Mult()` and `FE_Evolution::ImplicitSolve()` replace the line `z += b;` with a few lines that call eg. `rhs.SetTime()` and `b->ParallelAssemble()` to get the correct (time-dependent) vector you want to add to `z`.

One of the things that will make this tricky is being careful with memory so you don't create a new vector at each timestep, but I think the outline I've given above will get you started. Let us know if you have questions.

**Comment by raphaelzanella** [comment]
Ok thanks', I got it.
In addition to replacing `B` by `b` in the `FE_Evolution` constructor, I added the `FunctionCoefficient` `f` so that I can use `f.SetTime` inside `FE_Evolution::Mult()` and `FE_Evolution::ImplicitSolve()`.
I create (and delete once used) a new `HypreParVector` at each time step.
It might not be optimal but it works.
