### ISSUE TITLE
Segmentation fault when loading curved Gmsh mesh

### ISSUE THREAD

**Issue by benzwick** [mfem/mfem#2032]
I am trying to generate a curved mesh using quadratic elements with Gmsh. When trying to load the mesh using MFEM (e.g. the mesh-explorer miniapp) I get a segmentation fault. The mesh with linear elements can be loaded without any problems. I cannot seem to find anything wrong with the quadratic mesh and it can be loaded into Gmsh. Does anyone have any idea what I might be doing wrong?

geometry file (.geo):
```
Mesh.MshFileVersion = 2.2;

Point(1) = {0, 0, 0, 1.0};
Point(2) = {0.5, 0, 0, 1.0};
Point(3) = {1, 0, 0, 1.0};
Point(4) = {1, 1, 0, 1.0};
Point(5) = {-0, 1, 0, 1.0};
Point(6) = {-0, 0.5, 0, 1.0};

Circle(1) = {6, 1, 2};
Line(2) = {6, 5};
Line(3) = {5, 4};
Line(4) = {4, 3};
Line(5) = {3, 2};

Curve Loop(1) = {2, 3, 4, 5, -1};

Plane Surface(1) = {1};

Physical Curve(1) = {1};
Physical Curve(2) = {2};
Physical Curve(3) = {3};
Physical Curve(4) = {4};
Physical Curve(5) = {5};
Physical Surface(1) = {1};
```

mesh with linear elements:
```
$MeshFormat
2.2 0 8
$EndMeshFormat
$Nodes
8
1 0.5 0 0
2 1 0 0
3 1 1 0
4 -0 1 0
5 -0 0.5 0
6 0.3535533913981662 0.3535533897883814 0
7 0.6895299801724067 0.4136574664509627 0
8 0.4616109129283297 0.6709541058817441 0
$EndNodes
$Elements
14
1 1 2 1 1 5 6
2 1 2 1 1 6 1
3 1 2 2 2 5 4
4 1 2 3 3 4 3
5 1 2 4 4 3 2
6 1 2 5 5 2 1
7 2 2 1 1 5 4 8
8 2 2 1 1 6 5 8
9 2 2 1 1 3 7 8
10 2 2 1 1 2 1 7
11 2 2 1 1 1 6 7
12 2 2 1 1 7 6 8
13 2 2 1 1 4 3 8
14 2 2 1 1 3 2 7
$EndElements
```

mesh with quadratic elements:
```
$MeshFormat
2.2 0 8
$EndMeshFormat
$Nodes
23
1 0.5 0 0
2 1 0 0
3 1 1 0
4 -0 1 0
5 -0 0.5 0
6 0.3535533913981662 0.3535533897883814 0
7 0.1913417166168257 0.4619397660757584 0
8 0.4619397665017904 0.1913417155882935 0
9 0 0.7499999999993106 0
10 0.4999999999986718 1 0
11 1 0.5000000000013305 0
12 0.7500000000006894 0 0
13 0.6895299801724067 0.4136574664509627 0
14 0.4616109129283297 0.6709541058817441 0
15 0.2308054564641648 0.835477052940872 0
16 0.2308054564641648 0.585477052940872 0
17 0.4075821521632479 0.5122537478350627 0
18 0.8447649900862033 0.7068287332254813 0
19 0.5755704465503682 0.5423057861663534 0
20 0.7308054564641648 0.835477052940872 0
21 0.5947649900862033 0.2068287332254814 0
22 0.8447649900862033 0.2068287332254814 0
23 0.5215416857852865 0.383605428119672 0
$EndNodes
$Elements
14
1 8 2 1 1 5 6 7
2 8 2 1 1 6 1 8
3 8 2 2 2 5 4 9
4 8 2 3 3 4 3 10
5 8 2 4 4 3 2 11
6 8 2 5 5 2 1 12
7 9 2 1 1 5 4 14 9 15 16
8 9 2 1 1 6 5 14 7 16 17
9 9 2 1 1 3 13 14 18 19 20
10 9 2 1 1 2 1 13 12 21 22
11 9 2 1 1 1 6 13 8 23 21
12 9 2 1 1 13 6 14 23 17 19
13 9 2 1 1 4 3 14 10 20 15
14 9 2 1 1 3 2 13 11 22 18
$EndElements
```

The quadratic mesh looks like this:
![Screenshot_20210202_142616](https://user-images.githubusercontent.com/33216696/106560873-b4d52500-6562-11eb-9e7d-3d46ba90d10f.png)

**Comment by mlstowell** [comment]
Hi, @benzwick,

The problem seems to be the element orientations.  MFEM computes the determinants of triangular elements and swaps the order of the vertices of any triangles having negative determinants.  Unfortunately this procedure only works for linear elements.  Higher order elements require more care and MFEM just ignores this and swaps the first two vertices in either case.  Even more unfortunately, the algorithm doesn't even extract the vertices for higher order elements before trying to swap them so it just seg faults when accessing the NULL pointer which should point to the vertices.

This is clearly a bug and we'll try to devise a solution.  In the mean time you may be able to have Gmsh produce elements with the orientations that MFEM expects.  In your sample geo file just reverse the order of the curve loop:
```
Curve Loop(1) = {-2, -3, -4, -5, 1};
```

Sorry for the trouble and thanks for letting us know.

Best wishes,
Mark

**Comment by benzwick** [comment]
Thanks @mlstowell, your solution works perfectly.

Regarding the ordering of the vertices:
> MFEM computes the determinants of triangular elements and swaps the order of the vertices of any triangles having negative determinants. 
> ...
> In the mean time you may be able to have Gmsh produce elements with the orientations that MFEM expects. 

Do you mean that Gmsh sometimes generates elements with negative determinants? Or does it have something to do with how MFEM reads the mesh file?

**Comment by mlstowell** [comment]
Hi, @benzwick ,

I'd need to dig a little deeper to be sure.  I suspect that Gmsh is producing perfectly fine triangles with positive Jacobian determinants.  MFEM assumes that elements in 2D meshes will obey a right-hand-rule when ordering their vertices.  Since Gmsh always produces meshes with coordinates in 3D it would be unreasonable to expect Gmsh to follow a right-hand-rule since the 2D mesh could describe a curved surface which may not even be orientable.  In such meshes (2D surfaces embedded in 3D) MFEM computes a rectangular Jacobian and computes a "determinant" for this by taking the cross product of the two rows of the Jacobian.  If this cross product is aligned with the z-axis then the "determinant" has a positive sign otherwise it is negative (I haven't verified this but I believe something like this is happening).  Most likely the current algorithm in MFEM dates from a time before support for surfaces in 3D was added and it probably needs to be updated.

Best wishes,
Mark

**Comment by mlstowell** [comment]
I hope @benzwick won't mind if I hijack this issue to discuss a possible solution.

@tzanio, @pazner, and @bslazarov, I'd like to hear your thoughts on this.  The crash occurs on the following line: https://github.com/mfem/mfem/blob/3454f1061d9bd1c3a4c36baf401c7c6dd435fab8/mesh/mesh.cpp#L4348
because the `vi` pointer is only set if there is no `Nodes` grid function.  In the 3D case the corresponding pointer is always set and the `Swap` succeeds.  However, wouldn't the `Nodes` grid function become invalid if the vertices are swapped?

**Comment by tzanio** [comment]
Hi Mark,

This was reported in https://github.com/mfem/mfem/pull/1999 and will be fixed by https://github.com/mfem/mfem/pull/1936.

ping: @v-dobrev

**Comment by mlstowell** [comment]
That's great.  I guess I missed that one.  Thanks!

**Comment by benzwick** [comment]
@mlstowell you were right, the original mesh that I was using had the node ordering reversed (see screenshot below). The ordering should be counterclockwise like this (https://gmsh.info/doc/texinfo/gmsh.html#Low-order-elements):
```
Triangle:               Triangle6:          Triangle9/10:          Triangle12/15:

v
^                                                                   2
|                                                                   | \
2                       2                    2                      9   8
|`\                     |`\                  | \                    |     \
|  `\                   |  `\                7   6                 10 (14)  7
|    `\                 5    `4              |     \                |         \
|      `\               |      `\            8  (9)  5             11 (12) (13) 6
|        `\             |        `\          |         \            |             \
0----------1 --> u      0-----3----1         0---3---4---1          0---3---4---5---1
```
However, I still don't understand why Gmsh would sometimes generate a mesh with the ordering reversed.

![Screenshot_20210207_103530](https://user-images.githubusercontent.com/33216696/107134903-1a455f00-6931-11eb-9a11-8f1c0603e6e4.png)

**Comment by benzwick** [comment]
Regarding the reordering of nodes within MFEM: maybe it would be better not to do it automatically because, as in the case here, the fact that the nodes need to be reordered suggests that there is a problem with the mesh that should be addressed before loading it into MFEM. I would prefer if by default an error was raised if an element with negative Jacobian is encountered when reading a mesh file. This would also be easier to implement than attempting to reorder higher order elements.

See also these related comments:
- https://github.com/mfem/mfem/pull/1936#issuecomment-742348852
  > Actually, now that I think about it: this happens only when the `Mesh` has `Nodes` (i.e. the mesh may be high-order), so just flipping the vertex indices may not be sufficient.

- https://github.com/mfem/mfem/pull/1936#issuecomment-767640252
  > Should we mention somewhere that the `fix_it` options works only on low-order meshes (when `Nodes == NULL`)?

**Comment by benzwick** [comment]
FYI the reversal of the node ordering in Gmsh for `Physical Curve` and `Physical Volume` is documented [here](https://gmsh.info/doc/texinfo/gmsh.html#Curves) and [here](https://gmsh.info/doc/texinfo/gmsh.html#Surfaces):
> In some mesh file formats (e.g. MSH2), specifying negative tags in the expression-list will reverse the orientation of the mesh elements belonging to the corresponding elementary curves in the saved mesh file.
