### ISSUE TITLE
CUDA slows down code

### ISSUE THREAD

**Issue by wcdawn** [mfem/mfem#2065]
I've written a program using MFEM. The main solver is a power-iteration eigensolver so there are many calls to the CG solver (and HypreBoomerAMG preconditioner). When I run with the device set to CUDA, the code runs slower. I'm not sure how this is possible. This seems to be the case for every test problem I run regardless of mesh size or vector-dimension.

I think part of my problem is using `QuadratureFunction` and `QuadratureFunctionCoefficient`. I have quantities that I do not want to have to recompute many times but they seem to be all stored on the Host.

I looked into this more by running `ex1p` since it uses the same linear solver and preconditioner I'm using. To slow things down to have a measurable runtime, I used 4th order elements. My command is simply
`./ex1p -o 4 -d cuda`
To make sure I wasn't missing something, I used `std::chrono` and timed only the call to `Mult()`. Running with CUDA had nearly the same runtime +/-3%.

I feel like I'm missing something here. I've read the [GPU Help](https://mfem.org/gpu-tips-n-tricks/) page but I'm not sure how to use it in my code. It seems to be focused on MFEM development, not using MFEM.

Is all I can hope for a 3% runtime improvement? Is there an example I can look for? I'm preparing for large runs on Summit so I need to be able to take advantage of the GPUs.

**Comment by rcarson3** [comment]
@wcdawn `QuadratureFunction` should not be an issue. I use them heavily in my application `ExaConstit`, and I'm able to achieve a 15-16x speed-up when running things on the GPU. Since, they are child class of `Vector` you can just do a `var.UseDevice(true)` and `var.Read/ReadWrite/Write()` to pull the data onto the device, and then you can use `MFEM_FORALL` with `mfem::reshape` (so you don't have to deal with raw pointers) to operate on the data.

Now, if you're doing `QuadratureFunctionCoefficient::Eval` that is going to be slow, since these operations must happen on the host. You're better off doing something like what's done here: https://github.com/mfem/mfem/blob/master/fem/bilininteg_mass_pa.cpp#L61-LL73

I would recommend defining `MFEM_TRACK_CUDA_MEM` when building MFEM and you'll then be able to track device-host data movement as seen here: https://github.com/mfem/mfem/blob/master/general/cuda.cpp#L37-L40 . I found this extremely useful to figure out where data motion was occurring and if I had something running on the host that I thought was running on the device when I was initially porting my app.

**Comment by artv3** [comment]
Hi @wcdawn ,

I agree with @rcarson3, data at quadrature points should be sampled on the GPU otherwise it will be slow. 
There is a quadrature interpolator in MFEM that you might be able to use if your function is stored as an mfem gridfunction.  

We are also actively working on supporting Hypre on GPUs through MFEM, thus at the moment HypreBoomerAMG can only be done on the host.  We have support for NVIDIA's AmgX if you need AMG + PCG on NVIDIA GPUs (feel free to ping about configuring it) as a stop gap. We have a few examples as well under examples. 
 
But when it comes getting good performance on GPUs from a developer perspective there are a few things to keep in mind. 
- Memory allocations become much more expensive, its best to allocate the memory upfront or use MFEM + Umpire for fast memory allocations (work in progress). 
-  Keep all the data on the GPU if possible as transfers are slow. 
- If computational routines are not on the GPU they will certainly show up as host spots. 

Also some questions
Are you reconstructing matrices in your code? Can your application use the partial assembly variants?

**Comment by artv3** [comment]
Also checkout nvvp for a timeline of your application, it can be used to look at "hot spots" and where time is being spent.

**Comment by wcdawn** [comment]
Thanks for the feedback! As of now when I set `QuadratureFunction::UseDevice(true)` I get the wrong answer but that just means I'm not properly syncing the memory at some point. Something for me to fix...

From both of your responses, it looks like I need to use some level of Partial Assembly to take advantage of these GPUs. Currently, I'm assembling the full matrices. My problem has a large vector dimension (~100) so I've had to reimplement many of the Integrators to support vector dimensions (on branch `wcdawn/TensorCoefficient`). The prospect of implementing Partial Assembly for everything sounds daunting. I may look into a different way to structure these equations so that I can use the existing integrators with partial assembly support.

I'll probably need to use AmgX so I'll have to look into configuring that.

I revisited `ex1p` using partial assembly. Using pa+cuda did help speed up the code. But, it took thousands of more iterations.

@artv3 I'm not sure what you mean "reconstructing matrices"?

**Comment by artv3** [comment]
@wcdawn do you have .Assemble() inside a loop for your bilinearforms? This comes up if the coefficients of your FEM operators have a dependence on time.

**Comment by wcdawn** [comment]
@artv3 No. The bilinear forms are assembled once and finalized. The linear forms are assembled many times and the quadrature functions are recalculated many times.

**Comment by YohannDudouit** [comment]
@wcdawn I would also highly recommend that you use some sort of profiler to get an idea of where you spend your time. I suspect that some critical parts of your code need to be ported to GPU.

**Comment by wcdawn** [comment]
I've looked into profiling the code. The MFEM instructions describe how to use `nvprof` but that has been deprecated and cannot support the newest generation of GPUs. I have the new Nsight Compute `ncu-ui` working. But, I have no idea what to look for. Notably, NVIDIA no longer includes `gld_efficiency` or `gst_efficiency` data. What statistics should I investigate? Do I need to look at each CUDA kernel call or are there some average/aggregate statistics?

I've also configured MFEM to work with AmgX. It looks like AMG+PCG from AmgX will be a good option for my problem. It looks like Partial Assembly does not work with AmgX. Is this correct?

**Comment by artv3** [comment]
@wcdawn AmgX through MFEM requires a HypreParMatrix, you can probably configure AmgX to be the preconditioner (with the HypreParMatrix) and use PA based operators for MFEM's CG - or you can just let AmgX do the preconditioning + CG with the HypreParMatrix. At the moment if you let MFEM do CG with Hypre data structures it will do computation on the CPU. 

One thing to do is look at how many routines are actually being offloaded to the GPU. Using NVVP (https://developer.nvidia.com/nvidia-visual-profiler) you can look at device activity, if there is a lot of blank on the device activity row then the code is not being offloaded to the GPU.

**Comment by YohannDudouit** [comment]
@wcdawn The first information you want to get from the profiler is where you spend your computation time (CPU or GPU), what are the functions/methods/kernels that take the most significant part of the time? Are these the functions/methods that you expect? Why are they slow? This is where you start looking at memory bandwidth and so on.

**Comment by wcdawn** [comment]
I am pursuing another method for solving these equations to better leverage the GPU power. Instead of writing a power iteration solver, we are going to use a SLEPc solver and the GPU performance in PETSc & SLEPc.

It did seem that the AmgX solvers were the best option but properly using CUDA with MFEM would require a good deal of specialty coding.
