### ISSUE TITLE
How to change the values of a GradientGridFunctionCoefficient ?

### ISSUE THREAD

**Issue by LeilaSalomon** [mfem/mfem#2073]
Hello :) 

I solve a Laplace equation to determine the velocity potential Phi in a domain Omega. After getting Phi, I would like to retrieve the velocities vx vy, by calculating the gradient of Phi. Then, these velocities are used to move an advection equation. To retrieve the flow velocities, I use : GradientGridFunctionCoefficient **velocity**(&Phi), which will then be used in my bilinear form k of the advection equation: 

     BilinearForm k(fes);
     k.AddDomainIntegrator(new TransposeIntegrator(new ConvectionIntegrator(**velocity**)));
     k.AddInteriorFaceIntegrator((new DGTraceIntegrator(**velocity**, -1.0, -0.5)));
     k.AddBdrFaceIntegrator((new DGTraceIntegrator(**velocity**, -1.0, -0.5)));

I would like to know if it's possible to change values of **velocity**? For example, I would like to impose a vx value on one of the domain boundaries ?

Best regards,

Leïla

**Comment by robert-chiodi** [comment]
Hi @LeilaSalomon ,

I believe in order to change the values of velocity, you would first need to project the `GradientGridFunctionCoefficient velocity` to a `GridFunction` defined for an appropriate FiniteElementSpace. You could then modify the appropriate values in that GridFunction and create a `VectorGridFunctionCoefficient` from it to use in your Convection integrators. Someone please feel free to correct me if this is wrong.

Hope that helps

**Comment by LeilaSalomon** [comment]
Hello Robert,

Thank you for your answer, it helped me a lot !
