### ISSUE TITLE
Some questions about ex2

### ISSUE THREAD

**Issue by HFH104864** [mfem/mfem#2080]
I am new to MFEM and a little bit new to C++ , so maybe the question is a little bit stuipid .

In order to compute  then stress sigma(u), strain eps(u) , accroding to #10 ,I have tried that code and I get the postproc.gf file .

 I return sigma(0,0) , So it looks like I got a  solution of stress . But in the postproc.gf file, I see three numbers are equal, and there are many groups of such numbers, and the number of groups is equal to the number of cells.As shown in the figure, by the way, the number of elements in the model is 4, I suspect this is the stress value of the integral point, if so, how do I get the stress value of the node

thank you!
![1614826884(1)](https://user-images.githubusercontent.com/69201217/109905002-10690e80-7cd9-11eb-9522-59af320e8457.png)

**Comment by xianyu-gao** [comment]
sorry，i don't know

**Comment by tzanio** [comment]
Hi @HFH104864,

Where to represent a coefficient (in your case `sigma(0,0)`) depends on the definition of the `FiniteElementCollection`.

For example `L2_FECollection pp_fec(p);` corresponds to discontinuous function which is a polynomial of order `p` in each element. In your case that order is `p=1` ad you can tell from the `L2_2D_P1` description in the saved file. For triangles that means three degrees of freedom per element. (In your case `sigma(0,0)` is a constant on each element, so these three degrees of freedom are the same)

In general, the stress is discontinuous, so it has multiple values in the vertices of the mesh. That's why the example uses a discontinuous space. If you really want a continuous representation, try replacing the `L2_FECollection` with `H1_FECollection`.

Hope this helps,
Tzanio

**Comment by HFH104864** [comment]
thank you for your anwer . And one more question , whether the stress obtained in that file can represent the true stress value

**Comment by HFH104864** [comment]
> 
> 
> Hi @HFH104864,
> 
> Where to represent a coefficient (in your case `sigma(0,0)`) depends on the definition of the `FiniteElementCollection`.
> 
> For example `L2_FECollection pp_fec(p);` corresponds to discontinuous function which is a polynomial of order `p` in each element. In your case that order is `p=1` ad you can tell from the `L2_2D_P1` description in the saved file. For triangles that means three degrees of freedom per element. (In your case `sigma(0,0)` is a constant on each element, so these three degrees of freedom are the same)
> 
> In general, the stress is discontinuous, so it has multiple values in the vertices of the mesh. That's why the example uses a discontinuous space. If you really want a continuous representation, try replacing the `L2_FECollection` with `H1_FECollection`.
> 
> Hope this helps,
> Tzanio
Thank you for your answer , and one more question. Whether the stress obtained in that file can represent the true stress value

**Comment by HFH104864** [comment]
And how can I get the VTK file about stress  , because I am trying to make a corresponding stress nephogram

**Comment by tzanio** [comment]
Sorry I didn't see the question above (I modified your post to make it clear).

Yes, that is the exact stress for the given discretization.

**Comment by HFH104864** [comment]
thank you !
