### ISSUE TITLE
Strain boundary conditions in Linear Elasticity 

### ISSUE THREAD

**Issue by rafaelmarch3** [mfem/mfem#2083]
Hello all, 

I am solving a linear elasticity problem whereby I deform a cube with a heterogeneous distribution of lame coefficients and measure the effective bulk and shear moduli.

I have successfully achieved this by applying stress (compressive) boundary conditions in all 6 faces. 

Now I would like to prescribe strain boundary conditions (i.e. percentage deformation) at the cube faces. Is there any way to apply strain instead of stress (traction) BCs? 

Thank you!

**Comment by rcarson3** [comment]
@rafaelmarch3 if you're trying to apply a given strain to a cube you won't want to use traction boundary conditions, since they are Neumann BCs. You'll instead want to make use of Dirichlet/essential BCs and apply given displacements to the faces of the cube. Since, you're dealing with a linear elastic material you should also be able to apply these displacements in one shot as well.  You should be able to just make use of the average displacement gradient across the body and then from there get out what ever strain formulation that you desire.

I would take a look at the documentation at https://mfem.org/fem_bc/ which goes over the various different ways to apply BCs in MFEM.

**Comment by rafaelmarch3** [comment]
> @rafaelmarch3 if you're trying to apply a given strain to a cube you won't want to use traction boundary conditions, since they are Neumann BCs. You'll instead want to make use of Dirichlet/essential BCs and apply given displacements to the faces of the cube. Since, you're dealing with a linear elastic material you should also be able to apply these displacements in one shot as well. You should be able to just make use of the average displacement gradient across the body and then from there get out what ever strain formulation that you desire.
> 
> I would take a look at the documentation at https://mfem.org/fem_bc/ which goes over the various different ways to apply BCs in MFEM.

Many thanks! I'm checking how to implement non-uniform Displacement boundary conditions (Dirichlet), in order to apply a constant strain at the model. I need Dirichlet boundary conditions whose values depend on the node coordinates. I'm still checking how to do this, if I cannot find out, I might post another question here soon. 

Thanks again!

Rafael.

**Comment by tzanio** [comment]
I'm closing this for now, but please feel free to reopen if you have further questions.
