### ISSUE TITLE
Ghost cells

### ISSUE THREAD

**Issue by geyan3566** [mfem/mfem#2095]
Hi,

I am developing a new FEM method that requires multiply layers of ghost cells on each local mesh and updates the solution on the ghost cells between each time step.
Does MFEM provide the functionalities above? 

Thanks,
Ge

**Comment by MarkShephard** [comment]
I can not directly answer the question of if MFEM supports multiple layer ghosting. However, I can point out that the proper specification of ghosting requires indicating the entities to be ghosted (e.g., mesh regions that are elements) and indicating the bridge entity (e.g. faces, edges or vertices) which will indicating what topological entity you want to use to define the neighbors to be ghosted. 

The PUMI software that is linked to MFEM for conforming mesh adaptation does support the definition of multiple level ghosting. See the attached paper. 

[654971.pdf](https://github.com/mfem/mfem/files/6117347/654971.pdf)

**Comment by tzanio** [comment]
Except in the case of DG (where we store face neighbors) we don't have ghost cells in MFEM, but only exchange surface data.

**Comment by geyan3566** [comment]
Thank you Prof. Shephard and tzanio for answering my question.
I'll install `pumi`  with `MFEM`. If there is other questions, I'll post here.

**Comment by MarkShephard** [comment]
Please note that PUMI can support the construction of multiple ghost layers in its data structures. Thus if you wanted to try to make use of that capability, the procedures that you are developing that need to make use of ghost information would need to first directly interact with the PUMI mesh structures. In addition, work would need to be done to take and needed  MFEM solution field data and load them into the PUMI field data structures since the PUMI API associated with ghost entities only interact with PUMI APF fields. This would likely be a fairly substantial development.

**Comment by geyan3566** [comment]
I had a configuration error while install `mfem` with `pumi`.
Here is the configuration error for `mfem`:

```
-- (optional) USER_CONFIG = /users/yang/code/mfem/config/user.cmake
-- USE_XSDK_DEFAULTS = 'OFF'
-- A library with LAPACK API found.
-- SCOREC component gmi_sim found: False
-- MFEM: using package MPI_CXX
-- MFEM: using package BLAS
-- MFEM: using package LAPACK
-- MFEM: using package METIS
-- MFEM: using package HYPRE
-- MFEM: using package PUMI
-- MFEM: using package POSIXCLOCKS
-- MFEM build type: CMAKE_BUILD_TYPE = Release
-- MFEM version: v4.2.1
-- MFEM git string: heads/master-0-g8af351185c1e7a81e8241534ed7ff7d52f04f172
-- Writing substitute header --> "mfem.hpp"
-- Writing substitute header --> "mfem-performance.hpp"
-- performance_ex1: add flags "-march=native -Wall -pedantic --param max-completely-peel-times=3"
-- performance_ex1p: add flags "-march=native -Wall -pedantic --param max-completely-peel-times=3"
-- CMAKE_INSTALL_PREFIX = /users/yang/code/mfem_install_pumi
-- simmodsuite_dir = ''
-- Configuring incomplete, errors occurred!
See also "/users/yang/code/mfem_install_pumi/CMakeFiles/CMakeOutput.log".
See also "/users/yang/code/mfem_install_pumi/CMakeFiles/CMakeError.log".
```

The pumi configuration file 
```
cmake ../core \
  -DCMAKE_C_COMPILER="mpicc" \
  -DCMAKE_POSITION_INDEPENDENT_CODE=YES \
  -DCMAKE_CXX_COMPILER="mpicxx" \
  -DSIM_MPI="mpich3.1.2" \
  -DENABLE_ZOLTAN=OFF \
  -DCMAKE_INSTALL_PREFIX=/users/yang/code/pumi_install
```

Here is the mfem configuration file:
```
cmake ../mfem \
-DCMAKE_BUILD_TYPE=Release \
-DMFEM_USE_MPI=YES \
-DMFEM_USE_METIS_5=YES \
-DMFEM_DEBUG=YES \
-DMFEM_USE_PUMI=YES \
-DMFEM_USE_PETSC=NO \
-DMFEM_USE_LAPACK=YES \
-DMFEM_USE_SUITESPARSE=NO \
-DMFEM_ENABLE_EXAMPLES=NO \
-DMFEM_ENABLE_MINIAPPS=NO \
-DPETSC_DIR=/opt/scorec/spack/install/linux-rhel7-x86_64/gcc-7.3.0/petsc-3.11.0-264efxjpnpgl5ls3erg652m6jy4qn4a7 \
-DPETSC_ARCH="" \
-DPUMI_DIR=/users/yang/code/pumi_install \
-DMETIS_DIR=/opt/scorec/spack/install/linux-rhel7-x86_64/gcc-7.3.0/metis-5.1.0-rn7k363kqpvbznmxb3jkkejwjcgfqpyu \
-DCMAKE_INSTALL_PREFIX=/users/yang/code/mfem_install_pumi
```

**Comment by MarkShephard** [comment]
Ge,

I should have put 2 plus 2 together earlier. I assume you are working with Jason on the summation by parts stuff. You want this multi-layer ghosting information for structuring the needed difference relations. 

As mentioned, this will not be that easy to do. I suggest that we set-up a WebEx of you and Jason with some SCOREC PUMI people to start the discussion. We want to have this discussion before you start trying to look at code since you really need to know what you are looking for and I do not know of any existing MFEM examples or miniapps that will provide a starting template for this (in general we avoid ghosting as much as possible). 

Mark

**Comment by jehicken** [comment]
Hi Mark,

Thanks.  Let me provide some more background: I asked @geyan3566 to look into the possibility of extending his discontinuous Galerkin difference code to parallel.  I knew that the ease/difficulty of this would depend on how many ghost/halo elements are available directly in mfem.  Since they keep only face-adjacent elements for DG, we are looking at a non-trivial development.

Parallel high-order was one of those things that would have been nice for Ge's thesis had it been available, but it is not essential.  Therefore, I do not want to waste your time, or the time of the PUMI folks.   We might consider a meeting if more ghost elements are more widely desired by the mfem community (which I doubt).  Even then, we (Ge and I) may not have the resources on our end to do this in a timely fashion.

Thanks again,
Jason

**Comment by tzanio** [comment]
Hi guys,

Just to chime in -- I totally agree that extending the ghost layer beyond face-neighbors will be non-trivial in mfem. This is enough for (high-order) DG, but I can see how you need more for GD :)

Tzanio
