### ISSUE TITLE
New integration rule

### ISSUE THREAD

**Issue by martemyev** [mfem/mfem#21]
Dear all,

I'd like to implement a new integration rule on a segment so that it would be used in square and cube integration rules (the same way it's done right now) and use it along with the existing integration schemes. For example, there is IntegrationRule::UniformRule(), which (as far as I understand) is not used anywhere in the code. Only IntegrationRule::GaussianRule() is. So, basically, my question can be reformulated in the following way: how can I switch to Uniform integration rule working with a high level code - for example, with Example 1. Once I can do that, I'll be able to incorporate a new integration scheme that I need.

Thank you,
Mikhail

**Comment by v-dobrev** [comment]
In Example 1, you can replace the default integration rule used by the DiffusionIntegrator by replacing the line
```
a->AddDomainIntegrator(new DiffusionIntegrator(one));
```
with something like this:
```
IntegrationRule my_ir(num_points);
// Set the coordinates and weights in my_ir.
DiffusionIntegrator *diff_int = new DiffusionIntegrator(one);
diff_int->SetIntRule(&my_ir);
a->AddDomainIntegrator(diff_int);
```
You can also replace the default MFEM integration rules by setting them in the global variable 'IntRules' using the Set method. This should work because initially the object is empty and new rules are allocated upon request if they are not already defined.

**Comment by martemyev** [comment]
Thank you, Veselin!

That was surprisingly easy!

Best regards,
Mikhail
