### ISSUE TITLE
Nonuniform order of elements

### ISSUE THREAD

**Issue by vikramsg** [mfem/mfem#211]
I think there was some discussion previously about this but I can't find it right now. 

How can I go about setting up a finite element problem with a non-uniform order. I am using the DG method and I see that basically each element type is decided by FECollection which is initialized with a constant number at the start. 

The finite element space is setup using this collection and so GetFE etc also gives a constant order element for each element. Am I right to assume that most of the setup required for nonuniform order would be in FECollection and then fespace as it would need the element number as an argument each time fec->DofForGeometry etc is called.

I would appreciate any pointers. Also if some work has already been done, please do share. 

EDIT: I think now that the post maybe a bit confusing. By order I mean the order of the polynomial, not the node ordering etc. of the mesh.

**Comment by jdahm** [comment]
There has been some internal discussion about how to add this, but nothing concrete has been decided. I am interested in seeing this feature added, so let me know if you start something.

It appears that, as you said, the interaction between the `FiniteElementSpace` and the `FiniteElementCollection` will have to change. `FiniteElementCollection`s are defined as finite elements of the same family with no concept of a mesh or element numbering, so maybe it's better to add the concept of "groups" of elements each with their own `FiniteElementCollection`.

I'm new to the project, so others may have more concrete information to add to our discussion.

**Comment by v-dobrev** [comment]
Here is one approach:
* We can add a base abstract class, say `VarFiniteElementCollection` ("Var" - short for "variable order") that supports the following virtual operation, e.g. `FiniteElementCollection &GetColl(int)`: given and integer (e.g. polynomial order/degree) return a reference to a `FiniteElementCollection` that corresponds to that integer.
* Then derived classes, e.g. `VarH1_FECollection` or `VarL2_FECollection` will construct and store the corresponding `{H1,L2}_FECollection` objects, of the required order, when requested by `GetColl()` and store it for future use.
* In class `FiniteElementSpace`, we can add a new "variable order" constructor that uses a `VarFiniteElementCollection` instead of `FiniteElementCollection`. We will also need to add an array of integers for all elements in the mesh to store the element orders.
* Then we need to go over all methods of the class `FiniteElementSpace` and make sure they handle correctly both the fixed- and the variable-order cases.
* Similarly, we need to examine all methods in `ParFiniteElementSpace` and probably other classes in the code.

**Comment by vikramsg** [comment]
Thanks @v-dobrev, 

I had actually dived head first into the implementation and started facing a few problems. I think the route you suggest seems much more streamlined. I'll try this approach.

**Comment by vikramsg** [comment]
I actually have it working now. Unfortunately some of the mesh refinement conditions were a little too complex for me, so I am actually using GetValuesFrom function in GridFunction to update the gridfunction values. Apart from that fes update, bilinearform update etc all work fine.

**Comment by tzanio** [comment]
Hi @vikramsg, can you clarify what you got working? Is it DG with varying polynomial orders between elements? Thanks, -Tzanio

**Comment by vikramsg** [comment]
Hi @tzanio , yes. The way I have implemented it is varying polynomial order only for DG. But as I said, its pretty hacky, since the GridFunction Update() had some conditions that I could not figure out so I used the GetValuesFrom function and temporary variables to do updates.

**Comment by tzanio** [comment]
Great to hear you got it working, @vikramsg. 

We will be interested in adding this to the library if you decide to clean it up in the future :)

 I'm closing this issue now. Feel free to reopen if you have any further questions.
