### ISSUE TITLE
Cannot currently compile MFEM with LIBCEED support

### ISSUE THREAD

**Issue by stefanozampini** [mfem/mfem#2134]
This is not really something vital at this time, more like a note.

In MFEM master, `fem/ceed/utils.hpp` includes `ceed-backend.h` which is not installed in prefix locations by CEED. This breaks builds when MFEM is configured using a LIBCEED installation.

 
```
[szampini@localhost git.libceed]$ git log -1
commit 3655fa6dc642b171b7b55da3830091895892d99f (HEAD -> main, origin/main, origin/HEAD)
Merge: e15f9bd0 d99129b9
Author: Leila Ghaffari <Leila.Ghaffari@colorado.edu>
Date:   Fri Mar 19 23:33:36 2021 -0600

    Merge pull request #714 from CEED/leila/ex-output-dir
    
    Fluids & Solids | add/modify cl options for viz output folder
```

**Comment by barker29** [comment]
Good catch @stefanozampini . At first I thought #2123 would fix this but it won't matter because we still need `ceed-backend.h` in the .cpp files. I can't think of a good fix. We probably don't want to require users to use a non-prefix in-source build of libCEED. Maybe the best solution is to include our own definitions of whatever functions from `ceed-backend.h` we use and hope the library doesn't change.

**Comment by v-dobrev** [comment]
@jedbrown, any thought on this? Should `ceed-backend.h` be installed by libCEED? Or should the necessary functions be made available in `ceed.h` or some other installed header?

**Comment by barker29** [comment]
I think `ceed-backend.h` is specifically not intended to be used by users, so it's intentionally not installed. The ceed-solvers stuff kind of hacks around this (which I thought we could get away with). Changing the Ceed interface is one option, but the more I think about it I think re-defining some of the backend Ceed functions in MFEM might be the way to go - if I remember correctly we already do something similar to this when we want to access some of hypre's "private" functions and data.

**Comment by jedbrown** [comment]
Let's install `ceed-backend.h` because it's supposed to be possible to package backends as plugins, distributed independently from libCEED. While one distribution scenario is that backends (which might not be open source) are compiled and distributed as binaries, another that we should support is that backends are distributed as source.
