### ISSUE TITLE
Complex-valued inhomogeneous Helmholtz equation

### ISSUE THREAD

**Issue by Vinc0110** [mfem/mfem#2167]
Hello,
I'm trying to implement an [inhomogeneous Helmholtz equation](https://en.wikipedia.org/wiki/Helmholtz_equation#Inhomogeneous_Helmholtz_equation) for the electric field *E* in MFEM, as it is usually derived from Maxwell's equations with time-harmonic fields. To be useful for typical rf electronic applications, one has to deal with **complex-valued material coefficients and field components**. 

Two years ago, this issue was already brought up in this issue https://github.com/mfem/mfem/issues/467. Several tips and hints are mentioned there, e.g. splitting the real and imaginary parts and formulating them as 2x2 block matrices. I did that:
![blocks](https://user-images.githubusercontent.com/63644854/114551882-400a1f80-9c64-11eb-82d8-6dbf3400757d.jpg)

Example [ex5.cpp](https://github.com/mfem/mfem/blob/master/examples/ex5.cpp) was mentioned as a guide on how to implement this in MFEM, but I find it quite hard to understand without additional documentation. 
Also, the [complex operator class](https://github.com/mfem/mfem/blob/master/linalg/complex_operator.hpp) was mentioned as a way to do this, but again, with only those few lines of comments in the code I'm having a hard time figuring out how to actually use it for my equations.

I'm also aware of the discussion in issue https://github.com/mfem/mfem/issues/1953 about the implementation of a complex-values r.h.s. The use of `(Par)ComplexGridFunction` is suggested there, but is that what I need here?

As you see, I'm having trouble putting all the pieces together. Could anyone please provide some more information or maybe point out how these classes are meant to be used? The documentation listed on [the website](https://mfem.org/fem/) is great, but unfortunately does not cover all these special classes. It would be great if anyone could point me in the right direction.

Thanks in advance,
Vincent

**Comment by psocratis** [comment]
Hi @Vinc0110 ,

One way to do this is form manually the 2x2 block system as you suggested above. 

In order to avoid this you can use  `ComplexLinearForm`,  `SesquilinearForm` and `ComplexGridFunction` classes which essentially do the same thing but it's hidden from the user. As an interface is very similar to the real case, the user has to provide the real and imaginary parts of the differential operator and the right hand side. A good starting point is [ex22.cpp](https://github.com/mfem/mfem/blob/master/examples/ex22.cpp) which demonstrates this for many problems including Helmholtz. Additionally you can take a look at [ex25](https://github.com/mfem/mfem/blob/master/examples/ex25.cpp), where PML formulations for Maxwell equations are considered. 

I hope this helps. 

Best,
Socratis

**Comment by Vinc0110** [comment]
Thank you for the hints. For some reason, I did not consider ex22, but it seems to do exactly what I need. It will keep me busy for a while, so I'm closing this issue for now.

Thanks, Vincent
