### ISSUE TITLE
Why FormLinearSystem does not reduce system size?

### ISSUE THREAD

**Issue by Marshdweller** [mfem/mfem#2182]
Sorry if my question is obvious, but I am really stuck.

I do not understand why 'FormLinearSystem' does not actually reduce the system matrix's size after elimination with 'DIAG_ZERO'? The matrix contains empty (all-zero) rows.

This is Laplace eq with L1 elements:

```
Vector xx(H_space_f->GetVSize()),bb(H_space_f->GetVSize());
xx=0.0;bb=0.0;
Vector XX,BB;
SparseMatrix AA;
blf_a->SetDiagonalPolicy(Matrix::DiagonalPolicy::DIAG_ZERO);
blf_a->FormLinearSystem(dirichlet_tdof_list,xx,bb,AA,XX,BB);
printf("\n\n AA: %u x %u \n",AA.NumRows(),AA.NumCols() );
printf("Done \n");
fflush(stdout);
```

I am solving a 3x3 block problem, and I need to remove BC-related equations from all blocks. Otherwise, off-diagonal blocks will have all-zero rows and columns, but I want them to be full rank.

Thank you.

M

**Comment by mlstowell** [comment]
Hi, @Marshdweller,

Well, I suppose you could say this is just the choice we made. If we had reduced the size of the linear system by removing the rows and columns associated with essential BCs we would need to copy our solution vectors to larger vectors and place the BC values on selected rows of these longer vectors after the solve. This is an extra step and it requires more memory to store the two vectors. Removing rows from a sparse matrix stored in CSR format is also non-trivial. We could come up with a clever way to do this without actually shifting the matrix entries to collapse the empty rows but this wouldn't be the CSR format anymore.

The option we chose was to maintain the size of the linear system and place the BC values into the right hand side vector so that the solver could place these values into the solution vector for us. As a consequence our sparse matrices have rows of zeros (and a single non-zero, typically) but this wasted space is a small price to pay so that we can avoid copying the matrix entries into smaller arrays.

When building block systems we typically place a '1' on the diagonal entry and zeros everywhere else in the row and column for each essential degree of freedom. The `Matrix::DiagonalPolicy::DIAG_ZERO` is used only in the off-diagonal blocks of the block operator and it will create singular blocks but this is generally not a problem. The diagonal block would use either `DIAG_ONE` or `DIAG_KEEP` (the later maintains the existing diagonal entry).

If having non-singular blocks is important then this can be accomplished by placing non-zero entries into the zeroed out rows of the off diagonal block but this would be very tricky. It would link together BC values from the three rows of the block system (creating triplets of related BC values) and effectively create small 3x3 linear systems for each triplet of boundary values. You would need to ensure that these 3x3 systems were non-singular and you would need to place linear combinations of your BC values into the right hand side vector so that the correct values end up in the solution vector.

I hope this clarifies things.
Best wishes,
Mark

**Comment by Marshdweller** [comment]
@mlstowell, thank you for such a clear explanation. So, it works as designed. Linking together Dofs between the parts of a partitioned solution vector looks quite tricky. I think I will try to derive a class from BilinearForm and implement something similar to Finalize to translate from  LIL to CRS. A simpler option is to copy the non-singular submatrix to a separate matrix.

Thank you!

Regards, 
M
