### ISSUE TITLE
How to assemble the ParBilinearForm ( w\cdot\nabla u, v) for a given VectorFunctionCoefficient w? 

### ISSUE THREAD

**Issue by Andr00dz** [mfem/mfem#2188]
Hi,

in order to implement a specific Navier-Stokes discretization, I need to assemble the `ParBilinearForm ( w\cdot\nabla u, v)`, where `w` is a given `VectorFunctionCoefficient` and `u, v` are the trial/test functions from a vector-valued H1 `ParFiniteElementSpace`.

The bilinearform is defined by `( w\cdot\nabla u, v)=\sum_i=1^d (w\cdot \grad u_i, v_i)`, where `u_i` and `v_i` denotes the ith entry of `u` and `v`.

For the scalar case, there is the `ConvectionIntegrator`. Unfortunately, I did not find the vector-valued version of `ConvectionIntegrator`. Is there an easy way, to assemble it with integrators, which are already implemented in mfem?

Thanks in advance,
Andi

**Comment by pazner** [comment]
This is very similar to what `ConvectiveVectorConvectionNLFIntegrator::AssembleElementGrad` does (but in that integrator, there is the assumption that the specified velocity lies in the given finite element space, and is not an arbitrary vector coefficient). If `w` actually comes from a grid function, you could probably use `ConvectiveVectorConvectionNLFIntegrator` out of the box. Otherwise, you could use the implementation as a starting point to write your own modified version.

**Comment by Andr00dz** [comment]
Thanks for the fast reply.

Yes, `w` stems from a `ParGridFunction` (its the velocity of a previous time step). It seems `ConvectiveVectorConvectionNLFIntegrator` is hidden in the source code and not yet listed in the [documentation](https://mfem.github.io/doxygen/html/index.html), which I use a lot.

Do you mean with "out of the box" that I can use `ConvectiveVectorConvectionNLFIntegrator` directly to assemble the bilinearform? I don't have much experience with `NonLinearForm` . Since `ConvectiveVectorConvectionNLFIntegrator` is `NonlinearFormIntegrator`, I guess that I can't just write

```
mfem::ParBilinearForm *aVarf(new mfem::ParBilinearForm(Vh_space));
aVarf->AddDomainIntegrator(new mfem::ConvectiveVectorConvectionNLFIntegrator(w));
aVarf->Assemble();
```
to assemble the required bilinearform. How can `ConvectiveVectorConvectionNLFIntegrator` be used to get my bilinearform that I can then further use to call `aVarf->FromLinearSystem(...)`?

**Comment by pazner** [comment]
You're correct, since `ConvectiveVectorConvectionNLFIntegrator` is a nonlinear integrator, it can only be used with a `NonlinearForm`, and not a `BilinearForm`.

(The reason for this is that the convective term in the N-S equations is nonlinear, and the form you are interested in assembling is a certain linearization of that form).

You can get the matrix associated with this system by calling `NonlinearForm::GetGradient` (essential boundary conditions can be set with e.g. `NonlinearForm::SetEssentialTrueDofs`).

If all you need is the assembled matrix, I believe that the above should be sufficient. If you really need to treat the form as a `BilinearForm`, then I would suggest creating your own `BilinearFormIntegrator` that essentially performs the same computations.

**Comment by Andr00dz** [comment]
I've managed to build the matrix `D`, which represents my above mention bilinearform, by the following lines:

```
mfem::ParNonlinearForm *nlVarf( new mfem::ParNonlinearForm(Vh_space));
nlVarf->AddDomainIntegrator( new mfem::ConvectiveVectorConvectionNLFIntegrator());
nlVarf->SetEssentialBC(ess_tdof_list, &b);
mfem::HypreParMatrix *D = dynamic_cast<mfem::HypreParMatrix*>(&nlVarf->GetGradient(x));
```
Is it correct that the call of `SetEssentialBC` transforms `D` and the rhs `b` in the following way?
```
D = | D_I  D_IB | -->  D = | D_I  0 |
    | D_BI D_B  |          |  0   I | 
```

```
| b_I  | -->       | b_I - D_IB x_B |
| b_B  |           |      x_B       |
```

**Comment by jandrej** [comment]
For the matrix, the behavior is as described. The treatment for the RHS is different though if you look at https://github.com/mfem/mfem/blob/d9275d734e060fc653236ab4901b370cbb6dd7ad/fem/pnonlinearform.cpp#L214

**Comment by pazner** [comment]
Also note that `SetEssentialBC` expects a "boundary marker array" rather than a list of essential DOFs.

**Comment by Andr00dz** [comment]
Thanks for the two comments. My goal is to solve a linear equation of the form `(A+D)x = b`.
In a previous step, the essential boundary tdofs were already eliminated in the matrix `A` and the rhs `b` was modified `(b_I -= A_IB x_B)` through the call of `FormLinearSystem(...)`. The diagonal entries of `A` at the eliminated rows/cols were set to `1`.
In order to solve now `(A+D)x = b` correctly, 

1.  the matrix `D` needs to be eliminated with `0` in the eliminated diagonal entries,
2. the rhs `b` needs to be additionally modified by `b_I -=  D_IB x_B`.

I think, step 1 is almost finished. I need to use `SetEssentialTrueDofs (const Array< int > &ess_tdof_list)` instead of `SetEssentialBC`.  The eliminiated diagonal entries can be manually set to `0` in a loop over the diagonal entries of `D`, which are listed in `ess_tdof_list`.

 Unfortunately, I don't see a way, to perform step 2. It seems, there is no such method in the [documentaion](https://mfem.github.io/doxygen/html/classmfem_1_1NonlinearForm.html) of `NonlinearForm`. Is there a secret/unlisted function that can perform step 2?

**Comment by Andr00dz** [comment]
I've managed to do step 2 via the eliminated matrix `mfem::HypreParMatrix *De = D->EliminateRowsCols(ess_tdof_list);`. I generate the matrix `D` without calling `nlVarf->SetEssentialBC(ess_tdof_list, &b);`, as the elimination is now done by `D->EliminateRowsCols`.

Thanks again for the comments.
