### ISSUE TITLE
What coverage settings?

### ISSUE THREAD

**Issue by adrienbernede** [mfem/mfem#2192]
#### A:
- [x] We need to change the default settings, this can be done using a yml configuration file. This file can be located:
1. In the project repo, named `codecov.yml`.
2. ~~On codecov.io website for MFEM org: https://codecov.io/account/gh/mfem/yaml~~

> Locally means version controlled, changes impact only branch up-to-date. Remote means not version controlled, act for all mfem org repos, can be edited only by project owners, changes impact all branches.

#### B:
- [x] The coverage results can:
1. Never impact the CI status.
2. ~~Impact the CI status when coverage drops a certain percentage compared to the base.~~

#### C:
- [x] Patch status (annotations in the PR diff) can:
1. ~~Be toggled with the "a" key.~~
2. Be deactivated in the yml config file.

#### D:
- [x] The status in the PR can be customized. 
1. ~~It could be shorter.~~
2. It could be removed completely, remaining accessible in the check section.

**Comment by adrienbernede** [comment]
A: 1
B: 2
C: 2
D: shorter

**Comment by tzanio** [comment]
A: fine with both
B: 2
C: 2
D: shorter

**Comment by pazner** [comment]
> A: 1
> B: 2
> C: 2
> D: shorter

Agreed with all of these

**Comment by v-dobrev** [comment]
A: 1
B: 1, also ok with 2
C: 2
D: is this about the posts from the "codecov" bot in PRs? This can be seen if you click on the "details" link next to "codecov/project" in the PR checks, so we can even disable the "codecov" bot posts.

By the way, I get "Unauthorized" if I click on "View this Pull Request on Codecov" on the "details" page -- I thought the coverage information is public? Is there a reason to restrict this?

Essentially, for me, the only thing from codecov I'd like to see on PRs are the "codecov/project" checks showing the coverage change (don't block PR merging because of this) and the "details" link for more info, if I want to look.
