### ISSUE TITLE
Question about mesh units and scale

### ISSUE THREAD

**Issue by ddkn** [mfem/mfem#2227]
Hello,

I am now playing more with the elasticity problem from ex2. I am able to create a mesh from Gmsh that works in MFEM. I realize that the Gmsh is using unitless dimensions. How does one scale the mesh units to *m*, *cm* or *mm* (or any unit for that matter) in MFEM? Or is should this be handled by the mesh creation tool? 

I realize if I am setting the Lame parameters based on Young's modulus and Shear modules (or Poisson's ratio), that I should be able to set the actual size of the mesh. But then the applied force vector, `pull_force`, in the example, is this just a raw force (N) over the attribute area or a pressure (N/m, Pa or PSI)?

I was looking at the examples and some api documentation, and it wasn't clear to me on how to do that. Any advice or help is appreciated.

Cheers,

**Comment by mlstowell** [comment]
Hello, @ddkn,

There are two answers to this question. The first is that you can use the `mesh-explorer` mini app to rescale the coordinates of any mesh it can open. This is an interactive tool found in the `miniapps/meshing` subdirectory. I believe the one the mesh is read by `mesh-explorer` you hit 's' and enter a scale factor to resize the mesh. You'll then need to write out the new mesh using the 'S' option.

The second answer is that we generally don't specify units anywhere in our code. As you alluded to, the units are tied to the values you specify for the forcing function and the Lame parameters. You could in theory solve any problem you like using an arbitrarily scaled mesh if you choose the forcing function and Lame parameters accordingly. As long as everything is self consistent your results should be fine. Of course it's often better to stick to standard systems of units so that you can avoid confusion.

Best wishes,
Mark

**Comment by ddkn** [comment]
Hi @mlstowell,

Thanks for getting back to me. I haven't gotten to the miniapps yet, as it mentioned to step through the examples before touching those, but I can take a look at that one for sure.

To make sure I understand things correctly, if I use Lame parameters "in" Pa (e.g., ~80E9 Pa,  but setting `lambda` to 80E9 for the corresponding attribute), with a forcing function "in" Pa (~20E3 Pa, setting the force function to 20E3). Everything should be fine? I did use Gmsh to specify an object of dimensions 20x20x20 "mm^3", where the surface attribute for the force function is a small circle on one side 2 "mm" diameter. The dimensions shouldn't matter because `lambda`, `mu` and the *force function* are applied consistently? I am staying in the same units for consistency.

Or since Gmsh doesn't have units, is MFEM interpreting this as meters? Or is everything still okay as above or am I simulating an object 20x20x20 "m^3". Sorry for the questions, as I am just trying to clarify some things that are not obvious to me.

Thanks!

**Comment by mlstowell** [comment]
Hi, @ddkn,

Well elasticity is not my specialty but I'll give it a try. The units for `lambda`, `mu`, and the forcing function will all cancel as long as they are the same. The displacement will have the same units as the mesh, whatever those are. For instance if you imagine your 20x20x20 mesh to be measured in millimeters then your computed displacement will also be in millimeters. On the other hand if you imagine your mesh to be measured in meters then your displacement is also in meters. This makes sense because you should expect a larger displacement since you applied a much larger force and this is linear elasticity after all.

If you apply a body force with units N/m^3 and the Lame parameters are in Pa=N/m^2 the units won't cancel and you'll get an extra ratio of whatever length unit you're using for your mesh divided by meters.

It can be quite confusing.

Best wishes,
Mark
