### ISSUE TITLE
Invalid mesh topology.  Interior edge found between 2D elements

### ISSUE THREAD

**Issue by nash169** [mfem/mfem#2233]
Hi,
I'd like to do some test about calculating Laplacian eigenfunctions on non-trivial surfaces. I'm trying to use the meshes from the Stanford repo:
https://graphics.stanford.edu/data/3Dscanrep/

Specifically I tried to use the bunny and the dragon (with different resolutions). In order to convert the ply file to a format suitable to mfem I load it with gmsh and then I re-save the mesh in .msh (format 2.2).

Although for all the meshes I tried I always get the same error:
Invalid mesh topology.  Interior edge found between 2D elements 9, 14 and 18. (this specific elements are for the mesh derived from dragon_vrip_res4.ply)

Is there a way to fix it? If there is a better tool to generate meshes for mfem or to fix inconsistencies in the mesh it would be ok for me. I don't need to stick to gmsh.

Thanks a lot in advance!

**Comment by tzanio** [comment]
Hi @nash169,

This message means that you have branching in the surface, e.g. 3 quads sharing an edge. 

We don't currently support that because some discretizations like DG are not defined with branching, but H1 discretizations could be well-defined if you are really interested in this case.

Maybe you can use some of the meshes from https://www.hexalab.net. Those seem to be well-defined for computations.

Hope this  helps,
Tzanio

**Comment by tzanio** [comment]
Glad you got it working.

Let us know if you get any interesting results!
