### ISSUE TITLE
Extended capability for `CurlInterpolator` [feature request]

### ISSUE THREAD

**Issue by pmocz** [mfem/mfem#2249]
As documented on https://mfem.org/lininterp/, the `CurlInterpolator` has two different case uses:
![image](https://user-images.githubusercontent.com/7489877/118542403-d0c29800-b707-11eb-9d58-996b0aa0e72e.png)

There would be a third useful case that is currently not implemented:
CurlInterpolator  |   H1  |  RT in 2D   |  curl(u zhat)

**Comment by tzanio** [comment]
Hi @pmocz,

Thanks for reaching out, I'm sure @mlstowell and @psocratis can help 😁 

Can you clarify what is your use case?

Is it `curl(u zhat)` where `u` is H1 scalar and `zhat` is a constant vector?

Can you provide more details about the overall scheme where you need this operation?

Cheers,
Tzanio

**Comment by pmocz** [comment]
That is correct, the use-case is:
 `curl(u zhat)` where u is H1 scalar and `zhat` is the unit vector pointing in the z-direction.

i.e., calculating the curl of an out-of-plane vector in 2D.

**Comment by mlstowell** [comment]
There is a trick which is probably undocumented which accomplishes this. If you build a `GradientInterpolator` using H1 and ND elements. You can use this to compute the curl you describe by `grad.Mult(u, du)` where `u` is in H1 and `du` is in RT rather than ND. This works because in 2D RT is just `zhat x ND` (or maybe `ND x zhat`, I forget).

Incidentally, we have a branch under review (see PR #1989) which implements 3D vector fields on 2D domains using specialized  ND and RT spaces.

**Comment by pmocz** [comment]
I could not get the "trick" to work for my application, but what seemed to work is to define a `CurlInterpolator` with domain H1, range RT in 2D, and multiply by minus 1
