### ISSUE TITLE
Namespace conflict with hypre

### ISSUE THREAD

**Issue by ScottMacLachlan** [mfem/mfem#225]
In v3.3 and newer (including git-master as of 06/22/17), the use of HYPRE_PARCSR in the enum Type member of the Operator class (linalg/operator.hpp) conflicts with its use as a #define'd constant in HYPRE.h within the hypre library.  Reproducible by using

#include "HYPRE.h"
#include "mfem.hpp"

in the headers (although the opposite order does work fine).  Suggested fix is to use a different keyword here that doesn't conflict with the hypre namespace.

**Comment by mlstowell** [comment]
On a related note, this type enumeration may not be the best thing to have in Operator.  In theory I like having easy access to type information in this way but it is not useful for user defined classes which inherit from Operator.

It seems to me that the primary purpose of this enumeration is to distinguish different internal matrix representations used in Petsc.  Perhaps it should be moved into the PetscParMatrix class and only contain the Petsc related types.  This would seem a more appropriate use of an enumeration since its members would be defined by Petsc's capabilities and our support thereof (mfem developer controlled) and not our user's potential extensions to mfem::Operator.

**Comment by gelever** [comment]
There is also a conflict with the C complex library.  ```I``` is a [macro](http://en.cppreference.com/w/c/numeric/complex/I) for imaginary number but also used throughout MFEM as variable name.
Reproducible by using
```
#include "complex.h"
#include "mfem.hpp"
```

Again, the opposite order does work fine.  This comes up when using LAPACKE, as it uses ```complex.h```

**Comment by tzanio** [comment]
I proposed a fix for the `HYPRE_PARCSR` conflict in #266.

The issue with the `I` macro is more complicated as this is something that has become widespread in the library...
