### ISSUE TITLE
Speedup calculation of complex-valued linear forms with vector function coefficient

### ISSUE THREAD

**Issue by adam-sim-dev** [mfem/mfem#2266]
Dear developers,

When we calculate the complex-valued linear forms with a complex-valued vector function coefficient, we may have to evaluate the complex-valued vector function two times, and then get its real and imaginary parts, respectively. See  L819-L837 in ex25p.cpp for an example. This may be due to for a `ParSesquilinearForm`, mfem first `FormLinearSystem` for the real part and then for the imaginary part (L1107-L1188 in complex_fem.cpp).

This will not be a problem when calculating the vector function is very cheap. However, for my application, I want to evaluate the complex-valued vector function only once because it's very expensive, which would speed up the calculation of complex-valued linear forms two times.

If there will be some improvements in the future, it will be appreciated.

Best,
Adam

**Comment by mlstowell** [comment]
Hello, @adam-sim-dev,

I understand your concerns I agree that this is an unfortunate limitation of the current implementation. As far as I know we don't have any plans to address this in the near future.

However, it may be possible to extend MFEM and fix this locally. The first step would be to create a suitable complex valued coefficient class. Next create a complex valued `LinearformIntegrator` class which could compute the proper integrals. Finally, create a derived class from `ParComplexLinearForm` which accepts the new integrator class and stores the real and imaginary portions of the local vector in the real and imaginary portions of the `ParComplexLinearForm`.

If we add this to MFEM in the future I expect we would follow this pattern except that we would probably modify `ParComplexLinearForm` rather than creating a derived class. Of course, we would also modify the `ComplexGridFunction` and `SesquilinearForm` as well.

Best wishes,
Mark
