### ISSUE TITLE
Boundary condition problem in ex2

### ISSUE THREAD

**Issue by HFH104864** [mfem/mfem#2289]
dear all 
  I was trying to apply a force to a boundary element using the code from ex2 and I was going to print the forces at each node . I found that  the forces at each node are not what I would expect .  
In the example model of MFEM, however, everything turned out fine.But when I use the grid file in VTK format obtained from GMSH, the node force is abnormal .I'm sure this is a model file problem, but I don't know why .I manually set the element's boundary attributes  that means setting the boundary attribute to 1 where I want to constrain, and setting the boundary attribute to 2 where the load is applied
Below is my VTK file and part of the output node forces (I only applied force on one boundary element, and set the force to 30, and the element type is tetrahedral)

[Desktop.zip](https://github.com/mfem/mfem/files/6584851/Desktop.zip)

And by the way , there is a warning   
MFEM Warning: Non-positive attributes in the domain!
 ... in function: void __cdecl mfem::Mesh::SetAttributes(void)
 ... in file: F:\mfem-master\mesh\mesh.cpp:1208

and I read the other answers, maybe this is the reason why the GMSH generated grid is missing the physical group?

If you can give me some advice I will be appreciated !

**Comment by HFH104864** [comment]
btw There is a weird output : number of finite element unknowns : 558 when running this line of code
 `cout << "Number of finite element unknowns: " << fespace->GetTrueVSize()`

**Comment by tzanio** [comment]
Hi @HFH104864,

As documented in other issues, the GMsh element and boundary attributes should be positive, i.e. start from 1 not 0. See for example https://github.com/mfem/mfem/issues/2259.

Hope this helps,
Tzanio

**Comment by HFH104864** [comment]
Thank you for your response , and I still have a qustion ;
At the beginning, when MFEM reads the GSSH grid, the GSSH elements and boundary properties are indeed negative, but I have written a loop in my code as follows:
`    for (int i = 0; i < mesh->GetNE(); i++)   
    {
        mesh->SetAttribute(i, 1);   
    }
    mesh->SetAttributes();`

` for (int i = 0; i < mesh->GetNBE(); i++)
        mesh->SetBdrAttribute(i, 3);`

With this code I can set the element property to 1 and the boundary property to 3, and I'm wondering if that works;
If it does ,  why do I get an abnormal node force, as I said above .

Thank you again!

**Comment by mlstowell** [comment]
Hello, @HFH104864,

First, one of your comments mentioned "weird" output of 558 degrees of freedom. Your mesh contains 186 vertices. In example 2 each vertex is assigned three degrees of freedom (since the mesh is three dimensional) describing the possible displacements of each vertex. Consequently the total number of degrees of freedom is 3*186 = 558.

You also mentioned "abnormal" vertex forces. Perhaps you expected the non-zero values in the attached image to be equal to 30 because this is the magnitude of your applied force. The load vector in a finite element linear system contains integrals of the applied source multiplied by each basis function. This makes the load vector values difficult to predict unless you have very simple element shapes over which to integrate.

If you can provide a more detailed description of any difficulties you're running into I'd be happy to help.

Best wishes,
Mark

**Comment by HFH104864** [comment]
Dear Mark
  well , Now I know about what that number 558 means . However ,to my second problem , I wrote two VTK files for testing, based on the format of the MFEM example . The only difference between these two files is that the coordinates of the points are different. That is, the coordinates ( X,Y,Z) of the points in one file are integer, while the coordinates in the other file are double . As the file I gave you shows.

[test.zip](https://github.com/mfem/mfem/files/6602192/test.zip)

  However, when I import each of them into ex2 to run,  acrroding to this line of code `b->Print();`  I found I get different node forces, even though I apply the same force.
  In my opinion, the result of node force obtained in Test2 file, the file with integer point coordinates, is correct.But I don't know why the other file got the wrong node force. The output of the two files is in the ZIP file above.

Sorry to bother you again!
Best wish

**Comment by mlstowell** [comment]
Hello, @HFH104864,

It's no bother. We're happy to help.

One source of confusion might be the use of the word "force". Technically in continuum problems we are not applying a force we are applying a force per unit volume, for a body force, or a force per unit area, for a surface force. You are applying the same force per unit area in each case but the areas are different so the total force being applied is also different.

For example in the first case your force is applied to a unit square so the four nodal forces must sum to 30*1 = 4*7.5 as you might expect. In the second case the area is close to 1.2^2 so the four nodal forces must sum to nearly 30*1.2*1.2=43.2=4*10.8.

The reason the second case doesn't work out to precisely 43.2 is that your area is larger than 1.2*1.2 because you seem to have a typo in your mesh file. You probably meant to have a x-cordinate of 2.4 on your 9th node but it's written as 2.2.

The important thing to remember is that in the finite element method we don't work with the PDE itself but rather with integrals of the PDE multiplied by the basis functions. This is called a "weak form" of the PDE, see [Weak Formulations](https://mfem.org/fem_weak_form/), for a little more detail on this.

Best wishes,
Mark

**Comment by HFH104864** [comment]
@mlstowell
Dear Mark
Thank you for your guidance , now I know how the nodal forces are calculated, right .  And what should I do if I want to apply a fixed amount of force on a node.
Best wishes.

**Comment by bslazarov** [comment]
Hi HFH104864,

If you need  fixed force per node you will need to calculate mesh dependent
coefficient, i.e., you will have to account for the different lengths
between the nodes in the mesh. This could be tricky. I wonder why would you
need fixed force per node. Usually the external input/loads are applied on
sides/planes/surfaces. If you give us more details about your intended use
we might be able to provide you with better tips on how to model your
problem with MFEM.

Best regards, Boyan

**Comment by HFH104864** [comment]
Dear Boyan

To be honest, I am developing a finite element analysis software by my own .Many of the functions of this software are incomplete, especially in the boundary conditions section. so it has not yet implemented the function of applying force on a surface like other mature finite element analysis software . 

Therefore, for applying the boundary conditions, I use an interactive approach, which is to select the boundary elements that I want to fix and apply the load, and set different boundary properties to them, as in ex2.

If this method is difficult, I may try to apply force to a surface, but as a novice, I expect this to be difficult

Best wishes.
