### ISSUE TITLE
Example 2 Manipulation

### ISSUE THREAD

**Issue by jhoy97** [mfem/mfem#2341]
Hi,

I am trying to adapt the code of example 2 to find the maximum deflection of this single material plate with a hole.  Is there a way to change `ex2.cpp` so that it can solve the problem with only one material?  

Also can the boundary attributes be changed so that it is not fixed to the left but instead two roller boundaries are attached to the left side and bottom of the plate?  Any help would be appreciated. 

Thanks

![plate](https://user-images.githubusercontent.com/78260282/122770949-ddee1c00-d29d-11eb-89d0-28e7d3da1a56.jpg)

**Comment by tzanio** [comment]
This is all doable, but it could be a bit it may require a bit of work to impose the roller BCs (if I understand correctly, e.g. the one on the bottom sets the y-displacements only to zero.

**Comment by jhoy97** [comment]
Ok, are there any other examples that I could base the code off of?  I am unsure where to begin, assume 6. of `ex2.cpp` needs modified for the BCs:
   `Array<int> ess_tdof_list, ess_bdr(mesh->bdr_attributes.Max());`
   `ess_bdr = 0;`
   `ess_bdr[0] = 1;`
   `fespace->GetEssentialTrueDofs(ess_bdr, ess_tdof_list);`

And to change the material conditions 7. of `ex2.cpp` would need modified(?):
   `VectorArrayCoefficient f(dim);`
  ` for (int i = 0; i < dim-1; i++)`
   `{`
     ` f.Set(i, new ConstantCoefficient(0.0));`
  ` }`
  ` {`
     ` Vector pull_force(mesh->bdr_attributes.Max());`
     ` pull_force = 0.0;`
     ` pull_force(1) = -25.0;`
     ` f.Set(dim-1, new PWConstCoefficient(pull_force));`
  ` }`

   `LinearForm *b = new LinearForm(fespace);`
   `b->AddBoundaryIntegrator(new VectorBoundaryLFIntegrator(f));`
   `cout << "r.h.s. ... " << flush;`
  ` b->Assemble();`

Thank you for the quick response!

**Comment by zahurullah123** [comment]
@tzanio we are trying to solve this example: 
![image](https://user-images.githubusercontent.com/72550338/123065199-df872380-d406-11eb-930c-6d64b60a6106.png)

Here we are solving only a quarter of the plate due to symmetry and will apply symmetry boundary conditions on the left and the bottom sides. On the left side, only the x-boundary condition is set to zero and on the bottom side, only the y-boundary condition is set to zero. We can only apply pressure on the right-hand side, which is not a problem and is similar to the beam problem. 

Do you have any suggestion on how to proceed with this issue or can you point to another similar problem. 

Many Thanks 
Zahur

**Comment by tzanio** [comment]
Sorry for the delay guys, I'll try to respond this weekend. -Tzanio

**Comment by zahurullah123** [comment]
@tzanio  many thanks. In addition, how can we post-process stress/strain (gradient of displacements) in addition to the displacement?

**Comment by jhoy97** [comment]
@tzanio did you get a chance to look at the problem?

**Comment by tzanio** [comment]
Apologies @zahurullah123 and @jhoy97, this felt through the cracks around the `mfem-4.3` release.

To impose boundary conditions on only the `x`- or `y`-component you can use the optional 3rd argument of `GetEssentialTrueDofs`:

https://github.com/mfem/mfem/blob/v4.3/fem/fespace.hpp#L758-L764

For the stress computation, see #10 and #109.

Hope this helps,
Tzanio
