### ISSUE TITLE
HYPRE API break

### ISSUE THREAD

**Issue by wcdawn** [mfem/mfem#2346]
It looks like some new HYPRE features modify the API.
The first compiling error I encountered was with `hypre_CSRMatrixAdd` which has a new function signature.

The API change in the HYPRE repo is [here](https://github.com/hypre-space/hypre/commit/8c9f41a4d021cca72e06a0beced71dd3261e31e3).

I'll start a PR for this but I'm not sure how big this problem is yet.

**Comment by v-dobrev** [comment]
Yes, I also see new methods in hypre v2.22.0: `hypre_CSRMatrixSetConstantValues` and `hypre_ParCSRMatrixSetConstantValues` which make the methods with the same names we have in `mfem::internal` unnecessary and create errors because of ambiguous calls.

We'll need a new PR to add support for the new hypre v2.22.0.

**Comment by tzanio** [comment]
Thanks for helping with this @wcdawn!

I'll close this issue in favor of discussion in #2348.
