### ISSUE TITLE
Example 12 (Test cases for EVSL)

### ISSUE THREAD

**Issue by liruipeng** [mfem/mfem#242]
Hi, MFEM developers,

We are looking for test cases of generalized eigenvalue problem for our eigensolver package, EVSL. I came across example 12 in mfem that is Linear Elasticity Eigenproblem. Mfem uses LOBPCG to compute a few smallest eigenvalues. Will it be interesting to compute much more eigenvalues inside the spectrum, since our methods are designed for computing interior eigenvalues more efficiently.

Thanks

-Ruipeng

**Comment by v-dobrev** [comment]
@mlstowell, @Dan2997925,

Do you know of any application(s) where the interior of the spectrum (in generalized eigenvalue problems) is of interest?

See Ruipeng's question above - I think they are interested in finding more applications and test cases for their package, EVSL.

Thanks!

**Comment by Dan2997925** [comment]
Eigenvalue problems of the form <curl W, curl W> x = omega^2 <v^2 W, W> x are very important in electromagnetics, e.g. resonant cavities. The "W's" above should be understood as Nedelec or H(curl) basis functions. The "v" is the index of refraction of the material, "omega" is the resonant frequency. The eigenvector "x" is the basis function expansion of the electric field in the cavity. The boundary condition is simply the Dirichlet BC on the whole boundary.

This problem is challenging for most eigensolvers because <curl W, curl W> has a large null space and nobody cares about these solutions, we care only about the eigenvalues away from zero.

For simple shapes e.g. rectangular bricks, cylinders, spheres, exact analytical solutions exist for the eigenfrequencies and eigenmodes, hence these are good test problems.

**Comment by liruipeng** [comment]
Thank you for your reply. This is definitely a problem we want to test

**Comment by mlstowell** [comment]
I agree with Dan2997925 but I would add one other interesting test problem which I think also has an exact solution.  Specifically, a cylindrical pipe which is used to model a coaxial transmission line.

This is interesting because the nontrivial topology of the mesh adds at least one mode to the null space which is not the gradient of a scalar function whereas all of the other modes in the null space are gradients of scalars.

**Comment by liruipeng** [comment]
Hi, Dan,

Thank you for your reply! I checked example 13p, which is the Maxwell Eigenproblem. The pencil (A,M) has many zero eigenvalues that are not of the interest. But we only care those that are away from zero. This is definitely a very challenging interior eigenvalue problem for (algebraic) eigensolvers which only take A and M as input, since one either has to compute a lot of zero eigenvalues before getting the wanted part of spectrum, or to use some shift-and-invert schemes which involve solving indefinite linear systems. In this scenario, our polynomial filtering algorithm can handle this problem better than the standard methods.

However, if we have more information than matrices A and M, there exists more efficient solvers. Like in MFEM,  the AME solver is used since the discretized gradient is available. AME calls LOBPCG to compute 5 eigenpairs in the divergence-free subspace, so that the zero eigenvalues will not appear at all. For sure, for Maxwell problems, AME solver will be much more efficient than our methods, but on the other hand, it is not a pure algebraic solver. 

So, my questions are:

1. Is it any meaningful that I ``pretend'' that I don't have the additional information other than A and M, or in some cases, this gradient space is not available or hard to get. Is there a need for a pure algebraic matrix eigensolver?

2. Even assume that we have the gradient space, is it useful to compute a significant part of the spectrum (e.g., thousands of eigenvalues and vectors) ?

Thanks

Best

-Ruipeng

**Comment by mlstowell** [comment]
Hello, Ruipeng,

I have been struggling with a modified form of the curl-curl operator mentioned by Dan that arises in Bloch wave problems.  This operator can be written as <(curl+i k x) W, (curl+i k x) W> y = omega^2 <v^2 W, W> y, where 'i' is the imaginary number, 'k' is a constant vector in R^3, and 'x' indicates a vector cross product.

This operator is Hermitian and contains a large null space like the curl-curl operator.  However, on unstructured meshes the null space cannot be filtered out using a modified gradient operator so the method used in AME will not work.  A purely algebraic eigensolver for this operator which efficiently computes interior eigenvalues would be very useful.

Regarding the number of eigenvalues, we would typically require dozens not thousands of eigenvalues.

Regards,
Mark

**Comment by liruipeng** [comment]
Dear Mark,

Thanks for your reply.

1. We currently don't support complex Hermitian matrices but adding this should be straightforward

2. Is there some example code available in MFEM for testing the problem you described?

Thanks

Regards,

-Ruipeng

**Comment by mlstowell** [comment]
Hello, Ruipeng,

MFEM does not support complex matrices either so I actually constructs it as a 2x2 block structured linear system.  The code to generate these matrices is not yet publicly available.  I was able to download EVSL and build its test codes.  I'm in the process of modifying my test code to output its matrices in the required format so that I can test the efficacy of the EVSL solvers on our linear systems using your test drivers.

Looking ahead I have two questions regarding EVSL.
1. I noticed on the EVSL web site that MPI parallelism is in the works.  Roughly when might we expect to see an MPI release?
2. I apologize if this is covered in the documentation which I haven't had a chance to look into yet.  I noticed that EVSL offers matrix-free functionality for the required matvecs but no mention is made regarding the direct solve.  Can this solve be done with a user supplied solver?

Thanks,
Mark

**Comment by liruipeng** [comment]
Hi, Mark,

1. We are developing the parallel version, pEVSL. But now only a (small) subset of EVSL has been done. It can be found at [.](https://github.com/liruipeng/pEVSL ). I apologize it is still not in a very nice shape as EVSL. We will continuously push more functionalities of EVSL into it. 

2. EVSL can also take user-provided direct solvers (is it for the mass matrix?). In EVSL/EXTERNAL we wrote interfaces to SuiteSparse[Cxsparse, Cholmod, UMFpack] and Pardiso. (In pEVSL, we did MUMPS and cluster Pardiso). If users want to provide their solvers, just follow the implementation of either of the above. Make sure to have the same function prototype.

BTW, in the development of pEVSL, we have been struggling for a while with distributed direct solvers. Neither MUMPS nor Pardiso is satisfactory at this point. The solve phase is too slow compared with the shared memory solvers. Any comments or suggestions.. 
 
Thanks

-Ruipeng

**Comment by mlstowell** [comment]
Hi, Ruipeng,

I was able to run a small example (1536x1536) from our Bloch wave problem using your MMPLanR driver this morning.  This was too small of a problem to compare solve times with our usual method but  EVSL did produce reasonable eigenvalues.  One interesting thing was that EVSL found one additional eigenmode that our HypreAME implementation did not find.  This mode corresponds to an eigenvalue which is lower than those found by our usual method but still well separated from zero. Unfortunately I cannot view the mode to see what it looks like.  I am curious but I may not have time right now to pursue this further.

Recently we have mostly been working with LOBPCG and related eigensolvers which do not require a direct solve.  In the past we relied heavily on PARPACK and SuperLU_dist.  This combination worked reasonably well although we ran into trouble with memory usage in SuperLU and PARPACK tended to be very sensitive to the shift parameter and sometimes failed to converge.  Colleagues have recommended MUMPs rather than SuperLU but I haven't had much experience with this.

Regarding serial vs. parallel performance, we have always required distributed memory parallelism so I don't think I've ever tried serial direct solvers.  Consequently, I cannot offer any useful suggestions.

Best wishes,
Mark

**Comment by liruipeng** [comment]
Hi, Mark,

Thanks for trying EVSL. I am very curious about the additional eigenvalue found in this case. Is it a spurious eigenvalue? Also, btw, you may try MMPLanN  first which is the driver for Non-restart Lanczos. This one is usually considered more robust compare to the thick restart one MMPLanR

Thanks

Regards,

Ruipeng
