### ISSUE TITLE
IMEX integration

### ISSUE THREAD

**Issue by bensworth** [mfem/mfem#2432]
Hi MFEM team, I implemented a handful of IMEX integration schemes, including RK methods from Ascher et al. and Kennedy and Carpenter, and IMEX-BDF methods, including some new ones with adjustable stability regions. Is this something you would like added to master? I would need some input on your side on code structure/design; there are a number of subtleties that do not line up with current MFEM structure. Most notably, the ImplicitSolve function for BDF-type methods is different than the stage approach to RK methods, and there are a few other similar issues regarding various mult/solve functions.

**Comment by v-dobrev** [comment]
Hi Ben, I personally think these could be useful to add to MFEM.

Do you know if some of these methods are available in SUNDIALS or PETSc?

**Comment by bensworth** [comment]
Good question:
- I believe the IMEX-DIRK methods, or similar methods if not exactly the same coefficients, are available in Petsc and Sundials.
- Took a quick look at the documentation for Petsc and sundials and I don't see IMEX-BDF. This was a bit surprising; perhaps @cjvogl or somebody that works with sundials can clarify? Although there are some downsides to BDF schemes, hard to argue w/ one solve per time step. The BDF schemes are the ones where (to me) it seemed like the functions needed to differ a bit.
- One downside of BDF schemes is shrinking stability for higher order. Working on a paper where one of the contributions is a modified IMEX-BDF with a parameter that allows for larger stability with a larger leading accuracy constant, or smaller stability with a smaller accuracy constant. These are definitely not in petsc or sundials as we have not submitted the paper yet.
- Last, I also implemented some new IMEX fully implicit RK methods, which use an explicit multistep method with fully implicit RK. So far, these appear to be quite good schemes, but they require having good solvers for fully implicit RK methods. This is also available in MFEM, from our recent papers (e.g., https://arxiv.org/abs/2101.01776), but the solver infrastructure is much more complicated. Getting the IRK sovlers into production quality would be a heavier lift I think.

**Comment by cjvogl** [comment]
> I believe the IMEX-DIRK methods, or similar methods if not exactly the same coefficients, are available in Petsc and Sundials.
While I do not know the specific methods under consideration, I will note that SUNDIALS does support user-defined Butcher tableaus, so any IMEX-DIRK method should be supported.  That said, I dont believe the particular SUNDIALS functions that support user-defined tableaus have been wrapped in MFEM yet... but it shouldn't be a substantial amount of work to do so (famous last words).

> Took a quick look at the documentation for Petsc and sundials and I don't see IMEX-BDF. This was a bit surprising; perhaps @cjvogl or somebody that works with sundials can clarify?
I may rope in @gardner48 to verify my response, but I don't believe SUNDIALS has IMEX-BDF: the IMEX capability resides within the ARKODE package (i.e., IMEX-ARK) while the BDF capability resides in the CVODE, CVODES, and IDA packages.

**Comment by cjvogl** [comment]
As far as whether there is interest in adding native MFEM IMEX integrators to master, I don't know that I can comment.  I was a bit surprised in interacting with @gardner48 to use the ARKODE MFEM wrapper to have SUNDIALS capability in the fusion LDRD that we were the first application to really test the ARKODE wrappers; however, I do have a good feeling as to whether that is more because people prefer to use home-grown integrator solutions or because there isn't much a demand for RK methods outside of the native MFEM solvers (e.g. IMEX-ARK).

**Comment by gardner48** [comment]
> I may rope in @gardner48 to verify my response, but I don't believe SUNDIALS has IMEX-BDF: the IMEX capability resides within the ARKODE package (i.e., IMEX-ARK) while the BDF capability resides in the CVODE, CVODES, and IDA packages.

That's correct, we don't have IMEX-BDF methods in SUNDIALS at this time only IMEX-RK methods (the next major release will include IMEX multirate methods). IMEX-BDF methods are something I would like to add but there has not been an application interest in these so I've not pushed it forward.

**Comment by bensworth** [comment]
Sounds good/makes sense. My implementation could probably be ported to sundials, but I haven't worked inside of sundials at all. For MFEM, it sounds like IMEX-BDF could be useful and FWIW I will be using it in a project w/ MFEM. The caveat with IMEX-BDF higher than first order is you need IMEX-RK to get HO initial solution values, so if we add IMEX-BDF to MFEM we need to add RK support as well. I can collect the BDF and RK (not IRK) code in a branch to start

**Comment by bensworth** [comment]
See https://github.com/mfem/mfem/pull/2474

**Comment by tangqi** [comment]
@bensworth Ben, I guess it is possible to extract a stand-alone high-order BDF integrator through this. Do you think if it is easy to support variable time steps and a proper starting (as you mentioned)? I am looking for a BDF integrator inside mfem.

**Comment by gardner48** [comment]
@tangqi You might also want to consider the MFEM interface to CVODE which provides adaptive step and order (1 to 5) BDF methods.

**Comment by tangqi** [comment]
@gardner48 Thanks a lot for the suggestion. I have my solver working for SNES + JFNK + fieldsplit + DIRK. I am considering to switch to BDF due to the system being not compatible to DIRK any more. 

Ideally, I want something working and simple for the implicit time stepping so that I can focus on the nonlinear solver and preconditioner part. I know CVODE's bdf is probably better than PETSc's. 

Do you think adding a custom preconditioner would be easy through the CVODE route? I am using either fieldsplit or my own version of fieldsplit through pcshell on PETSc atm. 

Qi

**Comment by gardner48** [comment]
Could you clarify what you mean by the system is not compatible to DIRK any more?

As far as the preconditioner interfacing goes, some small modifications to the MFEM + CVODE interface would be needed. You'd need to add a new method to the `TimeDependentOperator` class to solve the preconditioning system `P r = z`, add a wrapper function to the class method in the CVODE interface, and add a "Set" function call to attach the wrapper to CVODE but that should be it.

It would also be possible to use your SNES + JFNK + fieldsplit setup under CVODE but would require some more work to setup than just attaching a preconditioner.

**Comment by tangqi** [comment]
Thanks again for getting back to me. Yes, that's what I would guess. So I hesitated to try CVODE or even using TSSolve. Right now I am just using SNES. 

Previously, I am solving U' = f(t,U), so DIRK is perfect. Currently, my system becomes something like 
g(u1)*u2' + h(u3)' = f(t, U)
in certain components. I thought in general DIRK can be only applied to method-of-line to achieve high-order in time. (maybe I am wrong?)

One way is to define a new variable y as a function of u1, u2, u3, so that it becomes
y' = F(t, U)
But this practical system is not really designed for this. F may have 15 different nonlinear terms instead of 5. 

So I am hoping to use bdf to solve g(u1)*u2' + h(u3)' = f(t, U) directly.

**Comment by tangqi** [comment]
Hi @tzanio If I just stick to fully implicit second-order time stepping (with varying time steps and AMR), is there some option you recommended in mfem? Do we have something simple like BDF2? Or maybe generalized alpha would be a good option?

The application is still MHD but a much more complicated version.

**Comment by gardner48** [comment]
I see, your system is probably better expressed as a DAE `F(t, u, u') = 0` rather than an ODE `u' = f(t, u)`. Since you're using AMR, DIRK methods would be a better fit than the multistep methods in CVODE. I don't know much about the MFEM interface to PETSc but `TSSolve` should be able to handle this.

**Comment by tangqi** [comment]
hmm, do you think DIRK can solve systems like F(t, u, u') = 0? Somehow, I thought it has to be u'=f(t, u), otherwise you may not have error cancellation to get high-order in time. 

I am sure TSSolve can work for me, but I am not sure what would be a good single step option that can give me at least a second order accuracy. (We need some dissipation on the high K modes. DIRK was perfect)

**Comment by v-dobrev** [comment]
Hi @tangqi, it may be still possible to use DIRK methods if for your system of the form `F(u, u', t) = G(u, t)` you implement (in your `ImplicitSolve` method) a solver for the algebraic equation for `k`: `F(u + dt k, k, t) = G(u + dt k, t)`. Or is it the solution of this system that you are trying to avoid?

**Comment by bensworth** [comment]
Hi Qi, short answer:
- DIRK can solve DAEs. If the constraint is invertible, e.g., \Delta w = f,
you can get high order accuracy. We have some code that does this. If the
constraint is not invertible, e.g., incompressible \div p = 0, then you
need something different.
- For fully implicit, Sundials is probably good. If you want in MFEM for
one reason or another, I have BDF, and can add starter and adaptive time
stepping w/o much work.
- If we want to go IMEX at some point, we can use my code. I do not think
Sundials or PETSc support this right now. So far, BDF IMEX schemes also
seem quite robust. When I get back, I will be working on a paper on
variations in IMEX-BDF and we can talk more.

**Comment by tangqi** [comment]
Thanks a lot, Ben. I will have a chat with you when you are back. These all sounds very promising. Meanwhile, I will ping Veseline and Tzanio privately. Sorry, the discussions become a bit off from your original question. 

Thanks to all for the good suggestions. Appreciate that.
