### ISSUE TITLE
Repeated use of MG solver from ex26p

### ISSUE THREAD

**Issue by appelo** [mfem/mfem#2453]
I would like to use the solver in ex26p for a time discretization for the wave equation. Precisely if M is the mass matrix and L is the matrix for the Laplacian I would like to use:    

M * (UP - 2*U + UM)  = 0.5 * dt^2 * L * (UP+UM)
g = 0.5 * dt^2

Or equivalently, I want to **repeatedly solve** for UP in:

(M-g*L) * UP =  2 * M * U - (M-g * L) * UM 

while enforcing homogenous Dirichlet (or Neumann) boundary conditions. 

I have modified  `ConstructBilinearForm` from 
```
form->AddDomainIntegrator(new DiffusionIntegrator(one));
```
to 
```
form->AddDomainIntegrator(new MassIntegrator(one));
form->AddDomainIntegrator(new DiffusionIntegrator(gccof));
```
and this appears to work well.  

I am a bit confused how and when to use `M->FormFineLinearSystem` My reading of the documentation lead me to try:

```
for(int it = 1; it < 11; it++){
       MASS.Mult(U,TMP);
       A->Mult(UM,B);
       B.Neg();
       B.Add(2.0,TMP);
       M->FormFineLinearSystem(x, *b, A, UP, B);
       cg.Mult(B, UP);
       UM.Set(1.0,U);
       U.Set(1.0,UP);
       M->RecoverFineFEMSolution(UP, *b, x); 
       // vis. stuff...
}
```
Where this loop has been preceded by the call `M->FormFineLinearSystem(x, *b, A, UP, B);` and `U` and `UM` were then initiated as `Vector U(UP), UM(UP);`
 
Also, `MASS` is constructed according to: 
```
ParBilinearForm* mass = new ParBilinearForm(&fespaces->GetFinestFESpace());
mass->AddDomainIntegrator(new MassIntegrator(one));
mass->Assemble();
mass->Finalize();
HypreParMatrix MASS;
mass->FormSystemMatrix(ess_bdr,MASS);
```

This however does not appear to work and results in segmentation fault. Removing the  `M->FormFineLinearSystem(x, *b, A, UP, B);` makes the code run without halting but the results are corrupted (possible due to not handling boundary conditions correctly). 

Any advice, corrections or insight would be greatly appreciated.

**Comment by drzisga** [comment]
I haven't looked very deep into this issue yet, but it could have something to do with the size of the vectors. The vectors used for solving usually have a different size than the vectors representing a gridfunction.

Have you tried building your code in debug mode? This enables many vector size compatibility checks which help to catch such kind of errors.

Besides this I also want to warn you: The multigrid preconditioner as you are planning to use it is a bad preconditioner for the wave equation with larger wave numbers. Please refer to, e.g., [Why it is Difficult to Solve Helmholtz Problems
with Classical Iterative Methods ](https://www.tu-chemnitz.de/mathematik/numa/PubArchive/ernstGander2012.pdf) by Ernst and Gander and their other work.

**Comment by psocratis** [comment]
Hi @appelo, 

What @drzisga is saying is true about solving Helmholtz, but from what understand from the above you are interested in the time-dependent formulation which results in an SPD system, hence MG should be working fine.  

If you haven't found the issue yet, feel free to post a simple sample code that segfaults so we can check it out. 
In addition, you might find example 23 helpful as well. 

Thanks,

Socratis

**Comment by appelo** [comment]
@drzisga @psocratis thanks for the help and the suggestions. The debug mode returns `pure virtual method called` followed by `terminate called without an active exception`. I'll take a look at example 23 to see if it makes things clearer.   

A minimal example that reproduces the behavior is below, it is exactly `ex26p.cpp` except for the lines added within //NEW comments. 

```
   OperatorPtr A;
   Vector X, B;
   M->FormFineLinearSystem(x, *b, A, X, B);

   // 11. Solve the linear system A X = B.
   CGSolver cg(MPI_COMM_WORLD);
   cg.SetRelTol(1e-12);
   cg.SetMaxIter(2000);
   cg.SetPrintLevel(1);
   cg.SetOperator(*A);
   cg.SetPreconditioner(*M);
   cg.Mult(B, X);

       // NEW
   M->FormFineLinearSystem(x, *b, A, X, B);
   cg.Mult(B, X);
       // NEW
   
   // 12. Recover the parallel grid function corresponding to X. This is the
   //     local finite element solution on each processor.
   M->RecoverFineFEMSolution(X, *b, x);
```

Continuing the aside about MG and Helmholtz, the purpose of the exercise is actually to solve the time harmonic (Helmholtz) equation by instead finding initial data to the time domain wave equation by a filtering approach we call The [WaveHoltz](https://arxiv.org/pdf/1910.10148.pdf) method (see, SISC 2020, Vol. 42, No. 4 : pp. A1950-A1983). Sorry for the shameless plug, ... but It turns out that the matrix we must invert to get the Helmholtz solution using our method is SPD and, in addition, it comes from a bounded operator so the condition number does not depend on the mesh size. 

We have used it together with the MFEM SIPDG bilinear forms for both the standard Laplacian and the elastic Laplacian and it works pretty well with explicit solvers. As I am mainly interested in high order discretization we think there is a chance that implicit discretization of the time derivative may be faster (due to the unfavorable CFL number of high order element based methods). For low order methods (p=1) AMG + CG used together with an implicit time stepper is reasonable but once the order is higher the "break even" between explicit and implicit tilts in the favor of explicit. Now, as far as I could tell the impressive high order DG MG solvers by @pazner @tzanio has not made it into the release version of MFEM yet so in the meantime I thought I should try the MG solver in ex26p which also appears to work very well.

**Comment by drzisga** [comment]
Thanks for the minimal example @appelo. I could figure out that the issue is related to the operator pointer  `A` which is changed by the call of `FormFineLinearSystem`. The CG solver does not know about the updated operator and still uses the pointer to the previous operator which doesn't exist at this point.

Usually, you would need to call `cg.SetOperator(*A)` after `FormFineLinearSystem`, but this will call `SetOperator` of the Multigrid operator which is not supported. One could add a new method `SetOperatorAndPreconditioner` to `IterativeSolver` with which the user can update both the operator and preconditioner at the same time. Another possibility would be to remove the `MFEM_ABORT` from `Multigrid::SetOperator`. In this case, the user must make sure that the preconditioner is compatible with the operator `A`.

An easy but maybe not the most efficient workaround would be to create a new CGSolver object after each call of `FormFineLinearSystem` and pass the updated `A` as the argument to `SetOperator`.

**Comment by appelo** [comment]
@drzisga Thanks for clarifying this and thanks for the suggestions. I'll settle for the easy method for now. 

One more question. As the right hand side in the update 
`(M-g*L) * UP = 2 * M * U - (M-g * L) * UM` is a `TDOF dual vector` but the  `FormFineLinearSystem` requires a `ParLinearForm` what is the preferred way to go from a `TDOF dual vector` to a `ParLinearForm`?

**Comment by drzisga** [comment]
@appelo according to https://mfem.org/pri-dual-vec/ you may use `RecoverFineFEMSolution` to go from a linalg tdof dual vector to a finite element dof dual vector. `ParLinearForm` is also just a child class of `Vector` and you may pass a `Vector` to ` FormFineLinearSystem` instead of a `ParLinearForm`. You just need to be careful about the dimension of these vectors.

**Comment by pazner** [comment]
Hi, @appelo!

I think the easiest solution is as follows. You can modify `DiffusionMultigrid` so that `SetOperator` is a no-op, and then call `cg.SetOperator` after you call `FormFineLinearSystem`. For example, this modification to ex26p works for me:

```diff
diff --git a/examples/ex26p.cpp b/examples/ex26p.cpp
index 58189dbcc..caeb76abf 100644
--- a/examples/ex26p.cpp
+++ b/examples/ex26p.cpp
@@ -58,6 +58,8 @@ public:
       }
    }
 
+   virtual void SetOperator(const Operator &op) override { }
+
    virtual ~DiffusionMultigrid()
    {
       delete amg;
@@ -270,6 +272,12 @@ int main(int argc, char *argv[])
    cg.SetPreconditioner(*M);
    cg.Mult(B, X);
 
+   // NEW
+   M->FormFineLinearSystem(x, *b, A, X, B);
+   cg.SetOperator(*A);
+   cg.Mult(B, X);
+   // NEW
+
    // 12. Recover the parallel grid function corresponding to X. This is the
    //     local finite element solution on each processor.
    M->RecoverFineFEMSolution(X, *b, x);
```

Since (if I understand correctly) your system matrix remains unchanged between iterations, it may also be possible to avoid calling `FormFineLinearSystem` repeatedly. It just depends on how you compute the RHS vector (in particular w.r.t. the BCs). If possible, this will be the simpler/preferred way of implementing this, and will also help with the TDOF vector/ParLinearForm confusion.

**Comment by pazner** [comment]
@appelo, feel free to re-open this issue if you would like to continue discussion/encounter any further issues.

**Comment by appelo** [comment]
@pazner I plan to, I think I got the main idea from your answers but I have not had time yet to do a proper implementation. I will post an update once some proposal deadlines has passed ;-)
