### ISSUE TITLE
Different meshes lead to segmentation fault

### ISSUE THREAD

**Issue by michi002** [mfem/mfem#2485]
I intend to use two different refinements of a mesh and to have H1 elements on one mesh and L2 elements on the other.
I tried to to a mixed bilinear form with a mass integrator to implement a projection. This oddly leads to an segmentation fault if the mesh of the trial space is refined (in the code u_space) but not if the test space mesh (p_space) is refined.
I cannot yet say if the resulting matrix is correct for the latter case.
I added a minimal example below:

```c++
#include "mfem.hpp"

#include <iostream>

int  main(){
    const char *mesh_file = "/home/michael/Schreibtisch/git_repos/project_mathe_master/trilinos_rework/meshes/rectangle/rectangle_netgen.gmsh2"; 
    mfem::Mesh *mesh_u = new mfem::Mesh(mesh_file, 1, 1);
    mesh_u->UniformRefinement(); //without that or with mesh_p->UniformRefinement() no error occurs
    mfem::Mesh *mesh_p = new mfem::Mesh(mesh_file, 1, 1);
    //set up fem space
    const int order = 1;
    int dim = mesh_u->Dimension();
    //set up U_h
    mfem::FiniteElementCollection *u_coll(new mfem::H1_FECollection(order, dim));
    mfem::FiniteElementSpace *u_space = new mfem::FiniteElementSpace(mesh_u, u_coll);
    //set up P_h
    mfem::FiniteElementCollection *p_coll(new mfem::L2_FECollection(order, dim));
    mfem::FiniteElementSpace *p_space = new mfem::FiniteElementSpace(mesh_p, p_coll);

    mfem::MixedBilinearForm M_PU_form(p_space, u_space);
    M_PU_form.AddDomainIntegrator(new mfem::MixedScalarMassIntegrator);
    M_PU_form.Assemble();
    mfem::SparseMatrix M_PU = mfem::SparseMatrix(M_PU_form.SpMat());
    M_PU.Finalize();

    return 0;
}
```

**Comment by v-dobrev** [comment]
The class `MixedBilinearForm` expects that "Both trial and test spaces should be defined on the same mesh.", see https://github.com/mfem/mfem/blob/6206c775cca216706276a92e33c4a9d772c4b1bd/fem/bilinearform.hpp#L626-L641

Instead of defining a separate refined mesh, it may be possible to use what we call "Refined" elements, see class `RefinedLinearFECollection`: https://github.com/mfem/mfem/blob/6206c775cca216706276a92e33c4a9d772c4b1bd/fem/fe_coll.hpp#L1005-L1006

These elements define their basis functions on a refined reference element. With such elements, one needs to use "refined" quadrature rules. Currently, only a few of the integrators check for "refined" elements, e.g. here: https://github.com/mfem/mfem/blob/6206c775cca216706276a92e33c4a9d772c4b1bd/fem/bilininteg.cpp#L1131-L1134

However, adding such checks in other integrators should be simple.

These "refined" elements are not actively used and tested, so I'm not sure if everything works as expected -- let us know if you encounter any issues.

**Comment by tzanio** [comment]
I will close this issue now, but please feel free to re-open if you still have questions.
