### ISSUE TITLE
MatrixArrayCoefficient::Eval Bug

### ISSUE THREAD

**Issue by Andr00dz** [mfem/mfem#2500]
Hi,

there seems to be a missing initialization of the Matrix `K` when `MatrixArrayCoefficient::Eval(DenseMatrix &K, ElementTransformation &T, const IntegrationPoint &ip)` is called. Comparing Eval with other implementations (below with `IdentityMatrixCoefficient::Eval`), the matrix `K` is always initialized first.

https://github.com/mfem/mfem/blob/12c7976b2ef7ee800efa81370aa3b7f47d32eeda/fem/coefficient.cpp#L431-L441

https://github.com/mfem/mfem/blob/12c7976b2ef7ee800efa81370aa3b7f47d32eeda/fem/coefficient.cpp#L632-L638

**Comment by psocratis** [comment]
Hi @Andr00dz, 

I don't see the need of initializing the matrix in the case of `MatrixArrayCoefficient`. All of its entries are filled at line 438. The `IdentityMatrixCoefficient` is indeed initialized to zero because only its diagonal entries are then set to one. 

Is there a specific example that you noticed an unexpected behavior? 

Thanks, 

Socratis

**Comment by Andr00dz** [comment]
Hi @psocratis,

you are right that `K = 0.0` is not necessary. The missing `K.SetSize(dim);` leads to erros.

**Comment by psocratis** [comment]
Hi @Andr00dz, 

Oh, sorry I missed that.  So we need `K.SetSize(height, width);`  before the loop. Do you want to propose a small PR to fix it? 

Thanks for catching that. 

Socratis

**Comment by Andr00dz** [comment]
Hi @psocratis,

yes, I'll create a PR with the fix.

**Comment by tzanio** [comment]
Discussions continued in https://github.com/mfem/mfem/pull/2501
