### ISSUE TITLE
PrintMatlab might give you the wrong size

### ISSUE THREAD

**Issue by thorvath12** [mfem/mfem#2515]
Hi,

If for some reason, the last row(s) or columns(s) of a matrix are all zero, then the file created by `PrintMatlab` will not be read correctly by Matlab: the resulting matrix will have a smaller size. This can happen, for example, after boundary elimination. I added `out << height << " " << width << " 0.0" << '\n';` to `SparseMatrix::PrintMatlab` and something similar to `Operator::PrintMatlab`. If you think that it would benefit others, I am happy to make the necessary changes for every `PrintMatlab` function and create a pull request with the modifications.

Best,
Tamas

**Comment by pazner** [comment]
Hi @thorvath12, this seems reasonable to me. Note that `SparseMatrix::PrintMatlab` does print the size of the matrix as a comment at the beginning of the file (but `Operator::PrintMatlab` does not), so at least that information is available in the resulting file. As a related point, it might make sense to make `Operator::PrintMatlab` virtual, so that it will call through to appropriate member function defined in the derived classes.
