### ISSUE TITLE
How to get operator for projection from high order elements to low order and inverse.

### ISSUE THREAD

**Issue by chikitkin** [mfem/mfem#2541]
Dear MFEM community, 

I am looking for the simple way to get operator which can project, for example, GridFunc defined in 2nd order Nedelec space to 1st order Nedelec space on the same mesh. Also I need the inverse operation: given GridFunc (or vector of DoF)  for 1st order basis map it to 2nd order basis.

Thank you in advance!

**Comment by mlstowell** [comment]
Hello, @chikitkin,

The inverse operation is more simple because the 1st order space contained within the 2nd order space. This projection can be accomplished in two ways. First you could create a `GridFunctionCoefficient` based on the 1st order field and project this coefficient onto a 2nd order `GridFunction`. The second option is to build a `DiscreteLinearOperator` using an `IdentityInterpolator`. The results should be equivalent but there are different pros and cons for each approach.

The forward operation would involve an averaging of the 2nd order field to find the 1st order field which provides the best match. This can be done by creating a `MixedBilinearForm` and a `BilinearForm` both using the `MassIntegrator`. The `MixedBilearForm` would be a rectangular operator, call it `R`, mapping the 2nd order field, `f2`, to the dual of the 1st order field, `f1`. The `BilinearForm` would be a square operator, call it `M`, build with the 1st order space. You also need a solver, PCG with diagonal scaling usually works well, to solve for the 1st order field.
```
f1 = M^{-1} R f2
```

Best wishes,
Mark

**Comment by chikitkin** [comment]
Thank you, Mark, that's what I need!
