### ISSUE TITLE
Define new NonlinearFormIntegrators

### ISSUE THREAD

**Issue by brightzhang91** [mfem/mfem#2571]
Hi :)
I'm working to produce new NonlinearFormIntegrators for my electromagnetic applications. After reading the existing NonlinearFormIntegrators and the BilinearFormIntegrators,  I'm confused with the following issues when building the `AssembleElementVector()` and `AssembleElementGrad()`. 

1)   What should the  weight factor w be ?  They are generally 

`w = ip.weight / Trans.Weight() ;          w = ip.weight * Trans.Weight() ;   or       w = ip.weight ;  `
Is there any general rule for defining weight factor of new BilinearFormIntegrators?   How does this relate to w = det (J) for square J (J is the transformation Jacobian) or det(JtJ)^(1/2) for others?

2)    The use of CalcPhysCurlShape and CalcCurlShape .

I understand `CalcPhysCurlShape`  gives the "real value" for the curl of a vector field, and `CalcCurlShape` gives the curl of a field/basis mapped to the reference element. 
However the use of them in BilinearFormIntegrators still confuses me. Such as in `VectorConvectionNLFIntegrator` , the grad(u) is calculated with `CalcDShape` in Jacobian , but with `CalcPhysDShape` in residual. 

Thanks !
Bright

**Comment by brightzhang91** [comment]
Here is my implementation for Nonlinear CurlCurl Integrator defined in 3D Hcurl space. I'm not sure if I used the CalcPhysCurlShape, weight factor and maybe other issues correctly. Can anyone help with it?

The residual  ∇×|∇×u|^3 ∇×u    or    (|∇×u|^3 ∇×∅_i u  ,∇×∅_j)
```
void NL_EJIntegrator::AssembleElementVector(const FiniteElement &el,ElementTransformation &Ttr, 
                                                       const Vector &elfun, Vector &elvect)
   {
    int nd = el.GetDof(), dim = el.GetDim(); 
    DenseMatrix curlshape(nd,dim), curlshape_dFt(nd,dim), elmat(nd),curlphyshape(nd,dim); 
    elmat = 0.0;
    double w;
    Vector J(dim);
    elvect.SetSize(nd);
    elvect = 0.0;    

    const IntegrationRule *ir = IntRule;
    if (ir == NULL)
     { int order;
       if (el.Space() == FunctionSpace::Pk)
        { order = 2*el.GetOrder() - 2;}
        else
        { order = 2*el.GetOrder(); }
        ir = &IntRules.Get(el.GetGeomType(), order);
     }
    for (int i = 0; i < ir->GetNPoints(); i++)
     {
       const IntegrationPoint &ip = ir->IntPoint(i);
       Ttr.SetIntPoint(&ip);
       w = ip.weight / Ttr.Weight(); 
       el.CalcCurlShape(ip, curlshape);     
       el.CalcPhysCurlShape(Ttr, curlphyshape);
       MultABt(curlshape, Ttr.Jacobian(), curlshape_dFt); 
       curlphyshape.MultTranspose(elfun, J); // compute the current density J, elfun is the vector values of magnetic field H
       double J_norm = J.Norml2();
       double J_f = pow(J_norm, 3);  
       w *= J_f;     
       AddMult_a_AAt(w, curlshape_dFt, elmat);     
       elmat.AddMult(elfun, elvect);
     }    
   }
```
And the Jacobian   |∇×u|^3 (∇×∅_i   ,∇×∅_j) +  3|∇×u|^2 ((∇×∅_i )*(∇×u)   ,(∇×∅_j )*(∇×u)). 
                                   diagonal term                              off-diagonal term
```
void NL_EJIntegrator::AssembleElementGrad(const FiniteElement &el,ElementTransformation &Ttr, 
                                                     const Vector &elfun, DenseMatrix &elmat)
   {
    int nd = el.GetDof(), dim = el.GetDim(); 
    DenseMatrix curlshape(nd,dim), curlshape_dFt(nd,dim), elmat(nd),curlphyshape(nd,dim); 
    elmat = 0.0;
    double w;
    Vector J(dim);  

    const IntegrationRule *ir = IntRule;
    if (ir == NULL)
     {  int order;
       if (el.Space() == FunctionSpace::Pk)
        { order = 2*el.GetOrder() - 2;}
        else
        { order = 2*el.GetOrder(); }
        ir = &IntRules.Get(el.GetGeomType(), order);
     }
    for (int i = 0; i < ir->GetNPoints(); i++)
     {
       const IntegrationPoint &ip = ir->IntPoint(i);
       Ttr.SetIntPoint(&ip);
       w = ip.weight / Ttr.Weight(); 
       el.CalcCurlShape(ip, curlshape);     
       el.CalcPhysCurlShape(Ttr, curlphyshape);
       MultABt(curlshape, Ttr.Jacobian(), curlshape_dFt); 
       curlphyshape.MultTranspose(elfun, J); // compute the current density J, elfun is the vector values of magnetic field H
       double J_norm = J.Norml2();
       double J_f = pow(J_norm, 3);  
       w *= J_f;    
       // diagonal term of the Jacobian matrix
       AddMult_a_AAt(w, curlshape_dFt, elmat); 
       // off-diagonal term of Jacobian matrix
       curlshape_dFt.Mult(J,curl_dot_test);
       curlshape_dFt.Mult(J,curl_dot_trial);      
       double a = 3*pow(J_norm, 2)*(ip.weight*Trans.Weight());
       AddMult_a_VWt(a, curl_dot_trial, curl_dot_test, elmat); 
     }    
   }
```

**Comment by jandrej** [comment]
I can help with
> However the use of them in BilinearFormIntegrators still confuses me. Such as in VectorConvectionNLFIntegrator , the grad(u) is calculated with CalcDShape in Jacobian , but with CalcPhysDShape in residual.

The reason is simply that operations in the Jacobian might benefit from having the gradient in reference space and thus saving operations. In theory, you can use whichever function you like as long it is consistent with your formulation.

**Comment by brightzhang91** [comment]
> The reason is simply that operations in the Jacobian might benefit from having the gradient in reference space and thus saving operations. In theory, you can use whichever function you like as long it is consistent with your formulation.

 Understood. Thanks jandrej !

**Comment by mlstowell** [comment]
Hello, @brightzhang91, 

You may be interested in some documentation which is still in its earliest form: https://github.com/mfem/web/blob/integration-dev/src/integration.md

More still needs to be added but you may find the section on "Basis Function Evaluation" helpful.

Best wishes,
Mark

**Comment by brightzhang91** [comment]
Thanks very much Mark ! This really helps me to understand the Integrators in MFEM much better. I'll try to rebuild my NonlinearFormIntegrator and look forward to your further updates on this documentation. 

Thanks :)
Bright

**Comment by brightzhang91** [comment]
> Hello, @brightzhang91,
> 
> You may be interested in some documentation which is still in its earliest form: https://github.com/mfem/web/blob/integration-dev/src/integration.md
> 
> More still needs to be added but you may find the section on "Basis Function Evaluation" helpful.
> 
> Best wishes, Mark

Hi Mark
Many thanks for the website with the explanation of how to build a new Integrator in MFEM.  Now I have much better understanding of the philosophy and fundamentals behind the codes. I'm currently still confused with one issue: how is the weight factor in a `BilinearFormIntegrator` defined with respect to `IntegrationPoint.Weight()` and `ElementTransformation.Weight()` ? Can you help me understand it with some example BilinearFormIntegrators , e.g. `CurlCurlIntegrator` ?

Thanks very much !
Bright

**Comment by mlstowell** [comment]
Hi, @brightzhang91 ,

The weight factors from the quadrature rule, stored in `IntegrationPoint.weight`, assume we are integrating over a unit domain of some sort e.g. a unit interval, a unit square, etc.. The `ElementTransformation` handles the coordinate transformation from the unit domain to the physical domain so `ElementTransformation.Weight()` gives the determinant of the Jacobian of this coordinate transformation. As such `ElementTransformation.Weight()` gives, for example, the length in physical space of the actual 1D interval, or the area of the actual 2D quadrilateral, etc..

Consequently if we integrate on a unit domain of some sort we would only need the `IntegrationPoint.weight`. Whenever we integrate on an actual domain, which is essentially always, we need the product `IntegrationPoint.weight * ElementTransformation.Weight()`.

In the specific case of the `CurlCurlIntegrator` we are integrating the dot product of two vector fields in H(Div) (also known as RT in the MFEM lingo). This is because the curl of an H(Curl) field is in H(Div). Recall that coordinate transformations also alter vector fields so we need to use the Jacobian to alter the magnitude and direction of the curl of our ND basis functions. The appropriate transformation for these curls is to first multiply them by the Jacobian matrix and then divide the resulting vectors by the Jacobian determinant. The matrix multiplication is done [here](https://github.com/mfem/mfem/blob/0843a87d7953cf23e556dcfd426d27bd9cfb3e21/fem/bilininteg.cpp#L1910). The division by the Jacobian determinant is done [here](https://github.com/mfem/mfem/blob/0843a87d7953cf23e556dcfd426d27bd9cfb3e21/fem/bilininteg.cpp#L1905). In this integrator a small optimization is made which may partially hide what is happening. We do need the product of the integration weight and the Jacobian weight i.e. `ip.weight * Trans.Weight()`. However, the vector field transformation requires that we divide by `Trans.Weight()` for each RT field involved in the integral. This means that we must divide by `Trans.Weight()` squared. The end result is `ip.weight / Trans.Weight()`.

Best wishes,
Mark

**Comment by brightzhang91** [comment]
Thanks so much Mark for the explanation in great detail. This really helps me to understand the weight factors in the Integrators. I'll close this issue now and update later when I have it work correctly/having new questions. Look forward for your new updates on the documentation website !

Bright ;)
