### ISSUE TITLE
Element refinement depth & NCMesh partitioning

### ISSUE THREAD

**Issue by Dan2997925** [mfem/mfem#258]
When doing general non-conforming mesh refinement, is there a way to determine the depth of an element (distance from root)?

I see that ncmesh has a method GetElementDepth. I am trying something like:

```c++
for (int i = 0;i < pmesh->getNE();i++)
{
  int depth = pmesh->ncmesh->GetElementDepth(i);
  etc;
  etc;
}
```

however the answer I am getting doesn't look right. I'm wondering if my pmesh and the ncmesh have different element orderings or different numbers of elements. PS works fine in serial, so is this something to do with ghost elements maybe?

**Comment by jakubcerveny** [comment]
Hi Dan,

This should work, it's not clear to me why it doesn't. I've been using this
myself and in parallel too. The ghost elements are numbered after all
regular elements (index >= GetNE()), so that shouldn't be an issue. The
ordering should be consistent too. Perhaps if you could send me a
simplified example I could take look at it.

Jakub

**Comment by Dan2997925** [comment]
OK thanks the problem is likely on my end then.

**Comment by Dan2997925** [comment]
Another question, I don't understand the the partitioning I am getting when I create a Parmesh. See attached. Seems like an illogical partitioning from a communication point of view. I built the code using metis, is there a way to tell if metis is actually being used? My calling sequence is:

create Mesh
EnsureNCMesh
create ParMesh
Rebalance

![partitioning](https://user-images.githubusercontent.com/24529682/29725393-cc483202-8980-11e7-9a07-c00bbb1245fd.PNG)

**Comment by jakubcerveny** [comment]
If this is an NCMesh, Metis is not used. NCMesh uses the space-filling
curve approach to partition the mesh. This works great if the coarse mesh
has very few elements. If it has a lot of elements, they should be ordered
somehow up front, e.g., using Gecko, so that their sequence is some kind of
space filling curve too. I suspect your image shows the coarse mesh,
ordered by layers and rows. The NC code just splits the global element
sequence into N parts. Within one coarse element, after refinement, the
Hilbert curve is created. But the coarse mesh needs ordering up front. We
should add code to do that automatically, but this has not been done yet.

Jakub

**Comment by Dan2997925** [comment]
Thanks, but not sure I am following.

Yes this is a NCMesh, and my plot is of the coarse mesh (the original Parmesh before any refinement).

So what do I do to make this original partitioning more reasonable? Are you saying I need to reorder my serial mesh, using Gecko or some other method, and then call mesh->ReorderElements?

Do I reorder the elements before or after I call EnsureNCmesh?

Why does the code
partitioning = mesh.GeneratePartitioning(NRanks, part_method);
not work if the mesh is an NCmesh?

**Comment by jakubcerveny** [comment]
> So what do I do to make this original partitioning more reasonable? Are
you saying I need to reorder my serial mesh, using Gecko or some other
method, and then call mesh->ReorderElements?

Yes, exactly.

> Do I reorder the elements before or after I call EnsureNCmesh?

Before. This is because mesh->ReorderElements doesn't work with NCMesh (I
think).

> Why does the code
> partitioning = mesh.GeneratePartitioning(NRanks, part_method);
> not work if the mesh is an NCmesh?

This is the other (standard/older) code branch that works with regular
meshes and bisection based AMR. This is the Metis partitioning, which looks
nice, but cannot be rebalanced. Once you start working with nonconforming
meshes many things are done in a different code branch that uses
space-filling curve partitioning and rebalancing. This is hopefully a
temporary state, we should unify the two code paths in the future. Also the
Gecko reordering should be done automatically, but we're not there yet,
sorry.

Jakub

**Comment by Dan2997925** [comment]
I don’t know anything about Gekco and an internet search was not helpful.

Do you have space filling curve code that I could use to reorder my elements?

**Comment by jakubcerveny** [comment]
I don't, unfortunately. As I understand it, Gecko is an internal Lab code
or it is unreleased. Aaron Fisher added some support for it into MFEM last
year. He should know more.

Jakub

**Comment by v-dobrev** [comment]
One simple solution for this mesh may be to generate the mesh rotated so that the number of elements in x-direction is 2 and the larger number of elements are in the y- and z-directions. This way the element numbering will follow the thin direction first. After the mesh is created you easily rotate it using `Mesh::Transform()` with a transformation given as either a `VectorCoefficient` or a C-function.

**Comment by lindstro** [comment]
I am the author of gecko.  This code has been released but is not yet available online.  I've been meaning to clean the code up and give it an open source license, but I've been too busy with other projects to make this happen.  I'm attaching a beta version of the code in case @Dan2997925 wants to give a go.
[gecko.zip](https://github.com/mfem/mfem/files/1252871/gecko.zip)

**Comment by v-dobrev** [comment]
One alternative to Gecko, which will probably not give as good results, is to use `Mesh::GeneratePartitioning()` (which uses METIS) with some number of partitions (not necessarily the number of processors) and then re-enumerate the elements subdomain by subdomain following the original element order in each subdomain.
