### ISSUE TITLE
FiniteElementSpace::GetFaceInteriorDofs returns empty array

### ISSUE THREAD

**Issue by marc-85** [mfem/mfem#2589]
Hello,

I am trying to recover the nodes of an internal face (i.e., not a boundary face) in an L2 (discontinuous) `FiniteElementSpace`. I was hoping that `FiniteElementSpace::GetFaceInteriorDofs` would return the face nodes for both elements sharing the face but it systematically returns an empty `Array<int>`. Is this behavior expected? I could not find anywhere in `fspace.cpp` a function where `FiniteElementSpace::fdofs` is filled out so I am clueless at the moment. 

For reference, the `FiniteElementCollection` that I am using to define the `FiniteElementSpace` has `GaussLobatto` points, and so there should be points at the element faces.

Hope you can help and very many thanks in advance!
Marc

**Comment by pazner** [comment]
Hello @marc-85,

Yes, the behavior you describe is currently the "intended" behavior.

Because MFEM supports different types of bases for DG spaces, including "open" bases like Gauss-Legendre, there are not always DG DOFs that are associated with faces. In special cases like Gauss-Lobatto or Bernstein, there are indeed nodal points that lie on the faces, but MFEM does not identify these DOFs as face DOFs because it doesn't generalize to all bases.

That being said, there is demand for providing a way to extract this kind of information, so I hope that we will be able to provide an easy way to get those DOFs in the future.

In the meantime, you can use some logic to identify those DOFs given the element DOFs. This is done for tensor-product elements here:
https://github.com/mfem/mfem/blob/c2f9d3f5b100a954a1bb26133c6278671b8ac16a/fem/restriction.cpp#L561-L667

**Comment by marc-85** [comment]
Thanks @pazner,

This is very helpful. Many thanks
