### ISSUE TITLE
How to solve 2D and 3D magnetostatics problems

### ISSUE THREAD

**Issue by tuckerbabcock** [mfem/mfem#2590]
Hi all,

I've developed a 3D nonlinear magnetostatics solver based on MFEM, but I'd now like to be able to solve 2D problems with it as well. I realize that in 2D the magnetostatic equations can be simplified and implemented as a scalar Poisson problem with H1 elements. I would rather not use this approach though, and instead want to use Nedelec elements with the curl-curl form of the problem. I want to do this so that I can use all the same integrators I've written for the 3D analysis (I don't believe I can use the Poisson form since elements from an H1 collection don't implement `CalcCurlShape`). I'm wondering if you all could offer some guidance on how I might be able to do this, and how `CalcCurlShape` actually works for 2D elements. Some specific questions:
- Why does the curlshape matrix only have one column in 2D? What do it's entries mean?
- How can I get the magnetic flux density with this 2D curlshape? In the 3D `NonlinearFormIntegrator` I'd do `curlshape_dFt.AddMultTranspose(elfun, b_vec);` to get the magnetic flux density as a vector with length 3, but in 2D since `curlshape_dFt` is `ndofx1` `b_vec` would be a vector with length 1, and I don't know how to interpret that.
- How can I visualize the 2D magnetic flux density field? For my 3D problem, I'm able to use a `DiscreteLinearOperator` with a `CurlInterpolator` added to it, but this doesn't work in 2D since `CurlInterpolator::AssembleElementMatrix2` calls `ProjectCurl` from an RT element, which forwards to `ProjectGrad_RT` for the 2D RT elements (since it assumes the domain field would be in H1).

My main goal is to be able to solve 2D magnetostatics problems without having to write new integrators just for the 2D case, so if there is a simpler approach to doing that without needing a 2D ND space, please let me know as well.

Thanks as always!

**Comment by mlstowell** [comment]
Hi, @tuckerbabcock,

I understand your desire to reuse your 3D code in 2D. You may be interested in PR #1989 which came from a similar motivation.

Regarding your specific questions:

- The curl of a two dimensional vector field is always directed out of the plane i.e. it is always scalar valued. This is sometimes called the `rot` operator.
- The scalar is just interpreted as the z-component of the magnetic flux (assuming your 2D domain is the xy-plane).
- I'n not certain the `CurlInterpolator` supports this but the natural way to compute the curl of a Nedelec field in 2D produces its result as an L2 field (rather than H1).

I believe the PR I mentioned above goes into this in some detail but basically 2D EM often involves problems which are decoupled from each other. In 2D magnetostatics the usual thing to think about is the direction of the current. If the current is in the plane then `B` and `H` will only have z-components. If the current is in the z-direction then `B` and `H` will have only components in the x and y directions. In the first case you solve for `A` using 2D Nedelec basis functions, in the second you solve for `A_z` using H1 basis functions. If the magnetic permeability is anisotropic and blends these two polarizations then you may want to try PR #1989. If the magnetic permeability is isotropic but `J` has both in-plane and out-of-plane components then you'll need to couple the Nedelec and H1 polarizations using `BlockOperators` (assuming your nonlinearity involves both polarizations) or use something like PR #1989.

Best wishes,
Mark

**Comment by tuckerbabcock** [comment]
Thanks for the reply @mlstowell.

Of course you're right, the curl of any 2D vector field would be the scalar out of the page value. I didn't jump to that at first since I was wanting to represent `A_z` with the 2D Nedelec field, and somehow just have the other vector component be zero/ignored, but I see now that that doesn't make much sense.

I took a look at PR #1989 and I'm not sure how I'd be able to use it. My current density is strictly out of the page, so I'm only dealing with `A_z` (in this 2D case). At first I thought I would want to use the ND_R1D collection (since the documentation suggests it's for when the vector field varies along one dimension), but it requiring `dim == 1` rules that out for me.

Since representing `A_z` with H1 elements is the straightforward choice, maybe the right approach for me is to create a new FE collection that uses finite elements that inherit from the H1 2D elements but have been extended to have the same interface as the ND elements so that I may use them in the same integrators? Do you have any thoughts on that approach @mlstowell, or perhaps could tell me if I've misunderstood PR #1989? Also, what's the status with that PR? It looks like it's been two months since the last commit.

Thanks for your help as always,
Tucker

**Comment by mlstowell** [comment]
Hi, @tuckerbabcock,

The ND_R1D basis is for 3D vectors on 1D domains. Meaning that the vector field has x, y, and z components but each of these only varies as you move in the x direction. For a 2D domain you'd want to use ND_R2D. These are a direct sum of the 2D Nedelec basis and the H1 basis. If your current is always in the z direction and your permeability doesn't mix the z component with the xy components then you don't really need PR #1989 although it would work fine. By the way this PR is ready to go except that I was waiting until another change to the fe.[ch]pp files made its way into master. That happened last week so I'll start pushing on this PR again.

You could create a set of specialized basis functions and an accompanying FECollection. To be honest it might be easier to write a new integrator for the 2D case.

Best wishes,
Mark

**Comment by tuckerbabcock** [comment]
Thanks @mlstowell!

I'll close this issue since you've been able to help me address my concerns. I'll look forward to the PR being merged!
