### ISSUE TITLE
Boundary elements with wrong orientation: 588 / 588 (fixed)

### ISSUE THREAD

**Issue by adam-sim-dev** [mfem/mfem#2627]
When I run my code linked with mfem in debug mode with a tetrahedral mesh, I see the following warning:

`Boundary elements with wrong orientation: 588 / 588 (fixed)`

This warning comes from 

`int Mesh::CheckBdrElementOrientation(bool fix_it)`

I am wondering, which is a correct orientation for the boundary element? In my case, each boundary is a triangle with three vertices.

Thanks.
Adam

**Comment by tzanio** [comment]
This is probably harmless (the orientation is fixed), but for the record the boundary faces should be oriented such that the corresponding normal points outside the domain. See for example `data/ref-tetrahedron.mesh`

**Comment by adam-sim-dev** [comment]
Thanks! That makes the problem clear. I will try to fix my mesh input.

**Comment by tzanio** [comment]
Hi @faircdl,

Can you send a simple mesh where you see this message?

It is probably harmless, coming from different default orientation in Cubit vs MFEM, but you can also pre-process the mesh (e.g open it and save it in MFEM) to avoid this message in the future.

Tzanio

**Comment by v-dobrev** [comment]
Hi @faircdl,

Note that there are two different messages: one is for boundary elements (whose orientation is typically automatically fixed, according to the MFEM conventions -- the fixing algorithm assumes that the "volume" elements are already oriented according to the MFEM conventions); and the second message is about the elements, i.e. the "volume" elements -- this is what you see. Since you are exporting from Cubit, I suspect you have hex elements. For hex elements we do not automatically perform vertex permutations to fix the orientation because it is not clear what ordering convention was used when the mesh was written. The hex `.gen` mesh in the repo (https://github.com/mfem/mfem/blob/master/miniapps/electromagnetics/cylinder-hex-q2.gen) does not have that issue and it was also generated by Cubit. (It has some inverted boundary elements which are automatically fixed: `Boundary elements with wrong orientation: 102 / 204 (fixed)`.) I'm not sure how and why Cubit is generating hexes that are sometimes inverted and sometimes not inverted.

Just FYI, the expected vertex ordering in MFEM is:
```ascii
  z  y
  | /     7-----6
  |/     /|    /|
  +--x  / |   / |
       /  |  /  |
      /   3-/---2
     /   / /   /
    4-----5   /
    |  /  |  /
    | /   | /
    |/    |/
    0-----1
```
