### ISSUE TITLE
Navier-Stokes periodic boundary condition

### ISSUE THREAD

**Issue by Andr00dz** [mfem/mfem#2628]
Hi,

I'd like to implement periodic boundary conditions for Stokes/Navier-Stokes, where the velocity is periodic (u_left=u_right) and the pressure satisfies (p_left=p_right+C). (The boundary condition is described at the beginning of https://www.sciencedirect.com/science/article/pii/S0893965906000978 )

Concerning the mesh: My current approach starts in gmsh, where I can set specific boundaries to be periodic, which leads to the behavior (in mfem) that all unknowns are periodic.

Is there an easy way to disable the periodicity for the pressure?

**Comment by bslazarov** [comment]
Hi,

May I ask what is the purpose of the BC? If you want to do homogenization, i.e., estimating an effective permeability for the unit cell, you will need to add only an acceleration term to the equation and you can avoid adding jump in the pressure. Let me know if that is the case so I can provide you with more details.

**Comment by Andr00dz** [comment]
Hi @bslazarov,

the goal of this BC is to model periodically repeated domains by only considering only one repeated section of the domain and prescribing a fixed flow rate across the periodic boundary. This can be done by setting u_left = u_right, (du_left/dn = -du_right/dn), p_left=p_right+C. (The constant C is determined by prescribing a specific flow rate across the periodic boundary)

**Comment by bslazarov** [comment]
Hi,

If you are planning to relate the average velocity <u> to the average driving pressure <p> you can replace the jump C in the pressure with a contribution to the RHS of the NS equation. The pressure can be decomposed to \nabla p+ g_p, where g_p is a pressure gradient. For jump C, g_p will be equal to C/h, where h is the length of the cell. Taking the average <\nabla p+ g_p> will result in <\nabla p>+g_p. Thus, instead of prescribing the pressure jump on opposite sides of the cell, you can add acceleration temp g_p to the momentum equation and use periodic BC for the pressure.

**Comment by Andr00dz** [comment]
Thanks for pushing me in the right direction. I found a [reference](https://doi.org/10.1080/10407799808915063) that uses the above mentioned approach:

- In my situation, the pressure p can be expressed as `p(x,y)= -c*x+p_p(x,y)`, where p_p(x,y) is periodic.

Substituting p with the expression above in the momentum equation leads to the additional source term `c` in the x-component momentum equation. The constant `c` can then be iteratively adjusted until a prescribed average flow rate is attained.

I will try out the above mentioned approach and close this issue for now.
