### ISSUE TITLE
How to open MFEM mesh format in Paraview

### ISSUE THREAD

**Issue by WeizhaoLi2018** [mfem/mfem#2636]
Hello MFEM team,

I am interested in the MFEM mesh format to visualize high order discontinuous solutions and I have a question about the mesh format. On the MFEM website, it says "visualization tool natively supported by MFEM is ParaView".  But when I use Paraview to open a sample mesh file ('beam-quad.mesh' from the website), paraview does not recognize the mesh format. Is there some extra plugins I need to install on Paraview so that it could recognize the MFEM format?

Thanks a lot for your help!

**Comment by pazner** [comment]
If you want to use ParaView to visualize meshes and solutions from MFEM, you will need to export them to ParaView format. ParaView cannot read MFEM format (either natively or through a plugin).

In order to export your mesh to ParaView format, the following function should do it.
```c++
#include "mfem.hpp"
using namespace mfem;
int main()
{
   Mesh mesh = Mesh::LoadFromFile("../data/beam-quad.mesh");
   mesh.PrintVTU("beam_paraview");
   return 0;
}
```

If you also want to visualize solution fields, look at `ParaViewDataCollection`.

**Comment by WeizhaoLi2018** [comment]
Okay, got it!
Thank you for the reply.
