### ISSUE TITLE
Compute nhat within coefficient

### ISSUE THREAD

**Issue by wcdawn** [mfem/mfem#2647]
I would like to compute the outward-normal unit vector within a coefficient.
Depending on the orientation of the face, the value of my coefficient will be different.
This is being used in conjunction with a `BoundaryFlowIntegrator` to evaluate an "inflow" condition.

I have tried
```cpp
Vector nhat(3);
CalcOrtho(Tr.Jacobian(), nhat);
nhat /= nhat.Norml2();
```

For now, I am running a simple 2d square problem. For all boundaries, nhat=(0,-1) is returned.
How should I go about evaluating this quantity?
Thanks!

**Comment by v-dobrev** [comment]
In `BoundaryFlowIntegrator` there are two coefficients, I assume you are talking about the scalar boundary coefficient `f`? Note that this coefficient is already ignored in certain cases, based on the sign of `u.n`: https://github.com/mfem/mfem/blob/167ff72edccc4e5b0a642ae3392ccaf50f455b9e/fem/lininteg.cpp#L685-L688
For example, if `alpha=1`, `beta=0.5` then `w=0` when `un >= 0` (i.e. `u.n >= 0`) and effectively this is the same as setting `f=0` at such quadrature points. Note that `un` is a scaled version of `u.n` -- it is `u.n` multiplied by the weight from the change of variables that comes from changing the face integral from physical coordinates to reference coordinates.

If this behavior is not sufficient for your use case, you can compute the normal (non-unit) vector similar to the code snippet you posted above -- you may need to set the size of `nhat` to be `Tr.GetSpaceDim()` instead of 3. You say you need to evaluate "the orientation of the face" -- is this the orientation relative the same vector field `u` as in the `BoundaryFlowIntegrator` or some other vector field?

**Comment by wcdawn** [comment]
@v-dobrev Thank you for taking a look at this.

Yes, in the `BoundaryFlowIntegrator`, my `f` coefficient changes based on the orientation of the face relative to a vector field. I have a vector field (constant through the domain) and there is a unit vector `omega`. The value of `f` changes for different values of `nhat*omega`.

I think I found my issue. There's a comment here in `BoundaryFlowIntegrator` that confused me a bit
https://github.com/mfem/mfem/blob/2519a91d015d7842df62aa9cce4df9a17f443c9a/fem/lininteg.cpp#L672-L674

When I changed `*Tr.Elem1` to `Tr`, my `f` coefficient behaved as I expected. I don't entirely understand why.

**Comment by v-dobrev** [comment]
Let me try to clarify the comment.

Typically, when one defines `u` for this integrator, it is the same `u` that is used in the `ConvectionIntegrator` and that must be defined at every quadrature point in every element. In particular, if one is implementing a custom coefficient, they will expect the `ElementTransformation` to be a "volume" transformation and not a boundary or face transformation; similarly they will expect the third argument to be a quadrature point in the reference "volume" element (that can be used with the "volume" `ElementTransformation`).

For that reason, the code snippet you linked uses the "volume" transformation `*Tr.Elem1` and its corresponding "volume" quadrature point `eip`. If you use the face transformation `Tr` (with that, one needs to use the face quadrature point `ip`) then you need to make sure that the coefficient `u` supports this. For example, for `VectorConstantCoefficient` and `VectorFunctionCoefficient` this is not a problem and the code will work as expected. With the `VectorGridFunctionCoefficient` this was a problem, until recently -- the implementation was assuming the `ElementTransformation` and the quadrature point were both "volume". This limitation was recently lifted and now `VectorGridFunctionCoefficient` should work with all types of transformations. Therefore, with the latest MFEM, the main potential issue is with custom-defined `VectorCoefficient`s that assume a "volume" transformation and quadrature point -- for that reason, the above snippet is still using the "volume" transformation when calling `u->Eval`.

**Comment by wcdawn** [comment]
Thank you for the clarification. I understand that my use of the integrator is a bit abnormal. For my purpose, I expect `nhat` to be computed for the face to determine the incoming/outgoing angle of the face.
