### ISSUE TITLE
Unable to see why automated testing fails

### ISSUE THREAD

**Issue by JacobLotz** [mfem/mfem#2650]
I am working in the nurbs-knot2edge branch. I am finishing up my work for creating a pull request. However, some tests seem to fail, but I am unable to see why it fails. (See attached screenshot.)

How can I see a more detailed error message? For other commits I see a much more detailed error message at a commit.

Kind regards,
Jacob Lotz

![Screenshot from 2021-11-08 17-42-33](https://user-images.githubusercontent.com/69582468/140782716-9f1d0d30-1283-4477-9bd4-d69694e30568.png)
)

**Comment by tzanio** [comment]
I am not sure if that's the reason, but can you merge `master` in your branch and resolve the conflicts that are listed in https://github.com/mfem/mfem/pull/1630?

**Comment by JacobLotz** [comment]
This indeed solved the problem! Thanks! 
Now among some other stuff I have to fix, after the merge of master into nurbs-knot2edge it fails the branch history test.
It fails since I have changed a large number of files in the merge. Can I ignore this?

**Comment by tzanio** [comment]
> It fails since I have changed a large number of files in the merge. Can I ignore this?

If that's the only reason it fails, then you can ignore it.

**Comment by v-dobrev** [comment]
In #1630, there is a big commit (23730a69) that was later reverted (3ba52502) -- this big commit is the reason the `branch-history` test fails -- we do this so that we can assess if such big commits are worth keeping in the git history in the repo.

In this case, we should probably just squash-merge that PR when ready, if @JacobLotz and @IdoAkkerman are okay with that.

On the other hand, the failure on appveyor (https://ci.appveyor.com/project/mfem/mfem/builds/41478884) seems to indicate some problems with the Windows build.
