### ISSUE TITLE
Variable vector boundary condition for solving static mechanics.

### ISSUE THREAD

**Issue by random2000** [mfem/mfem#2664]
I would like to compute static mechanics for membrane inflated with air pressure.

Boundary condition for applying air pressure is "sigma(u).n = f" like example 2.
(I think f is corresponding with pressure. Is that correct?)
In example 2, vector f is constant vector.
However, direction of pressure vector f is changing through inflating elastic membrane, because area of mesh on boundary surface is variant.

Are there any methods to apply variable vector boundary condition?
Is the f direction being converted internally?

Thank you.

**Comment by vladotomov** [comment]
Hi @random2000,

Since `f` is a `VectorCoefficient`, it can be made time-dependent by using `VectorCoefficient::SetTime()` in the time loop, and `VectorCoefficient::GetTime()` in the evaluation of `f`.

I'm not sure what you mean by "`f` direction being converted internally". In example 2, `f` is evaluated in physical space, and the direction is set by the user. The normal `n` is the outward normal to the boundary. If the boundary is moving, `n` would change automatically.

Vladimir

**Comment by random2000** [comment]
Dear vladotomov

Thank you for your reply.

I understood that "boundary is moving, n would change automatically".
It is a very useful information for me.

While pressurized surface deform, external force direction given by air pressure on the surface is changing.
But It is not still clear for me that this function is usable on which types of problem, time-dependent, time-independent, or both of them.

Is it possible to set boundary condition "sigma(u).n=f" without setting time?

My question "Is the f direction being converted internally?" means that whether f direction being converted to appropriate direction in the time-"independent" computation like example 2.
I would like to know if the pressure boundary condition works properly by applying a constant vector f to the boundary condition.

Thank you.

**Comment by vladotomov** [comment]
As the surface deforms, `n` changes. I guess `u` would change as well in time, thus the term `sigma(u).n` changes in time. Then since we enforce `sigma(u).n=f` in the weak form, the meaning of would `f` change in time, as we're using it to constrain the values of different quantities. So in this sense, yes, `f` is being converted internally.

In ex2 `f` is a _force_ vector (or _traction_), which is not equivalent _pressure_.

**Comment by random2000** [comment]
Thank you for your polite answer @vladotomov.

I understood that f is a force. ( From this fact, is n a normal vector of boundary surface which has a physical dimension of [m^2]? )
Sorry for complex questions.
In short, my objective is simulate a elastic membrane inflation with a static mechanics formulae.
I would like to simulate membrane deformation inflated with a air pressure.
How can I apply air pressure as a boundary condition on the boundary surface?

random2000

**Comment by vladotomov** [comment]
I believe that should be `p n` (pressure times the normal) for `f`, but I'm not an expert. You may want to check some books for the model. Here's some stuff that @bslazarov showed me:


![traction](https://user-images.githubusercontent.com/17843342/142711672-ed5b2450-eba3-4622-8403-b1ad919270c4.png)


I believe (2.39) is the integral we use in ex2, with `t=f` and `Na` is a  basis function. Then for the pressure:


![pressure](https://user-images.githubusercontent.com/17843342/142711695-ec053d71-a6f7-4ddf-9175-22d34f2f2ad0.png)

**Comment by random2000** [comment]
Thank you for sharing valuable information, @vladotomov and @bslazarov.
I had not understand about basis function of boundary condition and I couldn't understand theoretical detail, but now I can imagine it physical view point.

I have trusted that it can be formulated as a linear or bilinear form.
However, I consider to formulate and compute this types of problem as a nonlinear problem now.

random2000
