### ISSUE TITLE
How to apply Neumann boundary conditions for an eigenvalue computation

### ISSUE THREAD

**Issue by Amudtogal** [mfem/mfem#2673]
Hey mfem-team,
here is another beginner question from me... :smile: 
Considering an example like [ex2p](https://github.com/mfem/mfem/blob/master/examples/ex2p.cpp), if I want to compute eigenvalues for an equation, the right hand side will change to a `ParBilinearForm` which contains the `MassIntegrator`.

As the `addBoundaryIntegrator` function of this `ParBilinearForm` will only take `BilinearFormIntegrators`, I can not use the `VectorBoundaryLFIntegrator` (or any other of the [Boundary Integrators](https://mfem.org/fem_bc/) for that matter) anymore.

How can I then still apply Neumann boundary conditions on the right-hand side?

**Comment by Amudtogal** [comment]
Hey,
is there a ressource I could look into to understand how I can make this work?
Or do you know someone I could ask about this? An example somewhere?

I would really appreciate some help :smile:

**Comment by mlstowell** [comment]
Hello, @Amudtogal,

I may be misunderstanding your goal but inhomogeneous boundary conditions are incompatible with eigenvalue problems.  Generally speaking you have two choices for boundary conditions in eigenvalue problems; homogeneous Dirichlet or homogeneous Neumann. In the first case you must constrain certain degrees of freedom to be zero. In the second you do nothing since the natural boundary conditions are that the Neumann constraints are equal to zero.

Best wishes,
Mark

**Comment by mlstowell** [comment]
Hello again, @Amudtogal, 

The other part of your question dealt with `ParBilinearForm::AddBoundaryIntegrator`. This does indeed only accept `BilinearFormIntegrator` objects. Many of our `BilinearFormIntegrator` objects can be used with spaces of dimension 1, 2, or 3 so these same integrators can also be used on boundary surfaces. It may be that we don't have the specific integrator that you need for your formulation. If you can provide us with more information about the equations you're trying to solve perhaps we can offer more specific advice.

Best wishes,
Mark

**Comment by v-dobrev** [comment]
Since you mention `ex2p`: you can take a look at `ex12p` -- it solves a linear elasticity eigenvalue problem.
