### ISSUE TITLE
Parallel variable-order finite element space

### ISSUE THREAD

**Issue by adam-sim-dev** [mfem/mfem#2700]
Dear developers, 

Any progress of the parallel variable-order finite element space? I see the serial version has already been added, however, all my other codes are using the parallel mesh and spaces, so it's very difficult to test the serial variable-order finite element space.

Best,
Adam

**Comment by tzanio** [comment]
This is on our todo list, but I don't believe we have made any progress in the last few months.

@jakubcerveny, do you mind summarizing what variable-order functionality is currently available?

**Comment by jakubcerveny** [comment]
The current support for variable orders is still limited. We have demonstrated in serial that it is possible to constrain the nonconforming "p" and "hp" interfaces in a similar way we constrain ordinary hanging nodes. Many things are still missing though, such as variable-order space serialization and visualization, and of course extending the method to parallel spaces. Unfortunately due to a switch to another project I probably won't be able to return to this earlier than mid-2022.

**Comment by adam-sim-dev** [comment]
Hi Jakub, thanks for the prompt reply. The development of variable orders won't be terminated, is that right?

**Comment by jakubcerveny** [comment]
No that's not the plan, it's just a question of resources...

**Comment by tzanio** [comment]
Hi @adam-sim-dev,

This is still on our long-term plan, but we don't have resources for it in 2023 at LLNL. (Help of course is always welcome!)

Tzanio
