### ISSUE TITLE
Several warning when turn on -Wshadow

### ISSUE THREAD

**Issue by adam-sim-dev** [mfem/mfem#2701]
Hi,

There are several warnings when using -Wshadow for mpic++. I know this is not a big issue, while it will be much clean if they can be fixed.

PS, I copy the flags from kokkos:

   -Wall -Wunused-parameter -Wshadow -pedantic
   -Werror -Wsign-compare -Wtype-limits
   -Wignored-qualifiers -Wempty-body
   -Wclobbered -Wuninitialized

Best,
Adam

**Comment by tzanio** [comment]
Thanks for reporting this @adam-sim-dev.

I took a quick look and none of the warnings I saw appeared to be a problem, but we should take a careful look and resolve them if possible.

Could be a good project for #DocumentationDay.

Tzanio

**Comment by v-dobrev** [comment]
None of the `-Wshadow` warnings really needs "fixing" in my opinion -- e.g. I don't see a good reason to disallow function parameters to be called `out` just because we have a global object called `mfem::out`.

Another warning that we do not enforce is `-Wunused-parameter` -- we have a lot of unused parameters in the code.

What we enforce is `-pedantic -Wall -Werror` as tested by the github actions, see here: https://github.com/mfem/github-actions/blob/ff5143d4ef55622afdacc945960b097ab790ef8c/build-mfem/action.yml#L89-L92

Personally, I typically use: `-Werror -pedantic -Wall -Wextra -Wno-unused-parameter` (with apple-clang) which currently does not produce any warnings on `master`.

Regarding the other warnings you listed above (except `-Wclobbered` which is not supported by clang) -- none of them trigger any warnings on `master` with apple-clang.

**Comment by adam-sim-dev** [comment]
As I said before, I know it's not a problem. I have no preference, just post it here if it could be useful. Personally, I will follow Veselin's advice on my side. Feel free to close this issue.

**Comment by tzanio** [comment]
I run some test and here is what I see:

- I did not get any warning from `-Wall -pedantic -Wsign-compare -Wtype-limits -Wempty-body -Wclobbered -Wignored-qualifiers -Wuninitialized`

- There are many warnings (over 2000) from `-Wunused-parameter`, some of which are in external headers (e.g. from hypre). I don't think we can enforce this strongly.

- There are  many warnings (over 2000) from `-Wshadow`. It will be a significant effort to enforce this, and I personally don't think it is worth it.

**Comment by mlstowell** [comment]
I tend to find such warnings annoying so I do sympathize. I'll take a stab at resolving at least some of them.

**Comment by tzanio** [comment]
This is now being addressed in the PRs listed above. See the follow-on discussions there.
