### ISSUE TITLE
Reading in a Cubit mesh

### ISSUE THREAD

**Issue by srwopschall** [mfem/mfem#271]
Hi,

Can you please provide some guidance in terms of reading in a cubit mesh? My mesh file is "my-mesh.exo" and I am getting an MFEM abort: "Can not determine Cubit mesh filename!..." Any guidance would be very helpful.

**Comment by jakubcerveny** [comment]
Hi Steve,

I believe this is due to a little quirk in the Cubit mesh loader. For Cubit
meshes, you need to open the file with an mfem::named_ifgzstream (which
remembers the filename) instead of opening it with the standard
std::ifstream.

Or, use the other Mesh constructor that takes a filename and this will be
taken care of for you.

Hope this helps,
Jakub

**Comment by srwopschall** [comment]
Thanks Jakub. 

So to be clear, I read in a mesh file (e.g. const char *mesh_file) and the code I'm working with would do the following:

Mesh *mesh;
named_ifgzstream imesh(mesh_file);
mesh = new Mesh(imesh, 1, 1);

I'm getting a "fatal NetCDF error: Invalid dimension ID or name ... in function: void mfem::ReadCubit...."

Is there a requirement on the mesh file extension?

Steve

**Comment by jakubcerveny** [comment]
I'm not sure, maybe not all kinds of Cubit meshes are supported. I'm
copying Dan who might know more...

What type of elements are you loading, Steve?

Jakub

**Comment by srwopschall** [comment]
These are linear eight node hex elements.

**Comment by juan42** [comment]
What other information can you give us about the mesh? Exodus format is supported with the HDF5/netCDF backend and only in 3D. HEX8 works with these.

**Comment by srwopschall** [comment]
It is a 3D mesh of a lattice unit cell. It looks like there is an issue with the mesh name that is being read in. I read the mesh file, for example "my_mesh.exo" (exodus file format), and create a mesh 
object:

Mesh *mesh = new Mesh(mesh_file, 1, 1);

where mesh_file is my input mesh of type const char*.

The error I get is "Fatal NetCDF error: Invalid dimension ID or name, which is printed from 
ReadCubit in mesh/mesh_readers.cpp.

**Comment by jakubcerveny** [comment]
I’m fairly sure only full 3D meshes are supported.

**Comment by tzanio** [comment]
Hi @srwopschall, were you able to resolve this issue?

If not, can you send a small mesh that demonstrates the issue?

For reference, here are some CUBIT meshes that are readable in MFEM:
- https://github.com/mfem/mfem/blob/master/miniapps/electromagnetics/cylinder-hex-q2.gen
- https://github.com/mfem/mfem/blob/master/miniapps/electromagnetics/cylinder-tet-p2.gen
- https://github.com/mfem/data/blob/master/coil.gen

Cheers,
Tzanio

**Comment by v-dobrev** [comment]
Steve,

I don't think the extension matters - we simply pass the filename to NetCDF, so I'm not 100% sure. Just in case, you can try renaming the file to `*.gen` to see if that makes any difference.

According to Dan: "The MFEM Cubit reader can read a Genesis file produced by Cubit. Not sure if this is same as exodus or not."

Since the exodus cubit mesh does not seem to work -- I guess it is different from genesis.

**Comment by juan42** [comment]
@srwopschall 
The actual problem is, that you probably haven't defined any sidesets. I ran into the same issue a few minutes ago. After defining sidesets in cubit everything works fine!
