### ISSUE TITLE
CMake build does not have '..' in include search path.

### ISSUE THREAD

**Issue by sshiraiwa** [mfem/mfem#274]
Hi, 

Maybe this is not an issue for other people or maybe I had other errors in my build
process,,  but let me report a problem I encountered.

When using GNU make, it generates the following build command for an example

mpicxx  -O3 -I.. -I/Users/shiraiwa/sandbox/include -I/Users/shiraiwa/sandbox/include ex1p.cpp -o ex8p -L.. -lmfem -L/Users/shiraiwa/sandbox/lib -lmetis -L/Users/shiraiwa/sandbox/lib -lHYPR

CMake, on the other hand, does do this
/opt/local/bin/mpicxx   -I/opt/local/include/mpich-clang37 -I/Users/shiraiwa/sandbox/include -I/Users/shiraiwa/src/mfem_sep_2017/cmbuild  -O3 -DNDEBUG   -o CMakeFiles/ex8.dir/ex8.cpp.o -c /Users/shiraiwa/src/mfem_sep_2017/examples/ex8.cpp

Notice that -I.. is missing in CMake version. Unfortunately, I had old mfem header files stored in the same place as other library (Metis and Hypre), and since there were a few changes of signature,
it caused my example sag-fault.

--
Syun'ichi

**Comment by v-dobrev** [comment]
CMake converts all relative paths to absolute. In the GNU make build line, `-I..` and `-L..` point to the root of the mfem source (my guess is that you ran that command in the `examples` directory). In the CMake build the mfem headers that one has to use are in the root CMake build directory, so I guess that is the path `-I/Users/shiraiwa/src/mfem_sep_2017/cmbuild`. I think that everything looks correct.

Actually, I think I see what your point is: you had old mfem headers in `-I/Users/shiraiwa/sandbox/include` and since that came before `-I/Users/shiraiwa/src/mfem_sep_2017/cmbuild` on the command line, the compiler found the old mfem headers first and included those. Is that the issue? I think we can easily fix it by moving the mfem build directory first. This is what GNU make does too.

Thanks for pointing out this issue.

**Comment by sshiraiwa** [comment]
I saw your fix. Thank you so much.
