### ISSUE TITLE
ProjectGridFunction error

### ISSUE THREAD

**Issue by Watchmojo** [mfem/mfem#2747]
Hi, 

When projecting a GridFunction into another GridFunction in the same fes, there seems to be a persistent level of minor (~1e-16) error concentrated at random element interfaces. This may not cause any harm for occasional use, but would gradually drift the solution away when used repeatedly.

**Comment by pazner** [comment]
If you know that the FES is the same, why not just set the grid functions equal to each other? `ProjectGridFunction` is most useful in cases where either the spaces or the bases are different. That being said, some error of around machine precision (~1e-16) should not be much of an issue, since most finite element operations will also have round-off errors of this magnitude.

**Comment by Watchmojo** [comment]
Yes. Adding an additional `if' to set GridFunctions equal to each other when the same fes is used solves the problem.
