### ISSUE TITLE
How to evaluate the integral of the form $\int u ds\int v ds$

### ISSUE THREAD

**Issue by sin2cos** [mfem/mfem#2764]
![51D245E3-B63E-409B-866E-88AB387AA9A5](https://user-images.githubusercontent.com/62394271/149388140-55c54c3d-52d2-4c1d-bc04-cb42f34e19c1.jpeg)
Hi, I am new to MFEM, I am trying to solve my EIT problem with MFEM, but an integral of the form $\int u ds\int v ds$ appears in my weak form, as been highlighted in the picture, and I checked the integrators in MFEM, I can not figure out how to implement this integral. 

Is there a way to do it?

Thanks a lot!

**Comment by mlstowell** [comment]
Hi, @sin2cos, 

This does look unusual but there may be a way to handle this. It would help to know a little more about the problem. For example, what is the, `e_l`, domain of these integrals?

Also, just out of curiosity, what is EIT?

Best wishes,
Mark

**Comment by sin2cos** [comment]
@mlstowell

Hi Mark,

Sorry for bothering, I still can not solve the above problem, do you have any idea on how I may deal with it?

Best Wishes,
Changyou

**Comment by mlstowell** [comment]
HI, @sin2cos,

I just saw your follow-up email today. I hope you don't mind but I'm more accustomed to keeping the discussion here in the GitHub issue.

In your email you mentioned that the `e_l` are patches of the surface of your object. I assume the surface of the object is also the surface of your mesh. If this is the case the integrals `\int_{e_l}u dS` and `\int_{e_l}v dS` will be equal and can be computed as linear forms i.e. using a `ParLinearform` object and its `AddBoundaryIntegrator` method (the patch can be specified with the optional `bar_attr_marker` argument) with a `DomainLFIntegrator`. The tricky part will be the assembly.

If I understand your equations correctly, and I am not at all certain that I do, each surface patch will lead to a dense block in your linear operator. This is very odd for a finite element method so perhaps I'm not understanding the equation properly. To form this block I believe you would take the linear form, call it `w`, and produce the outer product with entries`w[i] * w[j] / |e_l|`.

Unfortunately, MFEM does not have a way to allocate your matrix with these dense blocks so you may need to write some custom code to accomplish this.

Best wishes,
Mark

**Comment by sin2cos** [comment]
@mlstowell 
Hi Mark,

Thank you for your detailed information, I think you have understand my question correctly, and your suggestion here is helpful for solving my problem. The only thing I don’t understand is whether parallel computation is still doable with MFEM after the outer product with entries w[i] * w[j] / |e_l|.

I am actually trying to understand the codes these days, hope I can inherit from some BilinearForm class to write my own BilinearForm to implement this weak form, but this looks like a hard task for me since I am quite new to MFEM.

Best wishes,
Changyou

**Comment by mlstowell** [comment]
Hello, Changyou @sin2cos, 

I'm sure MFEM can do much of the work but we may not have a complete solution. Finite element bilinear forms integrate each element separately but you need to incorporate information from other elements on the same surface patch. This is not something that usually happens in finite element methods and we don't have an easy way to setup the BilinearForm matrix with the necessary number of nonzero per row nor to fill those entries with data from multiple boundary elements.

I do see two options. The choice between them may depend on how you need to use this operator. The first option could be used if you need a sparse matrix representation of this bilinear form (to pass along to a sparse direct solver for example). You would need to count the number of degrees of freedom associated with each surface patch and use this information to allocate a sparse matrix with enough nonzeros to hold the dense portions. We should have the necessary code in MFEM to determine the size and location of these patches in the matrix. Filling the patches would require additional communication between processors. This could be tricky but I think it could work.

The second option would be much easier to implement but it could only compute the action of your operator rather than filling a sparse matrix. As such you could use this with an iterative solver but it might be difficult to find a suitable preconditioner. This option would involve forming a bilinear form in the usual MFEM manner containing the first and second terms in your operator. The third term, the one with the outer products, would involve computing and storing linear forms for each surface patch. Then to compute the action of the operator, `A*x`, you first multiply by the bilinear form then loop over the patches and add terms which look like `(w.x)*w`. Another advantage of this option is that all of the necessary parallel communication would be handled in the inner products `w.x`.

I'd be happy to offer further advice if either of these options sounds reasonable.

Best wishes,
Mark

**Comment by sin2cos** [comment]
@mlstowell 
Hi Mark,

Sorry for the late reply, I was in a vocation, and I did not check emails for a while. I believe you have solved my problem. I am writing the code based on your suggestion, and I will let you know whether it works.
Best wishes,
Changyou
