### ISSUE TITLE
Use GetHessians in RHS

### ISSUE THREAD

**Issue by tangqi** [mfem/mfem#2765]
Hi, 
I am trying to solve the following equation for f
Δf = Phi_xx Phi_yy -Phi_xy^2 - J^2 - (J_x Psi_x + J_y Psi_y)
where Phi, Psi, and J are all already solved GridFunctions. 

I am trying to define RHS as a coefficient and then call DomainLFIntegrator like this
```
    double RHSCoefficient::Eval(DenseMatrix &M, ElementTransformation &T,
                     const IntegrationRule &ir)
    {
       ...
        Psi->GetGradients(T, ir, gradPsi);
          J->GetGradients(T, ir, gradJ);
          J->GetValues(T, ir, Jvalue);
        Phi->GetHessians(T, ir, Hessians);

        for (int i=0; i<ir.GetNPoints(); i++)
        {
            M(0,j)= Hessians(i, 0)*Hessians(i,2) - Hessians(i,1)*Hessians(i,1) 
                  -Jvalue(i)*Jvalue(i)-gradJ(0,i)*gradPsi(0,i)-gradJ(1,i)*gradPsi(1,i);
        }
    }
```

But this is not how GetHessians work. Any suggestions?
Qi

Correction: I think to use DomainLFIntegrator, I need to evaluate the RHS at the integration point instead of evaluate at each element. So I am not sure how to use GetHessians. Is there any other solution? It is only in post-processing, so it is fine if the solution is very expensive.

**Comment by v-dobrev** [comment]
If I understand correctly, the rhs `Phi_xx Phi_yy -Phi_xy^2 - J^2 - (J_x Psi_x + J_y Psi_y)` is a scalar, so you need to derive your `RHSCoefficient` from class `Coefficient` and override the virtual method: https://github.com/mfem/mfem/blob/0f239c22e03b8e3b7d8e3311597ca6d809e8f5c2/fem/coefficient.hpp#L53-L59 In that case you only have a single `IntegrationPoint` and not `IntegrationRule` (which is an array of `IntegrationPoint` with some additional methods). In order to call the method `GetHessians` you can add an `IntegrationRule ir` with one point to your class `RHSCoefficient`, initialize it with the constructor: https://github.com/mfem/mfem/blob/0f239c22e03b8e3b7d8e3311597ca6d809e8f5c2/fem/intrules.hpp#L217-L218 and then inside the definition of `Eval` simply copy the `IntegrationPoint &ip` to `ir` with `ir.IntPoint(0) = ip;`.

Does this make sense?

One thing to remember is that `Phi` has discontinuous first derivatives across element boundaries, so computing the Hessian locally on each element may not be always sufficient -- e.g. for Phi in a linear FE space on triangles or tets, the Hessian will be 0. Therefore, one may need to reconstruct a global approximation of the Hessian first to take into account the jumps of the first derivatives of `Phi` across faces.

**Comment by tangqi** [comment]
Thanks @v-dobrev for the suggestion. It makes sense and I am working on that.

I have one question on your point of reconstructing Hessian. I am working on a model that needs a lot second-order derivative terms in my nonlinear residual, for instance,
\partial_{RZ}\Psi ( (\partial_R \Psi)^2 - (\partial_Z \Psi)^2 ) + \partial_R \Psi \partial_Z \Psi(  \partial_{ZZ}\Psi-  \partial_{RR}\Psi)
I am using higher order bases, so none of them will be 0 but the direct evaluation of Hessian will have kink or discontinuity along the element interface. 

In such a case, will you suggest to reconstruct Hessian first and then evaluate the nonlinear term in the residual? Is there any other approach to evaluate this nonlinear term? Unfortunately, I cannot really do integration by parts.

**Comment by v-dobrev** [comment]
> In such a case, will you suggest to reconstruct Hessian first and then evaluate the nonlinear term in the residual?

Generally, I expect that reconstructing a Hessian approximation will be more accurate, however there may be cases where it is not essential.

> Is there any other approach to evaluate this nonlinear term?

The only thing that comes to mind is if the term you have can be simplified by introducing some auxiliary field derived from \Psi. However, I suspect you would have done that already if it were possible.

**Comment by tangqi** [comment]
Thanks a lot. @v-dobrev It was very helpful. 

I got this working in post processing. I will open a new issue if I run into more questions regarding the new model.
