### ISSUE TITLE
Read a PETSc DMPlex as a mesh for MFEM

### ISSUE THREAD

**Issue by tbridel** [mfem/mfem#2772]
Dear all,

I am in the following situation. I have a Gmsh mesh containing two domains (two physical surfaces or two physical volumes for instance). On one I wanna use finite volume and on the other finite elements. I am also using PETSc, meaning I’m reading the Gmsh mesh into a DMPlex and then splitting it into two parts , one for the FV and one for the FE. I would like to pass the FE part to MFEM to solve , say, a heat equation. 
Hence my question, can MFEM « read » a DMPlex mesh and work with it ? 

Thank you !
Thibault

**Comment by jandrej** [comment]
Hello Thibault,

while probably doable, we currently don't read `DMPlex` or any PETSc `DM` directly. What you can do is to create a "translate function" that creates an `mfem::Mesh` from a `DMPlex` object by iterating through the elements.

If you plan to use AMR, I don't think this will be a viable solution due to overhead and the vastly different concepts in `DMPlex` and `mfem::Mesh` of handling non-conforming meshes in the case of quadrilaterals and hexahedrons.

**Comment by tbridel** [comment]
Hi Julian,

Thank you for your answer.
I thought I would ask because since one can link PETSc to MFEM for the
algebra machinery, I wondered if maybe you had given a thought to linking
the DMPlex capabilities as well ! It's okay, I'll see what I can do and
I'll come back to you if I need help !

Cheers,

Thibault

Le dim. 16 janv. 2022 à 19:56, Julian Andrej ***@***.***> a
écrit :

**Comment by tzanio** [comment]
@stefanozampini, any thoughts on this?

**Comment by stefanozampini** [comment]
As @jandrej already said, writing a conversion from a cell-vertex mesh is doable and quite easy, I can give help if needed and point to the relevant DMPlex API, mostly `DMPlexGetTransitiveClosure`. There are possibly a few difficulties in handling orientations since DMPlex handles hexas a little bit differently (all normals pointing outward). For high order meshes, it is more cumbersome, as we need to handle the dof ordering.

The difficult part is to handle AMR and the mapping of the FEM fields

**Comment by stefanozampini** [comment]
@tbridel @jandrej @tzanio Forgot to mention that I already have some code in PETSc to handle` DMPLEX` viz through `glvis`. Take a look here https://gitlab.com/petsc/petsc/-/blob/main/src/dm/impls/plex/plexglvis.c#L389. This can be modified to create an `mfem::Mesh` instead of sending ASCII data through the GLVIS socket
