### ISSUE TITLE
Issue with Jacobian for 2D boundary integrator

### ISSUE THREAD

**Issue by M8kmyday** [mfem/mfem#2776]
I am doing a 2D full-wave electromagnetic eigenvalue calculation to get the complex propagation constant followed by post-processing with the eigenvectors to get the electromagnetic fields along with quantities calculated from the fields.  I am working on calculating the loss adder due to finite conductivity boundaries.  I currently brute-force integrate the fields along the boundaries and get the correct answer, but I would like to do the calculation with an MFEM integrator to get better consistency.

The previously calculated fespace_Ht_Et and grid_Ht_re gives the correct magnetic field result that computes the correct average propagated power as part of a Poynting vector calculation and the loss adder.  I'm sure the H-field is correct.  The next step is to integrate the squared magnitude of the tangential component of the H-field along the boundaries.  I have this code snip to do that for the real part (for now):

      Array<int> bdr_attr(pmesh->bdr_attributes.Max());
      bdr_attr=1;

      VectorGridFunctionCoefficient Ht_re_coef(grid_Ht_re);

      // tangential - real
      ParLinearForm lossPECt_re(fespace_Ht_Et);
      lossPECt_re.AddBoundaryIntegrator(new VectorFEBoundaryTangentLFIntegrator(Ht_re_coef),bdr_attr);
      lossPECt_re.Assemble();

      double Ht_reDotHt_re=lossPECt_re(*grid_Ht_re);

When I run the code, I get the following error at the line "lossPECt_re.Assemble();":

      Assertion failed: (height == x.Size() && width == y.Size()) is false:
       --> incompatible dimensions
       ... in function: virtual void mfem::DenseMatrix::MultTranspose(const mfem::Vector&, mfem::Vector&) const
       ... in file: linalg/densemat.cpp:220

The fundamental problem seems to be at line fem/lininteg.cpp:616, which is

      Tr.Jacobian().MultTranspose(f_loc, f_hat);

breaking on this line and printing Tr.Jacobian() yields

      Thread 1 "openEM2D" hit Breakpoint 1, mfem::VectorFEBoundaryTangentLFIntegrator::AssembleRHSElementVect (this=0x55555613a310, el=..., Tr=..., elvect=...)
      at fem/lininteg.cpp:616
      616           Tr.Jacobian().MultTranspose(f_loc, f_hat);
      (gdb) print Tr.Jacobian()
      $1 = (const mfem::DenseMatrix &) @0x555556121dd0: {<mfem::Matrix> = {<mfem::Operator> = {
      _vptr.Operator = 0x555555f5c468 <vtable for mfem::DenseMatrix+16>, height = 2, width = 1}, <No data fields>}, data = {h_ptr = 0x5555561c2820,
      capacity = 2, h_mt = mfem::MemoryType::HOST, flags = 18, static def_align_bytes = 16, static new_align_bytes = 16}}
      (gdb)

so the Jacobian is being calculated as a 2x1 matrix rather than a 2x2.  The MultTranspose then breaks and the program errors out with the error message.

**Comment by mlstowell** [comment]
Hello, @M8kmyday, 

The `VectorFEBoundaryTangentLFIntegrator` class is only designed to be used in 3D.

If your field is represented using Nedelec basis functions then the integral of the tangential components can be easily computed using the `VectorFEDomainLFIntegrator`. This works because the Nedelec basis functions corresponding to degrees of freedom on the boundary are all tangent to that boundary.

Best wishes,
Mark

**Comment by M8kmyday** [comment]
Wouldn't a domain integrator integrate over the entire 2D cross section?  I'm looking for the value just at the boundary.

**Comment by mlstowell** [comment]
The integrators don't control their domain. The domain is determined by the method used to add the integrator to the `ParLinearForm`. In this case you're using `AddBoundaryIntegerator` so it will loop over boundary elements. I see that this is a bit counterintuitive particularly since the integrator has "Domain" right there in the name. We probably need better documentation to explain this more fully.

**Comment by M8kmyday** [comment]
Ok.  I'll work on this and report back.

**Comment by M8kmyday** [comment]
Changing to:
      `lossPECt_re.AddBoundaryIntegrator(new VectorFEDomainLFIntegrator(Ht_re_coef),bdr_attr);`
I get the error:
      `MFEM abort: method is not implemented for this class
       ... in function: virtual void mfem::FiniteElement::CalcVShape(mfem::ElementTransformation&, mfem::DenseMatrix&) const
       ... in file: fem/fe.cpp:49`
The H-field is calculated using RT elements, which is supported by VectorFEDomainLFIntegrator, according to the documentation.  I switched the H-field to ND elements, and the error is eliminated, but then the H-field is visibly very incorrect.

**Comment by mlstowell** [comment]
Oh, I had assumed `H` was in ND.

RT basis functions on the 1D surface of a 2D mesh are essentially equal to the discontinuous scalar L2 basis functions and represent only the normal component of the vector field. In other words you have no information about the tangential components of an RT field on the boundary of the mesh. This is not peculiar to 2D meshes the same limitation would exist on the 2D boundary of a 3D mesh.

What you are calling `H` I would think of as `B` i.e. the magnetic flux density. Since `B` is a flux density the most natural basis functions to represent it are RT. On the other hand `H`, the magnetic field strength, is most naturally represented by ND. Of course these two vector fields typically only differ by a constant multiple so many people use them interchangeably, especially when the magnetic permeability is that of vacuum.

However, when we discretize vector fields using ND or RT, neither of which is fully continuous, we must make sacrifices. Specifically, for RT we lose accuracy in the tangential parts of the vector field at element interfaces and boundaries. Similarly for ND we lose accuracy in the normal component of the vector field at element interfaces and boundaries.

In my own applications I have developed the habit of often computing E, D, H, and B where E and H are in ND and D and B are in RT. Normally the primary field is E or H then B or D can be computed using Faraday's or Ampere's Law. Then compute the remaining fields using the constitutive laws. In this case you could probably compute H from B as H=`mu^{-1}B`. This will involve two mass matrices, one of them rectangular, and a simple solve.

**Comment by M8kmyday** [comment]
I am solving a system in E only, where E=Et+zhat Ez exp(-gamma z).  Et is in ND and Ez is in H1.  As an experiment, I switched Et to RT, but the needed CurlCurl method is not supported.  H is calculated from the solution for E, with once again, H being defined as Ht+zHat Hz exp(-gamma z).  I can do Ht in either RT or ND, but the ND solution is completely wrong.  Here is an example computed field that is correct with Et in ND and Ht in NT:
![odd mode vector Et (white) Ht (black) with Et background](https://user-images.githubusercontent.com/90462987/150046069-9267442b-6c0a-4713-9464-4279b0ce22c8.png
Et is in white and Ht is in black.  The background is Et.  The ND field at the boundary is normal to the perfect electric conductor (PEC) surface, and the RT field is parallel to the PEC.  For the loss adder, I need to integrate Ht at the boundary, but I get the "method is not implemented" error.  Right now, I am just manually integrating Ht along the boundary since it is tangential there, anyway.

**Comment by mlstowell** [comment]
Hi, @M8kmyday, 

That image looks reasonable to me. By the way, I'm not familiar with the term "loss adder".

It seems that you will need Ht represented in the ND basis. You say that you have tried this and the result is completely wrong. Perhaps we can fix it. We should be able to compute H from E using Faraday's law: `Curl Ez = i omega mu Ht`. 
The curl operator would use the `MixedScalarWeakCurlIntegrator` with a coefficient equal to 1. The operator on the right hand side would be the `VectorFEMassIntegrator` with coefficient mu or omega*mu. Is this similar to what you tried?

Best wishes,
Mark

**Comment by M8kmyday** [comment]
Since I have solved solutions for Et and Ez, I am using linear operators to calculate the H components from the E components.  For Ez, the solution is stored in grid_Ez_im_iom, where the Ez field component has already been multiplied by 1/(omega mu).  Here is one part of it:
      fec_Ht_Ez=new RT_FECollection(mesh_order-1,pmesh->Dimension());
      fespace_Ht_Ez=new ParFiniteElementSpace(pmesh,fec_Ht_Ez);

      ParDiscreteLinearOperator Ht_Ez(fespace_Ez,fespace_Ht_Ez);
      Ht_Ez.AddDomainInterpolator(new CurlInterpolator());
      Ht_Ez.Assemble();
      Ht_Ez.Finalize();

      ParGridFunction grid_Ht_Ez_re(fespace_Ht_Ez);
      Ht_Ez.Mult(grid_Ez_im_iom,grid_Ht_Ez_re);

      VectorGridFunctionCoefficient Ht_Ez_re_coef(&grid_Ht_Ez_re);
I end up having to do real and imaginary parts plus add in the components from Et.  In transmission line problems, Ez and Hz tend towards zero, so the larger contribution is from Et, where the math has Ht calculated as a scaled version of zHat x Et.  I also use linear operators for the zHat x Et calculation.

The loss adder is the loss due to finite conductivity boundaries.  It is common in microwave engineering to solve with PEC boundaries (or PMC, as needed) then integrate the tangential H-field over the PEC boundaries and multiply the magnitude squared times the surface resistance to get the added loss.  This can then be added to the directly computed loss from dielectric losses.  Doing things this way is plenty accurate almost all the time, and the eigenvalue problem is a standard Ax=kBx form.  To solve directly solve with impedance boundaries pushes to a polynomial eigenvalue problem.  I might put that in at some point since SLEPc has a solver for that.

**Comment by M8kmyday** [comment]
Switching to ND for the H-field produces the incorrect results due to my custom cross-product interpolator.  MFEM's VectorCrossProductInterpolator is restricted to 3D, but I have a 2D problem where I need to calculate zHat x Et, where Et is a 2D vector field in x-y, resulting in a new 2D vector field in x-y.  The custom interpolator is

      class zHatCrossProduct2D : public DiscreteInterpolator
      {
         public:
         zHatCrossProduct2D() {}
         void AssembleElementMatrix2(const FiniteElement &nd_fe,
                                     const FiniteElement &rt_fe,
                                     ElementTransformation &Trans,
                                     DenseMatrix &elmat);
      };
      
      void zHatCrossProduct2D::AssembleElementMatrix2(
         const FiniteElement &dom_fe,
         const FiniteElement &ran_fe,
         ElementTransformation &Trans,
         DenseMatrix &elmat)
      {
         // Vector coefficient product with vector shape functions
         struct VCrossVShapeCoefficient : public MatrixCoefficient
         {
            const FiniteElement &fe;
            DenseMatrix vshape;
      
            VCrossVShapeCoefficient(const FiniteElement &fe_, int dim)
               : MatrixCoefficient(fe_.GetDof(),dim), fe(fe_),
                 vshape(height, width)
            {
               MFEM_ASSERT(width == 2, "");
            }
      
            virtual void Eval(DenseMatrix &M, ElementTransformation &T,
                              const IntegrationPoint &ip)
            {
               M.SetSize(height, width);
               fe.CalcPhysVShape(T, vshape);
               for (int k = 0; k < height; k++)
               {
      //            M(k,0) = -vshape(k,1);
      //            M(k,1) =  vshape(k,0);
      //
      //            keep original orientation for identity operation
                    M(k,0) = vshape(k,0);
                    M(k,1) = vshape(k,1);
               }
            }
         };

         int dim=2;
         VCrossVShapeCoefficient dom_shape_coeff(dom_fe,dim);

         if (ran_fe.GetRangeType() == FiniteElement::SCALAR)
         {
            // ToDo - VQ has been taken out, so this line needs to be fixed up.
            // However, a SCALAR result would never show up in this code, so it should
            // not be a problem to just leave it.
            //elmat.SetSize(ran_fe.GetDof()*VQ->GetVDim(),dom_fe.GetDof());
         }
         else
         {
            elmat.SetSize(ran_fe.GetDof(),dom_fe.GetDof());
         }

         Vector elmat_as_vec(elmat.Data(), elmat.Height()*elmat.Width());
      
         ran_fe.ProjectMatrixCoefficient(dom_shape_coeff, Trans, elmat_as_vec);
      }

For a simple test, I have

      ParDiscreteLinearOperator Ht_Et(fespace_Et, fespace_Ht_Et);
      Ht_Et.AddDomainInterpolator(new zHatCrossProduct2D());
      Ht_Et.Assemble();
      Ht_Et.Finalize();
      grid_Ht_re=new ParGridFunction(fespace_Ht_Et);
      Ht_Et.Mult(*grid_Et_re,*grid_Ht_re);

where grid_Et_re is previously calculated and verified against analytical test cases.  fespace_Et and fespace_Ht_Et are ND.

In one example, Et looks like this:
![Screenshot from 2022-01-28 09-48-34](https://user-images.githubusercontent.com/90462987/151580747-34406cf3-3584-4f6b-a0cd-ddc30ca99b8f.png)
Calculating grid_Ht_re using the identity operation just under the comment line "keep original orientation for identity operation", I get the same result:
![Screenshot from 2022-01-28 09-50-55](https://user-images.githubusercontent.com/90462987/151581065-3bbb60d1-36b3-4899-81d9-92b22b3fba1e.png)
When I use the element swap above the commented line "keep original orientation for identity operation", I get this result:
![Screenshot from 2022-01-28 09-48-52](https://user-images.githubusercontent.com/90462987/151581213-67100ebe-6ade-4a65-8788-0c3c357d5017.png)
According to https://mfem.org/lininterp/, where 
![Screenshot from 2022-01-28 10-09-26](https://user-images.githubusercontent.com/90462987/151581447-745666e5-4466-47fa-bd95-990b7c9462db.png)
I would expect that an ND to ND interpolation would work, but something is going wrong [either my understanding or my code].

Can you comment?

**Comment by mlstowell** [comment]
Hi, @M8kmyday, 

Unfortunately, ND to ND interpolation will not work for the zHat cross product in 2D. The trouble is that ND degrees of freedom on the edges of the mesh cannot be uniquely determined. In the original ND field we have a unique vector component aligned with the edge but the perpendicular component of the field is not unique. The value of the perpendicular part of the field is some average of the perpendicular components from the two neighboring elements. Clearly the perpendicular component is the only relevant piece when we compute the zHat cross product. The problem is that interpolators are not capable of performing such an average. They merely interpolate values within individual elements.

You have two methods to choose from but each of them will involve the use of `BilinearForms` and an additional mass matrix solve. The solve is needed to accomplish the averaging that is required to handle the discontinues of the vector fields across element interfaces. Choice number 1 is to compute B in RT using interpolators and then convert B in RT to H in ND using bilinear forms to find the GH that best matches your B (feel free to think of this as H in RT but I find it easier to keep things clear in my head if I call it B). The second choice is to use bilinear forms to directly compute H in ND from E in ND.

Rather than using the `zHatCrossProduct2D` to map from ND to ND you can use `VectorFEMassIntegrator` with a 2x2 matrix coefficient. The idea is to build a pair of bilinear forms. The first might be called `m` and it would be built with `VectorFEMassIntegrator` as a domain integrator and using no coefficient. The second might be called `z` and it would be build with `VectorFEMassIntegrator` as a domain integrator and using {{0,-1},{1,0}} as a `MatrixConstantCoefficient`. With these you could compute `v=z x Et` as `v = m^{-1}*z*Et`.

If you have `Bt` in RT and you want to compute `Ht` in ND. You can use one bilinear form (call it `m`) and one mixed bilinear form (call it `r` since it's rectangular). Each of them would use the `VectorFEMassIntegrator`. Then compute `Ht` as `Ht = m^{-1}*r*Bt`.

These mass matrix solves using `m` are typically very inexpensive. Using PCG with a diagonal scaling preconditioner typically solves in about 20 iterations (perhaps a little more or less based on the number of nonzeros per row in `m`).

Best wishes,
Mark

**Comment by M8kmyday** [comment]
Hi Mark,

Thanks for the background, and I was afraid that that is what the answer would be.

This will take quite a while to implement.  Because I am solving a 3D problem on a 2D space (i.e. guided waves), I will need to set this up for two sets of contributions, one from Et and one from Ez.  Since all this is complex, I'll need to set up the real and imaginary parts, save the setups to files, import the files to a C program, solve in complex PETSc in C, save to files, and finally import back into the real-valued MFEM framework.  This will be about 2X as much work as it was to solve the original complex eigenvalue problem.  I just mention this to show how the limited support for complex creates a lot of extra coding for someone working in the frequency domain.

In the end, it will be worth it.  As an example, for a partially-filled rectangular waveguide example at 12 GHz, I get a propagation constant of beta/ko=1.12289737254 from MFEM FEM vs. beta/ko=1.12289737253 from the analytical solution [with a numerical solution for a small transcendental equation] for an error of 6.99969e-12.  This may be as good as it can get when using double precision.
