### ISSUE TITLE
Question about the (ess_tdof_list,x,b,a,X,B,A)->size() meanings,what happen to the myid=0 in MPI using.

### ISSUE THREAD

**Issue by xigetongkuaizao** [mfem/mfem#2778]
I am confused about the matrix size of( a,b,x A,B,X AND the ess_tdof_list),especially running with the MPI. So I coding in using: 
code :  

```c++
pcg->SetPreconditioner(*prec);  //from the ex4p.cpp line 251
pcg->Mult(B, X);
cout << "ess_tdof_list=------" << "++" << ess_tdof_list.Size() << "---myid---" << myid << endl;
MPI_Barrier(MPI_COMM_WORLD);
cout << "x,b a,a=------" << "++" << x.Size() << "++" << b->Size() << "++" << a->NumRows() << "++" << a->NumCols() << "---myid---" << myid << endl;
MPI_Barrier(MPI_COMM_WORLD);
cout << "X,B A,A=------" << "++" << X.Size() << "++" << B.Size() << "++" << A->Height() << "++" << A->Width() << "---myid---" << myid << endl;
MPI_Barrier(MPI_COMM_WORLD);
```

mpiexec -n 4 ex4p

The result:
```console
ess_tdof_list=------++72---myid---0
ess_tdof_list=------++72---myid---1
ess_tdof_list=------++72---myid---2
ess_tdof_list=------++104---myid---3
x,b a,a=------++2568++2568++2568++2568---myid---0
x,b a,a=------++2636++2636++2636++2636---myid---1
x,b a,a=------++2700++2700++2700++2700---myid---2
x,b a,a=------++2644++2644++2644++2644---myid---3
X,B A,A=------++2600++2600++2600++2600---myid---1
X,B A,A=------++2652++2652++2652++2652---myid---2
X,B A,A=------++2580++2580++2580++2580---myid---3
X,B A,A=------++2568++2568++2568++2568---myid---0
```

Questing:   why  (X,B A,A).size()=(x,b a,a).size()=2568 in the MPI id=0,while the other id(1,2,3) the size() is different???

**Comment by tzanio** [comment]
This is due to the fact that some of the parallel degrees of freedom are shared between processor, and in MFEM such shared  objects are assigned to the lowest MPI rank.

Consider for example this portion of the image in https://mfem.org/howto/assembly_levels (see also https://mfem.org/pri-dual-vec/#true-degree-of-freedom-vectors):

![tdofs](https://user-images.githubusercontent.com/1278247/150704008-8d269f72-090c-4979-905e-211591f5b7c5.png)

While the finite element objects `x`, `b` and `a` correspond to the 4 meshes on the right which are completely disjoint, the linear algebra objects `X`, `B` and `A` correspond to the *true* degrees of freedom on the left where MPI rank 0 is in lower left and MPI rank 3 is in the upper right.

Since a shared degrees of freedom is assigned to the MPI tasks with lowest rank (that contain it), MPI rank 0 ends up with more true dofs than MPI rank 3.

Hope this helps.

Tzanio
