### ISSUE TITLE
Duplicated information in output file (ParaView)

### ISSUE THREAD

**Issue by barreracruz** [mfem/mfem#2906]
I use ParaView to visualize my results (`ParaViewDataCollection`s). I have noticed that the output mesh is conformed of element/cell each with unique set of nodes, i.e., facets of contiguous elements will not share their nodes, generating duplicated information. I know I can use the `Clean To Grid` filter to fix this; however, it would be nice if MFEM could somehow circumvent this issue. The unnecessary duplication of data increases the size of an output file significantly for big problems and slows down loading and operating on them.

**Comment by pazner** [comment]
Hello @barreracruz,

MFEM doesn't currently support outputting VTU without duplicating the nodes on element interfaces. Because we support spaces that are more general than just continuous FEM (Nédélec, Raviart-Thomas, DG) on the same mesh, it is generally useful for MFEM to duplicate these nodes.

Of course one could imagine a special case to avoid duplication when only H1 fields are being saved, but this is not implemented.

You can achieve significantly smaller file sizes by calling `ParaViewDataCollection::SetDataFormat` with `VTKFormat::BINARY32` (for most visualization purposes Float32 will be fine) and `ParaViewDataCollection::SetCompression` to enable compression (MFEM will need to be compiled with zlib support). In my experience this is enough to compensate for the duplication.

**Comment by barreracruz** [comment]
Thank you, @pazner

**Comment by benzwick** [comment]
See also #1757
