### ISSUE TITLE
Ability to compare results from data structures calculated with differing numbers of MPI ranks

### ISSUE THREAD

**Issue by tepperly** [mfem/mfem#2937]
This is similar to #1155 , but because we're trying to do this in a general software library, we don't have access to the original serial mesh or its partitioning.

### Introduction - Motivating scenario

We're using MFEM data structures in a nonlinear programming optimization framework called LiDO. In particular, we're using ParGridFunction and ParLinearForm in the calculation of objective function and constraint functions values and their derivatives. The particular problem I am working with does not have any MFEM linear solves. It's just doing integrations over quantities on the mesh. In the context of the nonlinear programming solution, the convergence path and number of iterations changes dramatically as the number of MPI ranks increases while keeping the MFEM mesh size constant. The degree of the changes suggests that the value and derivative values being calculated are changing as the number of MPI ranks changes.

I suspect that the problem is in our use of MFEM rather than MFEM itself. However, debugging this situation would be much easier if I could compare true DOF values from ParGridFunction and ParLinearForm's generated with differing numbers of MPI ranks in a semantically consistent manner. By semantically consistent, I mean that we're comparing the same global DOF element between data in a 1-rank and an n-rank instance of a ParGridFunction/ParLinearForm.

Because we're doing this in a general purpose optimization package that needs to support arbitrary numerical models, we don't have access to all the arguments used in the creation of the ParGridFunction/ParLinearForm such as is required by the approach mentioned in #1155. Ideally, we're looking for a solution that works from the information available inside a ParGridFunction/ParLinearForm.

### Desired feature

There are many ways that our feature request could be implemented, and by suggesting some, I mean to illustrate rather than limit the possibilities. Ultimately, I am looking for a way to map the true DOF data from a ParGridFunction/ParLinearForm into a form where the ordering of DOF values is independent of the number of MPI ranks and the mesh partitioning. For example the third DOF would refer to the same DOF regardless of the size of the MPI communicator being used and how the mesh was partitioned onto the communicator.

Here are some examples of how this feature could be implemented to meet our needs:

- Provide a function/method to output a ParGridFunction/ParLinearForm's to DOFs to a binary or text file using an ordering that's independent of communicator size/graph partitioning
- Implement a function/method to convert a ParGridFunction/ParLinearForm to their serial counterparts GridFunction/LinearForm
- Implement a function/method to convert a ParGridFunction/ParLinearForm defined on one communicator to a corresponding data structure on a sub communicator.
- Get the true DOF's from a ParGridFunction/ParLinearForm as a hypre vector and using an understanding of MFEM's internals order it appropriately to achieve the objective

### Benefits of the feature

I think the feature would be beneficial for debugging. It would also be useful for writing continuous integration tests. For example, one could write a test to verify that a solutions to a given problem are consistent within some tolerance regardless of the number of ranks being used. If the approach involved generating an HDF5, one could potentially save a file from a 2-rank job and use it as the input for a 8-rank job.

**Comment by tzanio** [comment]
Hi @tepperly,

Thank you for bringing this to our attention and for the nice description.

We discussed this internally and folks on the team have several ideas how this could be done.

I will list a few of them below, but we will also be interested in having a technical meeting to discuss this in more detail.

1️⃣  If the goal is to detect incorrect runs, we feel that a simple functional like the `l1`-norm of the degrees of freedom should be sufficient to flag bad results. This is simple to compute, and unless the bug is very subtle, the difference between correct and incorrect run should be significant.

2️⃣  One can user `findpts` to sample the function in fixed set of points and compare the results. This may be a bit expensive, but maybe could be done fully in parallel.

3️⃣  The values at degrees of freedom can be saved as a point cloud with the dof coordinates, and then one can compare the two point clouds. There could be potential round-off issues with this.

What do you think?

Tzanio

**Comment by goxberry** [comment]
To add to the use cases @tepperly mentioned, I work on a programmatic project that performs this sort of "permutation to canonical form" on the equivalent of a `GridFunction` for output from Diablo. In this scenario, we typically take output from an 8-rank or 32-rank solution, merge the outputs onto a single rank, and construct the permutation from data exposed by Diablo, and permute the `GridFunction` accordingly. We have to do this because we need to pass our `GridFunction` to tools we don't control and the interfaces for these tools require a particular ordering, e.g., legacy modal analysis tools, some CFD solvers, comparisons to experimental data.

Typically, this ordering is the equivalent of `mfem::Ordering::byVDIM` in ascending order of nodes, where the node numbering comes from the finite element mesh passed into Diablo. In these scenarios, we don't refine the mesh at all within Diablo. We don't care if the reordering and merging is expensive -- we actually do this ourselves in Python at the moment -- because we use these permuted results many times in downstream post-processing, so the cost of reordering is amortized over many post-processing analyses. Typical problems for us involve no more than 10 million dofs, and run on no more than 256-ranks, but we do all of the post-processing in serial.

We're not computing errors, so option 1 does not apply, though I agree that an `l1` error would be really useful for the sorts of CI comparisons @tepperly discusses. Approaches like 2 and 3 would be useful for this programmatic project when it transitions from using Diablo to using Smith, though the time horizon for that transition is probably in the 3-5 year range at the earliest. If approaches like 2 and 3 are nonstarters, or if this functionality weren't included in MFEM, we'd probably write it ourselves again, but given the close relationship to @tepperly's request, this use case seemed worth mentioning.

**Comment by tepperly** [comment]
Okay to do option 1, I think I would need to follow a process like this:

1. Run my code on one MPI rank and save the result to a file.
2. Run my code on _n_ MPI ranks and load the ParGridFunction results from step one into the ParGridFunction on _n_ MPI ranks.
3. Compare the two ParGridFunctions that are both instantiated on the same MPI communicator and get a l1 norm.

Is there currently a way to do steps one and two (i.e., write a file for a ParGridFunction on 1 rank that's read correctly into a ParGridFunction on n-ranks)?

Alternatively, I don't necessarily need to use a file if there is an in-core way to transfer data to/from a ParGridFunction on one rank to a ParGridFunction on n-ranks.

I am unfamiliar with findpts. FWIW, I've implemented the approach you suggested in email. It's a complete serial bottleneck, but it basically proved that the problem was elsewhere. It turns out in parallel different ranks were evaluating MFEM integrals in different orders. E.g., rank 0 was evaluating constraint 1,2,3,4, and rank 1 was evaluating 3,1,2,4. Oddly enough, it ran but gave incorrect values.

**Comment by tzanio** [comment]
Thanks @goxberry and @tepperly. Lets follow-up in a technical meeting.

**Comment by tepperly** [comment]
I think they plan to work on this.

**Comment by tzanio** [comment]
See https://github.com/mfem/mfem/pull/3325
