### ISSUE TITLE
Where to look for dof numbering for high-order L2 on tetrahedrons?

### ISSUE THREAD

**Issue by stefanozampini** [mfem/mfem#2941]
We would like to visualize high order meshes from PETSc using GLVIS. To do that, we rely on L2 spaces. Highorder hexahedral cells viz works fine; however, we have issues for Tetrahedral meshes. Can someone tell me how cell dofs are ordered in a L2 Tetrahedron?

PETSc discussions here:
https://gitlab.com/petsc/petsc/-/issues/1117
https://gitlab.com/petsc/petsc/-/merge_requests/5037

**Comment by tzanio** [comment]
Is this helpful: https://github.com/mfem/mfem/blob/master/fem/fe/fe_l2.cpp#L484-L490

**Comment by stefanozampini** [comment]
Thanks @tzanio I was able to get a solution by looking at your high order gmsh reader. BTW, is it tested for third order tetrahedra https://github.com/mfem/mfem/blob/master/mesh/mesh_readers.cpp#L1829? The ordering seems fishy and did not work for me.

**Comment by tzanio** [comment]
> BTW, is it tested for third order tetrahedra https://github.com/mfem/mfem/blob/master/mesh/mesh_readers.cpp#L1829? The ordering seems fishy and did not work for me.

@mlstowell, if I recall correctly you added the code above. Can you answer @stefanozampini, if that's the case?

**Comment by mlstowell** [comment]
Hello, @stefanozampini,
The Gmsh node ordering [documentation](https://gmsh.info/doc/texinfo/gmsh.html#Node-ordering) is a bit ambiguous above second order. Also, I don't think we have any unit tests which cover this. However, I did create a simple single tetrahedron mesh at third order and run it through a modified version of our `test_get_value` unit test. This is hardly exhaustive but it did pass the test.

I'd be happy to look more closely if that would be useful to you.

Best wishes,
Mark

**Comment by v-dobrev** [comment]
Hi @stefanozampini,

I'm reading https://gitlab.com/petsc/petsc/-/issues/1117 and I'm not sure if the MFEM node/dof ordering for tets question is still outstanding.

Let me try to clarify: the ordering is essentially "lexicographical" with simple node coordinate transformation to ensure symmetry of the nodes when the "open" point distribution (`op` in the code) is not uniform -- this "stretching" is given by the weight `w` here: https://github.com/mfem/mfem/blob/1d0396339788b48d2e8dba84bfcfa748d4bbe69a/fem/fe/fe_l2.cpp#L488-L489

Basically, when the 1D "open" points `op` are uniform, i.e. `op[i]=double(i)/p, i=0,...,p`, then `w = 1` and there is no "stretching" and one recovers the uniform points in the tet -- our reference tet is `(x,y,z): x >= 0, y >= 0, z >= 0, 1-x-y-z >= 0`.

It is very easy to change the 1D "open" points you want to send to GLVis: this is encoded in the FE collection name:
* `L2_3D_P3` uses the 1D Gauss-Legendre points for `op`
* `L2_T1_3D_P3` uses the 1D Gauss-Lobatto points for `op` (in this case this is also the distribution of the nodes/dofs on the edges)
* `L2_T?_3D_P3` uses the basis defined by the number `?` as given by this enum: https://github.com/mfem/mfem/blob/1d0396339788b48d2e8dba84bfcfa748d4bbe69a/fem/fe/fe_base.hpp#L27-L41 and their 1D point distribution defined by this function: https://github.com/mfem/mfem/blob/1d0396339788b48d2e8dba84bfcfa748d4bbe69a/fem/fe/fe_base.hpp#L58-L75

For visualization purposes, in order to capture continuity across element boundaries, it is best to use a "closed" set of points like Gauss-Lobatto.
