### ISSUE TITLE
L2 projection between two spaces

### ISSUE THREAD

**Issue by e-aranda** [mfem/mfem#3016]
Hello,
this is my situation: I have two meshes Th1 and Th2, where Th2 is obtained as a submesh of Th1 (for example, using trimmer miniapp).
I have some gridfunction in a L2 space of Th2, and I would like to consider the extension, by 0, of this function to the L2 space of Th1. Any hints of how could I do it?

**Comment by vladotomov** [comment]
If somehow you know the map between the element numbers of the two meshes, you can just iterate in Th1 and set the DOF values from Th2.

If Th2 is always a submesh of Th1, you can compute the map simply by comparing physical coordinates of the element centers, e.g., with `Mesh::GetElementCenter()`.

If the correspondence is not known, you can interpolate in physical space with `miniapps/gslib/field-interp.cpp`. You would interpolate all DOF locations from Th1, and get `default_interp_value' (see `fem/gslib.hpp`) for the ones not found in Th2.

**Comment by e-aranda** [comment]
Ok, thanks. So I have to build "at hand". But, what if my meshes are parallel?

**Comment by vladotomov** [comment]
If Th1 and Th2 have different parallel partitions, you should probably use `gslib`. Otherwise you'll have to communicate the maps yourself.

The `gslib` methods work in parallel, although our interpolation example is serial. You can get an idea what modifications are needed by looking at `miniapps/gslib/pfindpts.cpp`.
