### ISSUE TITLE
Output/Probe matrix

### ISSUE THREAD

**Issue by jandrej** [mfem/mfem#304]
I am looking for a method on how to construct an output matrix such that
```
y = C u
```
where C is the output matrix and u is the state vector (solution of a linear system). C should describe a mapping from geometric points on the domain (not necessarily gridpoints) to function values y. So C is num_probes x num_states. Is there a convenient method on how to construct such an operator?

We don't necessarily need the C matrix, rather something that computes y from u.

In other words we need a measurement of a function at a geometric location. (In our case this is also a vector function, namely deformation in x y z).

My first idea would be to inherit from GridFunction (or use an existing method?) to hand over an array with coordinates and compute y through that. Since i cannot guarantee that the coordinates are located at quadrature points, i would have to interpolate somehow, thats where i am unsure on how to approach that.

Appreciate any help

**Comment by juan42** [comment]
What i think i need is a "consistent interpolation".
Pseudocode ->
```
GridFunction gf
gf.evaluate_at(x, y)
-> find the element in which (x,y) lies
  -> use the polynomial basis to evaluate its value
```
It looks like GridFunction::GetValue/s implements the second part, but i still need to find the mapping from (x,y) to the cell.

Maybe this makes my problem more clear.

**Comment by tzanio** [comment]
This is not 100% robust, but you can use the `FindPoints` method of `Mesh` or `ParMesh`:

https://github.com/mfem/mfem/blob/ef6c759a4ef3d235abacc3153d9cfd92ced7114c/mesh/mesh.hpp#L1093-L1110

This is a recent addition via https://github.com/mfem/mfem/pull/240 and https://github.com/mfem/mfem/pull/265.

**Comment by juan42** [comment]
Thanks @tzanio !
This works in combination with GridFunction::GetValue. I attached a small code snippet which demonstrates what i did. If this works with a vector valued problem on Monday i will close the issue.
```
   Vector point(2);
   point(0) = 0.5;
   point(1) = 0.5;
   DenseMatrix points(dim, 1);
   points.SetCol(0, point);

   Array<int> elem_ids;
   Array<IntegrationPoint> ips;
   
   mesh->FindPoints(points, elem_ids, ips);
   cout << x.GetValue(elem_ids[0], ips[0]) << endl;
```

**Comment by juan42** [comment]
Works fine for our cases. Thanks again!

**Comment by iDiara** [comment]
Hello @tzanio!
I'd like to understand the reason FindPoints is not 100% reliable? Even if i am locating one point a time?
Also, if it happens that the point is located outside the mesh, can one apply the method ProjectPoint(...) from Geometry class? 
I mean is the idex returned corresponds to the element whose center is the nearest w.r.t the point being located?
Thank you
zaq

**Comment by tzanio** [comment]
We have a more robust option now, @kmittal2 can provide more details.

**Comment by kmittal2** [comment]
Hi @iDiara, we have added support for high-order interpolation using the `gslib` library: see the serial and parallel version of the [findpts](https://github.com/mfem/mfem/blob/master/miniapps/gslib/findpts.cpp) miniapps. Using `FindPointsGSLIB` class, we can interpolate a desired grid function at a given set of points in physical space. For the points that are located outside the domain, `FindPointsGSLIB` tries to return the interpolated grid function at the closest point in the domain. Take a look at these miniapps and let me know if you have any questions.

**Comment by iDiara** [comment]
Thank you @tzanio and @kmittal2!
I went through the miniapps and like it.
The reason I want to use the method FindPoints is because
given the fact i am looking only one point a time, it would not be necessary 
to call the whole gslib for that it the local method can do the job. But because the latter is 
not that reliable (and i would like to know why), i will go with the findpointsGSLIB.

**Comment by iDiara** [comment]
@kmittal2,
I have one question. Because I am rather interested in simplicial meshes,
how the findpointGSLIB works with them? I mean, if the mesh presents some strong curves,
would the method be able to precisely locate the sought point? 
Just to be sure i understand the technique used here, if the returned id is zero, we can be sure the point is really
outside the computational domain, right? and there is no way to track it back into the mesh?
I am trying to explain what i wanna do with the method. In fact, 
I should start with an initial point that is being inside the domain
but throughout the process, it might be found outside at some point. So, when the findPointsGSLIB assign 0 value as interpolation of the field, the point would be lost, right?

**Comment by kmittal2** [comment]
Hi @iDiara,

Yes, `findpts` can handle curvilinear meshes.
For your problem, I would recommend first using the method `FindPointsGSLIB::FindPoints(Vector xyz)` to find the location of the point. Then use `FindPointsGSLIB::GetCode` to get the `code` returned by `findpts`. `code = 1` means the point was found inside an element, and `code=2` represents the point was found on the border. For `code=2`, you can check the returned `FindPointsGSLIB::GetDist` value which represents the distance between the actual point and the found point on the mesh. If this `distance` is finite, that means the point was outside the domain but within a tolerance that `findpts` was able to find it. If the `distance` is machine precision, that means the point was located on the edge/face of an element. If `code=2`, the point was far enough outside the domain that `findpts` could not find it.

Hopefully this clarifies your questions.

Ketan

**Comment by iDiara** [comment]
Yes, it does and thank you @kmittal2!
And i went through these details in your implementation of the method.
I think things are clear now. In the setup step of the method, for the field-diff miniapp, there is the code
```  
// Mesh bounding box.
   Vector pos_min, pos_max;
   MFEM_VERIFY(mesh_poly_deg > 0, "The order of the mesh must be positive.");
   mesh_1.GetBoundingBox(pos_min, pos_max, mesh_poly_deg);
   cout << "Generating equidistant points for:\n"
          << "  x in [" << pos_min(0) << ", " << pos_max(0) << "]\n"
          << "  y in [" << pos_min(1) << ", " << pos_max(1) << "]\n";
   if (dim == 3)
   {
      cout << "z in [" << pos_min(2) << ", " << pos_max(2) << "]\n";
   }
```
and based on this, the library will make a new mesh that cover the actual mesh, 
in order to make sure the sought point(s) will be surely captured, right?

Thank you for your help.

**Comment by kmittal2** [comment]
Hi @iDiara,

No, the above snippet of code that you shared does not generate a new mesh. 
We just use the bounding box information to generate a set of points within the bounding box (stored in Vector `vxyz` in `findpts.cpp`) that we can then find using `FindPointsGSLIB`. This is done for the purpose of setting up an example.

Ketan

**Comment by acfisher** [comment]
For the meantime put it in this branch of the web repo:
https://github.com/mfem/web/tree/searchable-articles/src/howto
Examples can be found in that folder.

@kmittal2 can you handle this?
