### ISSUE TITLE
GetGeometricFactors might return stale data

### ISSUE THREAD

**Issue by jandrej** [mfem/mfem#3042]
documentation should be updated to reflect that `GetGeometricFactors` may not actually return accurate information for the current mesh state

**Comment by samuelpmishLLNL** [comment]
here's a small reproducer of the issue:

```cpp
#include "mfem.hpp"

int main() {

  constexpr auto flags = mfem::GeometricFactors::COORDINATES | mfem::GeometricFactors::JACOBIANS;
  const mfem::IntegrationRule& ir = mfem::IntRules.Get(mfem::Geometry::Type::SQUARE, 3);

  mfem::Mesh mesh = mfem::Mesh::MakeCartesian2D(1, 1, mfem::Element::Type::QUADRILATERAL);

  {
    auto geom = mesh.GetGeometricFactors(ir, flags);
    std::cout << "geometric factors from original mesh: " << std::endl;
    for (int i = 0; i < geom->X.Size(); i++) {
      std::cout << geom->X[i] << " ";
    }
    std::cout << std::endl;
  }

  mfem::VectorFunctionCoefficient some_deformation(2, [](const mfem::Vector& x_old, mfem::Vector& x_new) {
    x_new[0] = 1.1 * x_old[0];
    x_new[1] = x_old[1];
  });

  mesh.Transform(some_deformation);

  {
    auto geom = mesh.GetGeometricFactors(ir, flags);
    std::cout << "geometric factors after transforming mesh: " << std::endl;
    for (int i = 0; i < geom->X.Size(); i++) {
      std::cout << geom->X[i] << " ";
    }
    std::cout << std::endl;
  }

  mesh.DeleteGeometricFactors();

  {
    auto geom = mesh.GetGeometricFactors(ir, flags);
    std::cout << "geometric factors after transforming mesh AND deleting geometric factors: " << std::endl;
    for (int i = 0; i < geom->X.Size(); i++) {
      std::cout << geom->X[i] << " ";
    }
    std::cout << std::endl;
  }

}

/*
output: 
$ ./mfem_mesh_geometric_factors 
geometric factors from original mesh: 
0.211325 0.788675 0.211325 0.788675 0.211325 0.211325 0.788675 0.788675 
geometric factors after transforming mesh: 
0.211325 0.788675 0.211325 0.788675 0.211325 0.211325 0.788675 0.788675 
geometric factors after transforming mesh AND deleting geometric factors: 
0.232457 0.867543 0.232457 0.867543 0.211325 0.211325 0.788675 0.788675
*/
```

notably: if you distort the mesh and then ask for the geometric factors, `GetGeometricFactor`'s attempt to memoize ends up returning old data.

The expected behavior is: calls to `mfem::Mesh::GetGeometricFactors(...)` should return information that is consistent with the current state of the mesh.

**Comment by mlstowell** [comment]
Would it be acceptable to call `DeleteGeometricFactors` from within `Transform`?

Clearly we also need a note in the documentation to remind users to call `DeleteGeometricFactors` if they are adjusting the geometry of the elements by some other means.

**Comment by samuelpmishLLNL** [comment]
> Would it be acceptable to call DeleteGeometricFactors from within Transform?

I think this is a necessary change.

> Clearly we also need a note in the documentation to remind users to call DeleteGeometricFactors if they are adjusting the geometry of the elements by some other means.

Improving the documentation is also helpful, since having undocumented requirements like this is dangerous.

----------

Initially, I had hoped that we might fix the flawed implementation of `mfem::Mesh::GetGeometricFactors` so that it would just always return the right answers, but it seems like that might be impossible. Functions like `mfem::Mesh::GetNodes()` that expose the mesh's internal data representation prevent us from detecting if a user deforms the mesh, so there's no good way to automatically invalidate the cache of previously-computed geometric factors.

Now, I find myself leaning toward trying to deprecate `mfem::Mesh::GetGeometricFactors()` altogether, since it's confusing and dangerous to provide a getter method that can return incorrect output. Furthermore, `mfem::Mesh::GetGeometricFactors()` is really just an alias for the constructor of `mfem::GeometricFactors` (which hopefully always returns the correct output), so removing it would decrease the complexity of `mfem::Mesh` with no real loss of functionality.

**Comment by v-dobrev** [comment]
We should document (in the doxygen docs for `GetGeometricFactors` and `GetFaceGeometricFactors`) the need to call `Mesh::DeleteGeometricFactors` or the new `Mesh::NodesUpdated` when modifying the mesh in a way that will change them.

Apart from this, is there anything else we should consider doing in order to resolve this issue?

**Comment by v-dobrev** [comment]
See #3343 for suggested doxygen updates to resolve this issue.
