### ISSUE TITLE
Testing with CMake

### ISSUE THREAD

**Issue by stefanozampini** [mfem/mfem#306]
Here are some issues I encountered with cmake builds.

- If you don't specify -DMFEM_ENABLE_MINIAPPS=1 -DMFEM_ENABLE_EXAMPLES=1
configure, and make are fine, but then make test complains about not being able to find executables
If you add the two flags above, then all the tests are fine (except for some building issue, see below)
I guess configure should complain about MFEM_ENABLE_TESTING being set without those two variables set. Also, why just typing make triggers other targets than building just the library when -DMFEM_ENABLE_MINIAPPS=1 -DMFEM_ENABLE_EXAMPLES=1?

[szampini@localhost build-debug]$ make 
[ 42%] Built target mfem
[ 42%] Built target copy_data
[ 42%] Built target exec_prerequisites
[ 43%] Built target ex8p
[ 45%] Built target ex15p
........

- How can I trigger the testing of the PETSc suite?

- I think there's an error in config/defaults.cmake. PETSC_ARCH is a STRING, not a PATH

diff --git a/config/defaults.cmake b/config/defaults.cmake
index e26a566..8391664 100644
--- a/config/defaults.cmake
+++ b/config/defaults.cmake
@@ -130,7 +130,7 @@ set(NetCDF_REQUIRED_PACKAGES "" CACHE STRING
 
 set(PETSC_DIR "${MFEM_DIR}/../petsc" CACHE PATH
     "Path to the PETSc main directory.")
-set(PETSC_ARCH "arch-linux2-c-debug" CACHE PATH "PETSc build architecture.")
+set(PETSC_ARCH "arch-linux2-c-debug" CACHE STRING "PETSc build architecture.")
 
 set(MPFR_DIR "" CACHE PATH "Path to the MPFR library.")
 

- One last comment: I have some problems building the miniapps (examples are fine). Any idea? I really hate hate hate CMAKE.....

....
[ 82%] Built target examples
[ 85%] Built target mfem_miniapps_common
[ 86%] Building CXX object miniapps/tools/CMakeFiles/display-basis.dir/display-basis.cpp.o
c++: error:  -fPIC: No such file or directory
miniapps/tools/CMakeFiles/display-basis.dir/build.make:62: recipe for target 'miniapps/tools/CMakeFiles/display-basis.dir/display-basis.cpp.o' failed
make[2]: *** [miniapps/tools/CMakeFiles/display-basis.dir/display-basis.cpp.o] Error 1
CMakeFiles/Makefile2:2649: recipe for target 'miniapps/tools/CMakeFiles/display-basis.dir/all' failed
make[1]: *** [miniapps/tools/CMakeFiles/display-basis.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by v-dobrev** [comment]
Since the `test` target in CMake is built-in, you cannot make it depend on other targets: see [this old issue](https://cmake.org/Bug/view.php?id=8438) which is now moved [here](https://gitlab.kitware.com/cmake/cmake/issues/8438). So, when the examples and miniapps are not enabled (i.e. built by the default target `all`), one has to build them explicitly with the `exec` target before running the `test` target.

There is a separate target, `test_petsc`, for testing of the PETSc examples. You can also use `ctest -C PETSC -R petsc` to run those tests.

I'll update the type of `PETSC_ARCH` in #263 - thanks for reporting this.

Regarding the building issue: I'm not sure why the compiler thinks `-fPIC` is a file. I just ran `make miniapps -j 4 VERBOSE=1` without any issues. Can you try running `make display-basis VERBOSE=1` to see the full compile and build commands. That should give you some clue as to what is going wrong.

**Comment by tzanio** [comment]
@stefanozampini, were you able to resolve this?

**Comment by tzanio** [comment]
Closing this issue now. 

@stefanozampini, feel free to re-open if you still have questions.
