### ISSUE TITLE
Question about the maxwell.exe miniapps,how the J project to the edge basis for every elements. 

### ISSUE THREAD

**Issue by xigetongkuaizao** [mfem/mfem#3092]
I want to set up a face source just in the position -1<x<1,y=0,-1<z<1 replace the  cylindrical rod of current density from the example.
And the  original code is :
" if ( xv >= 0.0 && xv <= h && xp <= r )"---line 477 from maxwell.cpp

(1)So I change the code to 
" if ( xv >= 0.0 && xv <= h && x[0]>=-1.0&&x[0]<=1.0 && x[1] =0 )" 
I get the correct J while  the wrong E and wrong H with the number zeros .

(2)And I change again:
" if ( xv >= 0.0 && xv <= h && x[0]>=-1.0&&x[0]<=1.0 &&x[1]>=-0.05 &&x[1]<=0.05 )"
This time get the correct J ,E,H.

(3)When I  change the (2)'s 0.05 to 0.005 ,It get the (1)'s result.

(4)When I  change the (2)' 0.05 to 0.125 ,It also get the (1)'s result. Because the cube.mesh are 16-16-16 elements for xyz's range: -1:1,-1:1,-1:1.so the x[1]=0.125just as the x[1]=0 is in the edge; 

I try to print the vector x, find  the coordinate is may be from the ND-element.  the 3D coordinate has some points in edge and in the inner of the element. I don't know why.

I just do not understand the vector x meaning and how the J project to the vector(edge basis) for each element . 

And run with :
mpiexec -np 4 maxwell  -m ../../data/fichera.msh -rs 3 -ts 0.25 -tf 10
-dp '0.0 0.0 -1.0 0.0 0.0 1.0 0.1 1 .5 1' 
And I fix the fichera.msh to a cube range (-1:1,-1:1,-1:1) .
the right J dt.N=1
![111](https://user-images.githubusercontent.com/97080450/175914206-c4237940-627f-4aab-ab80-de6083ae7fb3.png)
the right E dt.N=5
![222](https://user-images.githubusercontent.com/97080450/175914699-acab90c1-c04f-49e2-8146-71642d8a78da.png)

**Comment by mlstowell** [comment]
Hello, @xigetongkuaizao, 

The vector `x` used on line 477 of maxwell.cpp is the coordinate in physical space where the current density should be evaluated. I believe you understand this correctly. I suspect the confusion is in how this current density function is used within the code.

The current density is used in two different ways. First, it is projected onto a Nedelec GridFunction for visualization. Second, it is integrated over the problem domain to compute the current source term `J` used in the Maxwell equations. 

The projection used for visualization evaluates the current density at a specific set of points in each element, called interpolation points, which correspond to the individual basis functions in a one-to-one manner. For Nedelec basis functions some of these interpolation points happen to lie on the edges of the mesh. If the interpolation points on certain edges happen to satisfy x[1]==0 then you should see the field as you expect it (note however that comparing double precision numbers for equality is usually not a good idea because of round-off error).

On the other hand the integration used to produce the source term in the PDE uses quadrature points distributed throughout the element. It's important to note that these quadrature points usually do not lie on the surfaces of the elements. So, in this case x[1] would never equal 0 so your source term would be zero and your E and H fields would likely be zero as well.

The assumption made in `maxwell.cpp` is that the current density `J` is a volumetric current density rather than a sheet or line current. There are two ways to model a sheet current. First, you could approximate the sheet current by a finite width volumetric current density and ensure that your mesh resolves this finite width. Second, you could implement the current density function using a Dirac delta function in the y direction. I don't think we have this type of delta function implemented in the code but we do have coefficients based on standard delta functions. It should be possible to implement a delta function in just one direction but it may require some custom code of other improvements.

Best wishes,
Mark
