### ISSUE TITLE
How to load a ParGridFunction from 1 File

### ISSUE THREAD

**Issue by cdelv** [mfem/mfem#3098]
I Saved a PargridFunction as one with 

`u->SaveAsOne("Velocity.txt");`

The same I did with the ParMesh. The reason I'm doing this is that I want to be able to resume the simulation on different computers. Then, I don't want to be constrained by the number of cores. 

I'm having problems when reading the Grid. I tried first To read the file to a GridFunction and then create the ParGrid like this

```
    H1_FECollection vfec = H1_FECollection(Parameters.order, pmesh->Dimension());
    ParFiniteElementSpace vfes = ParFiniteElementSpace(pmesh, &vfec, pmesh->Dimension());
    
   mfem::ifgzstream ifs("Velocity.txt")
   GridFunction load;

    if(mpi.Root()){
        load = GridFunction(&mesh, ifs);
    }

    if (mpi.WorldSize() > 1 )
    {
       MPI_Bcast(load, load.Size(), MPI_DOUBLE, 0, MPI_COMM_WORLD );
    }

    ParGridFunction pload = ParGridFunction(&vfes, &load);
```
Here the Bcast is failing. If I try to load it directly to de ParGrid It also fails

`pload = ParGridFunction(pmesh, ifs);`

And If I try without the Bcast the result is entirely wrong. 

Also, If I create the GridFunction without the mpi.Root() it fails.

I ran out of ideas. Please someone help me. The idea is to repeat the same operation for the pmesh.

**Comment by cdelv** [comment]
Update, I tried to load the GridFunctionon each core and then create the ParGrid. Like this

```
for (int i = 0; i < Mpi::WorldSize(); ++i)
    {
        if(Mpi::WorldRank()==i){
            mfem::ifgzstream ifs("Velocity.txt");
            load = GridFunction(&mesh, ifs);
        }
        MPI_Barrier(MPI_COMM_WORLD);
 }

pload = ParGridFunction(&vfes, &load);
```
This Worked. But when I made the visualization the mesh was completely wrong.

**Comment by termi-official** [comment]
I also ran into this problem at a point and the most straight forward approach to solve this problem was for me just to store the mesh partitioning, such that I could call this (https://docs.mfem.org/html/classmfem_1_1ParGridFunction.html#a0fa0ab068a7c868bc53c84876cfa34c9) constructor.

**Comment by termi-official** [comment]
> [...]  if I generate the partition with an 8-core computer and then I want to use 12 cores I would have to use 8 cores on the bigger computer right?

AFAIK there is no direct possibility to switch the number of processes. My current workflow, if I want to change the number of processes, is basically one application that calls the 'save_as_one' functions for the mesh and data and another application which does the repartition of the mesh and grid functions. Not sure if it is the intended way, but it works sufficiently good for my purpose, because I do not need to scale up to millions of cores (for now).

> MFEM doesn't have the functionality to load_from_one function? It has a save_as_one though.

From my understanding, not directly, because the partitioning information is lost. If I understand everything correctly, then this is intended to be able to scale to really large problems, because problems (e.g. through AMR) can get so large that it becomes essentially impossible store even just partitioning on a single machine. However, I think the exact explanation should come from one of the MFEM devs.

**Comment by cdelv** [comment]
@tzanio. Should we have a function on MFEM capable of loading a serial mesh and doing the spatial distribution?

**Comment by tzanio** [comment]
As @termi-official pointed out, there is no easy way to switch the number of tasks in the parallel distribution, but we are working on it, see https://github.com/mfem/mfem/issues/2937 and https://github.com/mfem/mfem/issues/1155.

ping: @bslazarov
