### ISSUE TITLE
Frequency domain electromagnetic problem with iterative solver

### ISSUE THREAD

**Issue by Wayne901** [mfem/mfem#3115]
Hi, everyone. I'm looking for a FEM framework that effectively solves large scale electromagnetics wave problem in frequency domain. 

For example, an antenna, a RF filter or an EM wave scatterer problem. MFEM is capable of assembling such problems with Nedelec basis functions (issue https://github.com/mfem/mfem/issues/1617).

My question is as the size for a 3D problem grows, DOF quickly go over 1/10 to 1 million, and direct solver meets storage and time bottlenecks. I've coding 3D frequency Maxwell wave euqations with FEniCS before, a naive preconditioner+gmres choice does work. ILU
, HYPRE BoomerAMG and AMS preconditioners for example. 

Since it has been 2 from years https://github.com/mfem/mfem/issues/1617, I wonder if there are examples about Krylov solver for 3D indefinite Maxwell problem? Most electromagnetic examples in MFEM code examples are definite Maxwell Problem https://mfem.org/examples/#:~:text=Example%2031%3A%20Anisotropic%20Definite%20Maxwell%20Problem. 

Will (geometric & algebraic) multigrid or domain decomposition preconditon be good choice for wave problem and suit MFEM framworks? All suggestions are wellcomed. Thank you!

**Comment by psocratis** [comment]
Hi @Wayne901, 

As you may know, indefinite wave propagation problems are hard to solve and the main reason is that the standard iterative solvers and preconditioners do not work (at least not as in the definite case). There are several research works in the topic (Shifted Laplacian, Domain Decomposition, Sweeping preconditioners, etc) which show some promise, but often with limitations. In MFEM, there is an implementation of the `Source Transfer Preconditioner` (this is built on the sweeping preconditioner) in a dev branch [here](https://github.com/mfem/mfem/blob/DST-maxwell-solver-dev/examples/maxwell-solver-dev/maxwellp.cpp). This preconditioner requires a structured mesh and the definition of a PML on the subdomains, but it works and scales really well. 

Additionally, you can find an example of frequency domain Maxwell equations with a "naive" preconditioner in ex25/ex25p. There we use GMRES along with the AMS preconditioner for the definite part of the operator. It's a very simple preconditioner and it does not scale, but it is convergent. Geometric multigrid preconditioners can also work with the limitation that the course grids need to be "fine" enough, and this often leads to expensive coarse solves. 

Lastly, I would estimate that if your problem is about 1 million dofs (that's not too bad) then a multifrontal direct solver should do the work and I expect that it would even be faster than any iterative solver (i.e., MUMPS SuperLU, PARDISO). MFEM provides interfaces to all these solvers. 

I hope this helps. 

Best, 

Socratis

**Comment by Wayne901** [comment]
Hi @psocratis ,

Thanks for your reply. 

For the Source Transfer Preconditioner or sweeping preocnditioners, it seems one should **define a PML on subdomains** and **source transfer from one to another subdomain**. Does it mean a domain-by-domain solving strategy and the propagation of EM/elastic wave is known a priori? I'm not familiar with this preconditioner, but for a scattering problem (an incident wave project to a PEC obstacle, as shown in the picture), the propagation direction is cannot be defined (if I understood it well).
![image](https://user-images.githubusercontent.com/52063692/180987925-9d188fad-2326-4251-8edf-edc59d70b90a.png)

And about the problem scale, actually I'm looking to solve EM problems (complex geometries such as microchips, multilayer electronic device packaging) up to 0.1 and even 1 billion DOFs on supercomputer. Therefore I have to choose a robost iterative solver.

I've notice a DofMapsDST file in your dev branch. That's interesting and I wonder what DOF Mapping/Assignment does MFEM support? 

Suppose I have a simple mesh with for triangles and distributed to 2 processors (each gets 2 trias), Nedelec 1st used. Can I operate DOFs to decouple the 2 subdomain, by:

1. assign a dof for the interface edge in every adjacent subdomain, result in 2 dofs (5 and 7) for interface edge in total.
2. rearrange the dofs arbitrarily (not shown in the picture). For example, rearrange DOF 6,7,8,910 to 6,8,9,10,7 and permute the corresponding matrix.

![1658832933355](https://user-images.githubusercontent.com/52063692/180990053-b165aacc-e7df-4a8f-b115-9b418864da01.jpg)

**Comment by Wayne901** [comment]
I'm interested in the DOFMapping because a block-diagnal matrix and block-diagnal preconditioner should work. As long as the local index and global index of each edge is callable, and user can construct the dof with a given order (like 1,2,3,4,5, 6,8,9,10,7), this should work. Information between 5 and 7 will be glued by some boundary condition.


@psocratis will it be possible to parallel the assemble and LU factorization on each subdomain? Say, we assign one subdomain (and mesh divided by METIS) to each processor?

Thank you my friend.

**Comment by psocratis** [comment]
> Does it mean a domain-by-domain solving strategy and the propagation of EM/elastic wave is known a priori?

No, you don't need to know the propagation direction a priori. There is a specific sweeping strategy that would cover all possible directions of propagation. However, for a problem with multiple scatterers or problems where a lot of scattering is happening, these types of solvers lose their efficiency. 

> @psocratis will it be possible to parallel the assemble and LU factorization on each subdomain? Say, we assign one subdomain (and mesh divided by METIS) to each processor?

The Domain Decomposition (DD) approach is not that simple. MFEM does provide the tools for you to build a DD solver (see this [PR](https://github.com/mfem/mfem/pull/2920)), but you have to design the transmission conditions on the interfaces of the subdomains.  The Source Transfer preconditioner falls into this category by using a PML. Without these special transmission conditions, you basically have a Schwarz solver and it is known that it does not work for indefinite problems.

I am sorry I don't have better news for you, but high-frequency wave propagation problems are indeed very hard to solve and to the best of my knowledge there is no generic scalable linear solver for their solution yet.

Best, 

Socratis

**Comment by Wayne901** [comment]
Yeah it is non-trival to implement DDM. I'm planning to use Robin transmission boundary condition from this group https://ieeexplore.ieee.org/abstract/document/5678600/ .

By the LU factorization, I mean a block-diagonal precondition. There will be off-diagonal coupling terms but not considered for preconditioning. 

One last question. Does MFEM support element-wise (on node or edge) dof assign. Just like the draft I've shown, a total 10 dofs with order [1,2,3,4,5, 6,8,9,10,7] on a 9-edge mesh?

Thank you

**Comment by dylan-copeland** [comment]
@Wayne901 In branch `complex-strumpack-dev-dylan`, I implemented a DDM with Robin transmission conditions, following papers by Peng and Lee as you referenced. However, I do not recommend using that branch, as it is a couple of years old and is a very complicated "experimental" implementation. I never got around to cleaning up that branch and making it more production-ready or user-friendly. Instead, the PR that @psocratis mentioned for submeshes should help to make a simpler, cleaner implementation.

Aside from the question of implementation, I can briefly summarize the results of experimenting with DDM. Basically, I found that DDM enables solving problems a little larger than a direct solver can handle (e.g. direct solver can do 50 million DOFs, and DDM can do 1 billion DOFs). However, going to much larger problems is not possible with direct solvers on subdomains, because too much memory is required on each subdomain. The high memory usage even occurs just from matrix assembly, even without direct solvers. My conclusion was therefore that matrix-free solvers are necessary on the subdomains, which is an open area of research. So DDM will buy you a little more computational power, but not much until matrix-free methods are extended to these indefinite problems.

**Comment by Wayne901** [comment]
@dylan-copeland Thank you Dylan

Yes a direct solver on subdomains (to construct a block-diagonal preconditoner) is very storage-ineffecient. Meanwhile sparse preconditioners such as ilu don't work on this indefinite problem. Might see if low-rank matrix factorization works (BLR, H-matrix, first time read this yesterday), to give a good approxiamtion of the subdomain matrix, while saving some storage. It's really intractable.

About the matrix-free, does it compute y_i=A_ii·u_i inside a cell and add it to soluiton without assembling matirx A? I'm not familiar with this technique, and I guess it accelerate matrix-vector multiplication which involves in iteration solver(feel free to correct me if wrong). How does matrix-free method reduce matrix assemble storage? That's a promising point, but matrix elements are always there assembled or not assembled, so I didn't undertand it. Matrix-free doesn't seem to help a  more stable iterative solver, do you mean we should incorporate matrix-free technique into large scale problem?

Your information is very helpful. Thank you!

**Comment by dylan-copeland** [comment]
@Wayne901 In MFEM, there are different types of "matrix-free" operators. There is partial assembly (PA) which stores some coefficient and geometry data at quadrature points, and there are other options. The idea is to use less storage and more computation, but the computation is designed to take advantage of GPU acceleration (e.g. using tensor-product factorizations). In any case, my point is that some kind of matrix-free method is necessary to avoid matrix storage, especially for high-order FEM. With such a method, direct solvers are no longer possible, so iterative solvers are necessary. However, good preconditioners, without access to the matrix entries, are unknown.

**Comment by Wayne901** [comment]
Thank you Dylan. I know what matrix-free method aims for now. 

Your replys help a lot. Thank you all.
