### ISSUE TITLE
question about mass and stiffness matrix.

### ISSUE THREAD

**Issue by jsfeng-fudan** [mfem/mfem#3125]
For time-dependent PDE, where can I find the basic principle for weak form of PDE. Since there are different methods for time
discretization. As the example.9 shows the realization of DG Advection problem. In the code, the explanation is

```c++
/** A time-dependent operator for the right-hand side of the ODE. The DG weak
form of du/dt = -v.grad(u) is M du/dt = K u + b, where M and K are the mass
and advection matrices, and b describes the flow on the boundary. This can
be written as a general ODE, du/dt = M^{-1} (K u + b), and this class is
used to evaluate the right-hand side. */
```

I can not grasp the bilinear form ( M and K) from weak form with Galarkin method.
Can you give me some clues?

It is appreciated if someone can guidance .

**Comment by TobiasDuswald** [comment]
I'm not sure if the question is more specific than the one that I'm just seeing but if you're generally interested in time-dependent PDEs and how to address them with the finite element method, this text may give some intuition: http://hplgit.github.io/INF5620/doc/pub/H14/fem/html/._main_fem020.html
You may also try to reverse engineer from example 9 because the code will define what `M` and `K` are.
