### ISSUE TITLE
Projection error

### ISSUE THREAD

**Issue by rmvega1025** [mfem/mfem#3181]
I recently tried using mfem 4.4 in a code that I am working on after using mfem 4.2.1 for quite a while. The code worked in 4.2.1, but is now crashing with 4.4. I have narrowed the error down to a ProjectCoefficient call:

```c++
mfem::FiniteElementCollection* lo_fec;
mfem::FiniteElementSpace* lo_fes;
mfem::GridFunction lo_gf;
lo_fec = new mfem::L2_FECollection( 0, domain->lo_mesh->Dimension() );
lo_fes = new mfem::FiniteElementSpace( domain->lo_mesh, lo_fec );
lo_gf.SetSpace( lo_fes );

for ( int cell_index = 0; cell_index < lo_mesh->GetNE(); cell_index++ )
{
      // get piecewise constant value of field in cell and assign it to GridFunction
      double cell_value = ....;
      lo_gf[cell_index] = cell_value;
}

mfem::FiniteElementCollection* ho_fec;
mfem::FiniteElementSpace* ho_fes;
mfem::GridFunction ho_gf;
ho_fec = new mfem::L2_FECollection( 0, domain->mfemMesh->Dimension() );
ho_fes = new mfem::FiniteElementSpace( domain->mfemMesh, ho_fec );
ho_gf.SetSpace( ho_fes );

mfem::GridFunctionCoefficient lo_coef( &lo_gf );
ho_gf.ProjectCoefficient( lo_coef );
```

Basically, I have a high order mesh, and a refined low order mesh. the GridFunctions are set on the low order mesh, and projected up to the high order mesh. BOTH ARE 0TH (PIECE_WISE CONSTANT) ORDER L2 GRIDFUNCTIONS. The only difference is that one is on the high order mesh, and the other is on the low order mesh.

The error I am getting is:

Verification failed: (GetLastOperation() == Mesh::REFINE) is false:
 --> 
 ... in function: const mfem::CoarseFineTransformations &mfem::Mesh::GetRefinementTransforms()
 ... in file: mesh/mesh.cpp:9851

Admittedly, the low order mesh might be a bit tangled as shown in the attached figures, but I did not get this error in version 4.2.1. I also verified that the projection was happening correctly.

<img width="1199" alt="lo" src="https://user-images.githubusercontent.com/81265187/187739485-7ddbd620-b07d-4cb4-a1df-5ea42aeb16d6.PNG">

<img width="1194" alt="ho" src="https://user-images.githubusercontent.com/81265187/187739514-6ce615fc-53e6-4903-aa00-d9c35fa4fe5a.PNG">

**Comment by pazner** [comment]
#### Explanation of what is happening:

I think what is happening here is that MFEM doesn't understand the relationship between `lo_mesh` and `mfemMesh`. You write in the comment that the only difference between these meshes is that one is low-order and the other is high-order, so the two meshes should have identical topology, numbering, etc. But MFEM isn't aware of this relationship, it just knows that you are trying to project a grid function defined on one mesh onto a grid function defined on another mesh, and the two meshes may not be related at all.

This probably worked "by chance" in past versions of MFEM because it just assumed that the two meshes were identical, which happened to work in your case (what it would have done was just assign the piecewise constant values to the elements of the high-order mesh, it wouldn't do any more sophisticated projection). But it failed in other cases, like when one mesh is a refinement the other. We added support for when one mesh is refined, and so it checks that either the meshes are the same or that one is refined, and if not then it fails because it doesn't know how to handle the situation.

#### Proposed workarounds:

* If you just want to project piecewise constant values onto a grid function on the high-order mesh, you can do this with a loop, and set the DOFs yourself.
* Could you just create `lo_fes` using the high-order mesh `mfemMesh`, and then construct the low-order grid function as before, and then try `ProjectCoefficient`? This should also have the same result as what you were doing previously.

**Comment by rmvega1025** [comment]
Is there a generally correct way to project a GridFunction on one mesh onto a GridFunction on another mesh? Because eventually the low order mesh will be piecewise constant, but the other will be higher order.

**Comment by pazner** [comment]
If there is no relationship between the meshes then you could use something like gslib/findpts. If there is a relationship (same topology, one is a refinement of the other, etc.), then there are some ways of using the `CoarseFineTransformations`. It really depends on your specific use case.

**Comment by rmvega1025** [comment]
Well, one will always be a refinement of the other.

**Comment by vladotomov** [comment]
I think @aaronskinner is already doing something very similar.
