### ISSUE TITLE
basic questions on mfem

### ISSUE THREAD

**Issue by marcsolal** [mfem/mfem#3236]
I just discovered the existence of mfem. This looks very powerful and I am very interested.
I am using fem mostly to simulate piezoelectricity. I have some basic questions on what is possible with this library.
1. The obvious question: I saw that the library provides prebuild formulations. I did not see any piezoelectric formulation, but I would like to make sure it does not.
2. Is it possible to work with complex dof. Typically, I am solving harmonic problems and any loss results in imaginary part of the coefficients.
3. Is it possible to have a mesh where the number of dofs per nodes is not constant. For example, a piezoelectric material would need 4 dofs per node, 3 for mechanical displacement and 1 for electrical potential. Vacuum will only need 1 dof per node (electrical potential) and a metal would only need only the mechanical displacements.
4. I could not find how to define a specific physics in the documentation. I am sure it is possible, but I did not find it. I looked at some of your examples and the ones I looked were using a physics which is already defined. Is there an example showing how to define a specific physics. Normally, I would define the formulation at the element level.
Thanks for this nice library.
Marc

**Comment by mlstowell** [comment]
Hello, Marc (@marcsolal),

Thank you for the kind words. I hope that you will find MFEM useful.

I'm not familiar with piezoelectric simulation but I suspect we do not have an example or miniapp with all of the necessary features. However, it seems likely we have many of the pieces you might need. If you could share the equations and any other distinctive requirements we'd be happy to give you some more specific feedback.

We have at least two examples (ex22 and ex25) which demonstrate the use of complex-valued fields. The approach we take is to simulate the real and imaginary parts of a PDE as a pair of coupled equations. The reason for this approach is partly historical in that our solvers were only real-valued at one time. We have recently added support for some complex-valued direct solvers so it might be reasonable to consider building complex-valued linear systems. I don't think we currently have plans to do this.

Your third question pertains to what we call different physics in different regions. This is a feature we have received many questions about and as luck would have it we just began adding this two weeks ago. Since it is such a new feature I am not yet familiar with its use or possible limitations. There is one example that I'm aware of that you could examine which can be found [here](https://github.com/mfem/mfem/blob/master/miniapps/multidomain/multidomain.cpp). This example demonstrates a one-way coupling between two equations and I'm not sure if a full coupling is possible yet. Another approach which we have often used in the past is to approximate your multi-physics problem by using extreme coefficient values in certain regions to effectively disable certain physics in select regions. Clearly this has drawbacks but it can produce suitable results.

Rather than thinking directly about the "physics", e.g. force or energy balance, we tend to think about mathematical operators. If you can write the necessary physics as a set of coupled partial differential equations we can probably help you determine a suitable means to discretize the relevant fields and produce the necessary mathematical operators needed to build the discrete linear system.

Best wishes,
Mark

**Comment by marcsolal** [comment]
Classification | PRIVATE

Thanks for answering.
Regarding the “physics”, we need to couple the classic elastic waves equations (for anisotropic materials) with the electrostatics (Poison type of equations). I will give more details when everything is back to normal after the hurricane. Basically, for each material we have a stiffness tensor, a permittivity matrix and a piezoelectric tensor linking displacements and electrical potential.
Marc

**Comment by marcsolal** [comment]
Classification | PRIVATE

I tried to rewrite the general piezo equation below. Usually, the structure comprises not only piezo materials but also dielectric (same equations, piezo tensor e=0), metals (only first equation, potential is constant, e=0), and vacuum (only Poisson equation). Tensors have many symmetries.
Marc

***@***.***

**Comment by mlstowell** [comment]
Hello, @marcsolal,

Unfortunately, I don't see any equations but I think I'm starting to get the picture. You've probably noticed that our elasticity examples involve linear or non-linear elasticity with isotropic materials. While our FEM framework could easily support anisotropic materials I don't think we currently have the necessary integrators implemented in the library. Of course MFEM is extensible so they could be added by the user. An alternative would be to construct the necessary operators using our `BlockOperator` class with existing scalar integrators such as the `DiffusionIntegrator` with a tensor material.

The coupling terms would face similar challenges. Again both approaches could work; implement new integrators with higher rank tensor coefficients or low rank tensor coefficients with existing integrators and `BlockOperators` to glue them together.

Best wishes,
Mark

P.S. I hope the hurricane didn't create too much chaos for you.

**Comment by marcsolal** [comment]
Classification | PRIVATE

The equations were in my email. It was a screen copy. I guess github is not keeping them.
Thanks, I think I would have to add my own integrators…I will have a look on all that.
Marc
