### ISSUE TITLE
Anisotropic time dependent heat conduction problem.

### ISSUE THREAD

**Issue by jsfeng-fudan** [mfem/mfem#3239]
Hi, 
I see the example 16 for nonlinear heat conduction, in this example, kappa and alpha are both scalar constant, which means isotropic.
but for real application, these coefficients are matrix. how do we modified the code :
void ConductionOperator::SetParameters(const Vector &u)
{
   GridFunction u_alpha_gf(&fespace);
   u_alpha_gf.SetFromTrueDofs(u);
   for (int i = 0; i < u_alpha_gf.Size(); i++)
   {
      u_alpha_gf(i) = kappa + alpha*u_alpha_gf(i);
   }

   delete K;
   K = new BilinearForm(&fespace);

   GridFunctionCoefficient u_coeff(&u_alpha_gf);

....
   K->AddDomainIntegrator(new DiffusionIntegrator(u_coeff));
.....
}

**Comment by mlstowell** [comment]
Hello, @jsfeng-fudan,

For anisotropic materials like you describe we use objects derived from `MatrixCoefficient`. In this example I would probably write a custom `MatrixCoefficient` which would work in a manner similar to a `GridFunctionCoefficient` except that it would return a matrix-valued coefficient rather than a scalar. You could initialize this custom coefficient with a `GridFunction` using the vector values stored in `u` along with whatever matrix-valued `kappa` and `alpha` would be appropriate. This custom matrix-valued coefficient would then be passed into the `DiffusionIntegrator` in precisely the same manner as the scalar coefficient.

Best wishes,
Mark
