### ISSUE TITLE
4.5: installs cmake file with SuperLU include directory but cmake only looks for SuperLUDist

### ISSUE THREAD

**Issue by yurivict** [mfem/mfem#3276]
```lib/cmake/mfem/MFEMTargets.cmake``` has this lines:
```
set_target_properties(mfem PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/usr/local/include;/usr/local/include/superlu;/usr/local/include/suitesparse;/usr/local/include/conduit;/usr/include;${_IMPORT_PREFIX}/include"
```

```/usr/local/include/superlu``` is installed by superlu-5.3.0

But the cmake script looks for ```SuperLUDist``` [here](https://github.com/mfem/mfem/blob/master/CMakeLists.txt#L307) which doesn't install the above directory.

**Comment by yurivict** [comment]
@v-dobrev The 4.5 release is broken.
Dependencies fail to build.

```glvis-mesh-visualizer-4.2``` and ```axom-0.7.0``` both fail with this error:
```
CMake Error in lib/CMakeLists.txt:
  Imported target "mfem" includes non-existent path

    "/usr/local/include/superlu"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.
```

**Comment by v-dobrev** [comment]
As far as I remember, we have not changed anything related the SuperLU_DIST in the CMake build system since the last release.

What SuperLU_DIST-related command line options do you give to CMake?

Where are the SuperLU_DIST files `superlu_defs.h` and `libsuperlu_dist.so` actually located?

If the logic here https://github.com/mfem/mfem/blob/2eb2061fb0cc944f76177d038a215dac5dfa4abc/config/cmake/modules/FindSuperLUDist.cmake#L18
does not work with the SuperLU_DIST installation layout you have, you can set directly `SuperLUDist_INCLUDE_DIRS` and `SuperLUDist_LIBRARIES` on the CMake command line.

**Comment by tzanio** [comment]
@white238, do you have any issues building mfem-4.5 and SuperLU with CMake in your application?

**Comment by yurivict** [comment]
not stale

**Comment by v-dobrev** [comment]
I asked some questions above, that may help me identify the issue:

> What SuperLU_DIST-related command line options do you give to CMake?
>
> Where are the SuperLU_DIST files `superlu_defs.h` and `libsuperlu_dist.so` actually located?

Can you please answer these?
