### ISSUE TITLE
Surface current integrals

### ISSUE THREAD

**Issue by JeremiahDBrown** [mfem/mfem#3283]
I'm working on some calculations involving surface current integrals of the form:
$\vec L = \int_S (\hat n\times\vec E)f(\vec r) dS'$
$\vec N = \int_S (\hat n\times\vec H)f(\vec r) dS'$
The first of these is pretty straightforward using the VectorFEBoundaryTangentLFIntegrator.  However, that integrator requires a field in the H(curl) space.  To obtain $\vec H$ from $\vec B$ (H(div) space), I assumed the best approach was to use a MixedBilinearForm with a MixedVectorMassIntegrator.  When I try that, the boundary dof magnitudes are significantly smaller than expected, as is the result of the Boundary Tangent Integrator on the resulting $\vec H$ field.  Is there a better way to compute $\vec H$ that is accurate on the boundaries?

Also, is the direction of the $\hat n$ vector well-defined?  I set up a test case using the cube-nurbs.mesh, and the resulting integrals have the opposite sign I would expect for a normal vector pointing outwards.  I don't think it is particularly important for my case, but I was curious.

**Comment by JeremiahDBrown** [comment]
I'm still hoping to get some help on this!  I was trying the following:

    FiniteElementCollection *fec_nd = new ND_FECollection(2, mesh->Dimension());
    FiniteElementSpace *fespace_nd = new FiniteElementSpace(mesh, fec_nd);
    FiniteElementCollection *fec_rt = new RT_FECollection(2, mesh->Dimension());
    FiniteElementSpace *fespace_rt = new FiniteElementSpace(mesh, fec_rt);

    MixedBilinearForm rt_to_nd(fespace_rt, fespace_nd);
    rt_to_nd.AddDomainIntegrator(new MixedVectorMassIntegrator());
    rt_to_nd.Assemble();
    rt_to_nd.Finalize();
    rt_to_nd.Mult(x_rt,x);

Where x_rt is an initialized GridFunction in the RT space, and x is an empty GridFunction in the ND space.  Here, I'm just treating $\mu^{-1}$ as 1 for testing purposes.  The result for x is dramatically different from x_rt on the boundaries, which is what I'm most concerned about since I'm trying to integrate surface currents.  I'm sure I'm missing something here.  How should I approach this?

**Comment by vladotomov** [comment]
Hi @JeremiahDBrown,

If you want to do an L2 projection, don't you need a ND mass matrix that must be inverted? What you have computed above seems to be the right-hand side vector.

For other approaches, you should check `FiniteElement::Project(...)` which will probably interpolate, and also the class `class DiscreteLinearOperator` in `fem/biliinearform.hpp`.

**Comment by JeremiahDBrown** [comment]
@vladotomov ,
In the code above, I'm computing $\vec H = \mu^{-1}\vec B$, where I let $\mu=1$ for visualization purposes.  $\vec B$ is the magnetic field and is in H(div) space.  Ultimately, I don't really care about the computation of $\vec H$ so much as I want to compute $\int_S (\hat n\times \mu^{-1}\vec B) f(\vec r) dS'$ on the boundary.  I've tried the interpolation approach, and it yields similar results to the MixedBilinearForm - specifically, it looks fine in the interior of the domain but doesn't give correct values on the boundaries, which is the only thing I'm actually concerned about!

Is it necessary to extend the simulation region and create an interior boundary where I want to compute the surface integral?

**Comment by vladotomov** [comment]
I don't have any guesses. I can take a look if you provide a reproducer.

**Comment by mlstowell** [comment]
Hi, @JeremiahDBrown,

Converting a H(Div) field to an H(Curl) field is a common problem with no easy solution. The basic issue is that a discrete RT (aka H(Div)) space has fewer degrees of freedom than the corresponding ND (aka H(Curl)) space so you need to provide additional data somehow.

The conversion typically works well in the interior because there's enough data available locally. Consider a simple hexahedral mesh where every interior node touches eight elements. At 1st order the ND DoFs are associated with the edges and the corresponding basis functions are vectors aligned with those edges. The RT DoFs are on the faces and the corresponding basis functions are vectors that pierce the faces. So, the ND DoF on a typical interior edge will depend on the eight faces pierced by that edge which touch the nodes terminating the edge. Therefore the ND DoF can be computed as a weighted average of the eight nearby faces. On the other hand if you consider an edge on the boundary you loose at least four of those nearby faces because they would be outside the domain. Not only that but the remaining four are all off to one side of the edge you're interested in. Consequently ND DoFs for boundary edges must be _extrapolated_ from those four nearby faces which are all biased and lead to a systematic error which cannot be easily removed.

What can be done? 
* First, provide the boundary values as Dirichlet boundary conditions when solving the ND mass matrix. Clearly this is not an option in your case because these boundary values are precisely what you're trying to compute. 
* Second, extend the domain as you suggested. If this is feasible it might be the best solution as long as you can properly terminate the problem on the new boundary. In many cases I doubt this would be feasible.
* Third, provide an additional constraint. For example, is `H` divergence free everywhere _even on the boundary_? If so, you may be able to impose a constraint on the weak divergence of `H` using a block operator when solving for `H`. Depending on how the domain is terminated this may not be possible.
* Fourth, resolve the mesh near the boundary. This should always be possible although it may be computationally expensive. This should work because `H` should converge to `B` as the mesh is refined. The goal is to make the systematic error smaller than your desired error tolerance.

I hope this helps.
Best wishes,
Mark

**Comment by JeremiahDBrown** [comment]
@mlstowell ,
Thanks for the comments.  That helps a lot.  Unfortunately, I'm running into a couple of issues now.  First, I'm using Cubit to create the meshes, and it appears that the direction of the surface normal for the interior boundary is not necessarily consistent from one face to the next.  I am integrating over a cube with one vertex at [0,0,0] and the other at [1,1,1].  I have initialized my field and integration functions so that the integral is only nonzero on the cube faces x=0 and x=1.  The integration result should be $2 sin(\pi/4)/\pi - 6 sin(\pi/4)/\pi = -sin(\pi/4)/(\pi/4)$.  When I integrate over the boundary of a simple cube mesh, I get this result exactly.  When I extend the mesh and integrate over an interior boundary, the sign on one of the two faces is flipped.

The second problem is that if I project the same function onto an RT space and then try to convert to ND to perform the same integration over an interior boundary, the magnitude is much smaller.

I've attached my mesh files.  Below is the code listing demonstrating what is going on:

#include <stdio.h>
#include <iostream>
#include <cmath>

#include <mfem.hpp>

using namespace std;
using namespace mfem;

int main(int argc, char *argv[]) {
  Mesh *mesh = new Mesh("testmesh.g");
  Mesh *mesh0 = new Mesh("testcube.g");
 
  FiniteElementCollection *fec_cube = new ND_FECollection(2, mesh0->Dimension());
  FiniteElementSpace *fespace_cube = new FiniteElementSpace(mesh0, fec_cube);

  FiniteElementCollection *fec_nd = new ND_FECollection(2, mesh->Dimension());
  FiniteElementSpace *fespace_nd = new FiniteElementSpace(mesh, fec_nd);
  FiniteElementCollection *fec_rt = new RT_FECollection(2, mesh->Dimension());
  FiniteElementSpace *fespace_rt = new FiniteElementSpace(mesh, fec_rt);

    // function to project on volume: f(x,y,z) = [0, 0, x+y]
  VectorFunctionCoefficient funcVol(3, [](const Vector &x, Vector &v) {
    v.SetSize(3);
    v(0) = 0;
    v(1) = 0;
    v(2) = x(0)+x(1);
  });

    // integration function, dotted with n x f, g(x,y,z) = [0, cos(kz), 0]
  VectorFunctionCoefficient integFunc(3, [](const Vector &x, Vector &v) {
    v.SetSize(3);
    v(0) = 0.0;
    v(1) = cos(M_PI_4 * x(2));
    v(2) = 0.0;
  });

    // Expected result of boundary integration:
  cout << "Integration target: " << sin(M_PI_4)/M_PI_4 << "\n";

    // Test integration on boundary of simple cube:
  LinearForm test_cube(fespace_cube);
  test_cube.AddBoundaryIntegrator(new mfem::VectorFEBoundaryTangentLFIntegrator(integFunc));
  test_cube.Assemble();
  GridFunction x0_cube(fespace_cube);
  x0_cube.ProjectCoefficient(funcVol);
  cout << "Vector Integration of simple cube: " << test_cube(x0_cube) << "\n";

    // boundary 1 is between two blocks in the mesh; inner block has same size as simple cube
  Array<int> bdr_attr(mesh->GetNBE());
  bdr_attr = 0;
  bdr_attr[0] = 1;
  LinearForm test(fespace_nd);
  test.AddBoundaryIntegrator(new mfem::VectorFEBoundaryTangentLFIntegrator(integFunc), bdr_attr);
  test.Assemble();
  GridFunction x0(fespace_nd);
  x0.ProjectCoefficient(funcVol);
  cout << "Vector Integration on inner block (ND elements): " << test(x0) << "\n";

    // Project function onto RT space, then convert to ND
  GridFunction x_rt(fespace_rt);

  MixedBilinearForm rt_to_nd(fespace_rt, fespace_nd);
  ConstantCoefficient ones(1.0);
  rt_to_nd.AddDomainIntegrator(new MixedVectorMassIntegrator(ones));
  rt_to_nd.Assemble();
  rt_to_nd.Finalize();

  GridFunction x_nd(fespace_nd);
  x_rt.ProjectCoefficient(funcVol);
  rt_to_nd.Mult(x_rt,x_nd);
  cout << "Vector Integration on inner block (GF converted from RT elements): " << test(x_rt) << "\n";

  delete fespace_nd;
  delete fec_nd;
  delete fespace_rt;
  delete fec_rt;
  delete fespace_cube;
  delete fec_cube;
  delete mesh;
  delete mesh0;

  return 0;
}
[testmeshes.zip](https://github.com/mfem/mfem/files/9993644/testmeshes.zip)

**Comment by mlstowell** [comment]
Hi, @JeremiahDBrown,

I'm not surprised that the normal of an interior surface has an inconsistent direction. In order to make this work I think you would need to write a custom integrator and a custom vector coefficient. The vector coefficient would need to define the outward normal direction from your surface. The integrator would need to use this user-defined normal to compute the integral. I haven't thought about this in great detail and there may be other complications but I think it would work.

In the last section of the attached code the RT->ND conversion is incomplete and the resulting vector, `x_nd`, is not mathematically speaking a GridFunction. It is a LinearForm. This is why the magnitude is wrong and on an unstructured mesh it would probably look quite noisy. This type of conversion is a two step process. The first step is precisely what you show except that `rt_to_nd.Mult(x_rt,x_nd)` should write to some temporary vector (technically a `LinearForm` but any `mfem::Vector` should work). Then next step is to solve a square mass matrix using this temporary vector as the right hand side and `x_nd` as the solution. The square mass matrix should be built using a `BilinearForm` on the ND finite element space. The integrator would be `MixedVectorMassIntegrator`.

The way I think of this process is that we are computing a weighted average. The multiplication by the rectangular mass matrix is computing the numerator of the average with the appropriate weights. The denominator divides by the weights of the ND basis functions themselves.

Best wishes,
Mark

**Comment by JeremiahDBrown** [comment]
Thanks @mlstowell.  That makes sense.  I think I have both of these fixed now.  I did create a new Integrator class that is initialized with the location of a point strictly inside a simply connected convex boundary.  That way I can check the dot product of the element normal vector and a vector from that interior point to decide if the sign of the result from the TangentLFIntegrator needs to be flipped for the given element.  Thanks for your help.

```
class InteriorBoundaryTangentLFIntegrator : public VectorFEBoundaryTangentLFIntegrator
{
public:
  InteriorBoundaryTangentLFIntegrator(Vector &point, VectorCoefficient &QG,
                                  int a = 2, int b = 0)
    : VectorFEBoundaryTangentLFIntegrator(QG, a, b), interior_point(point) {}
  
  using VectorFEBoundaryTangentLFIntegrator::AssembleRHSElementVect;

  virtual void AssembleRHSElementVect(const FiniteElement &el,
                                    ElementTransformation &Tr,
                                    Vector &elvect);
private:
  Vector interior_point;
};
void InteriorBoundaryTangentLFIntegrator::AssembleRHSElementVect(
    const FiniteElement &el, ElementTransformation &Tr, Vector &elvect)
{
  VectorFEBoundaryTangentLFIntegrator::AssembleRHSElementVect(el, Tr, elvect);

  Vector pos(3);
  Tr.Transform(Tr.GetIntPoint(), pos);
  pos -= interior_point;
  Vector elNormal(3);
  CalcOrtho(Tr.Jacobian(), elNormal);
  if( pos*elNormal < 0 )
    elvect.Neg();
}
```
