### ISSUE TITLE
Question about boundary elements and VTK/VTU meshes

### ISSUE THREAD

**Issue by shani9383** [mfem/mfem#3378]
(Following up on https://github.com/mfem/mfem/issues/3344#issuecomment-1334511882)

Hi,  

1. Can you please share with me how you defined the boundary surfaces or nodes (for applying the boundary conditions) in my mesh file?  

2. Except from converting my mesh file from VTK to VTU in Paraview ,did you modify anything else? 

3. I cannot generate boundary nodes for my VTK file. Thus, I am trying to generate a native MFEM mesh file (.mesh) from other FEA input file (as .inp (Abaqus) or Ansys). I noticed that the mesh format requires you to define all the boundary surfaces of the body (although boundary conditions are not applied on them). Is this really required? Way? When generating inp or ansys or other fem input files, I receive only the nodes of the boundary where the boundary condition applies. How can I solve this problem? Note that my mesh file is quite large. 

Tnx
Shani

**Comment by pazner** [comment]
Hi @shani9383, did you have a specific question or was this issue opened by mistake?

**Comment by shani9383** [comment]
Hi,  

1. Can you please share with me how you defined the boundary surfaces or nodes (for applying the boundary conditions) in my mesh file?  

2. Except from converting my mesh file from VTK to VTU in Paraview ,did you modify anything else? 

3. I cannot generate boundary nodes for my VTK file. Thus, I am trying to generate a native MFEM mesh file (.mesh) from other FEA input file (as .inp (Abaqus) or Ansys). I noticed that the mesh format requires you to define all the boundary surfaces of the body (although boundary conditions are not applied on them). Is this really required? Way? When generating inp or ansys or other fem input files, I receive only the nodes of the boundary where the boundary condition applies. How can I solve this problem? Note that my mesh file is quite large. 

Tnx
Shani

**Comment by pazner** [comment]
> 1. Can you please share with me how you defined the boundary surfaces or nodes (for applying the boundary conditions) in my mesh file?

VTK/VTU meshes do not contain boundary element information. That is just how VTK format works. When you load a VTK/VTU mesh into MFEM, MFEM will generate boundary elements consisting of all faces that belong to only one volume element (if a face belongs to two elements, it is in the interior; if it belongs to only one element, it is on the domain boundary).

Because the mesh file does not contain boundary information, all boundary elements are given the same attribute. If you want to apply different types of BCs to different parts of the boundary, you will need a mesh format that contains boundary information.

> 2. Except from converting my mesh file from VTK to VTU in Paraview ,did you modify anything else?

No

> 3. I cannot generate boundary nodes for my VTK file. Thus, I am trying to generate a native MFEM mesh file (.mesh) from other FEA input file (as .inp (Abaqus) or Ansys). I noticed that the mesh format requires you to define all the boundary surfaces of the body (although boundary conditions are not applied on them). Is this really required? Way? When generating inp or ansys or other fem input files, I receive only the nodes of the boundary where the boundary condition applies. How can I solve this problem? Note that my mesh file is quite large.

In most finite element problems, you need *some* boundary condition enforced at every boundary (though sometimes the BCs are "natural" or "do nothing" conditions).

I would recommend including boundary elements for every boundary face in your mesh, and just give the different BC surfaces different attributes. That will be the most flexible approach.

**Comment by queen333597** [comment]
> Because the mesh file does not contain boundary information, all boundary elements are given the same attribute. If you want to apply different types of BCs to different parts of the boundary, you will need a mesh format that contains boundary information.

Among the MFEM-compatible mesh formats that contain boundary info, do you have a recommendation on which one would be better/easier to use for applying boundary attributes?

**Comment by pazner** [comment]
> Among the MFEM-compatible mesh formats that contain boundary info, do you have a recommendation on which one would be better/easier to use for applying boundary attributes?

I suppose it depends on how you are generating/processing your meshes. Boundary attributes should work properly with [Gmsh](https://gmsh.info) and [CUBIT/NetCDF](https://cubit.sandia.gov) formats (and of course with MFEM's "native" mesh format).

**Comment by pazner** [comment]
Closing for now. Please re-open if there are other questions.
