### ISSUE TITLE
Document and clarify TimeDependentOperator::ImplicitSolve notation

### ISSUE THREAD

**Issue by jandrej** [mfem/mfem#3395]
I keep on forgetting doing this.

* Write a clarification that one only needs to implement a backward euler step for `k = f(x + dt k, t)`

**Comment by tzanio** [comment]
Specifically, say that:

- Solving $k = f(x + \Delta t\\, k, t)$ is equivalent to determining the *backward Euler* "implicit" slope $$k = \frac{x^{n+1}-x^n}{\Delta t} = f (x^{n+1}, t^{n+1}),$$ since $x^{n+1} = x^n + \Delta t\\, k$ implies $k = f (x^n + \Delta t\\, k, t^{n+1})$.
-  In other words, being able to solve that equation for $k$ (given $x$, $t$ and $\Delta t$) is equivalent with being able to take a backward Euler step.
- A standard way to solve $f(x + \Delta t\\, k, t) - k = 0$ is with the Newton method $$k^{n+1} = k^{n} - \left[ \frac{\partial f}{\partial x}(\tilde{x}^n, t) \\, \Delta t - I \right]^{-1} \Big( f(\tilde{x}^n, t) - k^n \Big),$$ where $\tilde{x}^n := x + \Delta t\\, k^n$.
- The above is equivalent with applying the Newton method for determining $\tilde{x}$ from $\frac{\tilde{x}-x}{\Delta t} = f (\tilde{x}, t)$, i.e. $\Delta\\, t f (\tilde{x}, t) - \tilde{x} + x = 0$, which results in the iteration $$\tilde{x}^{n+1} = \tilde{x}^n - \left[ \Delta t\\, \frac{\partial f}{\partial x}(\tilde{x}^n, t) - I \right]^{-1} \Big( \Delta t\\, f(\tilde{x}^n, t) - \tilde{x}^n + x \Big).$$

**Comment by tzanio** [comment]
Discussion continued in #3443.
