### ISSUE TITLE
./ex1p -m ../data/periodic-cube.mesh

### ISSUE THREAD

**Issue by Watchmojo** [mfem/mfem#34]
Hi, 

I tried to run "./ex1p -m ../data/periodic-cube.mesh" and visualize with GLVis. It is equivalent to the fully-developed laminar solution in a square duct. However, I only see a perfectly blue cube. It seems that the periodic boundary condition is not applied?

Could you please explain to me why this happened? And, if I just want to simulate a fully-developed laminar solution in a square duct, do I need to modify "periodic-cube.mesh"? 

Thank you,
Frank

**Comment by tzanio** [comment]
Hi Frank,

By default Example 1 imposes zero Dirichlet boundary conditions on all six sides, which is why you see the blue cube. If you press the "i" key (twice) you will see the solution in the interior.

The boundary conditions are specified in terms of the boundary attributes. For example, to specify periodic boundary conditions only on the `x=0` and `x=1` faces, you can change the essential boundary attributes as follows:

```c++
   ess_bdr = 0;
   ess_bdr[0] = ess_bdr[2] = 1;
```

The corresponding solution on the `periodic-cube.mesh` looks like this:
![glvis_s01](https://cloud.githubusercontent.com/assets/1278247/12693543/afbb4aee-c6c1-11e5-82d0-bfc7159bcbc7.png)

You can walk through the different boundary attributes on a given mesh with the 'F9' and 'F10' keys. (Numbering in `ess_bdr` starts from zero.)

Hope this helps,
Tzanio

**Comment by Watchmojo** [comment]
Hi, Tzanio,

It worked perfectly. 

I figured out how the ess_bdr should be specified myself. However, I did not know it also affects the periodic boundary condition, because I thought the periodic boundary condition only defines the interconnection and is not actually a boundary. 

Thank you very much,
Frank

**Comment by Watchmojo** [comment]
Hi, Tzanio,

I also specified ess_bdr[3]=ess_bdr[5] = 1 and the same results appeared. Is it necessary do this?

Thank you,
Frank

**Comment by tzanio** [comment]
Hi Frank,

No, you don't need to specify these. Since the domain is periodic, the values on `ess_bdr[0]` and `ess_bdr[3]` are the same (in fact there is only one set of values in our finite element space). Therefore, setting `ess_bdr[0]` as a zero Dirichlet boundary implies that `ess_bdr[3]` is zero Dirichlet too.

To understand this better, try the same settings with `../data/inline-hex.mesh`, which is non-periodic mesh that has the same boundary attributes.

Cheers,
Tzanio

**Comment by Watchmojo** [comment]
Hi, Tzanio

It makes sense. Thank you very much.

Frank

**Comment by Watchmojo** [comment]
Hi, Tzanio

Could you please explain to me how the coordinates of vertices are specified in "periodic-cube.mesh"? I understood until the line 108 (nodes). How come there are 216 coordinates listed at the end instead of 27? 

Also, can I specify the collection points type in line: FiniteElementCollection: L2_T1_3D_P1? I read the code reading the mesh. Isn't the Gauss-Lobatto points and Gauss integration implemented as default? Why is the order of polynomial also specified in line FiniteElementCollection: L2_T1_3D_P1?

Thank you very much for your time.
Frank

**Comment by jakubcerveny** [comment]
Hi Frank,

For an explanation of periodic meshes, see my comment on another issue:
https://github.com/mfem/mfem/issues/18#issuecomment-145392592

Jakub

**Comment by Watchmojo** [comment]
Hi, Jakub,

I figured out the periodic meshes now. Thank you.

I have the following new questions:
1. How can I calculate d/dx, d/dy, dz for a scalar gridfunction?
   In ex1p, after obtaining the solution for x, I added:

    ParGridFunction wrk(fespace);
     x.GetDerivative(1,2,*wrk);
     x=(const Vector &)wrk;

    Is dx/dx2 calculated to wrk? 

2. I looked into GetDerivative, the dshape and inv_jac are calculated every time calculating the derivatives. Why not store these useful matrix instead? For my problem, I will use this derivative function a lot. 

Thank you very much for your time.
Frank

**Comment by Watchmojo** [comment]
Hi, Tzanio and Jakub,

I made a mistake while copying wrk to x. After fixing this mistake, I still see something incorrect. 

I run ex1p with periodic-cube.mesh, and only specified 1 ess_bdr. This is equivalent to the laminar solution in a 2d plane channel. The results seem to be okay. 
![snapshot1](https://cloud.githubusercontent.com/assets/16857800/12697742/37068cf0-c750-11e5-8141-230ae44cc069.png)

Then, I want to test the parabolic solution by plotting du/dz, which should be a linear variation. However, I saw du/dz are both 0 at walls. 
![snapshot2](https://cloud.githubusercontent.com/assets/16857800/12697753/821912da-c750-11e5-9ad6-da0026bcda04.png)

I then plotted d^2u/dz^2, which should be a constant. However, I saw something like this.
![snapshot3](https://cloud.githubusercontent.com/assets/16857800/12697774/e3e7d000-c750-11e5-9850-7c4c6455ccc1.png)

Here are my additional code in ex1p.cpp:
#define nwrks 20
...
ParGridFunction *wrks[nwrks];
for (int i=0;i<nwrks;i++) wrks[i]=new ParGridFunction (fespace);
...
   x.GetDerivative(1,2,*wrks[0]);
   x=(const Vector &)*wrks[0];   // du/dz
   x.GetDerivative(1,2,*wrks[0]);
   x=(const Vector &)*wrks[0];  //d^2u/dz^2

Could you please point out where I did wrong?

Thank you,
Frank
