### ISSUE TITLE
Reference for the implementation of the fe basis

### ISSUE THREAD

**Issue by edwardt9** [mfem/mfem#3420]
Dear developers,

I am reading the code in the fem/fe folder, where can I find the specific formulations for the RT and ND basis which could help me understand the code?

Thanks.

Best,
Thomas

**Comment by v-dobrev** [comment]
Take a look at #566 and #1311.

Specifiically, the RT basis definition on triangles/tets is described here: https://github.com/mfem/mfem/issues/566#issuecomment-412405129. The construction on quads/hexes uses similar degrees of freedom, however the basis evaluation is simpler because one can take advantage of the tensor-product structure of the basis.

Let us know if you have any questions.

**Comment by edwardt9** [comment]
Hi @v-dobrev , I have looked at issues #566 and #1311, however, I am still not clear about the explicit mathematical formulas used for the basis. Are there any papers or textbooks I can read as a reference?

**Comment by edwardt9** [comment]
> * Mixed Finite Element Methods and Applications, Daniele Boffi, Franco Brezzi, Michel Fortin. [chapter 2]
> * Finite Element Methods for Maxwell's Equations, Peter Monk. [chapters 5, 6]

Hi @v-dobrev , thanks for the books, I will read them and try to understand FEM.

> Note that the vector finite element bases used by MFEM are nodal (i.e. the DOFs are the vector values at a set of points, called nodes, dotted with a normal/tangential vector associated with each node). This choice of DOFs generally gives rise to basis functions different from the descriptions in the books above. However, the discrete function spaces spanned by these basis functions are the same.

This may be the reason why the implementation of the basis is hard to understand. In some books, the formulas of the basis are explicit, so it is easier to understand for people like me not so deep in math and FEM.
