### ISSUE TITLE
Strange exception thrown in UniformRefinement() for twist mesh miniapp

### ISSUE THREAD

**Issue by i3s93** [mfem/mfem#3421]
Hello, I would like to generate highly refined meshes using the Twist mesh example code provided in the mesh miniapps directory, but I am seeing some strange output. For example, with the serial build, if I run `./twist -o 3 -nt 6 -rs 8 -e 8`, the program gives the following exception:
```
terminate called after throwing an instance of 'std::bad_array_new_length'
what():  std::bad_array_new_length
Aborted
```
However, if I reduce the number of serial refinements (changing `-rs 8` to `-rs 6`) the same program completes as expected. Is there a particular reason why this behavior occurs? For the record, I'm using the Intel/19.1.1 compiler on the current master branch of MFEM. Thank you in advance for any clarification you can provide on the matter.

**Comment by v-dobrev** [comment]
This is probably due to 32-bit integer overflow for the 3rd order mesh nodes.

At `-rs 6` there are 786,432 hexes and the number of nodes per element is 4^3=64 for a total of 50,331,648 nodes. Each additional level of refinement multiplies that number by 8, so for `-rs 8` one will have 3,221,225,472 nodes each with (x,y,z) component, so the nodal grid function will have almost 10 billion doubles (~80 GiB). Since we use `int` to store and specify sizes of `Vector`, `GridFunction`, etc these sizes are too big.

With quadratic elements (`-o 2`) and `-rs 8`, the nodal grid function will need about 4 billion doubles (32 GiB), so that will overflow the 32-bit `int` too.

With linear elements (`-o 1) `-rs 8` will probably work. For higher orders, you will need to run in parallel where only local sizes use 32-bit `int` and global sizes can be 64-bit (by configuring hypre with "big-int" or "mixed-int").

**Comment by v-dobrev** [comment]
Note that `twist` performs the twisting transformation at the coarsest mesh and then performs uniform refinements, so you do not need to save refined meshes. You can save a coarse mesh, then read it in your app, perform serial refinements, followed by parallel refinements and then solve the PDE problem of interest.

If you need to capture the twisting transformation more accurately, the app needs to be modified to perform the twisting transformation after some uniform refinements. Maybe just using higher mesh order (e.g. `-o 6`) may work well without modifying the app -- one can then drop to lower mesh-orders as the mesh is refined.

**Comment by i3s93** [comment]
Thank you @v-dobrev for looking into this issue. The overflow error makes sense for this use case. I will play around with this app some more and will close the issue.
