### ISSUE TITLE
Modifying assembled HypreParMatrix

### ISSUE THREAD

**Issue by sethwatts** [mfem/mfem#3448]
I am trying to solve an adjoint sensitivity problem where the coefficient matrix is singular (even when essential BCs are applied) but consistent. That is, solutions exist, but are not unique, and I just need any valid solution. When I solve the problem for a 2D mesh, a Krylov solver is able to handle the singularity and provide a solution; however, in 3D it is not able to do so. 

I can fix the singularity by augmenting the assembled matrix and then later making an adjustment to the solution due to the augmentation. Essentially I just want to add one to a given component on the matrix diagonal. Is it possible to do this to an assembled HypreParMatrix? None of the public methods, or those of Operator, suggest this is an intended use. Is it possible to update the matrix via accessors to the local diagonal? Or should I try to create another HypreParMatrix that is zero everywhere except for the augmentation and add that to the original system?

**Comment by tzanio** [comment]
Hi Seth,

How big is the nullspace of the matrix?

If it is something like constants in a pure Neumann problem, you just can iterate in the orthogonal complement of the nullspace (where the problem is nonsingular). This could be implemented with an `Operator` that first multiplies by the matrix and then removes the nullspace component with a projection like $I - P (P^T P)^{-1} P^T$ where `P` is a matrix with columns given by the nullspace vectors (so $P^T P$ is easy to invert).

Alternatively you can construct a block Operator that has the matrix in the (1,1) block and additional entries in the (1,2) and (2,2) blocks. This will be simpler (and more efficient) than enlarging the matrix.

Does this make sense?

Tzanio

**Comment by sethwatts** [comment]
Hi Tzanio -

Usually the nullspace is of dimension one, and even when it's larger I should have a basis. The representation of the basis is as HypreParVectors. Is there a convenient way to form their outer product $P P^T$ (or more often $v v^T$)? That would certainly solve my problem.

**Comment by tzanio** [comment]
Yes, if you have the columns of $P$ as `HypreParVectors`, say $v_1\, \ldots, v_k$ then you need to invert the $k \times k$ matrix $$(P^T P)_{ij} = v_i^T \cdot v_j$$ where each entry is just a call to `double InnerProduct(HypreParVector &, HypreParVector &)`.

When $k=1$, the projection is just $x_{out} = x_{in} - \alpha\,  v$, where $\alpha  = (v^T \cdot x_{in})/(v^T \cdot v)$.

For larger $k$, we have $x_{out} = x_{in} - P w$, where $w$ solves $(P^T P) w = P^T x_{in}$.

**Comment by tzanio** [comment]
Yes, `DenseMatrix` (or just `double` when $k=1$)

**Comment by sethwatts** [comment]
Thanks! Marking this issue closed.
