### ISSUE TITLE
Computing a field E of 3 components in the example 22

### ISSUE THREAD

**Issue by sp3c333** [mfem/mfem#3453]
Hello,

I am trying to implement a code computing E in the equation : Nabla X Nabla X E - k0^2* K* E=0
with K a matrix(3X3) composed of a real part and an imaginary part. Could you please explain to me how to compute a field (Ex,Ey,Ez) that has 3 components and then plot them in glvis?

I am using the example 22,31,32p to help me. It seems that these examples are computing a field of 1 component only. 

The following is what I have been trying to do: 
Use a "sesquilinearform" and separate the matrix "K" in real and imaginary parts: 
            a.AddDomainIntegrator(new CurlCurlIntegrator(stiffnessCoef), NULL);
            a.AddDomainIntegrator(new vectorFEMassIntegrator(K_real),new VectorFEMassIntegrator(K_imag));
Use E.projectBdrCoefficientTangent(Er,Ei,ess_bdr) to create a source that is located on the boundary (an antenna)

**Comment by mlstowell** [comment]
Hello, @sp3c333,

Sorry for the delayed reply. It sounds like you're looking in the right places. The Nedelec finite element space, used in `ex31p` for example, uses vector-valued basis functions so this example solves for a 3 component vector field. The visualization is all laid out there in lines 252-409. This example is a little more complicated than you might need because it handles 3 component vector fields on 1D and 2D meshes as special cases. The 3D case is fairly straight-forward by comparison.

If you have more specific questions I'd be more than happy to offer advice.

Best wishes,
Mark
