### ISSUE TITLE
need to set 'num_global_cols = n;', othersize will have release error?

### ISSUE THREAD

**Issue by zhuyidong-YP** [mfem/mfem#3463]
https://github.com/mfem/mfem/blob/61b394409bca6a9ecd3319c5a42d7eaedd5de5e6/linalg/superlu.cpp#L133

**Comment by v-dobrev** [comment]
Thank you for reporting this issue.

If I understand the issue correctly: we need to initialize the data member `num_global_cols` in the constructor you linked, otherwise that variable remains uninitialized. In turn, that can lead to problems when we use that uninitialized value (via the call `APtr_->GetGlobalNumColumns()`) here: https://github.com/mfem/mfem/blob/61b394409bca6a9ecd3319c5a42d7eaedd5de5e6/linalg/superlu.cpp#L270
 
Did I understand you correctly?

**Comment by zhuyidong-YP** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
