### ISSUE TITLE
CMake build system is missing hdf5_hl library

### ISSUE THREAD

**Issue by white238** [mfem/mfem#3467]
The following PR commented out logic to inject the hdf5_hl library after NetCDF but before the regular hdf5 library:

https://github.com/mfem/mfem/pull/3348

Specifically in the `config/cmake/modules/FindNetCDF.cmake`.

In Serac's use case, the `config/cmake/modules/FindHDF5.cmake` is never called, which would handle the ordering of the HDF5 libraries correctly. I am almost sure your file is actually never called. The `find_package(hdf5)`, buried in your `mfem_find_package` macro is calling the CMake FindHDF5 module.

I attempted to look into making the `mfem_find_package` handle the injection but didn't have time.

This is blocking Serac moving forward to anything after #3348.

**Comment by v-dobrev** [comment]
In MFEM's `CMakeLists.txt`, the variable `CMAKE_MODULE_PATH` is set too the directory `${PROJECT_SOURCE_DIR}/config/cmake/modules` -- that's why any `find_package` calls after that use the `FindXXX.cmake` files from there. Therefore, when we call `find_package(HDF5 ...)` through `mfem_find_package(NetCDF ...)` we should load MFEM's version of `FindHDF5.cmake`. Maybe that file is not actually read because `HDF5_FOUND` is already set to `TRUE`, e.g. if you called `find_package(HDF5 ...)` earlier?

In any case, I'm not sure why the MFEM version of `FindHDF5.cmake` was actually added (maybe @ptsuji can clarify the reasoning for adding it in #3117) and I added a comment about potential issues with that here: https://github.com/mfem/mfem/blob/61b394409bca6a9ecd3319c5a42d7eaedd5de5e6/config/cmake/modules/FindHDF5.cmake#L17-L21

In #3348 I commented the line (in `FindNetCDF.cmake`)
```cmake
list(INSERT NETCDF_LIBRARIES 1 ${HDF5_C_LIBRARY_hdf5_hl})
```
because it was breaking the standalone MFEM CMake build -- `HDF5_C_LIBRARY_hdf5_hl` was undefined and the `list` command was giving an error, if I remember correctly.

That said, from your experience described above, it looks like there are scenarios where reading MFEM's `FindNetCDF.cmake` does not actually read MFEM's `FindHDF5.cmake` but the one provided by CMake itself. I guess we can support both cases by checking if `HDF5_C_LIBRARY_hdf5_hl` is defined and calling the above `list(INSERT ...)` only in that case.

**Comment by white238** [comment]
I agree it should be calling your `FindHDF5.cmake`. I originally tested it by putting a message at the top of your file because I was in a hurry.

Due to my own stubbornness, I figured out CMake is not calling your `FindHDF5.cmake` because of the `NAMES` parameter on this line:

https://github.com/mfem/mfem/blob/8053bc25e42003368e09902d37b300fd94e9a5d6/config/cmake/modules/MfemCmakeUtilities.cmake#L392-L393

That is pretty baffling behavior.

That said, I am fine with whatever fix you feel comfortable with. The easiest solution is to possibly guard the `list(INSERT ...)` against a undefined variable.

**Comment by v-dobrev** [comment]
Do you set `NetCDF_TARGET_NAMES`? If not, the following `find_package` command should be called: https://github.com/mfem/mfem/blob/8053bc25e42003368e09902d37b300fd94e9a5d6/config/cmake/modules/MfemCmakeUtilities.cmake#L388
with `${ReqPack}` -> `HDF5`, `${Required}` -> `REQUIRED`, `${Quiet}` -> `<empty>`, `${PackComps}` -> `C;HL`. These values come from the default setting of the variable `NetCDF_REQUIRED_PACKAGES`: https://github.com/mfem/mfem/blob/8053bc25e42003368e09902d37b300fd94e9a5d6/config/defaults.cmake#L189-L190

---

In any case, can you check if replacing this line: https://github.com/mfem/mfem/blob/8053bc25e42003368e09902d37b300fd94e9a5d6/config/cmake/modules/FindNetCDF.cmake#L40
with
```cmake
if (HDF5_C_LIBRARY_hdf5_hl)
  list(INSERT NETCDF_LIBRARIES 1 ${HDF5_C_LIBRARY_hdf5_hl})
endif()
```
fixes the issue for you?

**Comment by white238** [comment]
We set the following before including MFEM in our build system for what we call the codevelop build:

https://github.com/LLNL/serac/blob/9daf004fad3a00f3b3b7fedfb87ac0ef4621d4e9/cmake/thirdparty/SetupSeracThirdParty.cmake#L208-L211

https://github.com/LLNL/serac/blob/9daf004fad3a00f3b3b7fedfb87ac0ef4621d4e9/cmake/thirdparty/SetupSeracThirdParty.cmake#L241-L244

Could setting the `HDF5_TARGET_NAMES` possibly be the difference since NetCDF depends on HDF5 in your macro?

As for the testing the `if` guard, I can do that tomorrow morning.

**Comment by v-dobrev** [comment]
Oh, my mistake: how we call `find_package` for HDF5 depends on `${ReqPack}_TARGET_NAMES`, i.e. `HDF5_TARGET_NAMES` and not `NetCDF_TARGET_NAMES`. That's what makes sense. So yes, since you set `HDF5_TARGET_NAMES` we end up using the `find_package` call that you linked. Sorry about the confusion.

So basically the idea is that you can circumvent the use of any `FindHDF5.cmake` module by setting `HDF5_TARGET_NAMES` which means we use `find_package` in "config mode" to search for `${target_}Config.cmake` (or `<lowercase ${target_}>-config.cmake`) where `target_` loops over the list `HDF5 ${HDF5_TARGET_NAMES}`. So with your setup, it looks like CMake will try to find the `HDF5Config.cmake` file that is typically installed by HDF5 itself when build and installed. This config files have their own conventions that differ a bit from the CMake-provided HDF5 module (and MFEM's HDF5 module).

Hopefully, adding the `if` guard will solve the issue for you and it should also work in a default MFEM CMake build with NetCDF enabled.

**Comment by white238** [comment]
I have confirmed that uncommenting out the `set(HDF5_ROOT ...)` and adding the if guard works in Serac.

**Comment by v-dobrev** [comment]
> @v-dobrev , I have confirmed that uncommenting out the `set(HDF5_ROOT ...)` and adding the if guard works in Serac.

Is this `set(HDF5_ROOT ...)` something in Serac or is it somewhere in MFEM?

**Comment by white238** [comment]
https://github.com/mfem/mfem/blob/61b394409bca6a9ecd3319c5a42d7eaedd5de5e6/config/cmake/modules/FindNetCDF.cmake#L21

**Comment by v-dobrev** [comment]
I see. Okay, I'll add these fixes in #3384.

**Comment by v-dobrev** [comment]
Done in 93cdcae1. Let me know if something does look right.

**Comment by white238** [comment]
@v-dobrev  thanks for the quick turn around!

**Comment by v-dobrev** [comment]
By the way, I added a few tweaks to the MFEM CMake build system (in #3384) that may help you simplify a bit the MFEM configuration in Serac: specifically, I think you should be able to just set
```cmake
set(HDF5_TARGET_NAMES "hdf5::hdf5_hl-static;hdf5::hdf5_hl-shared" CACHE STRING "")
```
and there should be no need to set `HDF5_IMPORT_CONFIG` (the first imported config will be used, if the `RELEASE` config is not available) and `HDF5_C_LIBRARY_hdf5_hl` (note that the `*hdf5_hl*` target is used in `HDF5_TARGET_NAMES`).

Also, it may be the case that the new `FindHDF5.cmake` may just work for you (as long as you set `HDF5_DIR`) without setting any of the variables `HDF5_{TARGET_NAMES,IMPORT_CONFIG,C_LIBRARY_hdf5_hl}`.
