### ISSUE TITLE
Potential bug in `mesh-explorer` from #3410

### ISSUE THREAD

**Issue by sebastiangrimberg** [mfem/mfem#3473]
https://github.com/mfem/mfem/pull/3410/files#diff-8c56ee51990f1f1cdac4f81ba286545405a6e164a04aeeec6796cd4a9af58129R962

```
int *part = mesh->CartesianPartitioning(nxyz);
partitioning = Array<int>(part, mesh->GetNE());
delete [] part;
recover_bdr_partitioning(mesh, partitioning, bdr_partitioning);
```

Is this a bug? As I understand (and as documented), this `Array` constructor doesn't inherit ownership of the data so the `part` pointer is free'd before being used in `recover_bdr_partitioning`. I think `delete [] part` needs to be moved to after the function call, but just wanted to ask first.

**Comment by v-dobrev** [comment]
The logic here is that `part` is temporarily wrapped by the temporary object `Array<int>(part, mesh->GetNE())` which is then copied (since `Array<T>` has no move assignment) to the `partitioning` object which has its own memory allocated. After the copy, `part` is no longer needed.

However, if we add a move assignment to `Array<T>` then
```c++
   partitioning = Array<int>(part, mesh->GetNE());
```
will invoke the move assignment after the constructor which will mean that `partitioning` will use `part` and there will be issues. To avoid this potential future problem, we can explicitly call the copy constructor by casting to rhs to a const reference. We have a function that does that in a convenient way: https://github.com/mfem/mfem/blob/61b394409bca6a9ecd3319c5a42d7eaedd5de5e6/general/array.hpp#L349-L350

However, in order to use it as
```c++
   partitioning = AsConst(Array<int>(part, mesh->GetNE()));
```
I had to change the definition a bit, making it a bit more general by switching its argument from `T&` to `const T&`:
```c++
template <typename T> const T &AsConst(const T &a) { return a; } 
```

**Comment by sebastiangrimberg** [comment]
Aha, I see now. Thank you @v-dobrev for the explanation! I learned something new today.
