### ISSUE TITLE
Combination of Sundials + SuperLU not working with 64bit integer

### ISSUE THREAD

**Issue by jandrej** [mfem/mfem#349]
The lines in 
https://github.com/mfem/mfem/blob/bc6b48421ac6506db6fea2f9d6222f145427f8c8/linalg/superlu.cpp#L71

prevent the usage combination of Sundials and SuperLU with 64bit integers.

**Comment by tzanio** [comment]
Can you clarify your use case? Do MFEM, SUNDILAS and/or SuperLU use 64-bit integers?

**Comment by juan42** [comment]
I was a bit short on time while writing this, sorry.

So if i compile hypre with 64bit integers, SuperLU with 64bit integers and then SUNDIALS with the hypre interface and 64bit (which is the default), i can not compile MFEM because of incompatible interfaces in SuperLU. The combination of SUNDIALS/hypre MFEM works flawlessly.

The errors occur in
https://github.com/mfem/mfem/blob/bc6b48421ac6506db6fea2f9d6222f145427f8c8/linalg/superlu.cpp#L81

because the interface expects long long int instead of int if SuperLU is compile with 64bit support.

**Comment by v-dobrev** [comment]
You are right, this a use case we have not tested but we should support. Thanks for reporting the issue.

**Comment by tzanio** [comment]
@jandrej and @gardner48 can you comment on this issue?

**Comment by jandrej** [comment]
This is a very specific use case since it involves building all depending libraries with 64bit integer support. I think that no urgent fix is needed until there is demand for using SuperLU on this large dof numbers.

If there is, I'm happy to get involved. A temporary pitfall prevention would be a compile time warning that we do not support SuperLU in a dependency chain with 64 bit integers right now.

**Comment by gardner48** [comment]
I agree with @jandrej's idea of printing a warning about 64-bit integer support. The Sundials configuration header 'include/sundials/sundials_config.h` will contain the macro `#define SUNDIALS_INT64_T 1` or  `#define SUNDIALS_INT32_T 1` to indicate if it was built with 32 or 64-bit integers. I know SuperLU_DIST has a defines a similar macro but I don't think that SuperLU does.

**Comment by tzanio** [comment]
@jandrej wrote in https://github.com/mfem/mfem/issues/349#issuecomment-496618310:
> If there is, I'm happy to get involved. A temporary pitfall prevention would be a build/configure time warning that we do not support SuperLU in a dependency chain with 64 bit integers right now.

Can you propose a PR please?

**Comment by tzanio** [comment]
Discussion continued in #1150.
