### ISSUE TITLE
2D possion eqution in FEM with MPI in 2 progress details

### ISSUE THREAD

**Issue by xigetongkuaizao** [mfem/mfem#3517]
I cannot figure out the 2D  possion eqution in FEM with MPI. In case there are two grids,one is composed of point(1 2 3),two is composed of point(2 3 4) ，and how to solve the electric potential of point(2 3) x2 x3 in 2 MPI progress? while the x1 and x4 is given with ρ1 ρ4. 
![image](https://user-images.githubusercontent.com/97080450/222306438-f0395178-c12e-4b8b-851b-7318336eab74.png)

**Comment by mlstowell** [comment]
Hello, @xigetongkuaizao,

This is a very large question which could be answered with varying levels of detail. For an overview of MFEM's design you might find this [publication](https://arxiv.org/abs/1911.09220) useful.

A greatly abbreviated version is that MFEM's `ParMesh`  object determines which processors are responsible for which elements with each element residing on exactly one process. Based on this mesh "partitioning" the `ParFiniteElementSpace` then determines which processors are responsible for which degrees-of-freedom (DoFs).

The finite element level objects in MFEM maintain copies of DoFs from neighboring processors so that they can compute local interpolations whenever necessary. The linear algebra level objects do not have such copies but they maintain communication patterns so that they can compute matrix-vector products, inner products, etc..

Partitioning details are generally hidden from the user so things like sources and boundary conditions are typically handled by objects which exist on all processors.

In the above example processor 1 would manage DoFs 1, 2, and 3 while processor 2 would manage DoF 4. The system matrix would be distributed across both processors with processor 1 storing rows 1 through 3 and processor 2 storing only row 4.

Best wishes,
Mark

**Comment by xigetongkuaizao** [comment]
I just take a look the MPI in PCG algorithm about the domain decomposition.I just wonder that the MFEM is using likness method?  for the PICTHURE :2D Possion eqution, 2 progress ,each have 2 grid.  @mlstowell 
![image](https://user-images.githubusercontent.com/97080450/223596897-ba64b64d-98fb-4e29-bc10-4cab05a99304.png)

**Comment by mlstowell** [comment]
Hello, @xigetongkuaizao,

Of course we do something similar but it is not exactly what you describe. During our `ParBilinearForm::Assemble` phase we do form the two 6x6 matrices that you show above. Then we call `ParBilinearForm::ParallelAssemble` which builds two new matrices on each processor. On processor 1 we would have a 6x6 matrix for the locally owned dofs and  a 6x2 matrix to multiply by rows 7 and 8 of the global vector. On processor 2 a 4x4 matrix for the locally owned dofs and a 4x2 matrix to multiply by rows 5 and 6 of the global vector.

During a matrix-vector multiplication we first use MPI to send the necessary entries from the vector `x` to the other processor; processor 1 sends `x5` and `x6` to processor 2 and processor 2 sends `x7` and `x8` to processor 1. Then processor 1 computes entries `b1`-`b6` and processor 2 computes `b7`-`b10`.

Best wishes,
Mark

**Comment by xigetongkuaizao** [comment]
thanks,mark! In case have a misunderstanding, I write it. and the a55 a56 a65 a66 is assemble by 2 grid in different progress reduce to progress 1. and I can do Matrix:A multiply Vector:p while p=[x1 x2 x3 ...x10],so I can get the q=A multiply p (q=[b1 b2 ...b10]) in your describe. Am I right? @mlstowell 
![image](https://user-images.githubusercontent.com/97080450/223632072-c70fadea-1b70-4ce1-9733-7266eb3fb605.png)

**Comment by mlstowell** [comment]
Yes, these matrix equations look correct.
