### ISSUE TITLE
Topology Optimization with HiOp

### ISSUE THREAD

**Issue by ricgross** [mfem/mfem#3545]
Hello everyone!

I am trying to solve a topology optimization problem via a density-based approach (SIMP), where the target is to minimize the compliance (objective function) while a volume constraint is set in place. I have looked through #3400, however I would like to solve the problem using HiOp. I have looked through the HiOp modification of `ex9` but I still have some doubts in how to implement the use of the HiOp solver in my problem.

`ex9` defines a derived class of `OptimizationProblem`, where the equality and inequality constraints (implemented via custom operators) are set. Furthermore, within the `OptimizationProblem` derived class, both the `CalcObjective` and `CalcObjectiveGrad` are redefined. 

My question is the following. In order to calculate the compliance, the nodal displacements from the FE analysis are required.  

![image](https://user-images.githubusercontent.com/112960841/225860869-3af989bc-7b2f-4c2c-9764-01b2c09e3d49.png)

This brings me to assume that I should implement the FE solve to get nodal displacements within the `CalcObjective` function. However, I also need to use the nodal displacements when calculating the sensitivities (i.e. gradients), thus in the `CalcObjectiveGrad` function. 
Can I avoid this issue by calling the FE solve within the definition of the `OptimizationProblem` or do I need to call for the FE solve twice, i.e. both in the `CalcObjective` and `CalcObjectiveGrad` functions? 

In advance, thanks for helping.

Best regards,
Riccardo

**Comment by vladotomov** [comment]
Hi Riccardo,

If it's the same calculation you should do it once of course. I guess the question is how to recognize that `CalcObjective` and `CalcObjective` are called with the same `Vector x` input. Unfortunately this can't be done with the present MFEM interface, but I see that HiOp provides a `bool new_x` in `HiopOptimizationProblem::eval_f` and `HiopOptimizationProblem::eval_grad_f`, see `linalg/hiop.cpp`.

So this `bool new_x` would be easy to add to the MFEM interface. Do you want to try it and make a new MFEM PR? It can be a member in `OptimizationProblem`, updated in the above HiOp adapter functions.

**Comment by ricgross** [comment]
Hi @vladotomov,

Thank you for your prompt reply.

I don't think I have understood your point entirely. Wouldn't the vector `x` be constituted by the physical densities of the elements, i.e. the design variables to be optimized?

**Comment by cnpetra** [comment]
what @vladotomov suggests should work. In your `class TopOpt :: public OptimizationProblem` have a helper method `evalFE` that does the FE analysis, computes the objective and the gradient, and stores in class members. Then in `TopOpt::eval_f` and `TopOpt::eval_grad_f` check whether you already have  `evalFE` at the `x` passed by HiOp to these methods; if yes pass the stored objective/gradient to HiOp; otherwise trigger a call to `evalFE(x)` and then pass the stored objective/gradient to HiOp.  

Do not assume that `eval_f` is called before `eval_grad_f` or the other way around.

In the meanwhile, we will coordinate to have the HiOp's "new_x" feature in MFEM. This will tell your TopOpt class when a "new" x is passed to `eval_f` and `eval_grad_g` so you can trigger evalFE without having to keep track that a new `x` is coming from HiOp.

**Comment by cnpetra** [comment]
I sugges to also take a look at this paper on HiOp's performance on some topology optimization problems: https://www.tandfonline.com/doi/abs/10.1080/10556788.2022.2117354

**Comment by ricgross** [comment]
Hi @cnpetra,

Thank you for your comprehensive reply.

I have a small question: when modifying the methods `eval_f` and `eval_grad_f` within `class TopOpt : public OptimizationProblem`, is it sufficient to simply add this check?

```
if (new_x)
{
evalFE(x_vec);
}

```
Would this guarantee that the `evalFE` does not get called twice?

**Comment by cnpetra** [comment]
I apologize, I mislead you a bit. You should overload `TopOpt::CalcObjective` and `TopOpt::CalcObjectiveGrad` (instead of `eval_f` and `eval_grad_f`). Everything I said about these functions still applies. 

I think these `TopOpt` overloads should look something like this:
```
virtual double CalcObjective(const Vector &x) const
{
    if ||x-x_last_||>1e-14 
    {
        evalFE(x); //-> fills in obj_ and grad_
        x_last_ = x; //save values of x in the member x_last_
    }
    return obj_;
}

virtual void CalcObjectiveGrad(const Vector &x, Vector &gradx) const
{
    if ||x-x_last_||>1e-14 
    {
        evalFE(x); //-> fills in obj_ and grad_
        x_last_ = x; /save values of x in the member x_last_
    }
    //copy values of grad_ to gradx
    gradx = grad_;
}
```

This [example](https://github.com/mfem/mfem/blob/701870a7daea3f846613feb296b2f71a6afd007e/examples/hiop/ex9.cpp#L137) should cover your setup. 

Including how you can to set up your mass/volume constraint in `TopOpt`, see [this](https://github.com/mfem/mfem/blob/701870a7daea3f846613feb296b2f71a6afd007e/examples/hiop/ex9.cpp#L109).

**Comment by vladotomov** [comment]
@ricgross see [this PR](https://github.com/mfem/mfem/pull/3552), let me know if it works. As Cosmin wrote, you can use `NewX()` in your problem's `CalcObjective` and `CalcObjectiveGrad`.

**Comment by ricgross** [comment]
Hi @cnpetra and @vladotomov,

Thank you for your help. 

I managed to make the script work  in both ways, i.e. either by including the changes suggested by @cnpetra in his previous comment, or by making use of the `NewX()` method @vladotomov implemented.  The latter is more elegant.

Just wanted to say thank you once again, as it will for sure help making my master's thesis even better :)
