### ISSUE TITLE
Compilation problem

### ISSUE THREAD

**Issue by Tomcat4891** [mfem/mfem#3593]
Hi.

Tried to compile the mfem.
The current version (git clone) gives the error:

...... linalg/strumpack.cpp (226) : error: no operator "<<" matches these operands
operand types are : std ::basic_ostream<char,std::char_traits> << strumpack::ReturnCode
MFEM_ABORT("STRUMPACK: 'factor()', error code = " << ret);

No such error for the version 4.4.

BR,
Andrew

**Comment by v-dobrev** [comment]
Interesting, maybe this is something new with new versions of STRUMPACK. What version of STRUMPACK are you using? For the MFEM v4.5.2 release, I tested with STRUMPACK v7.0.1 and that worked fine.

@pghysels, were there any recent changes to `strumpack::ReturnCode`?

In the meantime you can just comment out the printing of `ret`:
```c++
         MFEM_ABORT("STRUMPACK: 'factor()' error code = " /* << ret */);
```

**Comment by pghysels** [comment]
I don't recall any recent changes to `ReturnCode`.
We have this routine
```
inline std::ostream& operator<<(std::ostream& os, ReturnCode& e) { ...
```
in `StrumpackParameters.hpp`. Only thing I can think of is that it would be better to make the `ReturnCode& e` `const`?

**Comment by v-dobrev** [comment]
Making the argument `ReturnCode& e` `const` is a good idea. However, that should not be a problem here: https://github.com/mfem/mfem/blob/d4bc14a48a1781ae4f7a16855f98c491f1e98389/linalg/strumpack.cpp#L226
since `ret` is not `const`.

@Tomcat4891, in addition to the version of STRUMPACK that you are using, can you also post what compiler you are using and its version? I wonder if this error may be due to an older compiler.

**Comment by Tomcat4891** [comment]
My version of the strumpack package is 6.3.1.
I use the intel opeapi  toolkit  2023 :  mpiifort , mpiicpc, mpiicc

The Mfem 4.4 works fine, whereas the git clone version does not compile.

**Comment by Tomcat4891** [comment]
> Interesting, maybe this is something new with new versions of STRUMPACK. What version of STRUMPACK are you using? For the MFEM v4.5.2 release, I tested with STRUMPACK v7.0.1 and that worked fine.
> 
> @pghysels, were there any recent changes to `strumpack::ReturnCode`?
> 
> In the meantime you can just comment out the printing of `ret`:
> 
> ```c++
>          MFEM_ABORT("STRUMPACK: 'factor()' error code = " /* << ret */);
> ```

My version of the strumpack package is 6.3.1.
I use the intel opeapi toolkit 2023 : mpiifort , mpiicpc, mpiicc

The Mfem 4.4 works fine, whereas the git clone version does not compile.

**Comment by v-dobrev** [comment]
Looks like the issue is that STRUMPACK v6.3.1 did not define
```
std::ostream& operator<<(std::ostream& os, ReturnCode& e)
```
which is fine in MFEM v4.4 (and v4.5) because they do no attempt to print `ret`:
```
         MFEM_ABORT("STRUMPACK: 'factor()' error code = " << ret);
```
The print was added in MFEM v4.5.2 (and is also in `master`).

We can add a workaround for this in MFEM `master`.

@Tomcat4891, is it a problem for you to just switch to STRUMPACK v7.0.1? That should resolve the issue, I think.

**Comment by Tomcat4891** [comment]
Thank you for your reply. Yes, I will switch to strumpack 7.x + mfem 4.5.2 a bit later.
