### ISSUE TITLE
InnerProductCoefficient and ProjectCoefficient with GridFunction made with Nedelec elements

### ISSUE THREAD

**Issue by sp3c333** [mfem/mfem#3628]
Hello MFEM team,

Using the following code, I have encountered an error but I have not found the solution in mfem. Could you please help me to solve this error ? 

I am trying to decompose my 3D electric field computed through the wave equation into 3 components (along X,Y,Z) however the use of nedelec element is stopping me.

//u is the electric field in 3D with 3 component in each direction (x,y,z) defined using nedelec:
FiniteElementCollection* fec = NULL;    
fec = new ND_FECollection(order, dim);    
ParFiniteElementSpace* fespace = new ParFiniteElementSpace(pmesh, fec);
ParComplexGridFunction u(fespace);
.
.
.
a->RecoverFEMSolution(U, b, u);

GridFunction ur(fespace);
GridFunction ui(fespace);
ur = u.real();
ui = u.imag();

VectorGridFunctionCoefficient solCoefR(&ur);
VectorGridFunctionCoefficient solCoefI(&ui);

Vector xVec(3); xVec = 0.0; xVec(0) = 1;
VectorConstantCoefficient xVecCoef(xVec);
Vector yVec(3); yVec = 0.0; yVec(1) = 1;
VectorConstantCoefficient yVecCoef(yVec);
Vector zVec(3); zVec = 0.0; zVec(2) = 1;
VectorConstantCoefficient zVecCoef(zVec);

H1_FECollection fec_h1(order, dim);
ND_FECollection fec_nd(order, dim);

ParFiniteElementSpace fes_h1(pmesh, &fec_h1);
ParFiniteElementSpace fes_nd(pmesh, &fec_nd);

//What I had which run but probably leads to wrong field value due to the change of finite element:
//More specifically, I have non null tangential field while considering metallic BC, using tethradral mesh, it should lead to a null field  
ParGridFunction xCompR(&fes_h1);
ParGridFunction yCompR(&fes_h1);
ParGridFunction zCompR(&fes_h1);
ParGridFunction xCompI(&fes_h1);
ParGridFunction yCompI(&fes_h1);
ParGridFunction zCompI(&fes_h1);

//What I want to use but leads to an error at execution: 
ParGridFunction xCompR(&fes_nd);
ParGridFunction yCompR(&fes_nd);
ParGridFunction zCompR(&fes_nd);
ParGridFunction xCompI(&fes_nd);
ParGridFunction yCompI(&fes_nd);
ParGridFunction zCompI(&fes_nd);

xCompR.ProjectCoefficient(xCoefR);
yCompR.ProjectCoefficient(yCoefR);
zCompR.ProjectCoefficient(zCoefR);
xCompI.ProjectCoefficient(xCoefI);
yCompI.ProjectCoefficient(yCoefI);
zCompI.ProjectCoefficient(zCoefI);

The error occurs at the step with ProjectCoefficient and here is a the error message : 
MFEM abort: method is not overloaded
 ... in function: void __cdecl mfem::FiniteElement::Project(class mfem::Coefficient &,class mfem::ElementTransformation &,class mfem::Vector &) const
 ... in file: C:\Users\XXXX\MFEM_Windows\mfem-4.5-new\mfem-4.5\fem\fe\fe_base.cpp:128
Abort(1) on node 0 (rank 0 in comm 0): application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0

However, I noticed in ex24p that : 
//In example 24p:
int sdim = mesh->SpaceDimension();
FiniteElementCollection *trial_fec = NULL;
trial_fec = new ND_FECollection(order, dim);
ParFiniteElementSpace trial_fes(pmesh, trial_fec);
ParGridFunction gftrial(&trial_fes);
VectorFunctionCoefficient v_coef(sdim, v_exact);
//here is the part where the project coefficient work //with nedelec but using a vectorFunctionCoefficient:
gftrial.ProjectCoefficient(v_coef);

Therefore, Could you help me to isolate on a GridFunction each component of my 3D field defined using nedelec element ? Your help would be very appreciated.

Best regards.

**Comment by mlstowell** [comment]
Hi, @sp3c333,

There's a lot to go through here but let's start with the error you're seeing. The message is not very clear but I believe the cause is that you're trying to project a scalar-valued coefficient onto a  vector-valued `ParGridFunction`. This will not work.

You say you want to decompose the Nedelec fields into three separate Nedelec fields representing the x, y, and z, components of the original field. Is this correct? If so you should be aware that the resulting vector fields will not appear to be perfectly aligned with the x, y, and z directions. We can discuss your options but I'd need to know about your requirements.

Best wishes,
Mark

**Comment by sp3c333** [comment]
Thank you for your quick answer ! 
I hope the following will be more clear.

I am trying to decompose the real part "ur" and the imaginary part "ui" of my solution "u" into 3 components. My solution "u" is an electric field computed from the wave equation in 3D. In order to define the GridFunction "u", "ur" and "ui" corresponding to my solution, I used Nedelec elements. 

And Indeed, I want the 3 GridFunctions that are going to correspond to each of the 3 components of "ur" to be created using nedelec elements. This way I suppose that it would avoid some problems caused by the projection of nedelec elements on other elements (h1 in my original code). Therefore, I would have ur_X along X ; ur_Y along Y ; ur_Z along Z all 3 should be scallar fields (and similarely for the imaginary part "ui"). In my previous message ur_X = xCompR and ui_X = xCompI.

Why do you say that : "you're trying to project a scalar-valued coefficient onto a vector-valued ParGridFunction" ? I understand that what I am projecting is a scallar field but I do not understand why it would be projected on a "vector-valued ParGridFunction".

The goal is to plot each component of "ur" and "ui" so 6 graphs in total and to easly save them to files.

I am not sure to undersatand why you say : "resulting vector fields will not appear to be perfectly aligned with the x, y, and z directions". I though that using the inner product would do vec(E)*1x=Ex. 

Best regards.

**Comment by mlstowell** [comment]
Hi, @sp3c333,

Thank you. I think I understand now. In the pseudocode you included earlier you define `xCompR`, for example, in two different ways. First as `ParGridFunction xCompR(&fes_h1);` using H1 basis functions (which are scalar-valued) but then as `ParGridFunction xCompR(&fes_nd);` using Nedelec basis functions (which are vector-valued). I was under the impression that the error you reported came from the second case (when using Nedelec basis functions).

You are correct that projecting these three components onto an H1 field will produce odd results. This is because discrete Nedelec fields are only partially continuous and their discontinuities are incompatible with H1 fields (which are continuous). In my opinion, the best way to handle this is to project your individual components onto an L2 field (which is discontinuous). In other words I would suggest swapping out your H1 finite element space for an L2 using a finite element collection like this `L2_FECollection fec_l2(order, dim);`. The resulting field should be able to represent the individual components of your Nedelec field correctly.

My comment about "resulting vector fields will not appear to be perfectly aligned with the x, y, and z directions" assumes you're plotting your individual components using Nedelec basis functions and projecting, for example,  `(u.xVec)*xVec` onto them. This function is clearly aligned with the x-axis, however, the resulting Nedelec approximation of this vector function may have noticeable y and z components. If your using a hexahedral mesh and your edges all align with the coordinate axes you won't notice any issues but on a more general mesh the field will deviate from the x direction. This is easy to see, just project `xVecCoef` onto a Nedelec field on a tetrahedral mesh.

Best wishes,
Mark

**Comment by mlstowell** [comment]
Hi, @sp3c333,

How is `xCoefR` defined? I assume it's `InnerProductCoefficient xCoefR(solCoefR, xVecCoef);` (or something similar). This is a scalar coefficient meaning that it derives from `mfem::Coefficient`. When you call `ProjectCoefficient` using a Nedelec `GridFunction` you must provide it a vector coefficient derived from `mfem::VectorCoefficient`. Unfortunately, the error messages from `ProjectCoefficient` is not very helpful.

I would suggest this:
```
InnerProductCoefficient xCoefR(solCoefR, xVecCoef);

L2_FECollection fec_l2(order, dim);
ParFiniteElementSpace fes_l2(pmesh, &fec_l2);

ParGridFunction xCompR(&fes_l2);

xComp.ProjectCoefficient(xCoefR);
```
Along with similar lines for the other components.

Best wishes,
Mark

**Comment by sp3c333** [comment]
Thank you very much for your help and your explanations ! It works like a charm !

I have now understood that both Nedelec and L2 are discontinuous finite element and both lead to vector coefficients when InnerProductCoefficient is used.
However, I am not sure to understand something : 
Why projecting a field component "ur_X=xCoefR" coming from a field "u" that was initially defined using Nedelec elements on a ParGridFunction defined with L2 elements does not lead to problems. Since their are not identical finite elements, I would have expected to see some problems (similarly to those observed with h1). Would you have an explanation on that ?

Best Regards.

**Comment by mlstowell** [comment]
Hi, @sp3c333,

I'm so glad things are working for you now.

In MFEM we have four different ways to represent a vector-valued field; H1^3, Nedelec, Raviart-Thomas, and L2^3 (the "^3" means we can use three copies of these scalar-valued basis functions to represent the three components of a vector field). Each of these uses similar, but not the same, families of polynomials to approximate the fields inside an element. They also have different ways of enforcing continuity of the fields between neighboring elements. In order to avoid odd behavior you must ensure two things; the polynomial space of the new field is rich enough to contain the original field and the continuity is not more restrictive.

I suspect the odd behavior you saw was caused by the continuity restriction of the H1 space which must be completely continuous. Nedelec fields are only continuous in their tangential components. Raviart-Thomas are only continuous in their normal component. L2 fields are discontinuous. So, if you choose the polynomial orders correctly (order of the L2^3 space is greater than or equal to the order of the Nedelec or Raviart-Thomas space) then L2^3 can reproduce a Nedelec representation exactly (assuming the element Jacobians are constant or sufficiently low order polynomials themselves). The polynomials used in the H1 basis functions are the same as those used in L2 basis functions but the continuity restriction is much stronger. This means that even though the H1 polynomials are capable of reproducing a Nedelec field within a single element, they cannot reproduce the discontinuities present in most Nedelec fields. The projection operation does not attempt to smooth or average these discontinuities so the H1 representation can look different on slightly different meshes.

I hope this helps to clarify the issue.

Best wishes,
Mark
