### ISSUE TITLE
Bug in Curl calculation for HDiv on higher order hexahedra

### ISSUE THREAD

**Issue by hughcars** [mfem/mfem#3640]
This issue is a minimum working example of a bug with HDiv spaces on quadratic hexahedra elements. This is demonstrated using a hexahedral mesh of a cylinder cavity, and modification of ex13p to form a discrete curl matrix to calculate the B field (curl E) for each eigenmode, and modification of the visualization to report the curl E.

The error can be demonstrated using:
```
mpirun -np 1 ex13p -m ../../p2_hex_mesh_ref1.msh -rs 0 -rp 0 -o 3
```
but it is visible for other orders, refinements and for RT space of `order` and `order - 1`.

The issue does not appear to be present for linear meshes, demonstrated using:
```
mpirun -np 1 ex13p -m ../../p1_hex_mesh_ref1.msh -rs 0 -rp 0 -o 3
```
which has artifacts due to the mesh resolution, but does not demonstrate the non-physical singularity.

This is of particular consequence for AMR, where the ZZ error estimator is acting on the curl of the Nedelec element, measuring the distance between the ND space solution and the RT space solution. The singularity ends up driving AMR to continuously refine the region at the expense of all others. 

All of this is available on the branch `hdiv-high-order-hexahedra-bug-mwe`, and an example of the singularity can be seen here for p2:
<img width="400" alt="Screenshot 2023-05-03 at 1 41 34 PM" src="https://user-images.githubusercontent.com/114775781/236009717-f667c1d8-7e7f-4c22-99f4-a77b29520175.png">

and non issue here for p1:
<img width="250" alt="Screenshot 2023-05-03 at 2 30 00 PM" src="https://user-images.githubusercontent.com/114775781/236010634-e3afd677-73b2-47de-993b-55c2745b92a8.png">
where the singularities visible are induced for each edge of the linear mesh as it approximates the curved surface.

**Comment by mlstowell** [comment]
Hi, @hughcars,

I'm not sure I would characterize this as a bug. Clearly the mesh will be challenging since some of the hexes have interior angles of 180 degrees along one edge. To be honest I'm not certain if Nedelec and Raviart-Thomas basis functions are capable of working in such elements but I'm not surprised that they have trouble. Also the way MFEM performs AMR by uniformly refining hexes into 8 smaller hexes will not improve this mesh since this 180 angle will persist so we cannot expect AMR to help. 

<img width="982" alt="GLVis_s01" src="https://user-images.githubusercontent.com/6109571/236883625-9db5cb95-d467-4649-970f-70bb24e3a346.png">

Clearly the simple solution is to remesh without the 180 dihedral angles but I recognize that in a realistic mesh this is not always practical. Perhaps the better solution would involve using mesh quality metrics to identify problem areas and adjust the mesh where necessary. I would ask @kmittal2 or @vladotomov how they might approach this.

Best wishes,
Mark

**Comment by vladotomov** [comment]
Right, quads are not good at representing circles. For these people usually use the butterfly meshes.

<img width="272" alt="Screen Shot 2023-05-08 at 10 19 53 AM" src="https://user-images.githubusercontent.com/17843342/236888986-09e80ed2-8201-4e3d-9323-9683891f2982.png">

**Comment by vladotomov** [comment]
@mlstowell it's probably easy to generate this with the `extruder` miniapp?

**Comment by hughcars** [comment]
Thanks for the reply @vladotomov @mlstowell. That sounds reasonable. This was being generated whilst I was trying to pursue a "minimal" initial mesh for the AMR to begin from. I'll just place requirements on users to avoid this scenario, i.e that a minimal mesh able to capture the geometry might not actually be sufficient for solving on. 

Thanks for the response
