### ISSUE TITLE
Warning from icpx compiler: explicit comparison with NaN in fast floating point mode

### ISSUE THREAD

**Issue by adam-sim-dev** [mfem/mfem#3655]
This warning is from icpx compiler in Intel oneAPI 2023.1

In file included from fem/datacollection.cpp:17:
fem/picojson.h:200:3: warning: explicit comparison with NaN in fast floating point mode [-Wtautological-constant-compare]
                std::isnan(n) || std::isinf(n)
                ^~~~~~~~~~~~~
fem/picojson.h:200:20: warning: explicit comparison with infinity in fast floating point mode [-Wtautological-constant-compare]
                std::isnan(n) || std::isinf(n)
                                 ^~~~~~~~~~~~~
2 warnings generated.

fem/tmop_tools.cpp:544:11: warning: explicit comparison with NaN in fast floating point mode [-Wtautological-constant-compare]
          std::isnan(energy_out) != 0)
          ^~~~~~~~~~~~~~~~~~~~~~
1 warning generated.

**Comment by plopresti** [comment]
It's a legitimate warning. "fast" floating point mode means -fno-honor-nans and -fno-honor-infinities are set, so the code has a decent chance of being broken.

The underlying problem is that the Intel compiler [defaults to -ffp-model=fast](https://www.intel.com/content/www/us/en/docs/dpcpp-cpp-compiler/developer-guide-reference/2023-1/fp-model-fp.html) (!)

You probably want to set "-ffp-model=precise" or at least "-fhonor-infinities -fhonor-nans" on your command line both to silence this warning and to avoid serious and hard-to-debug problems. Ask me how I know...

**Comment by adam-sim-dev** [comment]
Thanks for the explanation. @plopresti
