### ISSUE TITLE
Local Time Stepping

### ISSUE THREAD

**Issue by pkgudla** [mfem/mfem#3663]
This issue has been raised earlier, but just wanted to know the current status of this. Has local time stepping been implemented in MFEM, or is it in the pipeline ? If in the pipeline or underdevelopment, can we contribute and when is it expected data that this could be available to the public ?

If it so happens, that there is no such implementation yet and it is not in the pipeline, can anyone be kind enough to suggest how this could be implemented ?

**Comment by termi-official** [comment]
I hope it is okay that I respond here (not a member of the MFEM team). I am developing local time stepping algorithms in MFEM and try to release the code alongside a paper (which I hope is soon), so it is technically possible. If the MFEM team wants, then I can try to make a PR with a template for LTS or just make a full miniapp from my code, but this might need a bit of time.

Regarding "how", this depends on your specific LTS scheme. E.g. for diffusion operators I just use the integrators (`DiffusionOperator` and `DGDiffusionOperator`) available in MFEM to assemble the local matrices for the application of the local action per element. For the local face integrals you can take the code in the Kelly error indicator as a template https://github.com/mfem/mfem/blob/0f5d34b2b490819789d6c85546e17724ff37f021/fem/estimators.cpp#L229-L244 just note that the coarse nc faces need extra treatment. Here you can extract the small faces from the information given in `mesh->ncmesh->GetFaceList()` and simply integrate over all fine faces on the coarse face. I have not required much more than this to get LTS up and running. I hope this helps.

**Comment by termi-official** [comment]
Is demand or interest for this infrastructure? In this case I can try to factor out the local time stepping classes from my framework and provide them directly in MFEM with some miniapp after I get the paper accepted.

**Comment by vladotomov** [comment]
Of course Dennis, it would be great to have an example that does local time stepping in MFEM.

**Comment by termi-official** [comment]
As discussed in the workshop let us start with what I have in my framework and [preprint on synchronous local time steping](https://arxiv.org/pdf/2310.07607.pdf). I hope that figure 2 summarizes the idea of the algorithm on a high level. Also note that I have not touched parallelization in the paper seriously because the design space is quite large.

Since I could not find good literature about this, I start with a summary of local time stepping for time-dependent ODEs: Semi-discretizing a time-dependent problem of the form $$\partial_t u = F(u,t)$$ with finite elements gives us the dofs $\tilde{u}$, a nonlinear operator $N$ and a mass matrix $M$ for the time dependent term, such that we obtain $$M d_t \tilde{u} = N(\tilde{u},t)$$. We can turn this problem into a pure ODE problem by inverting the mass matrix $$d_t \tilde{u} = M^{-1} N(\tilde{u},t) =: f(\tilde{u},t)$$. This can be also practically achieved by using DG discretizations (to obtain a block diagonal), but technically it is also possible to lump the mass matrix or use spectral elements. Anyways, the idea is that this allows us to investigate the problem as a pure ODE problem. Now we see that local time stepping is really just time discretization technique for ODEs. For ODEs is possible to assign different time step lengths to each single ODE in the system (in literature I usually find this named asynchronous local time stepping).
For context to the discussion which we had on zoom: A special case of this is what **I** call synchronous local time stepping (since I could not find a consistent naming in literature). Here where we define some global time interval length $\Delta t$ for a time interval of interest $[t_n, t_{n+1}]$. Now in the synchronous scheme we assign to each ODE some integer $N_i$, such that the local time step length is given by $\Delta t / 2^{N_i}$. This allows us to group the elements by their $N_i$ and hence possibly batched operations. Explicit local time stepping in these schemes generally works as variants of 
1. Choosing all ODEs $i$ for which the local predictor can be evaluated at its current local time $t^i$ and construct a prediction $\hat{u}_i$ for the next local time point (given some local time step length)
2. Choosing all ODEs $i$ with assigned current local time $t^i$ for which all $\hat{u}_j$ appearing in $f_i$ can be interpolated in time into the current stage of the time discretization (e.g. Runge-Kutta scheme), such that we can evaluate $f_i$ with some time interpolator for the $\hat{u}_j$
3. Goto 1 if there is any ODE whose local time is not at $_{n+1}$
Implicit local time stepping schemes on the other hand can be essentially seen as space-time fem with non-conforming time discretization.

Let us start with the algebraic perspective on this and structural properties coming from finite element discretizations. Note that I could not find any literature on this. DG schemes are a natural choice for local time stepping, because we can group the ODEs per element + the mass matrix is not super expensive to invert, but, as described above, nothing is stopping us to use other spatial discretization schemes, so I keep a very generic description for now.
I would describe local time stepping in a loop the following steps, where I denote the predictor function by $\hat{f}$ (which might come from a different operator $\hat{F} and the time interpolation operator by $T(\cdot, \cdot)$:
1. Build restriction operators $\hat{R}_v$ and $\hat{R}_p$ to extract the dofs where the predictor can be evaluated and their patches respectively
2. Update the predictor via $\hat{u}$ with the help of the right hand side $\hat{R}^T_v (\hat{R}_v\hat{f})(T(\hat{R}_p \tilde{u}, \hat{R}_p \hat{u})))$
3. Build restriction operators $R_v$ and $R_p$ to extract the dofs where the corrector can be evaluated and the associated patches respectively
4. Advance the solution $\tilde{u}$ with the help of the right hand side $R^T_v (R_v f)(T(R_p \tilde{u},  R_p \hat{u})))$

For higher order in time we might need to revisit how the interaction with the stages exactly works. I am also not sure under which conditions the operators coincide. Choosing the prolongation as the transpose should be correct in general. Also note that I have nowhere used any assumption regarding the spatial discretization yet. I think they "only" help us to efficiently construct the restrictions (without forming them explicitly).

cc @v-dobrev 
and @YohannDudouit : IIRC you helped me explaining LTS to Veselin on Zoom, so I would kindly ask you to take a look if this description is sound, since this is my very first try on writing down the class of schemes algebraically

**Comment by pkgudla** [comment]
Excited to see someone else also interested on this topic. 

@termi-official great that you could share this info with us here. Our work on implementing LTS is a work in progress and would be very interested in looking at what you have done and see if we can work together on few of the items. I didn't get a chance to look at the detailed description you posted and I'll get back after I review, but before that I just wanted to let you know our interest on this topic.

**Comment by termi-official** [comment]
Thanks. I need more time to write down details here. I will open a PR with a refactored prototype for a local time stepping miniapp if there are no mayor problems in the review regarding the actual method. Pinning down a generic algebra of local time stepping in a generic way is nastier than I anticipated.

Is there any specific physics you use and prior published material, if I might ask?

**Comment by pkgudla** [comment]
"Thanks. I need more time to write down details here. I will open a PR with a refactored prototype for a local time stepping miniapp if there are no mayor problems in the review regarding the actual method. Pinning down an algebra of local time stepping in a generic way is nastier than I anticipated"

I look forward to that and if there is anything that I could be of help, please do not hesitate. I checked out your work and I think it is very interesting. As part of PhD thesis I worked on a similar asynchronous time integrator (https://core.ac.uk/download/pdf/158313642.pdf) and have also been working on parallel strategies to exploit these methods.

Regarding the Physics, we have a broad interest in multiphysics uses case that are used in the industry, starting from thermo-mechanical analysis done in Additive Manufacturing to, crash analysis, to turbulence modeling to predict drag. As for the immediate usage, we are currently using customized MFEM examples to test and validate the code.
