### ISSUE TITLE
Add electromagnetic point source (dipole source) for ex22

### ISSUE THREAD

**Issue by shubiuh** [mfem/mfem#3664]
Hi MFEM team,

I use the MFEM code to simulate an electric dipole in a cube filled with conductive media commonly appearing in subsurface sensing.
Firstly I noticed that there is no example directly adding a point source so I started with ex0 which is a Laplace problem. The result looks good. Below is how I added the point source.
 ```cpp
 // 6. Set up the linear form b(.) corresponding to the right-hand side.
	//ConstantCoefficient one(1.0);
	DeltaCoefficient *delta_one; // add point source
	if (mesh.Dimension()==1)
	{
		delta_one = new DeltaCoefficient(0.5, 1.0);
	}
	else if (mesh.Dimension()==2)
	{
		delta_one = new DeltaCoefficient(0.5, 0.5, 1.0);
	}
	else if (mesh.Dimension() == 3)
	{
		delta_one = new DeltaCoefficient(0.5, 0.5, 0.5, 1.0);
	}
	LinearForm b(&fespace);
	//b.AddDomainIntegrator(new DomainLFIntegrator(one));
	b.AddDomainIntegrator(new DomainLFIntegrator(*delta_one));
	b.Assemble();
```

Then I started with ex22 and problem type 1 using H(curl) space for electromagnetics. But I have difficulty adding an electric point source. The electric field result looks unreal. Below is the code I added for a point source using `VectorDeltaCoefficient`.

```cpp
// 7. Set up the linear form b(.) which corresponds to the right-hand side of
    //    the FEM linear system.
    VectorDeltaCoefficient* delta_one; // add point source
    double src_scalar = -1 * omega_ * mu0_ * mu_ * src_amp;
    if (dim == 1)
    {
        Vector dir(1);
        dir[0] = 1.0;
        delta_one = new VectorDeltaCoefficient(dir, 0.5, src_scalar);
    }
    else if (dim == 2)
    {
        Vector dir(2);
        dir[0] = 0.0; dir[1] = 1.0;
        delta_one = new VectorDeltaCoefficient(dir, 0.5, 0.5, src_scalar);
    }
    else if (dim == 3)
    {
        Vector dir(3);
        dir[0] = 0.0; dir[1] = 0.0; dir[2] = 1.0;
        delta_one = new VectorDeltaCoefficient(dir, 0.5, 0.5, 0.5, src_scalar);
    }
    ComplexLinearForm b(fespace, conv);
    b.AddDomainIntegrator(NULL, new VectorFEDomainLFIntegrator(*delta_one));
    b.Vector::operator=(0.0);
    b.Assemble();
```

The difference between ex0 and ex22 is scalar field and complex-valued vector field. Can you help suggest how to add the point source correctly for the complex-valued vector field?

Best regards,
Shubin

**Comment by psocratis** [comment]
@shubiuh, ex25p includes a sample run for Maxwell with an approximate point source. Can you try replacing it with what you have above and run `mpirun -np 4 ex25p -o 2 -f 8.0 -rs 2 -rp 2 -prob 4 -m ../data/inline-quad.mesh` ? In particular, you can replace line 379 
```cpp
VectorFunctionCoefficient f(dim, source);
```
with  

```cpp
   double src_scalar = -1 * omega_ * mu0_ * mu_ * src_amp;
   Vector dir(2);
   dir[0] = 0;
   dir[1] = 1.0;
   VectorDeltaCoefficient f(dir,0.5,0.5,src_scalar);
```

With this change a get similar-looking results.

Best,

Socratis

**Comment by shubiuh** [comment]
Thank you @psocratis. I can repeat your suggestion. My issue may be related to the coarse mesh in 3D and the singularity of the point source. I will test the approximate implementation of the point source in ex25p for my case.

Cheers,
Shubin

**Comment by shubiuh** [comment]
Hi Socratis,

I tried the point source again and found an interesting issue. The result from the delta function has a half-grid shift compared to the implementation in ex25p. Below is the comparison.
**MFEM (amplitude of real part)** 
![ex25p_mfem](https://github.com/mfem/mfem/assets/36499014/5ef510b4-c63e-4a51-925f-67fef7ebd1bb)
**Delta function (amplitude of real part)**
![ex25p_my_way](https://github.com/mfem/mfem/assets/36499014/dfae0345-a13a-4c1d-926b-9e0c4f76ec47)
**MFEM (Z of real part)**
![ex25p_mfem_z](https://github.com/mfem/mfem/assets/36499014/6b92731c-c2e0-4ab0-949b-9ff2539d7a10)
**Delta function (Z of real part)** 
![ex25p_my_way_z](https://github.com/mfem/mfem/assets/36499014/45cb606f-89c8-48b0-870c-a63a008ca7a8)

Since the point source is in the center, the result should be symmetric. I am wondering if the half-grid shift is related to the MFEM or GLVIS visualization for the edge element.

Regards,
Shubin

**Comment by mlstowell** [comment]
Hi, @shubiuh and @psocratis,

I think this may qualify as a bug or at least a limitation in how delta coefficients can be used with H(curl) basis functions. I believe the trouble is that the delta coefficient is located at a vertex of the mesh so it should effect the 8 elements which meet at that vertex. However, the `LinearForm` class uses `Mesh::FindPoints` to locate the elements containing the center of the delta coefficient and this method only returns one element. I'm not sure if `Mesh::FindPoints` returns the first or last element containing that point but the important thing seems to be that it selects only _one_ element and computes the integrals of that element's basis functions multiplied by the delta coefficient. Judging by your images it is selecting one of the four elements above the center point. Selecting one fo the four elements below the center would be an equally valid choice and would produce a similar asymmetric solution.

Something similar must be happening in the scalar case (using ex0) but it isn't a problem because the H1 basis functions are centered at the vertices rather than the edges as in H(curl). When a delta coefficient is centered at a vertex it might be more correct, when using H(curl), to find all elements touching that vertex and use a weighted average of their effects. For H(div) we would need to identify centers located at vertices or along edges. For L2 all element interfaces would need special care. H1 is just a special case where no special precautions are necessary.

Best wishes,
Mark

**Comment by adam-sim-dev** [comment]
Hi Mark, @mlstowell 

> I think this may qualify as a bug or at least a limitation in how delta coefficients can be used with H(curl) basis functions. I believe the trouble is that the delta coefficient is located at a vertex of the mesh so it should effect the 8 elements which meet at that vertex. However, the `LinearForm` class uses `Mesh::FindPoints` to locate the elements containing the center of the delta coefficient and this method only returns one element. I'm not sure if `Mesh::FindPoints` returns the first or last element containing that point but the important thing seems to be that it selects only _one_ element and computes the integrals of that element's basis functions multiplied by the delta coefficient. Judging by your images it is selecting one of the four elements above the center point. Selecting one fo the four elements below the center would be an equally valid choice and would produce a similar asymmetric solution.

Please see the issue I opend before. https://github.com/mfem/mfem/issues/3567

**Comment by shubiuh** [comment]
Hi @mlstowell,

Thank you for pointing out the bug in current delta function implementation. I think it's hard to get a true Dirac delta function. However, it can be implemented as a volumetric delta function as you mentioned by weighting all the elements connecting to the point source.

Another way is to use the `VectorFunctionCoefficient` to approximate the point source as a Gaussian function (or sinc function as in [FDM paper](https://library.seg.org/doi/10.1190/1.1451454). However, I need to figure out how to calibrate the `coeff` for a point source with unit amplitude and pass the direction of the point source to the `source` function.

Regards,
Shubin
