### ISSUE TITLE
Different results between tetrahedral elements and cubic elements in the mesh

### ISSUE THREAD

**Issue by sp3c333** [mfem/mfem#3670]
Hello MFEM team,

Using the mfem meshes "inline-hex" and "inline-tet", I am computing the electric field with 3 components E(0)=Ex, E(1)=Ey, E(2)=Ez. In the problem that I consider, the field should have Ez=0 and all the domain. I obtain this results when using "inline-hex". However if I simply change the mesh use to "inline-tet", I obtain Ez != 0 (and it is wrong). 
Could you help me to use tetrahedral elements please?

My understanding of the problem:
I am considering that all boundaries are metallic and thus have null tangential components of the field on the boundary.
I impose my source with a boundary condition : 
VectorFunctionCoefficient ER(dim, E_exact_R);
u.ProjectBdrCoefficientTangent(ER, EI, f_bdr); with ER defined with: 
void E_exact_R(const Vector& x, Vector& ER){
            ER(0) = 0;
            ER(1) = 1000;
            ER(2) = 0;
        }
The way I understand it, using the mesh "inline-tet" instead of "inline-hex" change the basis when computing ER and thus ER(1) does not correspond to Ey anymore. If this is true, is there a way that I could impose my source using the X,Y,Z basis ?
If I am wrong about the change of basis, do you have any idea why Ez != 0 with "inline-tet"?

Thank you for your help.

**Comment by mlstowell** [comment]
Hello, @sp3c333,

I have been trying to reproduce this issue using [ex3p](https://github.com/mfem/mfem/blob/master/examples/ex3p.cpp) but the results are actually better than I expected. I'm seeing an `Ez` which is on the order of the solver tolerance with either mesh.

How large is the magnitude of your `Ez`? Does this magnitude change if you refine the mesh?

Best wishes,
Mark

**Comment by sp3c333** [comment]
Thank you for your quick answer.

No additional refininement steps are used in my code.
Considering a "inline-tet" with 20 points in each direction, I have Ey_max=807.9 and Ez_max=33.97. 
However, when using the "inline-hex", Ez is about 10^(-9) and Ey_max=805(with "inline-hex" and 16 point in each direction) .

Refining the mesh does not really improve the Ez when using "inline-tet". If I consider 16 points in each direction, Ez_max=56 and Ey_max=809. If I consider 25points in each direction, Ez_max=27 and Ey_max=802. 
On my laptop I can hardly do better resolutions.

I am considering a wave propagating in the void with f=4*c (with c the speed of light) and with a box of 0.5m (inline-tet), and Nedelec elements.
When saving under VTK format, my third component is also non-null so I suppose that it means that it is not linked to the plotting.

If you need additional information or parts of my code I can send them to you.
Thank you for your efforts.

**Comment by mlstowell** [comment]
Hello, @sp3c333,

I realize this looks like a roughly 7% error but the drop to 3.3% error when increasing the resolution by 50% is more than one might expect. This is actually an encouraging result. It means that the approximate solution is probably converging to the exact solution at or above the expected rate.

I'm sure this is not the answer that you want to hear but I think this is just the best you can expect. The reason the hex mesh seems to perform so much better is that the solution happens to align with the mesh in a convenient way. If your wave were polarized so that the vector field were aligned with (0, 0.866025, 0.5) instead of (0, 1, 0) you would see a similar (though probably smaller) issue even on the hexahedral mesh.

This is because Nedelec basis functions don't consider the vector components individually. They attempt to approximate the vector field as a whole. Also, they don't necessarily converge point-wise but in an integral sense. They are trying to minimize the L2 norm of the error so localized errors can sometimes be much larger than we would like. This is one of the trade-offs when using Nedelec basis functions.

To reduce these issues the user sometimes needs to try alternate approaches. For example, if you know that your z component must be zero then perhaps your mesh could represent the solution better if it used wedge shaped elements with their quadrilateral faces perpendicular to the xy-plane.

Best wishes,
Mark

**Comment by mlstowell** [comment]
Hello, @sp3c333,

I'm guessing that your exact solution is similar to a plane such as $1000 e^{i k x} \hat{y}$. I'm suggesting that if the exact solution were $1000 e^{i k x} (0.866025 \hat{y}+0.5 \hat{z})$ you would see a non-zero component in the direction  (0.5 \hat{y}-0.866025 \hat{z}) on a hexahedral mesh even though such a component should be zero.

Perhaps I've guessed incorrectly. Is your propagation direction $\hat{z}$? If so, you could see a non-zero component along the direction of propagation by shifting the propagation direction away from $\hat{z}$. For example, $1000 e^{i k(0.5 x+0.866025 z)} \hat{y}$ would probably show a longitudinal component on any of these cube-shaped meshes.

Best wishes,
Mark
