### ISSUE TITLE
Approximate a wire on Nedelec elements

### ISSUE THREAD

**Issue by Marshdweller** [mfem/mfem#3707]
Hello MFEM team,

I'm working on solving the "curl curl E + kE=J" equation using Nedelec elements on straight tets. My challenge is setting up J as a wire with an arbitrary shape (a set of 3D points) that I can't control. I can't modify the mesh or subtract the analytical solution either. So it boils down to approximate a straight wire from A to B.

What would be the best approach for implementing this? I'm currently considering the following workflow:

- Iterate over all tets and check if the wire intersects them.
- If there's an intersection, place a dipole in the tet and compute the expansion using the tet's basic functions.

Alternatively, I'm thinking of placing multiple dipoles along the wire and computing the expansions for each of them. However, I still need to handle special cases, such as dipoles located on edge, as mentioned by @mlstowell  [https://github.com/mfem/mfem/issues/3664](https://github.com/mfem/mfem/issues/3664)

Any advice is appreciated. Thank you!

**Comment by mlstowell** [comment]
Hi, @Marshdweller,

This is an interesting question and I'm not sure of the best approach. In the past I've modeled wires using a chain of edges. This scheme didn't work that well on unstructured meshes because it's hard to get the scaling correct (the current density appears to span a tube of elements touching the chain of edges). In your case it would require building a specialized mesh for each wire and this doesn't sound practical either.

Normally we view the linear form as an integral over each element of a coefficient multiplied by the basis functions within that element. In this case I might try to look at this from a different perspective. We could try to integrate along the wire rather than over each element. Determine a set of integration points and weights along the wire and use FindPoints to locate the elements containing each integration point. Then loop over the elements returned by FindPoints and evaluate the basis functions within those elements at the quadrature points given by FindPoints. Take the inner product of the basis function values with the current density vector (and the integration weight) at that point and sum the results into the appropriate rows of the LinearForm.

This would require some familiarity with the inner details of basis functions and finite element spaces but I think it could work.

If this does work it might be useful to implement this in a general purpose manner by using a 1D mesh to represent the wire. This will make integration along the wire a little easier (or at least make it look like more standard MFEM). FindPoints has been used before to share information between overlapping meshes and this is quite similar.

Best wishes,
Mark

**Comment by Marshdweller** [comment]
Thank you, Mark. It seems that constructing a "tube" of tets around the wire would give the most accurate result, although it requires mesh modification. Also, I saw people attempting to compute the E-field due to the wire analytically and then inject it into the FEM right-hand side. However, the wire goes close to the rough conductor/insulator interface, so it would be difficult to implement.

Regards,
M
