### ISSUE TITLE
ParMixedBilinearForm and Meshes with >1 element type

### ISSUE THREAD

**Issue by ryanblack129** [mfem/mfem#3723]
Hello,

**** This question is specific to PR #3215 ****

I am running into an issue with the parallel version of the example problem from the above PR on meshes with more than one element type. I am seeing the following behavior for a mesh containing both triangle and quadrilateral elements.

On 2 processors, the code seems to run just fine
![np2](https://github.com/mfem/mfem/assets/56736259/998fd725-592e-4abc-a6cc-3988aeb6dceb)
with errors
![image](https://github.com/mfem/mfem/assets/56736259/622fe3fe-1155-441d-8415-535d04c6e559)

But on 3 processors, the error increases
![np3](https://github.com/mfem/mfem/assets/56736259/4c8e4e18-3afa-433d-9977-afe289a957d4)
with errors
![image](https://github.com/mfem/mfem/assets/56736259/cafcf7b2-8191-4686-b9c7-1e43e779d838)

Similar behavior on more processors, below is a run on 7 processors
![image](https://github.com/mfem/mfem/assets/56736259/b64cd1ff-1566-437b-8092-08507dad78f3)
with errors
![image](https://github.com/mfem/mfem/assets/56736259/52efb474-db9f-474c-88a8-c815c1f58122)

I am thinking that `ParMixedBilinearForm::AssembleSharedFaces(int skip_zeros)` may have a bug.

Thanks for the help,
Ryan

**Comment by mlstowell** [comment]
Hi, @ryanblack129,

I've looked at your code and it looks correct to me. I've also tested some of MFEM's other DG examples on mixed meshes and they seem fine. Can you share the mesh shown above so that I can experiment with that as well?

Best wishes,
Mark

**Comment by ryanblack129** [comment]
Hi @mlstowell, 

Thanks for looking into this. I've attached the mesh file.

Best,
Ryan

[ex34p_StokesMixedMesh.zip](https://github.com/mfem/mfem/files/11739155/ex34p_StokesMixedMesh.zip)

**Comment by ryanblack129** [comment]
Hi @mlstowell,

Just wanted to give an update. It looks like the size of the vdofs array for the trial and test spaces when the face nbr element is a different type may be incorrect. 

In serial, for an interior face shared by a quad and tri, the test and trial vdofs size = element matrix height and width

![image](https://github.com/mfem/mfem/assets/56736259/f3b2b15f-483b-4f9a-891d-9817507d58eb)

However, in parallel (3 processor case)

![image](https://github.com/mfem/mfem/assets/56736259/0695542e-b1a3-440b-91f9-f345e6715340)

The line for `elem 2 dof trial` is from `trial_pfes->GetFE(Elem2NbrNo)->GetDof()`, while the lines for `elem 2 trial vdof size` are from `trial_pfes->GetFaceNbrElementVDofs(Elem2NbrNo, tr_vdofs2)` and `tr_vdofs2.Size()`. 

I think the sizes of the trial and test vdofs array for element 2 (triangle) should be 3 and 12 for a 1st order scalar trial space and a 2nd order vector test space.

Best,
Ryan

**Comment by ryanblack129** [comment]
Hi @mlstowell,

Just wanted to ping again on this issue. I've been able to get around this in my application using a single element type, but I am now running into geometries that would be best to mesh with more than one element type. 

Best,
Ryan

**Comment by v-dobrev** [comment]
Hi @ryanblack129, the output for Elem2 does look inconsistent and it looks like a bug.

I'm trying to reproduce the error in `ex14p` in the `master` branch with your mesh but it seems to work fine, e.g. the following run does not cause issues:
```console
mpirun -np 3 ./ex14p -m StokesMixedMesh.msh -rs 0 -rp 0
```
I'm running a debug build, so in `ParBilinearForm::AssembleSharedFaces`, if `vdofs_all` has more entries than the columns of `elemmat`, then we should get the following access to fail: https://github.com/mfem/mfem/blob/8a4affef5af84d74c9691f76b49624bdd7199d60/linalg/sparsemat.cpp#L2750 because of the bounds checks here: https://github.com/mfem/mfem/blob/8a4affef5af84d74c9691f76b49624bdd7199d60/linalg/densemat.hpp#L1294-L1298

Can you try the same run in your branch and setup? You can enable a debug build by adding the config flag `MFEM_DEBUG=YES` (if using GNU make) or by setting `-DCMAKE_BUILD_TYPE=Debug` (if using CMake).

Thanks!

**Comment by ryanblack129** [comment]
Hi @v-dobrev,

Thanks for looking into this.

I can confirm the same behavior on my end for `ex14p`. I am thinking there may be a bug in `ParMixedBilinearForm::AssembleSharedFaces`, probably with how I am getting the `vdofs`.

Best,
Ryan
