### ISSUE TITLE
Packaging mfem on Fedora

### ISSUE THREAD

**Issue by topazus** [mfem/mfem#3734]
The rpmlint tool showed `unused-direct-shlib-dependency` and `undefined-non-weak-symbol` issues. Here are a few message lines cut from [review.txt](https://download.copr.fedorainfracloud.org/results/topazus/test-review/fedora-rawhide-x86_64/06085485-mfem/fedora-review/review.txt)

```
mfem-mpich.x86_64: E: unused-direct-shlib-dependency /usr/lib64/mpich/lib/libmfem.so.4.5.2 libHYPRE.so.2.1
mfem-mpich.x86_64: E: unused-direct-shlib-dependency /usr/lib64/mpich/lib/libmfem.so.4.5.2 libmpi.so.12
mfem-openmpi.x86_64: E: unused-direct-shlib-dependency /usr/lib64/openmpi/lib/libmfem.so.4.5.2 libHYPRE.so.2.1
mfem-openmpi.x86_64: E: unused-direct-shlib-dependency /usr/lib64/openmpi/lib/libmfem.so.4.5.2 libmpi_cxx.so.40
mfem-openmpi.x86_64: E: unused-direct-shlib-dependency /usr/lib64/openmpi/lib/libmfem.so.4.5.2 libmpi.so.40
mfem-mpich.x86_64: E: undefined-non-weak-symbol /usr/lib64/mpich/lib/libmfem.so.4.5.2 HYPRE_ParaSailsSolve	(/usr/lib64/mpich/lib/libmfem.so.4.5.2)
```

ref: 
spec file: https://download.copr.fedorainfracloud.org/results/topazus/test-review/fedora-rawhide-x86_64/06085485-mfem/mfem.spec
copr build: https://copr.fedorainfracloud.org/coprs/topazus/test-review/build/6085485/

**Comment by topazus** [comment]
@tzanio @v-dobrev And I created the package review of mfem on redhat bugzilla. https://bugzilla.redhat.com/show_bug.cgi?id=2214308

**Comment by v-dobrev** [comment]
Looking at the build log (https://download.copr.fedorainfracloud.org/results/topazus/test-review/fedora-rawhide-x86_64/06085485-mfem/builder-live.log.gz) I see that the all CMake tests in the build directory ran fine, so the library `libmfem.so.4.5.2` must be linked fine. I'm not sure if something changes when it is installed and why `rpmlint` thinks there are issues. All the errors about "undefined-non-weak-symbol" are about symbols that should be present in `libHYPRE.so.*` or `libmpi.so.*`. I don't understand then why `libHYPRE.so.*` and `libmpi.so.*` are seen as "unused-direct-shlib-dependency" by `rpmlint`.

One thing that seems strange to me is that the HYPRE library is called `libHYPRE.so.2.1` instead of using the actual version (v2.28) which should result in `libHYPRE.so.2.28.0` or something like that.

By the way, I noticed in the build log that the run times of some of the MFEM tests in the MPICH build take very long time. The same tests in the `OpenMPI` build are as expected -- not very long.

**Comment by topazus** [comment]
> One thing that seems strange to me is that the HYPRE library is called `libHYPRE.so.2.1` instead of using the actual version (v2.28) which should result in `libHYPRE.so.2.28.0` or something like that.

This is because the soversion of hypre is set as 2.1 in its packaging, see: https://src.fedoraproject.org/rpms/hypre/blob/rawhide/f/hypre.spec#_20

**Comment by topazus** [comment]
@v-dobrev Thanks for the explanation. Though the issues still existed, which maybe we can ignore them for the moment. The package review of mfem was approved, mfem package will be made and available later on Fedora official repository.
Ref: https://src.fedoraproject.org/rpms/mfem

**Comment by topazus** [comment]
For now, mfem is available on Fedora rawhide, and is in testing status on Fedora 37 and 38. 

ref: https://packages.fedoraproject.org/pkgs/mfem/mfem/
