### ISSUE TITLE
Computing the integral of gradient normal to boundary

### ISSUE THREAD

**Issue by denislachapelle** [mfem/mfem#3753]
I am trying to compute the integral of gradient normal to a boundary, in fact I am expecting to compute the charge causing the electric field.

The mesh is 2D and there are two boundaries, more information can be see in the following issue: #3710.

Initially I compute the potential and then the gradient in rt_fespace. (rt_fespace are used in volta_solver.cpp)

glvis properly display both the potential and the gradient as shown below.
![image](https://github.com/mfem/mfem/assets/45741871/36ff57f9-55ee-4321-a544-71884cc6597f)
![image](https://github.com/mfem/mfem/assets/45741871/654dd910-bdbb-47ec-b035-c019e3436718)

The gradient is computed with the following code...

```c++
  FiniteElementCollection *rt_fec = (FiniteElementCollection*)new RT_FECollection(order, dim);
  FiniteElementSpace fespace_rt(&mesh, rt_fec);
  GridFunction dT(&fespace_rt);
  DiscreteLinearOperator grad(&fespace, &fespace_rt);
  grad.AddDomainInterpolator(new GradientInterpolator);
  grad.Assemble();
  grad.Finalize();
  grad.Mult(u, dT);
```

The code to compute the charge is shown below...

```c++
   LinearForm *rt_surf_int_ = new LinearForm(&fespace_rt);
   Array<int> bdr_marker(2); bdr_marker[0]=1; bdr_marker[1]=1;
   rt_surf_int_->AddBoundaryIntegrator(new VectorFEBoundaryFluxLFIntegrator, bdr_marker);
   rt_surf_int_->Assemble();
   double charge_D1 = (*rt_surf_int_)(dT);
```

The result is 0, I also try with bdr_marker[0]=0; bdr_marker[1]=1; and I get the same result.

The complete code in the attached zip file. 

[microstrip_issue.zip](https://github.com/mfem/mfem/files/11861584/microstrip_issue.zip)

Thank you for your help.
 Denis Lachapelle

**Comment by mlstowell** [comment]
Hi, @denislachapelle,

 To compute the charge I believe you want to compute `-Coeff Grad u` rather than `Grad u` but I suspect there's more that we need to look at. I've looked at the code you attached and I would like to try it on your mesh. Could you also provide the mesh file?

Best wishes,
Mark

**Comment by denislachapelle** [comment]
Mark, @mlstowell 
I attach both, the geo file and the msh file. 
[microstrip1_geo_msh.zip](https://github.com/mfem/mfem/files/11871895/microstrip1_geo_msh.zip)
Thank you for your help,
Denis

**Comment by mlstowell** [comment]
Hi, @denislachapelle,

 I've made a few changes which seem to help.
[microstrip_issue.zip](https://github.com/mfem/mfem/files/11887459/microstrip_issue.zip)

First, using the RT space with the `GradientInterpolator` did not work correctly. If you look closely at the vector field you'll see that it doesn't actually align with the gradient. It was rotated by 90 degrees. I think this is related to a coincidental relationship between the RT and ND spaces in 2D where they are identical except for a 90 degree rotation. In the attached code I use ND to compute and visualize the gradient as a sanity check.

Next, I compute `D = -epsilon Grad u` as an RT field. This involves a mixed bilinear form to compute the derivative and scalar product in one step. This leaves us with a dual vector (a.k.a. `LinearForm`) representing the resulting field. We then need to solve a mass matrix to find the related field vector (a.k.a. `GridFunction`). This `GridFunction` is plotted as the "Displacement Field".

Finally, I compute the integral of the normal component of the displacement separately on surfaces 1 and 2. This computation is essentially the same as your code. Note that these two integrals should perfectly cancel because the surface charges should balance. This does not occur in the code because of the field singularities on surface 2. If we refine the grid the values become closer.

To obtain these results I also had to alter your mesh by removing region 4. The only reason for this was to make surface 2 an outer boundary of the domain so that the `VectorFEBoundaryFluxLFIntegrator` would work as expected. When this is used on an interior boundary the normal to the "boundary" may not pierce the surface in a consistent direction. This in turn causes non-physical cancelations while summing the surface integral. A more robust way to compute surface integrals on interior surfaces is to write a custom vector field which will define the surface normal and a specialized integrator which will use this field to ensure the normal is consistently chosen.

Best wishes,
Mark

**Comment by denislachapelle** [comment]
Thank you @mlstowell,

I will need sometime to digest all the changes you made. Up to now I have compile it and look at the three glvis images and I see that the gradient direction make much more sense now. I notice that the "double CoeffArray[]={0.0, 0.0, 5.0, 1.0, 1.0};" was modified to dimension 5 instead of 3, I dont understand why.

Regards,
Denis

**Comment by mlstowell** [comment]
Hi, @denislachapelle,

I forgot to mention the `PWConstCoefficient`. Thank you for reminding me. The vector of coefficient values is indexed using the attribute numbers which are assumed to start counting from 1. Your mesh contained element attribute numbers 3, 4, and 5 so MFEM assumes the possible attributes will be 1, 2, 3, 4, 5. The vector used with `PWConstCoefficient` must have length equal to `max(attribute)` , 5 in this case. If the attribute number is `a` and the vector of coefficient values is `v` then the `PWConstCoefficient` will return `v[a-1]`.

Best wishes,
Mark

**Comment by denislachapelle** [comment]
@mlstowell 
I decide to modify the microstrip model rounding the corner of the domain and the trace itself, thus reducing the electric field in the corner; I expect the boundary integral to be more precise under these conditions.

![image](https://github.com/mfem/mfem/assets/45741871/219aa2aa-acdb-46d3-b591-58c411874033)

Computing the charge with and without round corner we see that the relative error is about 8% while 16% with square corner. So there is an improvement.

                #1	          #2	        Error
square	8.24939	7.01083	0.162325
round	7.44803	6.83284	0.086156

Is there a way to change the integration rule so that I can see if it is a way to reduce the error?

Any suggestion will be appreciated.

Regards,
Denis

**Comment by mlstowell** [comment]
Hi, @denislachapelle,

The integration rule order can be changed but it's a bit of a hassle. You'll need to modify the line where the `VectorFEBoundaryFluxLFIntegrator` is added to the `Linearform` because you'll need access to that integrator (or at least a pointer to it). Try something like this:
```
LinearFormIntegrator *linint = new VectorFEBoundaryFluxLFIntegrator;

int irorder = (something of your choice); // Default is (basis function order - 1)
const IntegrationRule &ir = IntRules.Get(Geometry::TRIANGLE, irorder);
lining->SetIntRule(&ir);
rt_surf_int_.AddBoundaryIntegrator(linit, bdr_marker);
```

**Comment by denislachapelle** [comment]
@mlstowell 

With the above change the value of charge D1 and D1 is about half, and the error persist. I have tried with different order and iorder values but the result are always similar. What a strange result!

Since the error persist, I suspect the error is more related to the gradient calculation than the integral. I will explore this now.

Denis

**Comment by mlstowell** [comment]
Hi, @denislachapelle,

The integration order should be related to the basis function order and the geometry order. Once the integration order is high enough to accurately integrate the basis and geometry functions the errors should not improve as this order is increased.

The basis function order can be increased to improve the accuracy of smooth solutions. Because you have locations where the gradient near the conductor is singular (or at least sharply increasing) the basis function order will not be able to accurately represent this gradient.

Usually mesh refinement is the better strategy in regions where functions exhibit these types of sharp fluctuations. For this reason I would recommend a basis function order no higher than 2 or 3 throughout the mesh and mesh refinement near the corners of the conductor. I suspect that if you could reduce the edge lengths on the conductor (particularly near its corners) you would see a reduction in the error.

Best wishes,
Mark

**Comment by denislachapelle** [comment]
I have tried many combinations to reduce the error some quite good success, but when the intagration rules order changed the value of charge D1 and D1 is about half.

**Comment by mlstowell** [comment]
As you increase the integration rule order (for a fixed basis function order) the charge values should converge to some values. Perhaps not the correct values but some value which does not change significantly if you increase the integration rule order further. This means that you are accurately integrating the basis functions on the given geometry.

Once you have found an appropriate integration rule order you can then refine the mesh in locations where the gradient is changing sharply. During this process the charge values should start to converge towards the expected values.
