### ISSUE TITLE
bug in GetVDim function of FiniteElement class

### ISSUE THREAD

**Issue by sbugenha** [mfem/mfem#3826]
Hello,

In writing some integrators, I noticed a bug in the GetVDim function of the FiniteElement class. It is always returning 0.

For example, the following code
```
FiniteElementSpace quad_vector_space(mesh, &quad_coll, dim);
FiniteElement* fe = quad_vector_space.GetFE(0);
cout << fe->GetVDim();
```
returns 0 for dim=2 and dim=3, whereas
`cout << quad_vector_space.GetVDim();`
returns an appropriate value (2 or 3)

Thanks,
Scott

**Comment by sebastiangrimberg** [comment]
Hi @sbugenha, I believe the confusion here is that the `vdim` for a `FiniteElementSpace` is actually a different thing than the `vdim` of a `FiniteElement`. Namely in the latter case it is the vector dimension of the element, which is only really relevant for vector-valued elements (Nedelec, Raviart-Thomas, for example). Alternatively the `vdim` of the space is what you expect, it is the number of times the scalar space is replicated in order to interpolate vector fields. This is the value you pass into the `FiniteElementSpace` constructor (which has a default value of 1).

Hope this helps. I suppose it could be adding to the confusion that the element vector dimension isn’t returning 1 for the scalar space but instead 0, but in either case it won’t give you the actual `dim` you are expecting and for this you use the `FiniteElementSpace` value.

**Comment by sbugenha** [comment]
Thanks @sebastiangrimberg, this clarifies things. I ended up just passing the FiniteElementSpace as a parameter for my integrator to get around this, but is there another way to access this information directly from the FiniteElement?

**Comment by sebastiangrimberg** [comment]
There isn't a way to get it from the `FiniteElement` unfortunately, since as the `FiniteElementSpace` is the only one who knows that it is supposed to stack/replicate the interpolation of each element and map `dofs` to `vdofs`. The `FiniteElement` exists at a lower level of the abstraction hierarchy and thus knows nothing about the `FiniteElementSpace`'s vdim. So indeed in your case the best way to do it is through the `FiniteElementSpace`. I'll close this for now but feel free to re-open if anything else comes up!
