### ISSUE TITLE
lexicographical ordering of tetrahedron meshes for matrix free linear elasticity

### ISSUE THREAD

**Issue by jtristano** [mfem/mfem#3838]
Hi,

We have modified hooke for basic matrix free elasticity.

I have written a mesh converter to write .mesh files.  I lexicographically order all of my nodes s.t. the lowest index is sorted from least x,  to greatest x, then least y to greatest y, then least z to greatest z

I thought that would be enough... 
I received this error: MFEM abort: Finite element not suitable for lexicographic ordering

I then sorted elements based on their nodal index such that each element is sorted from least index to greatest index and the elements are written to the file in least to greatest index

I did the same thing for boundary faces.

I still get the same error.

I used mesh explorer to reorder the elements, same error.   Any help would be appreciated

Regards
Joe

**Comment by sebastiangrimberg** [comment]
Hi Joe, this issue actually does not arise due to the ordering of nodes in the mesh but rather due to ordering of degrees of freedom on each element. Non-hexahedron elements don't have support for `mfem::ElementDofOrdering::LEXICOGRAPHIC` (they only support `mfem::ElementDofOrdering::NATIVE`). 

I believe the reason you get this error is likely related to the fact that the built in matrix-free integrators, via partial assembly, in MFEM only support tensor-product elements currently and thus they assume they can use a lexicographic degree of freedom ordering in order to set up the partial assembly data. This won't work for tetrahedra (or any non-hex element in 3D), unfortunately. If you have written your own kernels, you may still need to be careful about how the `ElementRestriction` objects are created and used (this seems to be the source of the error message you are getting currently). Hope this helps, thanks!

**Comment by jtristano** [comment]
Thank you @sebastiangrimberg ! Truly appreciate the thoughtful response!  We will investigate
Thanks
Joe
