### ISSUE TITLE
empty vdofs array in BilinearForm::Assemble when element matrices are pre-computed

### ISSUE THREAD

**Issue by chakshinglee** [mfem/mfem#3856]
The `vdofs` array on [bilinearform.cpp#L484](https://github.com/mfem/mfem/blob/64c872559477c733c9bfc73aae6dc3e24b45b6f6/fem/bilinearform.cpp#L484) is not filled when `element_matrices` is not `NULL`. 

I think the change was introduced in [b03e51f](https://github.com/mfem/mfem/commit/b03e51fdac56636faf34b357f0e7fdbee664ede9). @dylan-copeland, could we move [bilinearform.cpp#L471](https://github.com/mfem/mfem/blob/64c872559477c733c9bfc73aae6dc3e24b45b6f6/fem/bilinearform.cpp#L471) to before the if/else statement? Or is there another way to assemble the discrete system when element matrices are pre-computed?

**Comment by dylan-copeland** [comment]
Thanks @chakshinglee for finding this issue. Apparently, there were no tests of any kind in MFEM for this case, because all tests are run before a PR is merged. I was not familiar with the case of `element_matrices` being used, and it looks like `element_matrices` is defined only by the function `BilinearForm::ComputeElementMatrices()`, which is only called if the flag `MFEM_USE_LEGACY_OPENMP` is defined. Please correct me if I am missing something. If not, that may explain why this was never caught, that `MFEM_USE_LEGACY_OPENMP` is not tested and is rarely used.

In any case, I agree on the fix you proposed. It would be good for you test on your build and application, and make the PR if it works. I could easily make the PR, but I'm not sure about testing it.

**Comment by chakshinglee** [comment]
@dylan-copeland thanks for the feedback! Just to give some context: we are implementing some solvers that exploit the element matrices, and we call `BilinearForm::ComputeElementMatrices()` so that the matrices can be stored and extracted later (without computing them again).

I will make a small PR.

**Comment by pazner** [comment]
Was this resolved by #3859?

**Comment by chakshinglee** [comment]
yes, I am closing this issue
