### ISSUE TITLE
Docker builds are failing

### ISSUE THREAD

**Issue by v-dobrev** [mfem/mfem#3865]
These are run on branch `master`. For an example see https://github.com/mfem/mfem/actions/runs/6162244447/job/16723302171.

**Comment by sebastiangrimberg** [comment]
I noticed the same thing a few weeks back and it seems like the issue is not enough space on the runner image, and the attempt to free up space in the workflow at https://github.com/mfem/mfem/blob/master/.github/workflows/build-container.yaml#L40 is probably insufficient. I found two popular GitHub Actions for this problem in the marketplace: https://github.com/marketplace/actions/maximize-build-disk-space and https://github.com/marketplace/actions/free-disk-space-ubuntu. I don't know how to test out such a change through a PR but would think either of these could be a potential solution.

**Comment by tzanio** [comment]
@vsoch, can you help us with this?

**Comment by vsoch** [comment]
Sure! I've run into this exact issue, and you are spot on @sebastiangrimberg that any strategy to free up room is your best bet. I usually do the line you linked because it's "good bang for the buck (time)" but that can be too small for really large containers.

So you could try either of those, and I've made a similar one https://github.com/rse-ops/actions-cleaner for this same purpose. The drawback is that it does actually take time to do the cleanup - usually 4-5 minutes.

I would try any of those, and if you aren't sure, here is what I can see from their testing:

- https://github.com/easimon/maximize-build-space

```console
Run REPORT_FILENAME_BASE="${REPORT_DIR}/ubuntu-20.04_true_true_true_false_true"
Free space before: 19G
Free space after : 46G
Space freed      : 27G
Time elapsed    : 130 seconds
```
And the rse-ops before and after is here: https://github.com/rse-ops/actions-cleaner#metrics. I think they are probably similar enough that either would work! Let me know if you want help doing the PR or if @sebastiangrimberg you want to take a shot!

**Comment by vsoch** [comment]
Thank you @sebastiangrimberg !

**Comment by tzanio** [comment]
Unfortunately #3880 is also failing: https://github.com/mfem/mfem/actions/runs/6305937357

**Comment by sebastiangrimberg** [comment]
Some issue with the https://github.com/rse-ops/actions-cleaner action? Maybe we can try replacing with https://github.com/easimon/maximize-build-space instead.

**Comment by vsoch** [comment]
That definitely is strange - each cleaning step should be resilient to failure so something else is going on.

> Maybe we can try replacing with https://github.com/easimon/maximize-build-space instead.

I think this is best to do for now - I'm a bit underwater until Kubecon is done!  Then I can test it out and update the output command, and probably try to reduce that output (it's huge!)

**Comment by v-dobrev** [comment]
The Docker builds seem to be fine now: https://github.com/mfem/mfem/actions/runs/6317859782.
