### ISSUE TITLE
Resolve Ginkgo warnings and fix Ginkgo backend selection

### ISSUE THREAD

**Issue by v-dobrev** [mfem/mfem#3909]
1. When testing MFEM 4.6 with Ginkgo 1.6.0, I noticed a lot of warnings about deprecation:
    ```console
    In file included from linalg/linalg.hpp:49,
                     from linalg/sparsemat.cpp:14:
    linalg/ginkgo.hpp: In member function 'void mfem::Ginkgo::ResidualLogger<ValueType>::on_iteration_complete(const gko::LinOp*, const size_type&, const gko::LinOp*, const gko::LinOp*, const gko::LinOp*, const gko::LinOp*) const':
    linalg/ginkgo.hpp:339:42: warning: 'typename std::enable_if<(! gko::detail::have_ownership_impl<typename std::decay<_Tp>::type>::value), typename std::remove_reference<decltype (* declval<typename std::decay<_Tp>::type>())>::type*>::type gko::lend(const Pointer&) [with Pointer = const gko::LinOp*; typename std::enable_if<(! gko::detail::have_ownership_impl<typename std::decay<_Tp>::type>::value), typename std::remove_reference<decltype (* declval<typename std::decay<_Tp>::type>())>::type*>::type = const gko::LinOp*]' is deprecated: no longer necessary, just pass the object without lend [-Wdeprecated-declarations]
              matrix->apply(gko::lend(solution), gko::lend(res));
                                              ^
    ```

2. Fix the Ginkgo backend selection when MFEM uses "cpu" deveices -- Ginkgo should use its reference (single thread) backend instead of OpenMP. The OpenMP Ginkgo backend should be used when MFEM uses "omp" device. See the implementation here: https://github.com/mfem/mfem/blob/c0867ca009e9b5fafb5585318648f430b1d6eef0/linalg/ginkgo.cpp#L82
and, for some context, see the following two comments:
    * https://github.com/xsdk-project/xsdk-examples/pull/37#issuecomment-1532444883, and
    * https://github.com/xsdk-project/xsdk-examples/pull/37#issuecomment-1533563468;

**Comment by nbeams** [comment]
Hi @v-dobrev, I can start a PR for this. I was also wondering if we should bring the Ginkgo solver print settings in line with #2519?

**Comment by nbeams** [comment]
Also, in regards to point 2, do we want to check for OpenMP configuration of *both* MFEM and Ginkgo, or just Ginkgo? 
I started working on a build setup where we can use a little tester like `get_hypre_version.cpp` to check whether or not Ginkgo was compiled with OpenMP support, then use that to decide which type of CPU executor we want. That way, if Ginkgo is not compiled with OpenMP but MFEM is, or vice versa, it should still work. Would that be the preferred route?

**Comment by v-dobrev** [comment]
> Hi @v-dobrev, I can start a PR for this.

Thanks for volunteering to work on this, @nbeams!

> I was also wondering if we should bring the Ginkgo solver print settings in line with #2519?

It's up to you. I, personally, don't think it is important -- Ginkgo is a separate library so it is normal to have different printing parameters and formatting.

> Also, in regards to point 2, do we want to check for OpenMP configuration of _both_ MFEM and Ginkgo, or just Ginkgo? I started working on a build setup where we can use a little tester like `get_hypre_version.cpp` to check whether or not Ginkgo was compiled with OpenMP support, then use that to decide which type of CPU executor we want. That way, if Ginkgo is not compiled with OpenMP but MFEM is, or vice versa, it should still work. Would that be the preferred route?

Maybe we don't need a tester -- if Ginkgo provides config macros in some header for how it is built? In MFEM one can check `MFEM_USE_OPENMP`.

Regarding what combinations of backends to support: I think we can just keep it simple -- use the MFEM device config and try to use the respective Ginkgo backend. If the Ginkgo backend is not compiled, the user will get an error. The same will happen if the requested MFEM backend is not compiled. On the other hand, with libCEED, we have a way to set the libCEED backend using MFEM device spec like `-d ceed-cuda:/gpu/cuda/shared`, however, in this case it is useful to be able to switch between the different CUDA backends. I'm not sure if this makes sense for Ginkgo.

**Comment by nbeams** [comment]
From my previous discussions with the Ginkgo team, my understanding was that there is not a macro available for OpenMP status in Ginkgo that would work for both CMake and Makefile builds (in terms of importing the config). However, there is a function that can be used in a short test like 
```
int main()
{
   gko::version_info gko_version = gko::version_info::get();
   int ginkgo_with_omp = 1;
   if (strcmp(gko_version.omp_version.tag, "not compiled") == 0)
     ginkgo_with_omp = 0;

   return ginkgo_with_omp;
}
```

> Regarding what combinations of backends to support: I think we can just keep it simple -- use the MFEM device config and try to use the respective Ginkgo backend. If the Ginkgo backend is not compiled, the user will get an error. The same will happen if the requested MFEM backend is not compiled. On the other hand, with libCEED, we have a way to set the libCEED backend using MFEM device spec like -d ceed-cuda:/gpu/cuda/shared, however, in this case it is useful to be able to switch between the different CUDA backends. I'm not sure if this makes sense for Ginkgo.

One complication is the need to create a CPU Executor as a "base" when using a GPU Executor in Ginkgo. This can be either Reference or OpenMP; Ginkgo allows either. For serial/single node use, I don't think it would really matter which CPU Executor is paired with the "main" CUDA or HIP Executor. However, a while back I did some experimental tests for integrating distributed Ginkgo into MFEM, and with that current version/configuration, we ended up with a big performance hit if using the OpenMP Executor as the "base" (instead of Reference) for a CUDA Executor. So if that is happening, the user may not want to have the OpenMP as the CPU Executor, even if MFEM was built with OpenMP.

Maybe we can have the default be to try to match MFEM, and give an error if we can't (e.g. MFEM is configured with OpenMP, but Ginkgo is not --> error), but then also provide an "expert user" option for configuring Ginkgo where you can specify the CPU Executor for a GPU backend (like giving a specific libCEED backend instead of just using `ceed-cuda`).

**Comment by tzanio** [comment]
Discussion continued in #3934. Thanks @nbeams !
