### ISSUE TITLE
Ambiguous call of ND_TriDofTransformation::TransformPrimal and similar functions

### ISSUE THREAD

**Issue by sshiraiwa** [mfem/mfem#3945]
I am getting the following build error when building PyMFEM using MFEM4.6 on MacOS. One of wrapper cxx, wrapping
doftrans.hpp, does not build because this.  So far, I found this error occurring only MacOS environment, (see for ex. https://github.com/mfem/PyMFEM/actions/runs/6351178630/job/17251995979). 

Does anyone have any clue on this? It looks like relating to the member function inheritance in C++. Please let me 
know if there is anything I should do on the wrapper side. 
```
doftrans_wrap.cxx:8938:54: error: call to member function 'TransformPrimal' is ambiguous
      ((mfem::ND_TriDofTransformation const *)arg1)->TransformPrimal((mfem::Array< int > const &)*arg2,arg3);
      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~
/Users/syunichishiraiwa/venvs/env20230615/lib/python3.11/site-packages/mfem/external/ser/include/mfem/fem/doftrans.hpp:87:17: note: candidate function
   virtual void TransformPrimal(const Array<int> & face_orientation,
                ^
/Users/syunichishiraiwa/venvs/env20230615/lib/python3.11/site-packages/mfem/external/ser/include/mfem/fem/doftrans.hpp:424:9: note: candidate function
   void TransformPrimal(const Array<int> & face_orientation,
```

**Comment by tzanio** [comment]
@mlstowell, @sebastiangrimberg, @psocratis -- can you help?

**Comment by sshiraiwa** [comment]
In case this may help, I am uploading the wrapper code generated by SWIG. A problematic routine starts from line #8905 of doftrans_wrap.cxx.  
[doftrans_wrapper.zip](https://github.com/mfem/mfem/files/13061920/doftrans_wrapper.zip)

**Comment by sebastiangrimberg** [comment]
This is indeed unexpected because the second method listed in the ambiguous call error should override the first (which is pure abstract). This might be related to the `virtual` inheritance being used to avoid issues with the diamond pattern. Probably some specific compiler flags are needed to get this to work correctly inside of the Python wrapper on macOS.

One thing I would recommend trying is the code from this PR: https://github.com/mfem/mfem/pull/3820. I proposed refactoring the `DofTransformation` classes to avoid the need for this `virtual` inheritance pattern and simplify the inheritance in general quite a bit. My expectation is that this might play more nicely with your wrapper generation. If this resolves the issue maybe we can push to get this PR reviewed so it can get merged.

**Comment by sshiraiwa** [comment]
@sebastiangrimberg 
Indeed PR#3820 fixed the problem. Thank you very much. This has been holding up PyMFEM4.6... :D
p.s. I am using clang++15 from HomeBrew. Not sure if any flag avoid this error.
