### ISSUE TITLE
vtk mesh with boundary patches

### ISSUE THREAD

**Issue by XuliaDS** [mfem/mfem#3952]
I have a conformal mesh consisting of two materials that I can convert to VTK (originally in openFOAM format). I have a vtk file with the 3D mesh (mixed hex and tets) and a vtk file with the boundaries.

![vtk_example](https://github.com/mfem/mfem/assets/33522268/4a868ae0-49b9-4517-a14e-25bf7bfb8f77)

I want to be able to use the boundary patches selected and do a similar problem than the one shown in the example 2: linear elasticity on a beam. 
Is this supported? 

Many thanks!

**Comment by vladotomov** [comment]
Hi @XuliaDS, yes I think this should work.

Could you send us this mesh?

Thanks,
Vladimir

**Comment by XuliaDS** [comment]
Hi !

I've attached the files. I think I could also create a vtm file if needed.

[mesh.tar.gz](https://github.com/mfem/mfem/files/13264718/mesh.tar.gz)



Thanks !!!

**Comment by vladotomov** [comment]
Hi @XuliaDS,

These are binary mesh files -- for VTK MFEM currently supports only VTK (ASCII) and VTU (XML) unstructured meshes. See https://mfem.org/mesh-formats/.

**Comment by XuliaDS** [comment]
apologies...I tried attaching in ascii but the tarball folder is too big.  ( > 25Mb)
Can I send it to you via email ? 

Thanks

**Comment by vladotomov** [comment]
@XuliaDS
I was able to open it in VisIt and then convert to Legacy ASCII, but no luck, our VTK readers hit some topology errors:
` --> Invalid mesh topology.  Interior quadrilateral face found connecting elements 1116, 106033 and 106182.`
` --> Invalid mesh topology.  Interior triangular face found connecting elements 210424, 210429 and 210443.`

I tried to comment these verifications out and was able to visualize it in _`GLVis`_, but then trying to solve anything simple (`ex1`) led to segfaults.

Mark @mlstowell added these checks in 2021 and might know exactly what's happening. But otherwise at this point the 3D volumetric mesh is invalid for MFEM.

If you have another mesh or somehow get this fixed, your first test should be to solve `ex1` on it, to verify its validity in the MFEM readers. When that works, `ex2` is likely will work as well, as long as the boundary attributes are correct.

**Comment by XuliaDS** [comment]
Ah, thanks for the heads up. The mesh was computed with cfMesh+. If I run the checkMesh utility in openFOAM, I get a pass both in geometry and topology so I presumed it was fine. Obviously it depends on what we define as "PASS"...

I have tried other meshers (tetwild mainly). With tetWild I can edit and give it physical groups directly. Then I run MFEM successfully modifying slightly ex2.py.

If you are interested in adding this option (merging a vtk file with interior elements + boundary patches) into a single mesh file to use with MFEM, I can provide a suitable vtk-mesh split into patches. I'll do it with tetwild and then convert it. 

Otherwise, feel free to close this issue and mark as solved.

Again, many thanks!

**Comment by vladotomov** [comment]
Sure, If you have it as a valid MFEM mesh I'd be interested to have it. You can upload it here after the issue is closed. Thanks and good luck.

**Comment by v-dobrev** [comment]
Just to clarify about the error messages: these messages indicate that in the mesh there are more than 2 elements that have the same common face -- this is considered invalid since it mean that at least 2 elements overlap.

**Comment by XuliaDS** [comment]
In case you are interested, I have created a rather simple mesh: a box split into two materials  and four boundary patches. 
[box_2mat.tar.gz](https://github.com/mfem/mfem/files/13474805/box_2mat.tar.gz)


Thank you !


Xulia
