### ISSUE TITLE
Suitable mesher to rely on for volume meshing from scanned STL files

### ISSUE THREAD

**Issue by justAPhDStudent** [mfem/mfem#3992]
Hello,

I am trying to perform finite element analysis on scanned STL files. The geometry is complex and sometime I run into meshing issues on Gmsh using their Merge utility. The different boundary conditions can be specified as separate STL files and can be combined to a volume mesh with different physical regions attributes. 

My attempts with Gmsh have been futile and converting it a CAD BREP / STEP format is not an option as the scanned geometries are very complex with huge number of facets. I intend to perform parallel fea as the geometry is massive. 

Does anyone know any other way to create a volumetric mesh in this scenario; that could be imported to MFEM?

Best

**Comment by termi-official** [comment]
Let me make the start. I think the best thing which you could do first is checking the Gmsh issue tracker and opening an issue in the Gmsh repository, if there is nothing related. If there is some bug in Gmsh, then they can help you and from  my experience Prof. Geuzaine is very kind and active on the issue tracker.


If this is not an option and you want to go down further the meshgen rabbit hole, here are 3 alternative options:

I have played around with CGAL and this seems to be a promosing first approach to generate the mesh https://doc.cgal.org/latest/Mesh_3/index.html from your favorite representation and coarsen it (see https://doc.cgal.org/latest/Tetrahedral_remeshing/index.html ). It is still a bit dicey and it can also fail in some scenarios. I have not found time yet to finalize my implementation to make it public, because I am not having enough hands right now unfortunately. I am also not sure if this is a real upgrade to Gmsh, because you do the similar steps, but more manual stuff (like converting your representation into their formats).

Depending on which geometry you have and what your element number and quality goals are, HexEx might also be another option https://www.graphics.rwth-aachen.de/software/libHexEx/ to get full hexahedral meshes. Also quite dicey to use, because you have to convert your mesh representation to their internal formats.

Finally, since this is also accepted for some simulations in my area, there is also the sledge hammer to just voxelize the STL geometry and using it. But, depending on your exact physics and QOIs, there might be dragons. Note that this voxel mesh can technically also be fed into CGAL again, if you just need anything.

**Comment by justAPhDStudent** [comment]
Hello,

Thanks for your detailed explanation. I will have a look at the various hacks you pointed out. I think voxelizing the mesh to make it into a manifold one sounds promising from a Gmsh perspective, as Gmsh works fine with manifold or watertight STL meshes.

Best regards
