### ISSUE TITLE
Lack of FindScaLAPACK.cmake

### ISSUE THREAD

**Issue by adam-sim-dev** [mfem/mfem#4022]
MUMPS requires ScaLAPACK, however mfem does not provide a FindScaLAPACK.cmake module.

**Comment by v-dobrev** [comment]
Yes, we do not provide `FindScaLAPACK.cmake` module because we use directly the configuration file `scalapack-config.cmake` generated by the ScaLAPACK installation. For this to work, one has to set the CMake variable `ScaLAPACK_DIR` to include the full path to `scalapack-config.cmake`, see https://github.com/mfem/mfem/blob/860c95c2de9e2aa2e54d4c1f95cf75a5afb69012/config/defaults.cmake#L172-L177

If you have a problem when you set `ScaLAPACK_DIR` as described above, let us know and post what errors you get.

**Comment by adam-sim-dev** [comment]
I use ScaLAPACK from MKL, so I wrote a simple FindScaLAPACK.cmake to find MKL ScaLAPACK. For MKL ScaLAPACK, I have to comment Line 175, # set(ScaLAPACK_TARGET_NAMES scalapack)
