### ISSUE TITLE
CudaMalloc and CudaFree Optimization

### ISSUE THREAD

**Issue by jtristano** [mfem/mfem#4061]
Hi All,
Running  multigrid we see many cuda malloc and cuda free calls. for each addmult and addmulttranspose due to the temporary vector that is created along with some other memory allocation and deallocations that occur while running.  NVidia Nsight Systems shows that these ops seems to make the kernel memory bound.   Do you have thoughts on ways to allocate lazily once and reuse appropriate memory blocks instead of freeing them until the memory manager is destroyed at the end of the run?   In this way, the memory traffic wont be so "chatty" on the GPU.  Reuse the temp vectors and pointers to the other vectors when possible.

**Comment by pazner** [comment]
Hi @jtristano,

In general, many MFEM objects try to keep track of and reuse the workspace/temporary vectors that they need in order to minimize allocations. For example, `MultigridBase::InitVectors` is used to create the temporary vectors needed in the multigrid V-cycle so that they aren't allocated on every call to `Mult`.

Can you track down specifically where the allocations are happening in `AddMult` or `AddMultTranspose`? This seems like something that could be addressed.

Also, MFEM can use [Umpire](https://computing.llnl.gov/projects/umpire), which has support for memory pools, which can speed up allocations and memory management on the GPU.

**Comment by tzanio** [comment]
Discussion continued in #4064
