### ISSUE TITLE
how to parallize & store a serial gridfunction 

### ISSUE THREAD

**Issue by gridfunction** [mfem/mfem#4076]
Hello, 

I have two data sets: a serial mesh, and a list of nodal DOFs of the Q1-Lagrange finite element gridfunction.
My question is: after loading the mesh & data in serial. How to partition & save it to parallel?

The code may look like this:

```cpp
Mesh serial_mesh("mymseh.vtk");
// […]
GridFunction x(&V);
ifstream f("myDOFs.txt");
x.Load(f, x.Size());

ParMesh par_mesh(MPI_COMM_WORLD, serial_mesh);
ParGridFunction par_x(&par_mesh, &x, ???);// this line needs help
```

Many thanks,
Guosheng

**Comment by pazner** [comment]
Hi @gridfunction,

You can use the following `ParGridFunction` constructor to create a parallel grid function from a serial (global) grid function:

https://github.com/mfem/mfem/blob/4ba0c28a6ab815081946fdd7b5750be0324bc920/fem/pgridfunc.hpp#L83-L87

This requires knowing the partition of the serial mesh used to create the parallel mesh, so that should be done in two steps, like this:

```cpp
std::unique_ptr<int> partitioning(mesh.GeneratePartitioning(Mpi::WorldSize()));
ParMesh par_mesh(MPI_COMM_WORLD, mesh, partitioning.get());
ParFiniteElementSpace par_fespace(&par_mesh, &fec);
ParGridFunction par_x(&par_mesh, &x, partitioning.get());
```
