### ISSUE TITLE
Creating Extrapolation and Interpolation matrices in parallel

### ISSUE THREAD

**Issue by vikramsg** [mfem/mfem#409]
This is a more seeking advice kind of question. In principle I am doing something similar to what example 18 is doing so its easier to explain using that. In the nonlinear form part this is the part in ex18 that I have a question about.

```
DenseMatrix elfun1_mat(elfun.GetData(), dof1, num_equation);
DenseMatrix elfun2_mat(elfun.GetData() + dof1 * num_equation, dof2,num_equation);

for (int i = 0; i < ir->GetNPoints(); i++)
{
    elfun1_mat.MultTranspose(shape1, funval1);
    elfun2_mat.MultTranspose(shape2, funval2);
}
```
I do it differently, in that I don't make a DenseMatrix part but just use Eval's for getting values. 

So I have noticed that the rest of the operations are much much faster than the FaceIntegrator part. So I thought that replacing this with a global matrix vector operation should make it faster. I assemble shape1 and shape2 into two matrices and then just do  a Mult with the solution. And I do get a good speedup from that. 

But I am not sure how to do this in parallel. The matrix assemble is pretty similar to the BilinearForm assembly. I'll only need to add the AssembleSharedFaces part. But then what. How do I convert this SparseMatrix into a HypreParMatrix. 

I am not sure what is happening in ParBilinearForm::ParallelAssemble. If I get some pointers as to how this is being done, it should help me do what I want to do. Thanks.

**Comment by v-dobrev** [comment]
Let me see if I understand your question: you have a DG *linear* operator with face terms that you want to assemble as a HypreParMatrix, right?

If that is the case, you should take a look at ex9p and class DGTraceIntegrator. Or, ex14p and class DGDiffusionIntegrator. The basic idea is that the face integrators compute a local 2x2 block (dense) matrix that defines the interaction between two neighbor elements. Once that is defined, the library will handle the assembly to HypreParMatrix.

I'm not sure how ex18 is related - the face terms there are nonlinear, so there is no matrix assembly, just evaluation of the action of the nonlinear operator. Maybe I did not understand your question. If that is the case, can you clarify?

**Comment by vikramsg** [comment]
I will try to clarify. I am not trying to construct the Bilinear form of a DG Trace operator. If we consider the  DGTraceIntegrator, I look at it as doing two things to form a square matrix. First it extrapolates the internal cell nodal values to the face, and then the face terms are interpolated back to the nodes. In case that the face term is linear, this becomes a bilinear matrix. 

In the non-linear case, first we extrapolate internal node values to the face. Then we do a non-linear operation on the left and right face terms to create a common value and then interpolate it back to the nodes. So basically I am trying to do the first and last parts as a matrix operation. 

Here's roughly how I am creating the matrix to extrapolate values on all cells on the left of each face to the face. 

```
for (int i = 0; i < mesh.GetNumFaces(); i++)
{
  for (int p = 0; p < ir->GetNPoints(); p++)
  {
    fes.GetElementVDofs (T -> Elem1No, vdofs);
    el1->CalcShape(eip1, shape1);
    face_project_l.SetRow(face_coun, vdofs,  shape1);
    face_coun++; 
  }
}
```

The other matrices will be similarly created. Note that it is not a square matrix, but  a rectangular matrix of size {dofs x (number of face points)}.

This is what I want to do in parallel.

**Comment by v-dobrev** [comment]
Okay, I think I understand what you want to do. The first step is the construction of the local part of the matrix, let's call that `B_loc`. The rows of `B_loc` correspond to quadrature points on the faces of all elements of the local mesh. For faces internal to the local mesh, there are two rows that correspond to the two values on the two sides of the face (matching those two row-indices may be tricky.) For faces that are shared, `B_loc` has only the values computed from the local elements. The columns of `B_loc`, on the other hand correspond to the local dofs. One approach that I see is to expand the `B_loc` matrix with rows corresponding the quadrature points on shared faces that depend on what we call the face-neighbor elements - these are the elements in other MPI ranks that share a face with a local element. At the same time, `B_loc` is also expanded with columns corresponding to the dofs in the face-neighbor elements. In the ParMesh class, these face-neighbor elements can be made available locally by calling the method `ExchangeFaceNbrData()` and then can be accessed using the following methods in ParMesh: (scroll down inside the box to see all the content)
https://github.com/mfem/mfem/blob/155a5eb684b116c92cf2106daeb8c3ad7d8beb27/mesh/pmesh.hpp#L152-L170
The ParFiniteElementSpace also has a method called `ExchangeFaceNbrData()` that makes available locally data related to the face-neighbor elements - it can be accessed with the following methods:
https://github.com/mfem/mfem/blob/155a5eb684b116c92cf2106daeb8c3ad7d8beb27/fem/pfespace.hpp#L253-L260
The extended version of `B_loc` has the form
```ascii
B = / B_loc   0   \
    \   0   B_ext /
```
where `B_ext` corresponds to the face-neighbor elements. This `B` matrix can be computed locally after exchanging face-neighbor data - e.g. it can be stored as a SparseMatrix where the extra columns correspond to the face-neighbor dofs as defined by the ParFiniteElementSpace. The enumeration of the extra rows is up to you - probably something similar to what you already do for `B_loc`. When dealing with DG ParBilinearForms, we do the same kind of extension of the local SparseMatrix, e.g.
```ascii
A = /   A_loc   A_loc_ext \
    \ A_ext_loc     *     /
```
where the "external" rows are often not needed, so they are not stored, unless one sets the option
https://github.com/mfem/mfem/blob/155a5eb684b116c92cf2106daeb8c3ad7d8beb27/fem/pbilinearform.hpp#L54-L58

Once `B` is constructed locally as a SparseMatrix, it can then be convreted to HypreParMatrix using code very similar to the code here:
https://github.com/mfem/mfem/blob/155a5eb684b116c92cf2106daeb8c3ad7d8beb27/fem/pbilinearform.cpp#L141-L169
There are some differences with `B` because the row-partitioning will be different from the column partitioning. The OperatorHandles `hdA` and `dA` can be removed - one can simply construct the HypreParMatrix without wrapping it in OperatorHandle and converting it. However, one has to generate suitable row-partitioning, i.e. row-offsets, e.g. using the method
https://github.com/mfem/mfem/blob/155a5eb684b116c92cf2106daeb8c3ad7d8beb27/mesh/pmesh.hpp#L149-L150

I hope this helps. Let me know if you have further questions.

**Comment by vikramsg** [comment]
Hi @v-dobrev . Thanks for such a detailed answer.

I think I understand how to go forward, but I am not sure about the offsets part. What are they supposed to do.

**Comment by v-dobrev** [comment]
The offsets (aka the partitioning) are global offsets for some data - think of ordering all processor-local pieces of a vector in a global vector, rank by rank. For a parallel matrix you have two (generally different) sets of offsets (or partitions) - one for the rows and one for the columns. To construct these offsets, you only need the local size on each rank (the local number of rows in `B`) then you can just call `GenerateOffsets()`:
```c++
HYPRE_Int local_num_rows;
Array<HYPRE_Int> row_offsets;
// set locall_num_rows ...
pmesh->GenerateOffsets(1, &local_num_rows, &row_offsets);
// ...
```
After that, you can use `row_offsets` in the constructor:
https://github.com/mfem/mfem/blob/155a5eb684b116c92cf2106daeb8c3ad7d8beb27/fem/pbilinearform.cpp#L162-L165
as the second to last argument. For the matrix `B`, the last argument (the column partitioning, or column offsets) comes from the FE space: `pfes->GetDofOffsets()` - same as in the code above.

**Comment by tzanio** [comment]
Hi @vikramsg, were you able to figure this out?

**Comment by tzanio** [comment]
Closing this now. Feel free to reopen if you have further questions.

**Comment by vikramsg** [comment]
Sorry, I got caught in some stuff. The offsets part was a little confusing for me. It seems the syntax was actually the following

```
Array<HYPRE_Int> row_offsets, *offsets[1] = { &row_offsets };
```

and not 

```
Array<HYPRE_Int> row_offsets;
```

Is this correct?

**Comment by v-dobrev** [comment]
You are right, that was my mistake - the last parameter to `GenerateOffsets` is an array of pointers to `Array<HYPRE_Int>`. The size of the array is given by the first argument. Sorry about the confusion.

**Comment by vikramsg** [comment]
Sorry, I still have a problem. Unfortunately I am not able to re-open the issue.

@v-dobrev , I want to test the matrix created but I can't figure out how to pass the HypreParMatrix by reference. 

If I simply do
```
HypreParMatrix *mat;
GetMatrix(*mat);

void GetMatrix(HypreParMatrix &mat)
{
      mat = new HypreParMatrix(fes.GetComm(), nFacePts, glob_nFacePts,
                 fes.GlobalVSize(), face_proj_l.GetI(), glob_J,
                 face_proj_l.GetData(), dof_off, fes.GetDofOffsets());
}
```

I get the error

```
../../../../linalg/hypre.hpp:409:20: note: candidate: mfem::HypreParMatrix& mfem::HypreParMatrix::operator=(double)
../../../../linalg/hypre.hpp:409:20: note:   no known conversion for argument 1 from ‘mfem::HypreParMatrix*’ to ‘double’
../../../../linalg/hypre.hpp:174:7: note: candidate: constexpr mfem::HypreParMatrix& mfem::HypreParMatrix::operator=(const mfem::HypreParMatrix&)
class HypreParMatrix : public Operator
../../../../linalg/hypre.hpp:174:7: note:   no known conversion for argument 1 from ‘mfem::HypreParMatrix*’ to ‘const mfem::HypreParMatrix&’
```

**Comment by v-dobrev** [comment]
Can't you simply change the signature of the `GetMatrix` function? Something like this:
```
HypreParMatrix *mat;
mat = GetMatrix();

// ...

HypreParMatrix *GetMatrix()
{
   return new HypreParMatrix(...);
}
```

**Comment by vikramsg** [comment]
Thanks for the suggestion. 

The problem is I need the function to return multiple matrices. I can create a function for each matrix, but that becomes cumbersome.

**Comment by v-dobrev** [comment]
In that case just change the parameter `HypreParMatrix &mat` to `HypreParMatrix **mat_p` the set the value with:
```c++
   *mat_p = new HypreParMatrix(...);
```
and  call it as
```c++
HypreParMatrix *mat;
GetMatrix(&mat);
```
