### ISSUE TITLE
Multiple gpu and mpi

### ISSUE THREAD

**Issue by joetristano** [mfem/mfem#4130]
Does mfem take care of setting the device with gpu aware mpi?  I cant find where the CUDA_VISIBLE_DEVICES flag is set.  How is this done in practice?

Thanks in advance!
Joe

**Comment by tzanio** [comment]
ping: @v-dobrev

**Comment by jtristano** [comment]
@v-dobrev  any info on this?

**Comment by v-dobrev** [comment]
Regarding GPU-aware MPI -- we don't have a good way of detecting when it is supported by the used MPI implementation, so we leave the enabling of GPU-aware MPI to the application. Applications can call `Device::SetGPUAwareMPI(true)` to enable support in MFEM (by dafault, it is always disabled).

Regarding `CUDA_VISIBLE_DEVICES`/`ROCR_VISIBLE_DEVICES` -- MFEM does not look at these environment variables -- we assume that they are set by the user (or by the batch job system). Typically, we just run 1 MPI per GPU and each rank uses logical GPU 0 -- the mapping to physical GPUs is left to `CUDA_VISIBLE_DEVICES`/`ROCR_VISIBLE_DEVICES` which should be defined differently for different MPI ranks.

**Comment by joetristano** [comment]
Thanks for the info.  For large memory intensive jobs have you experimented with exclusive mode on the gpu?   

This question then leads to another issue that Ive read about on the issue page related to the management of vectors an the gpu.  https://github.com/mfem/mfem/issues/1516

Any thoughts from the team there?

**Comment by v-dobrev** [comment]
I don't know what "exclusive mode on the gpu" is, so I can't much about it. 😃 

I don't know of anyone that has explored further the observations from #1516 in order to find ways to improve the memory usage, if some non-trivial improvement is possible. @dylan-copeland, do you know if someone has looking into that?

**Comment by dylan-copeland** [comment]
I am not aware of anyone working on this issue since I posted in 2020, and I haven't worked on a related topic in recent years. This seems like a non-trivial problem that will take significant effort, and it hasn't been a priority so far.

**Comment by sebastiangrimberg** [comment]
One option for improving your GPU memory usage is to use unified memory (`mfem::MemoryType::MANAGED`) which in recent CUDA versions allows for oversubscription of GPU memory. Beware of performance though, I think paging can get quite slow. Here's an article I came across: https://developer.nvidia.com/blog/improving-gpu-memory-oversubscription-performance/. It could also be that Umpire has good ways of dealing with this, and might be worth exploring as well if you're really running up against bottlenecks.

Another thing I will point out is the `mfem::Workspace` capability from this PR: https://github.com/mfem/mfem/pull/4065. If you are pre-allocating a bunch of vector objects because you're worried about allocation costs, but only every need a few in scope at any one time, this PR does very well at reducing overhead. The memory footprint should essentially be the largest stack depth of vector allocations which are in scope at any one moment in your program, with the caveat that allocations of different sizes and out of order allocations/frees can cause issues. But it is a solution if you are currently preallocating a lot of GPU memory in classes and then not using it outside of a narrow scope.

**Comment by joetristano** [comment]
Great info!!! Thanks @joconnor819 fyi
