### ISSUE TITLE
Vector Finite Element Spaces not Matching Spatial Dimension

### ISSUE THREAD

**Issue by michi002** [mfem/mfem#4204]
I am trying to solve ODE systems with MFEM. The need of a FE-Solver arises since the ODEs are dependent on a spatial parameter.
However in this case I need vector FE spaces, for which the vdim does not equal the spatial dimension of the mesh. 
For example this code results in an error, running into an assertion, that is then violated:

```
        mfem::Mesh mesh(10, 10, mfem::Element::QUADRILATERAL);
        mfem::L2_FECollection fec(1, 2);
        mfem::FiniteElementSpace X(&mesh, &fec, 3);
        mfem::BilinearForm m(&X);
        m.AddDomainIntegrator(new mfem::VectorMassIntegrator());
        m.Assemble();
        mfem::SparseMatrix M = mfem::SparseMatrix(m.SpMat());;
        M.Finalize();
```

Is this a bug or intended behavior?
If yes, I would offer to help fixing it.

Greetings,
Michael

**Comment by sebastiangrimberg** [comment]
You need to provide your `VectorMassIntegrator` with the correct `vdim` to use, otherwise it will default to the space dimension (see https://github.com/mfem/mfem/blob/master/fem/bilininteg.cpp#L1546). To do so, use `VectorMassIntegrator::SetVDim`:

https://github.com/mfem/mfem/blob/37e03ab550e83cda2214e3b230e2aea5b24328c9/fem/bilininteg.hpp#L2462

**Comment by michi002** [comment]
Thank you very much. It works now. I was thinking it would default to `vdim`.
