### ISSUE TITLE
ParLinearForm does not match with local vector and HypreParMatrix

### ISSUE THREAD

**Issue by Wayne901** [mfem/mfem#4241]
Hi, I'm running a time-dependent EM wave problem. When I add a current source as miniapps/maxwell, I found the size of ParLinearForm is same as a ParGridFunction, but not as local Vectors or matrices. For example, the followings are same:
`Vector a; a.Size()`
`HypreParMatrix a; a.Height()`
`OperatorHandle a; ParBilinearForm->FormSystemMatrix(ess_dofs, a); a.Height()`
And the following sizes are different to the above:
`ParGridFuntion a; a.Size()`
`ParLinearForm jd; jd.Size()`
So when I add the ParLinearForm to an Vector as `du_dt.Add(1.0, jd);`, I get wrong result in parallel.

In `maxwell_solver.cpp`'s `ImplicitSolve()` it transfers every Vector into a GridFuntion. But I hope to keep them as vectors just like exp10p and exp16p. How to extract true dofs from jd? I tried something like
```
ParGridFunction gf(fespace);
gf.Distribute(jd);
gf.GetTrueDofs(z)
```
to transfer jd into an Vector z but paralleled results are still incorrect.

**Comment by pazner** [comment]
The differences you're encountering are because of the differences between "local vectors" (L-vectors) and "true vectors" (T-vectors).

A (Par)GridFunction is a "local vector" — it contains all the degrees of freedom for all the elements in the mesh partition. This means that degrees of freedom that lie on the boundary of the mesh partitions are shared (duplicated) among the MPI ranks of those partitions.

"True vectors" are vectors that contain only true DOFs (TDOFs). These are de-duplicated: every true DOF belongs to exactly one MPI rank.

When you  call `FormSystemMatrix`, the resulting matrix will act on true DOFs, so the dimensions will be _less_ than the dimensions of the grid functions or linear forms.

To get a true DOF vector corresponding to a ParLinearForm, call the function `ParLinearForm::ParallelAssemble`.

To extract a true DOF vector corresponding to a ParGridFunction, call the function `ParGridFunction::ParallelProject`.

To covert a true DOF vector _into_ a ParGridFunction, call the function `ParGridFunction::Distribute` (or `ParGridFunction::SetFromTrueDofs` — they are synonymous).

This diagram might help explain things:

![image](https://github.com/mfem/mfem/assets/11493037/8cf42482-a560-42f1-b530-d52a59f4e854)

There is also some documentation [here](https://mfem.org/pri-dual-vec/#true-degree-of-freedom-vectors).

**Comment by Wayne901** [comment]
Thank you @pazner, my current source is correct now with `ParallelAssemble()`. I have 2 last questions.

1. Is there something special about `HypreParVector`? I assume it's same as a `Vector` with true dofs size.
2. `ParallelProject` and `ParallelAssemble` calls 
    `pfes->GetRestrictionMatrix()->Mult()` and `pfes->GetProlongationMatrix()->Mult()Transpose`, respectively. Are they 
    equivalent?

**Comment by pazner** [comment]
> 1. Is there something special about `HypreParVector`? I assume it's same as a `Vector` with true dofs size.

`HypreParVector` is a `Vector` with size equal to the number of true DOFs. It also wraps a `hypre_ParVector`, which is an object from the _hypre_ library that allows it to easily interface with hypre matrices and preconditioners. In most MFEM code, you can use `Vector` instead of `HypreParVector`.

> 2. `ParallelProject` and `ParallelAssemble` calls
>    `pfes->GetRestrictionMatrix()->Mult()` and `pfes->GetProlongationMatrix()->Mult()Transpose`, respectively. Are they
>    equivalent?

`ParallelAssemble` will perform **_assembly_**, in other words it will _add_ contributions from shared processors. This is the right thing to do for dual vectors like linear forms. `ParallelProject` will _restrict_ the vector, meaning it will just take one of the shared values (if the code is consistent, all of the shared values will be equal, and it won't matter which one you take).

**Comment by Wayne901** [comment]
It's clear now. Thank you @pazner .
