### ISSUE TITLE
Can MFEM built with mumps with a different gcc version?

### ISSUE THREAD

**Issue by Wayne901** [mfem/mfem#4250]
I build my mfem, metis and other packages with gcc@10.1.0. However, gcc version 10 on centos creates so much bugs when building MUMPS. Can I build mumps (or even blas, lapack and scalapack) with another gcc than mfem's?

**Comment by tzanio** [comment]
I don't know for sure, but I suspect the answer is "maybe". 

Generally there could be issues when linking object files from different compilers/settings, which is why most applications build their full stack from scratch with the same compiler.

If it is just different versions of GCC though, with the same system libraries, then things may just work...

**Comment by Wayne901** [comment]
Thank you tzanio.
I changed my gcc to version 9.5.0 and installed mumps from spack smoothly. I guess it's better to reinstall hypre, metis and mfem with gcc@9.5.0 again then ...

**Comment by v-dobrev** [comment]
You should be able to build MUMPS with GCC 10 and later by adding `-fallow-argument-mismatch` to the fortran flags, similar to how it is done in Spack, here: https://github.com/spack/spack/blob/9e2558bd563af31355d83471f628a5d02656cdac/var/spack/repos/builtin/packages/mumps/package.py#L222-L230
