### ISSUE TITLE
Question on shared faces

### ISSUE THREAD

**Issue by kvoronin** [mfem/mfem#426]
Hello,

Is it a valid way to look at the truedof indices of the shared face dofs like that?
```
          std::set<int> shared_facetdofs;

           for (int grind = 0; grind < ngroups; ++grind)
           {
               int ngroupfaces = pmesh->GroupNFaces(grind);
               Array<int> dofs;
               for (int faceind = 0; faceind < ngroupfaces; ++faceind)
               {
                   Hdiv_space->GetSharedFaceDofs(grind, faceind, dofs);
                   for (int dofind = 0; dofind < dofs.Size(); ++dofind)
                       shared_facetdofs.insert(Hdiv_space->GetGlobalTDofNumber(dofs[dofind]));
               }
           }
           std::set<int>::iterator it;
           for ( it = shared_facetdofs.begin(); it != shared_facetdofs.end(); it++ )
               std::cout << *it << " ";
```

Thanks,
Kirill

**Comment by kvoronin** [comment]
Could also someone explain what is happening in SubDofOrder(), http://mfem.github.io/doxygen/html/fe__coll_8cpp_source.html#l00353 ?
E.g. what is to be changed for a 4D meshes.

**Comment by v-dobrev** [comment]
Regarding ParFiniteElementSpace::GetSharedFaceDofs(), the 2 is simply the dimension of "SharedFace". Also, it can also lead to `GetFace<Geometry::SQUARE,Geometry::SQUARE>()` call in `SubDofOrder()`.

The `SubDofOrder()` method from class `FiniteElementCollection` returns a subset of the local dofs in a finite element corresponding to one of its sub-manifolds. This includes applying suitable permutation of the local indices based of the orientation given as part of the `Info` parameter. Let me illustrate this with an example: let's assume that the `Geom` parameter is tetrahedron, `SDim` is 2, and `Info = 64*2+1`. This means that I want to get the indices corresponding to face 2 with orientation 1, relative to the reference orientation of face 2 inside the tetrahedron. The subset of indices is a subset of the set `{0,1,...,ndofs-1}` where `ndofs` is the number of dofs for a tetrahedron in the given FE collection. For simplicity let's assume that we have a linear tetrahedron element with 4 dofs in the 4 vertices. Face 2 is defined as the face with vertices `{0,1,3}`, see the array `Geometry::Constants<Geometry::TETRAHEDRON>::FaceVert`. Now, since we want to get the dof-ordering for orientation 1, we need to permute `{0,1,3}` accordingly. That is why we need to look into the definition of orientation 1 for a triangle - the array `Geometry::Constants<Geometry::TRIANGLE>::Orient` - which says that for the set `{0,1,2}` orientation 1 is given by `{1,0,2}`, so in our case the set `{0,1,3}` becomes `{1,0,3}`. If you have a high-order element with degrees of freedom on the edges and inside the faces, those additional dofs will need to be included in the returned index set.

**Comment by kvoronin** [comment]
Thank you for the comments, @v-dobrev!
I got the idea, in 4D it would be 3. I was confused because calling GetFace with the same geometry types seemed weird since I thought that one template parameter was for the element type and second for the face type.
