### ISSUE TITLE
Boundary integration of H(curl) problems

### ISSUE THREAD

**Issue by Wayne901** [mfem/mfem#4264]
Hi, I need to integrate some bilinear and linear boundary parts in an electromagnetic problem.
The terms to be integrated are
$\int_{\Gamma} \gamma (\hat{n}\times \boldsymbol{W})(\hat{n}\times \boldsymbol{E})ds$ and $\int_{\Gamma} \gamma (\hat{n}\times \boldsymbol{W})(\hat{n}\times \boldsymbol{E}^{inc})ds$, 
where $\boldsymbol{W}$, $\boldsymbol{E}$, and $\boldsymbol{E}^{inc}$ are test functions, trial functions, and a `GridFunction`, respectively.
For Nedelec basis functions, should I apply the `VectorMassIntegrator`($\gamma$) and `VectorBoundaryLFIntegrator`($\gamma\boldsymbol{E}^{inc}$)? I‘m not sure since there are $\hat{n}\times$ terms.

**Comment by Wayne901** [comment]
Well `VectorBoundaryLFIntegrator` is for H1 space, I think `VectorFEBoundaryTangentLFIntegrator` is correct for Hcurl space.

**Comment by najlkin** [comment]
Yes, you should use `VectorFE` variants, because Nedelecs are vector finite elements, i.e., certain components are stored at DOFs. This should not be confused with `Vector` variants, which assume scalar finite elements like H1 with vector dimension, i.e., all components are stored at every DOF (which are then called VDOFs).

**Comment by Wayne901** [comment]
Thank you najlkin, I'm clear with it now.
