### ISSUE TITLE
Behaviour of DiffusionIntegrator when used as boundary integrator

### ISSUE THREAD

**Issue by Rickbude** [mfem/mfem#4281]
Hi there, I have a question about the usage of a `DiffusionIntegrator` as a Boundary Integrator, and the behavior I should expect when doing so.

To understand why I even want to do this, let me describe the case first.

### The case

I am trying to model "free-space"/"open" boundary conditions for the Poisson equation using Asymptotic Boundary conditions (ABC's), as explained in Gratkowski (2016) - "General Closed-Form Asymptotic Boundary Conditions for Finite Element Analysis of Exterior Electrical Field Problems" (doi: [10.15199/48.2016.05.04](http://dx.doi.org/10.15199/48.2016.05.04)).

The weak form for the Poisson equation is given, after some manipulation, by:

```math
\iint_{\Omega}{\epsilon \nabla T \cdot \nabla V dS}
= \int_{\partial \Omega}{\epsilon T \nabla V \cdot \hat{n} dl}
+ \iint_{\Omega}{T\rho dS},
```

with $\epsilon$ the permittivity (let's take $\epsilon =\epsilon_0$ for simplicity), $V$ the potential, $T$ the test function. As an example, the second-order ABC boundary condition, expressed in 2D polar coordinates $(r,\phi)$, on the surface of a circle with $r=\mathrm{constant}=R$, is given by:

```math
 \nabla V \cdot \hat{n} = \frac{\partial V}{\partial r} = -\frac{1}{3R}\left(2V-\frac{\partial^2 V}{\partial \phi^2}\right)
```

This equation is obtained based on a multipole expansion of the potential. Substitute this into the weak form, and use partial integration to obtain for the boundary term (I think, I am not 100% sure about the partial integration):

```math
\int_{\partial \Omega}{\epsilon T \nabla V \cdot \hat{n} dl} = 
 - \frac{2\epsilon_0}{3R} \int_{\partial \Omega}{ TV dl} 
 - \frac{\epsilon_0}{3R}\int_{\partial \Omega}{ \frac{\partial{T}}{\partial{\phi}}\frac{\partial{V}}{\partial{\phi}} dl} 
```

### Implementation options

Clearly the first term on the right-hand side can be implemented using a `MassIntegrator` (Or should I use a `BoundaryMassIntegrator`, is there a difference?). My confusion is mainly about the second term on the right-hand side. I can come up with two ways of implementing this:

**Option 1**

use $dl = rd\phi$ and the chain rule:

```math
\frac{\partial{V}}{\partial\phi} = \frac{\partial{V}}{\partial{l}}\frac{\partial{l}}{\partial{\phi}}=r\frac{\partial{V}}{\partial{l}}
```
to write:

```math
\int_{\partial \Omega}{\epsilon T \nabla V \cdot \hat{n} dl} = 
 - \frac{2\epsilon_0}{3R} \int_{\partial \Omega}{ TV dl} 
 - \frac{\epsilon_0R}{3}\int_{\partial \Omega}{ \frac{\partial{T}}{\partial{l}}\frac{\partial{V}}{\partial{l}} dl} 
```

This seems to imply that I can use a `DiffusionIntegrator` with a scalar coefficient (or scaled identity matrix coefficient). 

**Option 2**

Use the chain rule to write $\partial{V}/{\partial\phi}$ in terms of $\partial{V}/{\partial{x}}$ and $\partial{V}/{\partial{y}}$:

```math
\frac{\partial{V}}{\partial\phi} 
= \frac{\partial{V}}{\partial{x}}\frac{\partial{x}}{\partial\phi}
+ \frac{\partial{V}}{\partial{y}}\frac{\partial{y}}{\partial\phi}
= -y\frac{\partial{V}}{\partial{x}}
   +x\frac{\partial{V}}{\partial{y}}
```

and use that to write:

```math
\int_{\partial \Omega}{\epsilon T \nabla V \cdot \hat{n} dl} = 
 - \frac{2\epsilon_0}{3R} \int_{\partial \Omega}{ TV dl} 
 - \frac{\epsilon_0R}{3}\int_{\partial \Omega}{ 
  \left(
  \left[\begin{matrix}
     y^2  &  -xy \\
     -xy    &  y^2 
  \end{matrix}\right]
   \nabla{V}\right) \cdot \nabla{T} dl
} 
```

Once again, we can use a `DiffusionIntegrator`, but now with a matrix coefficient. In contrast to the previous approach, this expands trivially to 3D simulations with 2D boundary segments.

### Questions

While this type of boundary condition seems to work well or circular boundaries, the ellipsoidal and rectangular boundaries (for which a `MixedScalarDerivativeIntegrator` or `MixedDirectionalDerivativeIntegrator` is needed) have an error of 1-2 orders of magnitude higher on a comparable mesh size/density. I am trying to determine whether this is because I made an implementation or derivation error, or because I am maybe misunderstanding how bilinearform integrators involving the gradient work on the boundaries. This finally brings me to the questions:

 * Does the `DiffusionIntegrator`, when used as a boundary integrator, operate in the same dimension number as the domain integrators? (2D in this case).  Or on the dimension number of the boundary segment? (1D in this case). If the latter is the case, why is a 2x2 matrix coefficient accepted?
 * Is option 1 or option 2 closer to how the code works? Which option is "better"? Strangely enough, the results are exactly the same in this example case (See picture below).

My apologies for this long post and the many questions.  Thanks in advance!

![image](https://github.com/mfem/mfem/assets/24381938/e634f447-6945-484c-8a28-fa965cf66538)

**Comment by v-dobrev** [comment]
Hi @Rickbude,

When a bilinear form integrator is used as a domain integrator, the assembly function calls its `AssembleElementMatrix` with the `FiniteElement` and `ElementTransformation` corresponding to every mesh element. With a typical 1D, 2D or 3D mesh, both the reference dimension (returned by `Mesh::Dimension()`) and and the space dimension (returned by `Mesh::SpaceDimension()`) are the same, so the Jacobian matrix of the `ElementTransformation` is square. All "volume" bilinear form integrators support this case of square Jacobian, at least for one of 1D/2D/3D case, and in many cases they support all dimensions. Now, when the mesh space dimension is larger than the reference dimension (e.g. a surface mesh with reference dim = 2 and space dim = 3) then the Jacobian matrix is no longer square but has dimensions (space dim) x (reference dim) and this case has to be handled properly inside the integrator in order to be supported. In some cases, this is easy to support -- e.g. for a mass integrator, one just needs to make sure to use `J.Weight()` to compute the weight associated with the change of variables in the integral from space dimension to reference dimension. For `DiffusionIntegrator` the change to support non-square Jacobian is a bit more involved but it is implemented -- in this case the integrator corresponds to the surface Laplacian (i.e. the Laplace–Beltrami operator on the surface).

When a bilinear form integrator is used as a boundary integrator, the same `AssembleElementMatrix` method is called, however now the `FiniteElement` argument corresponds to the boundary elements of the finite element space used by the bilinear form. For H1 space, the boundary elements are also H1; for H-curl space, the boundary elements are also H-curl; for H-div, the boundary elements are L2; for L2 space, there are no finite elements associated with the boundary. Note that for H-curl space using the boundary H-curl element means that the integrator will only have access to the tangential components; for H-div space using the boundary L2 element means that the integrator will only have access to the normal component. Another difference in the `AssembleElementMatrix` call (in the boundary integrator vs domain integrator use case) is that the `ElementTransformation` parameter will describe the boundary element which is a map from (Mesh::Dimention()-1)-dimensional space to Mesh::SpaceDimension()-dimensional space. So in order for a bilinear form integrator to work as a boundary integrator, it must support the case on non-square Jacobian, similar to the case of surface meshes.

Here are some details about some of the integrators you asked about:
* `DiffusionIntegrator`: as I mentioned above it works on boundaries and surface meshes. In general, the coefficient, say $Q$, can be (space dim) x (space dim) matrix -- this is because it is used in a product of the form $(\nabla v)^T Q (\nabla u)$ where $\nabla u$ and $\nabla v$ are the gradients of the trial an test functions, respectively. These gradients have space dim components, however they lie in the tangential plane of the boundary/surface element, so ultimately only the action of $Q$ in the tangential direction matters.
* `VectorFEMassIntegrator`: this integrator can be used as boundary integrator in an H-curl space in any dimension. As mentioned above, boundary integrators in H-curl spaces can only see the tangential components of the field, so they integrate the dot product of the tangential components of the trial and test functions.

Let me know if I overlooked something and did not answer all your questions.

**Comment by v-dobrev** [comment]
@mlstowell, this is another use case we may want to add to the MFEM website -- `VectorFEMassIntegrator` can be used as boundary integrator in a bilinear form defined on an H-curl space.

**Comment by Rickbude** [comment]
Thankyou for this incredibly helpful and elaborate response! I think I understand how it works now, so as far as I am concerned this issue can be closed. Is there a place where this sort of implementation details of MFEM are described in more detail? (aside from the code/doxygen itself ofcourse).

**Comment by v-dobrev** [comment]
There may be some discussion about topics like this in the mfem paper: https://doi.org/10.1016/j.camwa.2020.06.009 (arxiv version: https://arxiv.org/abs/1911.09220), however, I don't think we go into much detail there.
