### ISSUE TITLE
Correct way to use GetSerialMesh and GetSerialGridFunction

### ISSUE THREAD

**Issue by skbizport** [mfem/mfem#4472]
Hi

I am using a modified version of example ex2.cpp (Parallel linear static analysis) to compute von mises stress. My use case has a few post-processing steps on the results and finally I save the mesh and displacements/stress in a custom format. This process requires unification of mesh/stress/displacements from multiple ranks and generate consolidated arrays across in the final step. 

Methods GetSerialMesh() and GetSerialGridFunction() seem suitable for this purpose, however, the results from these methods vs. a single process computation are showing differences. I suspect I am not using these API's properly. An example or some documentation on this would be quite useful.

Here is the summary of the steps, based on ex2.cpp. 

```
//Step 1: Recover solution on a local rank
ParGridFunction x(fespace);
... 
a->RecoverFEMSolution(X, *b, x);
 
//Step 2: Compute local (rank) stress components
StressCoefficient stress_c(lambda_func, mu_func);
ParGridFunction sigma_xx(&scalar_dg_space);
stress_c.SetDisplacement(x);
sigma_xx.ProjectCoefficient(stress_c);
...
...  

//Step 4: Compute local von mises stress 
ParGridFunction local_von_mises(fespace);
    
for (int i = 0; i < x.Size(); i++)
{
     //compute von mises
     local_von_mises(i) = von_mises;
}
 
//wait for all to complete
MPI_Barrier(MPI_COMM_WORLD);

//Step 5: Get serial versions
if(rank == 0) {
  mfem::Mesh serial_mesh = ptrmesh->GetSerialMesh(0);
  mfem::GridFunction serial_stress = local_von_mises.GetSerialGridFunction(0, serial_mesh);
  mfem::GridFunction serial_displacement = x.GetSerialGridFunction(0, serial_mesh);
 
 //Step 6: Post process serial versions and store it in a file 
 ...
}
 ```

Appreciate any pointers.
Thx

Regards
SK

**Comment by kmittal2** [comment]
Dear @skbizport,

First of all, the `GetSerialMesh` etc should not be inside the `if (rank == 0) {` block. The methods you are calling require some parallel communication so the sample code you shared above will hang because not all MPI ranks are participating. See [this](https://github.com/mfem/mfem/blob/master/tests/unit/fem/test_pgridfunc_save_serial.cpp) unit test for example usage.

Second, the element and vertex numbering for the mesh obtained from these methods is not expected to match the numbering of the original serial mesh. So you will have to be careful about how you are comparing results on these two meshes.

Hope this helps,
Ketan

**Comment by skbizport** [comment]
Will take a look at the test.

Thx
SK
