### ISSUE TITLE
Regarding implementation of Dirichlet conditions in Example 1

### ISSUE THREAD

**Issue by Raghavendra0117** [mfem/mfem#4477]
Dear all,

I am trying to solve the following equation 
$\nabla .(\nabla u) =0$ with $u(z=0.5)$ = -10.0 and $u(z=-0.5)$ = 10.0
In this regard, i have added a few lines to the 'example-1' code .
The added lines are

```c++
ParLinearForm b(&fespace);
   
b=0.0;
ParGridFunction x(&fespace);
x = 0.0;
FunctionCoefficient initial(fun);
x.ProjectCoefficient(initial);

double fun(Vector &x)
{
    double val ;
    if(x[2]<=-0.5)
    {
        val = 10.0;
    }
    else if (x[2]>=0.5)
    {
        val = -10.0;
    }
    else
    {
        val = 0.0;
    }
     
   return val;
}
```

When i ran the code, it resulted a solution that looks exactly like the initial state.  There is no change between the initial grid function and the solution. 

"cylinder-hex.mesh" (you can find it in mfem/minapps/electromagnetics/) is used as input mesh. 
The obtained solution is shown in the following figure.
![ex1_modified_sol](https://github.com/user-attachments/assets/8fdf912a-a516-4f6f-8a0d-453d4ce57788)

It will be of great help if someone can help me in adding Dirichlet boundary conditions to solve the above equation.

Thanks a lot in advance
Raghavendra Kollipara

**Comment by psocratis** [comment]
@Raghavendra0117 ,

From the picture above it seems that the top and bottom Dirichlet values are enforced correctly, but also a homogeneous Dirichlet BC is enforced on the rest of the boundary. The mesh you are using has 3 different boundaries, distinguished by the attributes 1,2,3. The top boundary has attribute=1, the bottom attribute = 2, and the rest attribute = 3. If you want to enforce only Dirichlet on top and bottom you have to modify lines 215-220 as follows:

````cpp
if (pmesh.bdr_attributes.Size())
{
   Array<int> ess_bdr(pmesh.bdr_attributes.Max());
   ess_bdr = 1;
   ess_bdr[2] = 0; // this removes boundaries with attribute = 3 from the list of the essential boundaries.
   fespace.GetEssentialTrueDofs(ess_bdr, ess_tdof_list);
}
```` 

Here is the solution with the above change 
<img width="379" alt="image" src="https://github.com/user-attachments/assets/c453afe4-ff47-417f-a890-2c30ccb5031d">

Since each boundary (top and bottom) has a constant Dirichlet value you may want to avoid using a `FunctionCoefficient` and project the constant value directly on each boundary, i.e., you can replace 

````cpp
FunctionCoefficient initial(fun);
x.ProjectCoefficient(initial);
````

with 

````cpp
ConstantCoefficient ten(10.0);
ConstantCoefficient negten(-10.0);
Array<int> ess_bdr(pmesh.bdr_attributes.Max());
ess_bdr = 0;
ess_bdr[0] = 1;
x.ProjectBdrCoefficient(negten,ess_bdr);
ess_bdr[0] = 0;
ess_bdr[1] = 1;
x.ProjectBdrCoefficient(ten,ess_bdr);
````

I hope this helps.

Best,

Socratis

**Comment by Raghavendra0117** [comment]
Thanks a lot @psocratis.

I did not change the "ess_bdr" at all in the example 1 which is set to 1 for all boundaries. That was the mistake. Now the result is as expected.
![ex1p_sol](https://github.com/user-attachments/assets/a60f0ec5-03f9-4b2d-a800-45208eb26d5e)
