### ISSUE TITLE
Create `ParMesh` in cascading way

### ISSUE THREAD

**Issue by aschaf** [mfem/mfem#4479]
Hi,

I have a somewhat specific question. Is there an already implemented way to distribute a sequential Mesh in a cascading manner to a ParMesh. 

For instance, say we have 16 processors, we start with a serial mesh, refine it a few times, then distribute it to a `ParMesh` over 4 processors and again refine a few times and then finally distribute it to a `ParMesh` over all 16 processors. 

I have some ideas how to do that, I just want to make sure I am not reinventing the wheel.

Thank you,
Andreas

**Comment by v-dobrev** [comment]
This requires some form of re-partitioning for the ParMesh which is currently possible only if you convert the serial mesh to nonconforming mesh, e.g. using `EnsureNCMesh()`. You can then use a custom partitioning array to distribute the serial mesh to 4 processors assigning 0 elements to the remaining 16-4=12 ranks. After parallel refinement, you can re-partition the mesh to 16 ranks using `Rebalance(const Array<int> &partition)`.

Note that, If your mesh is tetrahedral, switching to NCMesh is somewhat limiting because not all tet refinement algorithms are available for NC meshes.

**Comment by aschaf** [comment]
Thank you. I will look into it and keep you updated.
