### ISSUE TITLE
Question on extracting dofs correspondence for a pair top-bottom of boundary elements

### ISSUE THREAD

**Issue by kvoronin** [mfem/mfem#450]
Hello,

Can some one help with the following problem? 
Consider a simplicial (tetrahedral) mesh for a cube, and imagine there is a pair of boundary elements given which have the same vertices up to a permutation, but with different last coordinate. I  other words, they are geometrically the same up to a shift in one of the coordinates.
Now I have a finite element space defined on the mesh, and I want to find a correspondence between dofs (in the end, true dofs) for this pair of boundary elements.

How should I do that?

I thought that I should do something like FiniteElementSpace::GetBdrElementDofs(), but somehow neglect the orientation. If someone can approve this plan and/or give more details, it would help. Foe example, if I do exactly the same, but instead of actual orientation of the dof's geometry entity, use always orientation = 0, will it be correct?

Thanks,
Kirill

**Comment by YohannDudouit** [comment]
Hi,

I'm not sure I understand what you really want to do. Do you want to know how one element is oriented relatively to the other element?

Sincerely,
Y

**Comment by kvoronin** [comment]
@YohannDudouit,

I want to get a set of pairs where in each pair first element is index of a dof for the boundary element at the bottom, second element is the index of a dof for the top boundary element. And these dofs must correspond to the same geometrical entity (say, face, or edge). Same means here "same up to a shift in the last coordinate" (at the beginning I have a pair of boundary elements which are the same, as a pair of bdr element indices). 
So, orientation only is not enough.

Thanks,
Kirill

**Comment by kvoronin** [comment]
I know how to compute a permutation of vertices so that vertices of the first bdr element transform into the vertices of the second (up to a vertical shift). But how to combine that with dof lists which I can obtain for each bdr element?

**Comment by YohannDudouit** [comment]
If I understand correctly your problem, there is only 2 possible permutations in 2D and 3 possible permutations in 3D (and one is identity). Once you have identified which permutation case you are in, and using the dofs ordering that you can find in fe.cpp (for the type of element you're using, e.g. line 7555 for H1_Tetrahedron), you should be able to deduce the dofs mapping between the two elements.

**Comment by kvoronin** [comment]
First, I think there are more permutations, like n! of the vertices. Second, what if dofs are not directly related to vertices? It is not only H1 elements which I need. Linear H1 and RT0 elements are probably the simplest cases. 

Can I claim, that when I call GetBdrElementDofs() the order of dofs for linear H1 will be the same as the order of vertices in GetBdrElementVertices()?

**Comment by tzanio** [comment]
@mlstowell, do I remember correctly that you also wrote a function to define periodic meshes?

**Comment by kvoronin** [comment]
@tzanio,

No, I am trying to implement a time-stepping approach, so I need to transfer the solution obtained for a single time step at time = tau to an initial condition for the next time step. 
For now I am fine with doing it for lowest order RT and linear H1 elements where I did it using the fact that dofs are related to faces or vertices only. But it would be nice to do it for general finite element spaces, of course.

**Comment by YohannDudouit** [comment]
If you want to implement this function yourself, all the information you need is in fe.cpp. Dofs ordering depends on the kind of elements, H1 and RT elements do not order dofs the same way (because they are not in the same locations). For instance, H1_tetrahedron first order corner dofs, then vertice dofs, then face dofs, then inner dofs. Where corner dofs are ordered the same way as for Linear H1, but you have to look in fe.cpp for the remaining dofs. On the other hand, RT elements don't have dofs in the corners or on vertices, so ordering starts on faces, and then comes inner dofs.

**Comment by sshiraiwa** [comment]
Hi all,

I didn't notice my name was mentioned a few days ago! Sorry.  Since I do things in Python 
mostly and therefore I cannot be helpful in terms of c++ coding. But, I am happy to 
to share my experience about this issue. 

What I did was similar to your situation. Suppose you have two surfaces which are 
meshed in the same way. Two surfaces are not necessary to be parallel, and but has 
to be composed by the geometrically same mesh elements, and each surfaces is labeled 
using a unique bdr_attribute. Then, mapping between DoF can be made in the following two steps.

1) First thing is to find a mapping between a boundary element on one surface to the other 
surface.  I used the following methods and mapped the boundary element id using the 
average of 3 (or 4) vertices.
   GetBdrAttribute
   GetBdrElementVertices
   GetVertex.

2) The second is more involved. We need to  find a mapping between a set of DoFs which belongs to a boundary element on one surface to the set of DoFs for the corresponding boundary element on the other surface. I did this by looking at the shape function, since the corresponding DoF should
produce the same shape. Here the same shape can be judged by,,if they have the
same value on the "selected" corresponding points. 
I used the integration points determined by determined by the integration rule of the FiniteElement. You can get this using GetNodes of FiniteElment returned by GetBE(). Then it is straightforward
to evaluate shape using either CalcShape or CalcVShape depending on the type of your FE.
Note also that you need to find the mapping between the integration points on one surface to the other.

In addition to the above,  there are a several point one has to be careful,,,

1) For the ND element, one to one correspondence of DoF is not guaranteed, even if
the mesh is the same. It can be possible thatDoF o n one surface is the linear
 combination of two DoFs on the other surface.

2) In the parallel situation, the information of the other side may not exist on the
same node. Therefore, we need to allgather the data (the location of integration points,
the shape function values and so on) of at least one surface among all node.

3) Additionally, in the parallel environment DoF and TDoF are different even when
the mesh is conforming. I used Dof_TrueDof_Matrix for this conversion.

This approach is general, not relying on any ordering of internal data structure. So it should 
work on RT too although I did this only for H1 and ND.  And perhaps it should work even 
if two surfaces belong to different mesh objects. 

p.s. it would be great if the MFEM team provides official c++ version to perform this mapping ;D

**Comment by kvoronin** [comment]
@sshiraiwa.

Thank you very much for sharing your thoughts. 
I ended up with implementing the first thing (1. in your reply) pretty much the similar way.
As for the second thing, I really like your idea of using the integration points and comparing shape functions. For now, I am satisfied by implementing only the RT0 and linear Lagrange elements (thus heavily exploiting the fact that dofs are either faces or vertices, in the latter case I dealt with vertex permutations for the pair of boundary elements), but when I was asking my original question I was wondering if something can be done following your approach.

Thanks again!

**Comment by mlstowell** [comment]
What I did was much simpler but may not be applicable to your case.  I would start with a serial mesh and create a mapping between the vertices on two disjoint boundaries.  Then use this mapping to eliminate the vertices on one boundary and replace them with their counterparts on the other boundary.  This creates a periodic mesh.  Then any finite element spaces created on this periodic mesh will naturally join across this pair of boundaries.

The relevant code can be found in the function MakePeriodicMesh in miniapps/common/bravais.cpp in the branch bravais-dev.

**Comment by kvoronin** [comment]
@mlstowell,
I'm afraid this it is not applicable in my case because at some point I will have different values on the two boundaries (after I solved a problem) and only after that I will transfer values from one boundary to the other.
Still, thanks for your comment, maybe I will use it later.

**Comment by tzanio** [comment]
Link to Mark's code:

https://github.com/mfem/mfem/blob/bravais-dev/miniapps/common/bravais.cpp#L6864-L7148
