### ISSUE TITLE
【bug】A bug with respect to the DG_FECollection

### ISSUE THREAD

**Issue by cglwdm** [mfem/mfem#4506]
Just run the following code, we will get null address with respect to the boundary element of DG_FEColletion, see the following code

```c++
const char *mesh_file = "../data/inline-tri.mesh";

Mesh *mesh = new Mesh(mesh_file, 1, 1);
int dim = mesh->Dimension();
ParMesh *pmesh = new ParMesh(MPI_COMM_WORLD, *mesh);
delete mesh;
int orderQ = 1;

FiniteElementCollection* P_coll(new DG_FECollection(orderQ, dim));
ParFiniteElementSpace* P_space = new ParFiniteElementSpace(pmesh, P_coll, dim);

for (int i = 0; i < P_space->GetNBE(); i++)
{
   printf("add=%p\n", P_space->GetBE(i));
}
```

**Comment by pazner** [comment]
Hi @cglwdm,

Perhaps confusingly, `FiniteElementSpace::GetNBE` returns the number of boundary elements in the mesh, however, DG finite element spaces do not have any boundary elements (even if the mesh does). This is because DG spaces do not necessarily have degrees of freedom belonging to element faces (e.g. with Gauss-Legendre basis, all nodes are interior).
