### ISSUE TITLE
【HypreBoomerAMG preconditioner does not work well on some condition】

### ISSUE THREAD

**Issue by cglwdm** [mfem/mfem#4639]
Sorry for this, I think I found the reason, the B in a) and b) is not the same one. Sorry for my mistake

I have a 6x6 block matrix and the first 4x4 can be static condensation. I have two approaches:

a） I eliminate the 4x4 block at the local level, then assemble the 2x2 block Matrix as a `HypreParMatrix` Abb1 form `HypreParMatrixFromBlocks`, I use a fixed matrix B to deduce the `HypreBoomerAMG` as amg, the I use amg as block preconditioners. It works very well! 

b) I eliminate the 4x4 block at the global level, using `ParMut` `ParADD` (The 4x4 global matrix are its inverse, so I do not need to perfom inverse), after the  eliminate, I got `HypreParMatrix` Abb2, since `Abb1==Abb2` mathematically,  I use the preconditioner in a), but It does not work well.

I use `Print()` to print Abb1 and Abb2, they have the same entries but in different orders, when I solver `Abb1 x= Fb` and `Abb2 x =Fb`, I will get the same solution, but in b) the preconditioner does not work well (almost the same as without  preconditioner).  So how does this happen and how  to fixe it?

I guess because I use `HypreParMatrixFromBlocks` in a) it will work well using block amg; but in b) the block amg does not work  since Abb2 does not come from `HypreParMatrixFromBlocks`

**Comment by cglwdm** [comment]
I use the code 
`  Array2D<HypreParMatrix*> Abb_block_new(num_b, num_b);
  Abb->GetBlocks(Abb_block_new);
  HypreParMatrix* Abb_new = HypreParMatrixFromBlocks(Abb_block_new);`

To get a new HypreParMatrix form HypreParMatrixFromBlocks, but the result is the same

**Comment by tzanio** [comment]
Hi @cglwdm,

To add a bit to you conclusions that the matrices are not the same:

In general, the performance of *algebraic* preconditioners, i.e ones that use the matrix entries explicitly such as AMG, can depend significantly on the ordering of the matrix unknowns. (This is not the case for methods that only use the action of the matrix, such as plain CG or polynomial Chebyshev smoothing). As one extreme case, consider a lower triangular matrix which will be solved by Gauss-Seidel in one iteration. If you reorder the matrix, e.g. flip it vertically, the problem can become really hard for Gauss-Seidel.

That being said, I wonder it the ordering of the unknowns is the real issue here. If I understand correctly, the matrix B is still 2x2, and BoomerAMG has to be informed that this is a system with [`HypreBoomerAMG::SetSystemsOptions()`](https://github.com/mfem/mfem/blob/v4.7/linalg/hypre.hpp#L1720)? Maybe this happens in one of the approaches and the other?

Hope this helps,
Tzanio
