### ISSUE TITLE
Can I solve complex-valued problems with MFEM?

### ISSUE THREAD

**Issue by JiananZhangCU** [mfem/mfem#467]
Hi, all,

I've reviewed MFEM examples and found that there seems no one handling complex-valued problems. They are either scalar-valued or vector-valued, but the unknown quantity are all real-valued.

Can MFEM of the current version handle complex-valued problems (such as the complex-valued Helmholtz problem)? If yes, are there any tutorials?

Thanks.

Jianan

**Comment by v-dobrev** [comment]
Hi @JiananZhangCU,

You can solve complex valued problems by reformulating them in 2x2 block form, i.e. separating the real and imaginary parts of a complex vector. We recently added a couple of new classes that should be helpful with such reformulation, see https://github.com/mfem/mfem/blob/master/linalg/complex_operator.hpp. However, right now, we do not have examples that illustrate their usage.

**Comment by tzanio** [comment]
Hi Jianan,

Just wanted to add that @mlstowell and @agrayver are also interested in complex-valued problem and may add some electromagnetic examples of this type in the future.

Tzanio

**Comment by JiananZhangCU** [comment]
Hi, @v-dobrev , @tzanio,

Grad to know that complex-valued problems are being fully considered in this project. Actually my major is also on computational electromagnetics. I heard of @agrayver from my previous experience with dealii. He contributed a lot on the EM part. 

Anyway, I will stay closely with the development of MFEM and hope I can also make some contributions to it in the future. By the way, thanks for adding me to the Users team.

Jianan

**Comment by xj361685640** [comment]
I am also interesting in the EM simulation, especially with DGTD method. Is there some examples about EM simulation using DGTD method?

**Comment by S-Villar** [comment]
Hello all,

I have been working for some months on a simulation in C++ based on MFEM libraries for EM wave propagation to simulate electron-cyclotron-resonance (ECR) plasma thrusters for project of H2020, MINOTOR, funded by the EC. I found your libraries really useful and first of all let me thank you for your amazing work developing MFEM. 

Answering @JiananZhangCU , as @v-dobrev mentioned you can solve this using block approach splitting real and imaginary parts in your equations and solving a block system. I recommend you using Example 5 as guidance for using blocks and also note Example 8 use of mixed bilinear forms, although sometimes they may not be necessary. I may warn you about the possible bad convergence of iterative solvers. I found the best approach to compile MFEM using SUITESPARSE and UMFPACK libraries specifically and solve with direct solver as in some examples. The block approach, although a bit more tedious in the mathematical formulation, works fine. However, making MFEM handle complex numbers in the future could be a nice contribution from my point of view. 

Furthermore I wanted to add a couple of questions regarding the use of MFEM. I have had some contact with  @sshiraiwa, who introduced me to your software and gave me really helpful hints and advice in the development of this simulation. 
- 1 . Here at Universidad Carlos III de Madrid we aim to reproduce **axisymmetric** EM wave propagation using FE formulation. Currently we are able to solve for planar combined with out of plane component (cartesian) EM propagation in a magnetized plasma with inhomogeneous properties. We have some ideas of how to implement the axisymmetric case, but we were wondering if you could give us any advice on how to do so with MFEM, or whether there are any axisymmetric simulations already done using your software.
- 2 .  Furthermore, I have seen that you define in the documentation (http://mfem.org/bilininteg/) some elements H_1^d as vector-valued basis functions constructed by copies of nodal elements for each component. I was trying to find without success a constructor of this collection in a FiniteElementCollection class similar to H1_FECollection, in which the user could specify that each component of a vector of dimension **n** is nodal. Is this functionality available? Otherwise, could you provide some example of how to create this new type of finite element space? Cause the only solution that comes to my mind now is to create a new block system with every component as nodal elements and applying the corresponding changes in the operators for the matrix building process. 

Thanks in advance,

Alvaro

**Comment by jakubcerveny** [comment]
Hi Alvaro,

as for your second question (if I understand correctly), for H1^d, you don't specify the vector dimension in the FECollection but in the constructor of the FiniteElementSpace ('vdim' argument). It is the space who takes care of copying the finite element in each component. See Example 2 for this.

Jakub

**Comment by S-Villar** [comment]
Hello Syun'ichi,

Thanks for your quick answer. If I understood your comment I did exactly this (for the Cartesian case) following the advice you gave me by email. I applied Fourier in z and built a block system for the out-of-plane component, splitting real and imaginary parts for both in and out of plane. Following your also I used 2D ND for the in-plane component and H1 for the out-of-plane. We have tested the simulation and converges to an analytical solution in a simple case (sinusoidal exact solution in PEC box). However in case of more complicated geometries, forcings, etc, I am not fully sure that the use of H1 for the out-of-plane component is compliant with the divergence free condition, and testing turns further complex.  I agree with you that the use of nodal elements H1 may not be a good approach, I just wanted to implement this H1 simulation as an exercise to compare with the mixed elements version of the code. We want to make sure that the use of H1 elements for the out-of-plane is not affecting the divergence-free condition.

Thanks a lot,

Alvaro

**Comment by JiananZhangCU** [comment]
Hi, Alvaro,

Thanks a lot for sharing your experience with us and giving me so many useful hints about solving complex-valued problems. I am going to follow your suggestions and start solving my own problem (waveguide discontinuity) with MFEM now. 

Best
Jianan

**Comment by S-Villar** [comment]
Hello all,

Thank you very much @jakubcerveny for the answer. Indeed it is as you said. 

I wanted to split in-plane and out-of-plane in my simulation and switch with a flag the elements for the in-plane "vector" elements. However some operators that I may need are missing in that case, MixedVectorProductIntegrator or MixedVectorGradientIntegrator. I guess the mixed bilinear integrators for H1d (for the in-plane component) with H1 (for the out-of-plane component) don't make so much sense for a general purpose and  that is why there is not in an explicit integrator for this purpose.

Thus, I decided to build the nodal elements simulation separately (not integrated with the mixed elements case) to check the solution with H1 nodal elements for each component of the electric field. I started with only in plane. Apparently I am getting an error that you can reproduce taking ex3.cpp and replacing lines:
- 101 and 102 by
`FiniteElementCollection *fec = new H1_FECollection(order, dim);
FiniteElementSpace *fespace = new FiniteElementSpace(mesh, fec, dim);`
- 124 by
 `b->AddDomainIntegrator(new VectorDomainLFIntegrator(f));`
- 142 and 143 by
  `a->AddDomainIntegrator(new VectorCurlCurlIntegrator(*muinv));
   a->AddDomainIntegrator(new VectorMassIntegrator(*sigma));`

Segmentation fault appears when assembling using specifically the VectorCurlCurlIntegrator.
What is wrong in this simple implementation? Could you specify how to do ex3.cpp but with nodal elements H1d. I guess I am missing something trivial...

PS: @JiananZhangCU , if you are gonna work in EM problems with MFEM I think it could be useful to keep contact between us. Do not hesitate to contact me whether you have any issue, that maybe I have been stuck with before.

Alvaro

Hereinafter I attach code for ex3.cpp with H1 elements that returns me this SIGSEGV signal (Segmentation Fault):


```
//                                MFEM Example 3
//
// Compile with: make ex3
//
// Sample runs:  ex3 -m ../data/star.mesh
//               ex3 -m ../data/beam-tri.mesh -o 2
//               ex3 -m ../data/beam-tet.mesh
//               ex3 -m ../data/beam-hex.mesh
//               ex3 -m ../data/escher.mesh
//               ex3 -m ../data/fichera.mesh
//               ex3 -m ../data/fichera-q2.vtk
//               ex3 -m ../data/fichera-q3.mesh
//               ex3 -m ../data/square-disc-nurbs.mesh
//               ex3 -m ../data/beam-hex-nurbs.mesh
//               ex3 -m ../data/amr-hex.mesh
//               ex3 -m ../data/fichera-amr.mesh
//               ex3 -m ../data/star-surf.mesh -o 1
//               ex3 -m ../data/mobius-strip.mesh -f 0.1
//               ex3 -m ../data/klein-bottle.mesh -f 0.1
//
// Description:  This example code solves a simple electromagnetic diffusion
//               problem corresponding to the second order definite Maxwell
//               equation curl curl E + E = f with boundary condition
//               E x n = <given tangential field>. Here, we use a given exact
//               solution E and compute the corresponding r.h.s. f.
//               We discretize with Nedelec finite elements in 2D or 3D.
//
//               The example demonstrates the use of H(curl) finite element
//               spaces with the curl-curl and the (vector finite element) mass
//               bilinear form, as well as the computation of discretization
//               error when the exact solution is known. Static condensation is
//               also illustrated.
//
//               We recommend viewing examples 1-2 before viewing this example.

#include "mfem.hpp"
#include <fstream>
#include <iostream>

using namespace std;
using namespace mfem;

// Exact solution, E, and r.h.s., f. See below for implementation.

void E_exact(const Vector &, Vector &);
void f_exact(const Vector &, Vector &);
double freq = 1.0, kappa;
int dim;

int main(int argc, char *argv[])
{

   // 1. Parse command-line options.
   const char *mesh_file = "../data/beam-tet.mesh";
   int order = 1;
   bool static_cond = false;
   bool visualization = 1;

   OptionsParser args(argc, argv);
   args.AddOption(&mesh_file, "-m", "--mesh",
                  "Mesh file to use.");
   args.AddOption(&order, "-o", "--order",
                  "Finite element order (polynomial degree).");
   args.AddOption(&freq, "-f", "--frequency", "Set the frequency for the exact"
                  " solution.");
   args.AddOption(&static_cond, "-sc", "--static-condensation", "-no-sc",
                  "--no-static-condensation", "Enable static condensation.");
   args.AddOption(&visualization, "-vis", "--visualization", "-no-vis",
                  "--no-visualization",
                  "Enable or disable GLVis visualization.");
   args.Parse();
   if (!args.Good())
   {
      args.PrintUsage(cout);
      return 1;
   }
   args.PrintOptions(cout);
   kappa = freq * M_PI;

   // 2. Read the mesh from the given mesh file. We can handle triangular,
   //    quadrilateral, tetrahedral, hexahedral, surface and volume meshes with
   //    the same code.
   Mesh *mesh = new Mesh(mesh_file, 1, 1);
   dim = mesh->Dimension();
   int sdim = mesh->SpaceDimension();

   // 3. Refine the mesh to increase the resolution. In this example we do
   //    'ref_levels' of uniform refinement. We choose 'ref_levels' to be the
   //    largest number that gives a final mesh with no more than 50,000
   //    elements.
   {
      int ref_levels =
         (int)floor(log(50000./mesh->GetNE())/log(2.)/dim);
      for (int l = 0; l < ref_levels; l++)
      {
         mesh->UniformRefinement();
      }
   }
   mesh->ReorientTetMesh();

   // 4. Define a finite element space on the mesh. Here we use the Nedelec
   //    finite elements of the specified order.
//   FiniteElementCollection *fec = new ND_FECollection(order, dim);
   FiniteElementCollection *fec = new H1_FECollection(order, dim);
   FiniteElementSpace *fespace = new FiniteElementSpace(mesh, fec, dim);
   cout << "Number of finite element unknowns: "
        << fespace->GetTrueVSize() << endl;

   // 5. Determine the list of true (i.e. conforming) essential boundary dofs.
   //    In this example, the boundary conditions are defined by marking all
   //    the boundary attributes from the mesh as essential (Dirichlet) and
   //    converting them to a list of true dofs.
   Array<int> ess_tdof_list;
   if (mesh->bdr_attributes.Size())
   {
      Array<int> ess_bdr(mesh->bdr_attributes.Max());
      ess_bdr = 1;
      fespace->GetEssentialTrueDofs(ess_bdr, ess_tdof_list);
   }

   // 6. Set up the linear form b(.) which corresponds to the right-hand side
   //    of the FEM linear system, which in this case is (f,phi_i) where f is
   //    given by the function f_exact and phi_i are the basis functions in the
   //    finite element fespace.
   VectorFunctionCoefficient f(sdim, f_exact);
   LinearForm *b = new LinearForm(fespace);
 //  b->AddDomainIntegrator(new VectorFEDomainLFIntegrator(f));
   b->AddDomainIntegrator(new VectorDomainLFIntegrator(f));
   b->Assemble();

   // 7. Define the solution vector x as a finite element grid function
   //    corresponding to fespace. Initialize x by projecting the exact
   //    solution. Note that only values from the boundary edges will be used
   //    when eliminating the non-homogeneous boundary condition to modify the
   //    r.h.s. vector b.
   GridFunction x(fespace);
   VectorFunctionCoefficient E(sdim, E_exact);
   x.ProjectCoefficient(E);

   // 8. Set up the bilinear form corresponding to the EM diffusion operator
   //    curl muinv curl + sigma I, by adding the curl-curl and the mass domain
   //    integrators.
   Coefficient *muinv = new ConstantCoefficient(1.0);
   Coefficient *sigma = new ConstantCoefficient(1.0);
   BilinearForm *a = new BilinearForm(fespace);
  // a->AddDomainIntegrator(new CurlCurlIntegrator(*muinv));
  // a->AddDomainIntegrator(new VectorFEMassIntegrator(*sigma));

//   a->AddDomainIntegrator(new VectorCurlCurlIntegrator(*muinv));
   a->AddDomainIntegrator(new VectorMassIntegrator(*sigma));
   cout << "BEFORE ASSEMBLY"<< endl<<flush;

   // 9. Assemble the bilinear form and the corresponding linear system,
   //    applying any necessary transformations such as: eliminating boundary
   //    conditions, applying conforming constraints for non-conforming AMR,
   //    static condensation, etc.
   if (static_cond) { a->EnableStaticCondensation(); }
   a->Assemble();
   cout << "AFTER ASSEMBLY"<< endl<< flush;
   SparseMatrix A;
   Vector B, X;
   a->FormLinearSystem(ess_tdof_list, x, *b, A, X, B);

   cout << "Size of linear system: " << A.Height() << endl;

#ifndef MFEM_USE_SUITESPARSE
   // 10. Define a simple symmetric Gauss-Seidel preconditioner and use it to
   //     solve the system Ax=b with PCG.
   GSSmoother M(A);
   PCG(A, M, B, X, 1, 500, 1e-12, 0.0);
#else
   // 10. If MFEM was compiled with SuiteSparse, use UMFPACK to solve the system.
   UMFPackSolver umf_solver;
   umf_solver.Control[UMFPACK_ORDERING] = UMFPACK_ORDERING_METIS;
   umf_solver.SetOperator(A);
   umf_solver.Mult(B, X);
#endif

   // 11. Recover the solution as a finite element grid function.
   a->RecoverFEMSolution(X, *b, x);

   // 12. Compute and print the L^2 norm of the error.
   cout << "\n|| E_h - E ||_{L^2} = " << x.ComputeL2Error(E) << '\n' << endl;

   // 13. Save the refined mesh and the solution. This output can be viewed
   //     later using GLVis: "glvis -m refined.mesh -g sol.gf".
   {
      ofstream mesh_ofs("refined.mesh");
      mesh_ofs.precision(8);
      mesh->Print(mesh_ofs);
      ofstream sol_ofs("sol.gf");
      sol_ofs.precision(8);
      x.Save(sol_ofs);
   }

   // 14. Send the solution by socket to a GLVis server.
   if (visualization)
   {
      char vishost[] = "localhost";
      int  visport   = 19916;
      socketstream sol_sock(vishost, visport);
      sol_sock.precision(8);
      sol_sock << "solution\n" << *mesh << x << flush;
   }

   // 15. Free the used memory.
   delete a;
   delete sigma;
   delete muinv;
   delete b;
   delete fespace;
   delete fec;
   delete mesh;

   return 0;
}


void E_exact(const Vector &x, Vector &E)
{
   if (dim == 3)
   {
      E(0) = sin(kappa * x(1));
      E(1) = sin(kappa * x(2));
      E(2) = sin(kappa * x(0));
   }
   else
   {
      E(0) = sin(kappa * x(1));
      E(1) = sin(kappa * x(0));
      if (x.Size() == 3) { E(2) = 0.0; }
   }
}

void f_exact(const Vector &x, Vector &f)
{
   if (dim == 3)
   {
      f(0) = (1. + kappa * kappa) * sin(kappa * x(1));
      f(1) = (1. + kappa * kappa) * sin(kappa * x(2));
      f(2) = (1. + kappa * kappa) * sin(kappa * x(0));
   }
   else
   {
      f(0) = (1. + kappa * kappa) * sin(kappa * x(1));
      f(1) = (1. + kappa * kappa) * sin(kappa * x(0));
      if (x.Size() == 3) { f(2) = 0.0; }
   }
}
```

**Comment by S-Villar** [comment]
Hello @tzanio,

Thanks a lot for you answer. As you say using `H1` elements  can give rise to spurious solutions. Just to clarify for my simulation I am using ND elements for inplane due to this issue. However, for the sake of making an exercise, I wanted to compare solutions using both element types.  I had already adjusted the integrators as you suggested. The above-shared code is just an example to clarify my question of how I would use the H1 elements (note that the line with adding the curlcurl operator for `H1` elements, `VectorCurlCurlIntegrator` was commented). I explain which lines are modified specifically (not so many), which are:

1. Defining the finite element collection and space.
2. Specifying the operator for the source term appropriate for the use of `H1`(`VectorDomainLFIntegrator`)
3. Specifying the operator for the matrix bilinear integrators using `H1` (the ones @tzanio just specified).

This code gives an error in the matrix assembly if I use `H1` but no error if I use `ND`.  I was wondering if I am missing any further modifications to adapt example 3 to nodal elements or I had some syntax error.

Regarding the use of `H1` the out-of-plane being classical, do you know any source where I could find this approach? I don't know if adding the dielectric tensor and planar propagation to the out of plane coordinate (thus coupling the out-of-plane component with inplane components) would result in spurious solutions. I apologize in advance about this last question since I know its not directly related to the MFEM, but any hint (or source) in this path would help me considerably.

Thanks in advance,
Alvaro

**Comment by agrayver** [comment]
@S-Villar depending on your particular task, you may want to consider using potential formulation in form of vector laplace + explicit gauge. In this case, H1 space is legitimate. Efficiency of this depends a bit on your material properties. For constant coefficients it should work quite well.
