### ISSUE TITLE
DG with Gauss Lobatto points

### ISSUE THREAD

**Issue by vikramsg** [mfem/mfem#477]
I was trying to do DG with Gauss Lobatto points, but I noticed that the mass matrix is not diagonal.

So I looked into the code and it seems that the L2_Element always defaults to the Gauss Legendre even though we select the Gauss Lobatto. For example CalcShape calls only OpenPoints. 

```
const double *op = poly1d.OpenPoints(p, btype);
```

Is there a way for the code to not do this, so that it uses the same points for integration and computation.

**Comment by v-dobrev** [comment]
The Gauss-Lobatto points can be used as both 'open' and 'closed', so that is not an issue.

To get a diagonal mass matrix with this basis you will need to explicitly set the `IntegrationRule` used by the `MassIntegrator` using the inherited method `SetIntRule`. The simplest way to get the Gauss-Lobatto `IntegrationRule` is to create an object of type `IntegrationRules`:
```c++
   IntegrationRules GLIntRules(0, Quadrature1D::GaussLobatto);
```
and then query this container object for the specific order you want, e.g.
```c++
   MassIntegrator *mass_integ = new MassIntegrator;
   mass_integ->SetIntRule(&GLIntRules.Get(Geometry::SQUARE, 2*np-3));
   // ...
```
if you want a tensor product rule with `np x np` points. Note that this will only work for tensor-product elements: `Geometry::{SEGMENT,SQUARE,CUBE}`.

**Comment by vikramsg** [comment]
Thanks. 

Another question, although I am not using it right now, but just so I know, what happens when we use non tensor-product elements. Do they use a completely independent set of quadrature?

**Comment by YohannDudouit** [comment]
With a tensor-product element, we only use 1d Integration rules, to compute and apply the operator (this saves memory and computation). 2d and 3d integration rules, for tensorial elements are build by tensorizing the 1d rules. But for non-tensorial elements, by definition, you don't have a natural way to tensorize integration rules, thus the integration rules are directly defined in 2d or 3d.
So, non-tensorial elements don't use different integration rules per se; it's more tensorial elements that exploit the fact that those integration rules can be written as a tensorial product of 1d integration rules.
