### ISSUE TITLE
RBM in HypreBoomerAMG::SetElasticityOptions

### ISSUE THREAD

**Issue by liruipeng** [mfem/mfem#483]
Dear MFEM team,

I am using ex2p to study linear elasticity problems. In RecomputeRBMs(), I found that the number of RBMs is 1 for 2D and 3 for 3D, which are different from older versions of MFEMS (where the numbers were 3 and 6). Can you please explain the changes? I am assuming that you removed the translation vectors. 

Thanks

-Ruipeng

**Comment by tzanio** [comment]
Hi Ruipeng,

Do you remember which version of MFEM had 6 RBMs in 3D?

I tried to look, but unless I'm mistaken that code hasn't changed since the elasticity solver was [originally added](https://mybitbucket.llnl.gov/projects/MFEM/repos/mfem/commits/f6bda0ef125d4e30ebb025a42f4ca7d8a6c92584#linalg/hypre.cpp) [LLNL-only link].

At any rate for that solver only the rotational RBMs are needed (since block-diagonal interpolation has the translations in its range), so the current code is correct for `HypreBoomerAMG::SetElasticityOptions`.

If you need to extend it, how about adding an optional parameter to `HypreBoomerAMG::RecomputeRBMs` which by default returns only rotations but when set can include also the translations (you'll need to add 3 more `static void func_*(const Vector &x, Vector &y)` functions for those).

Hope this helps,
Tzanio

**Comment by tzanio** [comment]
Hi Ruipeng, just following up -- you mentioned that there may be additional issues with the RBMs?

**Comment by liruipeng** [comment]
Hi, Tzanio,

Sorry for replying late. I added the translation RBM vectors as suggested. I was wrong last time about these vectors. There are no problems.

FYI, I looked at my copy of older version mfem and I found in mfem-3.0.1, we had all the rbm vectors.

Thanks a lot!

-Ruipeng

**Comment by tzanio** [comment]
Great, thank @liruipeng.
