### ISSUE TITLE
Nonlinear elasticity of a cantilever beam subjected to surface force or nodal force

### ISSUE THREAD

**Issue by JianhuaQin** [mfem/mfem#526]
Hello everyone,
Prior to the problem, I would like to thank MFEM team for providing us such a well-written code system.
I am trying to use MFEM to solve large deformations of a cantilever beam. The code is based on ex10: Nonlinear Elasticity. Given external force on the nodal points except from the dirichlet boundary, I tried to use the existing code in MFEM to form a vector B representing the right-hand-side of the FEM system (from ex. 2). I did as follows:
```c++
   VectorArrayCoefficient ff(dim);
   for (int i = 0; i < dim-1; i++)
   {
      ff.Set(i, new ConstantCoefficient(0.0));
   }
   {
      Vector pull_force(mesh->bdr_attributes.Max());
      pull_force = -0.0;
      pull_force(1) = -0.5e-4;
      pull_force(2) = -0.5e-4;
      ff.Set(dim-1, new PWConstCoefficient(pull_force));
   }

   LinearForm *bb = new LinearForm(&fespace);
   bb->AddBoundaryIntegrator(new VectorBoundaryLFIntegrator(ff));
   bb->Assemble();
   Vector BB;
   BB.NewDataAndSize(bb->GetData(), bb->Size());

```

Besides, I take s = 0 in the function
```
void InitialVelocity(const Vector &x, Vector &v)
{
   const int dim = x.Size();
   const double s = 0.0;//0.1/64.;

   v = 0.0;
   v(dim-1) = s*x(0)*x(0)*(8.0-x(0));
   v(0) = -s*x(0)*x(0);
}

```
In fact, the solution did not converge after 10 newton iterations(even 30 iteration).

To see what's wrong, I comment 
`//MFEM_VERIFY(newton_solver.GetConverged(), "Newton solver did not converge.");`

Finally, the results show that there is sth wrong in the element adjacent to the dirichlet boundary.
![qq 20180704131014](https://user-images.githubusercontent.com/34500412/42257994-0ae720c0-7f8c-11e8-84ba-025ea99c949f.png)

Since I am new to FEM, I must have some incorrect understaning to FEM. I hope someone can help me solve this problem.

Yours sincerely,
Jianhua

**Comment by v-dobrev** [comment]
Hi Jianhua,

One small correction to your code above: `pull_force(1)` is the force applied to volume attribute 2, and similarly, to set the force for attribute 1, you should set `pull_force(0)`. This shift by one is because MFEM expects the attributes to be >= 1 and the corresponding vector indices start with 0.

Another issue is with the rhs vector `BB` - since the problem has essential boundary conditions, the assembled vector `bb` has to be modified accordingly. So instead of simply setting `BB.NewDataAndSize(...)`, you should call
```c++
   GridFunction x(&fespace); // temporary
   x = 0.0; // Values for the essential b.c.
   Vector X; // temporary
   M.FormLinearSystem(ess_tdof_list, x, *bb, tmp, X, x, BB);
```
in addition to (or instead of)
```c++
   M.FormSystemMatrix(ess_tdof_list, tmp);
```
in the constructor of `HyperelasticOperator`. Note that `BB` should be stored inside the class, so it can be used later in the methods `Mult` and `ImplicitSolve`, e.g. in `Mult` (which is used for explicit time stepping only) you need to add
```c++
   z += BB;
```
before the call
```c++
   M_solver.Mult(z, dv_dt);
```

**Comment by JianhuaQin** [comment]
Dear Dr. Dobrev,
@v-dobrev
Thank you for your suggestion! 
Problem solved, now it wokrs perfectly!
Besides, thank you for reminding me about the pull_force vector.
Actually, I would like to give surface force on boundary attributes 2 and 3, which leads to pull_force(1) and pull_force(2) in the code.
Now I will  try force of gravity, then pull_force(2) should disappear.
Thank you again for helpling me with this issue.
Happy Independence Day!

Best wishes,
Jianhua
