### ISSUE TITLE
Is it not possible to refine hybrid meshes of quad & tri elements

### ISSUE THREAD

**Issue by cuneytsert** [mfem/mfem#531]
I guess it is possible to work with meshes of hybrid quad & tri elements. But I'm getting errors when I try to refine those meshes, even for uniform refinement. Is this not possible?

**Comment by v-dobrev** [comment]
Currently, hybrid/mixed meshes are not supported properly in MFEM, so I'm surprised that you were able to use a mesh like that. That said, uniform refinement for mixed meshes in 2D should not be too hard to implement - I'll take a look at that over the weekend.

**Comment by tzanio** [comment]
I think @tmmcmanus  cleaned-up the mixed mesh code (at least in 2D) so such meshes can be read and (at least some) bilinear forms can be assembled on them, see https://github.com/mfem/mfem/tree/mixed-elements-dev.

@mlstowell is also working on this in https://github.com/mfem/mfem/tree/prism-dev, but I'm not sure if the refinement has been addressed yet.

**Comment by cuneytsert** [comment]
I've not done a solution with mixed meshes. But I was able to read and display such a mesh in 2D, which made me think that they are supported. Than I tried to refine such meshes but it did not work. I'm trying to understand what exactly is supported in terms of hybrid/mixed meshes, hp non-conformity, AMR, etc., and ideally all these together.

**Comment by tzanio** [comment]
@cuneytsert: here is a summary:
- hybrid/mixed meshes -- not supported currently (reading+assembly should work), working to support them fully soon
- hp non-conformity -- not supported currently, we will have support for p-adaptivity for DG soon, but full suport for H1, H(curl), etc. spaces is not planned for the near future
- AMR -- fully supported, both conforming and non-conforming, local, parallel, etc.

**Comment by sbugenha** [comment]
Hi @tzanio and @v-dobrev 

I was wondering if there has been any added support for hybrid/mixed meshes in any of the newer versions of MFEM. I have written an incompressible Navier Stokes fluids solver in MFEM which I would like to run on hexahedral meshes of arbitrary geometries that incorporate boundary layer elements. Most of the open-source meshing software I use (namely cfMesh and snappyHexMesh) create hexahedron predominant meshes that incorporate polyhedrons near the surface boundaries rather than purely hexahedral meshes.  When I try to use my solver with these meshes, I get the following error:

"BilinearForm::ComputeElementMatrices: all elements must have same number of dofs"

If not yet available, is there any plan for future support for meshes of this type and any expected timeline for when this may become available?

Thanks,
Scott

**Comment by tzanio** [comment]
Hi Scott,

By polyhedrons do you mean tetrahedrons, (3-sided) prisms and (4-sided) pyramids?

If so, we are close to supporting AMR on such meshes (cc: @mlstowell, @acfisher).

If you mesh generator produces general polyhedrons, the classical finite element method is not applicable. You should either split them into the 4 standard shapes, or use something like [virtual finite elements](https://mfem.org/pdf/workshop24/14_Leng_HOPF-VEM.pdf).

Hope this helps,
Tzanio

**Comment by sbugenha** [comment]
Hi @tzanio and @mlstowell, @acfisher 

Yes, this is very helpful. I examined the element types a little closer, and it looks like the meshes are composed of a majority of hexahedrons in the center, and a mix of tetrahedrons, prisms/wedges (triangle bases, 5 faces total), and pyramids (square bases, 5 faces total) near boundaries and areas of more complex geometry.  It doesn't look like there are any more general polyhedrons in the mesh. 

That would be fantastic if there is AMR support for this type of mixed mesh in the near future. Is a mesh composed of a mix of these 4 element types currently supported for standard fixed cell (non-AMR) use?

Thanks,
Scott

**Comment by sbugenha** [comment]
Hi All,

Congratulations on release of MFEM 4.8! I've just installed the latest release and am excited to try out the new features.

One thing I thought I'd try out first is to test my code on a mixed mesh composed of a mix of hexahedrons, tetrahedrons, and pyramids. However, I'm still running into this error on the latest release of MFEM when I try to execute my code on a mixed mesh:

"BilinearForm::ComputeElementMatrices: all elements must have same number of dofs"

Is this expected behavior, and is there a workaround to this for mixed meshes?

Thanks,
Scott

**Comment by tzanio** [comment]
ping: @mlstowell

**Comment by v-dobrev** [comment]
@sbugenha, are you calling `BilinearForm::ComputeElementMatrices` directly from your code? If so, you can probably just comment out that call -- it is not strictly necessary.

**Comment by sbugenha** [comment]
@v-dobrev, thanks for the tip. Yes, I was calling BilinearForm::ComputeElementMatrices in the constructor for a custom NLF integrator that also uses some element matrices from BilinearForm operators. I got rid of that line of code and instead looped through the elements and saved the element matrices into arrays in the constructor. The code works now - thanks for your help!
