### ISSUE TITLE
Element transformations after adaptive mesh refinement

### ISSUE THREAD

**Issue by kswartz14** [mfem/mfem#546]
I added the following code to the bottom of `ex6.cpp`:

```c++
for (int i=0; i<fespace.GetNE(); i++)      
{
        ElementTransformation *eltrans = fespace.GetElementTransformation(i);
        DenseMatrix Jac = eltrans->Jacobian();
        std::cout << "Element = " << i << std::endl;
        std::cout << "Det Jac = " << Jac.Det() << std::endl;
}
```

and I noticed that even after refinement the determinant of each element’s Jacobian was the same, despite the element size varying due to refinement of certain elements. I attached the code output. 

Is this behavior expected?

**Comment by kswartz14** [comment]
[ex6_out.txt](https://github.com/mfem/mfem/files/2215462/ex6_out.txt)

**Comment by v-dobrev** [comment]
You need to set the particular quadrature point where you want to compute the `Jacobian` (or `Weight`, `InverseJacobian`, etc) using the method `SetIntPoint`. This is needed because the Jacobian is evaluated and stored in the `ElementTransformation` object - the only way to force re-computation is to call `SetIntPoint`. For exampe, inside the `i` loop, you can use:
```c++
   ElementTransformation *eltrans = fespace.GetElementTransformation(i);
   int geom = mesh.GetElementBaseGeometry(i);
   eltrans->SetIntPoint(&Geometries.GetCenter(geom));
   const DenseMatrix &Jac = eltrans->Jacobian();
   // ...
```
