### ISSUE TITLE
Nedelec bases on prisms and tetrahedra

### ISSUE THREAD

**Issue by mlstowell** [mfem/mfem#549]
Hello,
I need to have a discussion about high order Nedelec bases on prisms and tetrahedra.  Mainly so that I'm sure I have a reasonable understanding of the requirements before I make another attempt at implementing ND and RT bases for prisms.

The ND basis functions associated with edges have a clearly defined orientation which is directed along the edge.  Interior basis functions can be defined however we choose.  Basis functions on quadrilateral faces can also borrow their orientation from the bounding edges.  However, the basis functions associated with triangular faces must align with two of the three bounding edges and its important that neighboring elements choose the same pair of edges.

The tetrahedral implementation in MFEM reorders the vertices of each tetrahedron so that the two lowest vertex indices are first.  The ND basis functions on triangular faces are then defined so that they align with the two edges which meet at the vertex with the lowest index on each face.  This effectively determines the basis function orientations for every face in a tetrahedral mesh.  Moreover, face 0 of every tetrahedron in the mesh will choose the same pair of local edges to define its basis functions, and likewise for faces 1, 2, and 3.

I don't believe there's a way to define prisms so that they posses this same convenient behavior.  If we choose the basis functions on the base of the prism in a certain way there are still three possible choices for the orientation of the basis functions on the top of the prism.  In effect this produces three types of prisms in a general mesh.

This is unlike what we see for tetrahedra or hexahedra in MFEM.  At the very least I expect I'll need to introduce more flexibility into how we handle DOF permutations when working with prisms.  What I don't know is just how well I can contain these changes.  Any thoughts on potential solutions or pitfalls would be appreciated.

Thanks!
Mark

**Comment by Dan2997925** [comment]
I'm not sure I understand the issue. But what comes to mind is the following: Imagine a triangle, maybe share by two tetrehedrons, maybe shared by two prisms, maybe shared by one tetrahedron and one prism. It seems to me that the ND and RT basis functions on the triangle face should be solely determined by the vertices (global node indices) of the triangle face, independent of what type of elements the face is connected too. This means that the two triangular faces of a prism may have basis functions that are in different directions, but not sure why this is a problem.

Anyway if I completely misunderstood the problem, I'm going to need some pictures

**Comment by mlstowell** [comment]
You are correct @Dan2997925.  The problem arises in the implementation.  MFEM, like FEMSTER, defines vectors in the reference element for the basis functions to follow.  MFEM stores them "tk" arrays, FEMSTER called them "interpolationVects" but the idea is the same.  There is a one-to-one mapping between these tk vectors and local degrees of freedom.  This mapping is defined the same way for every Tetrahedron (or Hexahedron or Prism) in the mesh.  By convention we sort the vertices of each tetrahedron so that they choose the same two tk vectors on shared faces.  Neighboring elements might choose tk vectors in different order but they will be the same vectors e.g. tet1 may use tk[1] and tk[2] while tet2 may use tk[2] and tk[1] but we can be sure that tet2 will not choose tk[1] and tk[3].

For prisms we cannot ensure that the top and bottom of the prism will both choose the same pair of tk vectors.  In FEMSTER we did make this assumption but I think this was a mistake.   Our prism meshes were typically extruded from 2D meshes so perhaps we never saw a problem.

One solution I can think of is to define different mappings relating the dofs to tk vectors, one for each of the three choices of the upper pair of tk vectors relative to the lower pair.  Each prism element would then need to select one of these mappings.  This would effectively create three different sets of behavior for Nedelec prisms.  I think this could work from the basis function's point of view.  I suspect it would work from the FiniteElementSpace's point of view i.e. for matching dofs from neighboring prisms or tetrahedra.  I'm not so sure that it would work with mesh refinement.  Specifically, I'm concerned about constructing the operators which map grid functions from coarse to fine meshes.

The overarching question here is if I define prism basis functions so that different instantiations of the prism element may behave differently what could break?

**Comment by v-dobrev** [comment]
I think we should approach this issue in a more general way - the problem stems from the fact that the mapping of the global dofs to element local dofs is not a simple permutation with an optional sign flip. This is what we are assuming now by relying on methods like `FiniteElementSpace::GetElementDofs` to represent the global-to-local dof mapping.

So far this issue has appeared in the case of high-order Nedelec elements on tet meshes. The issue here is that the set of dofs associated with the interior of a triangle face has to be transformed (when mapping dofs from one side of the face to the other) by a change of basis matrix which is not a simple permutation with optional sign flip. We "fixed" the issue by enforcing special reorientation of the tets (using `Mesh::ReorientTetMesh()`), so that only simple transition matrices are required. However, this leads to the limitation that we can no longer refine the mesh (locally or globally).

The same problem now arises with prisms/wedges and now we cannot resolve the issue by simply reorienting the prisms.

Similar issue will arise when we consider H1 spaces with orders varying from element to element.

There are two approaches that I can see for resolving this issue in a general way:
1. Generalize all methods like `FiniteElementSpace::GetElementDofs()` to (optionally) return the global-to-local mapping as a small local matrix (square or rectangular) which has to be applied to the dofs after extracting a subvector of the global dof vector.
2. Split faces that require general transform of the dofs between the two adjacent sides into two independent sets of dofs (just the dofs interior to the face) and then enforce the continuity through the conforming prolongation operators - `FiniteElementSpace::cP` in serial, and `ParFiniteElementSpace::P` in parallel. In the case of H1 variable order spaces, the edges will need to be split too.

The second approach may be more straightforward to incorporate in the code, while the first one seems a bit more natural to me.

What do you guys think?

**Comment by mlstowell** [comment]
I had not considered variable order but you make an excellent point and we should try to prepare for that issue as well, if we can.

I think I see how we could solve the tet and prism issue with approach 1.  It's not so obvious to me how this would solve the variable order issue.  Wouldn't such a GetElementDofs method need to know the orders of the neighboring elements so that it could create an appropriate rectangular mapping operator?

**Comment by v-dobrev** [comment]
Yes, `GetElementDofs()` will have access to that information -- it is a method in the `FiniteElementSpace` where the element orders will be stored.

**Comment by tzanio** [comment]
This issue was discussed internally and will be implemented soon.
