### ISSUE TITLE
Use of angle brackets around file names for include statements

### ISSUE THREAD

**Issue by elfring** [mfem/mfem#559]
Would you like to [replace any double quotes](https://github.com/mfem/mfem/blob/27ffe35369dbe4bad60be9c896bdf3df3053b6ae/mfem.hpp#L17 "Check inclusion style") by [angle brackets around file names for include statements](https://stackoverflow.com/questions/21593/what-is-the-difference-between-include-filename-and-include-filename "What is the difference between #include <filename> and #include “filename”?")?

**Comment by jakubcerveny** [comment]
@elfring, what would be the motivation to do that? Do you mean in the whole project? Double quotes are correct IMO. Even in mfem.hpp, everything is simply relative to that file, no need to use the "system" brackets.

**Comment by elfring** [comment]
I suggest to reconsider the consequences of [the following wording](http://c0x.coding-guidelines.com/6.10.2.html "Source file inclusion") from [the section “16.2 Source file inclusion”](http://open-std.org/jtc1/sc22/wg21/docs/papers/2013/n3797.pdf "Draft for the C++ standard specification") in the standard specification for the programming language “C++”.

```
…
The named source file is searched for in an implementation-defined manner. If this search is not supported, or if the search fails, the directive is reprocessed as if it read

#include <h-char-sequence> new-line
…
```
- How do you think about to avoid “a duplicated file search” here?
- Would you like to [restrict the searched directories](https://gcc.gnu.org/onlinedocs/cpp/Include-Syntax.html "Description for include syntax") for header files of your software?

**Comment by jakubcerveny** [comment]
I don't think we want this (correct me if I'm wrong @tzanio and @v-dobrev). It's pretty standard you put your own headers in double quotes and system stuff in angle brackets. More importantly, having angle brackets everywhere would break dependency generation by `gcc -MM` and CMake.

**Comment by elfring** [comment]
There are different opinions about the handling of the involved implementation-defined behaviour.
- Will header files be also searched outside the specified include directories if double quotes are used for the discussed preprocessor statement?
- Is there a speed difference measurable if a file is not found there and the search will be retried with “the angle brackets inclusion method”?

**Comment by mlstowell** [comment]
Hi, @elfring,
I'm afraid I completely agree with @jakubcerveny on this topic.  The duplicated file search that you refer to is only what happens when the quoted file is not found where it was supposed to be.  If this is failing then we have put the wrong text in quotes or someone has installed our headers without the proper directory structure.

On the other hand if we use angle brackets the preprocessor has to search all of the system directories and all directories declared with "-I' arguments.  I would argue that this is a much more costly search, through an arbitrarily long list of directories, than that produced by using quotes (assuming the quoted text is correct).

Look at it this way: the quoted include directive should be used whenever you can supply additional information to the preprocessor so that it can avoid these searches entirely.  I believe this is the way we use quoted includes in MFEM.

Best wishes,
Mark

**Comment by elfring** [comment]
I suggest to take another look at the situation for an application programmer.
The required header files will be installed in a known directory.
* Do you expect then that the desired header files are usually not found in the source directory which is used by the programmer?
* Should headers be directly retrieved from a trusted include directory (without a lookup attempt from an other storage location)?

**Comment by stefanozampini** [comment]
The use of angle brackets is totally wrong for including your own headers
when compiling library code, since you know exactly the relative location
of the headers you need to include

Il Ven 27 Lug 2018, 13:26 Mark L. Stowell <notifications@github.com> ha
scritto:

**Comment by elfring** [comment]
>If, on the other hand, "mfem.h" had used the angle bracket, then the preprocessor would search for these included files in all of the locations specified on the command line with "-I" options.

It seems that you refer to a specific implementation-defined behaviour from a compiler version here.
Does the angle brackets inclusion method perform really more work than the other approach?

**Comment by elfring** [comment]
>The use of angle brackets is totally wrong for including your own headers when compiling library code,

It seems that you refer to the development situation for a software library maintainer.


>since you know exactly the relative location of the headers you need to include

It might look convenient to use double quotes there. But should software build configurations achieve desired effects in a safe way?
* Development
* Debug
* Test
* System integration
* Production release

**Comment by mlstowell** [comment]
The behavior I describe is outlined in section 6.10.2 of the C++ standard from April 12, 2011, ISO/IEC 9899:201x.

**Comment by jakubcerveny** [comment]
Using angle brackets inside the library would break things (see my second comment). In addition, it would be a security issue because incorrect headers could get included from unexpected locations. Double quotes are not a convenience, it's the correct thing to do inside the library where one knows the directory structure. Applications should  `#include <mfem.hpp>` but that's all. I suggest we close this issue.

**Comment by elfring** [comment]
>Using angle brackets inside the library would break things

How does such information fit to usage (and design) patterns from other well-known software libraries like “[Boost](https://www.boost.org/ "Portable C++ source libraries")”?

**Comment by mlstowell** [comment]
"Boost" is a header only library which is a very different thing from MFEM.  For one thing dependency generation is irrelevant for Boost because it's not a compiled library.

Do you have a specific reason why you think the include directives in MFEM should be changed?  Does this create some problem for your application?  We would be happy to offer advice to help resolve any issues you might be having.

**Comment by jakubcerveny** [comment]
I think this is some kind of spam:
https://github.com/OSGeo/gdal/issues/803
https://github.com/json-c/json-c/issues/440
...and many more
