### ISSUE TITLE
Memory deallocation for Mesh with Tetrahedrons

### ISSUE THREAD

**Issue by kvoronin** [mfem/mfem#574]
Hello,

I've noticed the construction with TetMemory used in deallocating elements of the Mesh which consists of Tetrahedrons, and I have a memory leak in my code around it.

What I am doing is: I create a new mesh with say 2000 elements, and then add them one by one using Element * el = new Tetrahedron(...) and AddElement(el). And valgrind then reports to me a memory leak, like all the element data was not freed in the end, after calling the destructor of Mesh object.

Is there anything special about Tetrahedron case? I noticed an if clause about it in Mesh::FreeElement(), does it require something special to be done during mesh construction which I missed?

Thanks,
Kirill

**Comment by v-dobrev** [comment]
The default memory management for `Tetrahedron` elements inside a `Mesh` object does not use `new` and `delete` - we use a custom allocator. Therefore, when adding elements to a `Mesh`, you should use either
* `Mesh::NewElement` and then `Mesh::AddElement`, or
* one of the `Mesh` methods: `AddTri`, `AddTriangle`, `AddQuad`, etc.

Since you still see a memory leak when using `AddTet`, there is still some memory issue that needs to be resolved. Can you run valgrind using the options `--leak-check=full --show-reachable=yes --track-origins=yes` and post the relevant output here?

**Comment by kvoronin** [comment]
Thanks for the response @tzanio,
It did help me to get a clearer picture. I fixed the issue by using AddTet() (previous message by me in this thread was wrong because I introduced another bug while replacing AddElement by AddTet()).
So, I've got the clean valgrind run.
