### ISSUE TITLE
How to impose external forces on boundary vertices in ex2?

### ISSUE THREAD

**Issue by JianhuaQin** [mfem/mfem#576]
Hello everyone,

In ex2, the external forces are constant over the boundary, the code is
```c++
   VectorArrayCoefficient f(dim);
   for (int i = 0; i < dim-1; i++)
   {
      f.Set(i, new ConstantCoefficient(0.0));
   }
   {
      Vector pull_force(mesh->bdr_attributes.Max());
      pull_force = 0.0;
      pull_force(1) = -1.0e-2;
      f.Set(dim-1, new PWConstCoefficient(pull_force));
   }

   LinearForm *b = new LinearForm(fespace);
   b->AddBoundaryIntegrator(new VectorBoundaryLFIntegrator(f));
   cout << "r.h.s. ... " << flush;
   b->Assemble();
```

However, in my case, the external forces vary in each boundary vertex.
Before posting this issue, I tried to solve this by myself. 
By using different bdr_attributes in each boundary segement and assumng that the force on each boundary segement is half of the forces on each boundary segement. 
The results are not ideal. I think this is because the forces on each boundary segement are not continuous, I can't take a combination of the half of forces in the two vertices as the average forces in the boudary segement.

Hopefully, someone would give me some advice on this issue! Thanks in advance!

Sincerely,
Jianhua

**Comment by jandrej** [comment]
Is your desired boundary value a continuous function f(x,y)?

**Comment by JianhuaQin** [comment]
Hi @jandrej,

The boundary forces are obtained from a fluid solver. Generally, they are discontinuous.

**Comment by jandrej** [comment]
Do you get the solution of the fluid solver on the same mesh? If yes, does the solution vector contain values at the nodes of the mesh? If you could get geometry information from the solver, for example a map which tells you `fluid_solver_solution(x, y) -> R^n`, then you could use a `FunctionCoefficient` or `VectorFunctionCoefficient` and implement a callback function that handles this mapping.

**Comment by JianhuaQin** [comment]
@jandrej 
Thank you for your advice!

The fluid solver and MFEM share the same boundary vertices/nodes. Therefore, it is possible to use `force(x, y) -> R`. By doing so, we can construct a coefficient that contains only the vertex number and solution verctor of the force. 
For example, (0, 1.0e-2, 1.0e-2), (1, 2.0e-2, 1.0e-2), (2, 1.0e-3, 1.0e-3)...

What I want to know is how to construct `LinearForm *b`.
In MFEM, I can only find `b->AddBoundaryIntegrator` and `b->AddDomainIntegrator`.
However, neither of them can be used for nodal forces.

**Comment by vikramsg** [comment]
If I had to do it, I would make a ```GridFunction``` which would take on the values you get from the fluid solver and then send it to ```b->AddBoundaryIntegrator(new VectorBoundaryLFIntegrator)```.

**Comment by JianhuaQin** [comment]
@vikramsg 
It seems to be a solution. But I don't know how to make the `GirdFunction`. The fluid solver is based on Lattice Boltzmann Method (LBM) and Immersed Boundary Method (IBM). Therefore, the forces are only on nodal points.

**Comment by mlstowell** [comment]
Hello, @JianhuaQin ,

I also like @vikramsg 's solution but unfortunately there is an outstanding issue (#565 ) in MFEM which will cause this to fail.

I see two ways to work around this issue but both of them require that you create a GridFunction on the MFEM mesh which approximates your force vector field from the LBM solver.  Once you have this GridFunction you can compute the needed LinearForm by performing a matrix-vector multiplication.  The matrix you'll need is a mass matrix computed on the boundary of the mesh:
BilinearForm m(fespace);
m.AddBoundaryIntegrator(new MassIntegrator);
//or
m.AddBoundaryIntegrator(new MassIntegrator, bdr_marker);
m.Assemble();

If you choose to use different bases for the LBM solver and the elasticity solver you can use a rectangular operator in the above by using a MixedBilinearForm with the same MassIntegrator instead.

Presumably you have a mapping from your LBM vertices to your MFEM boundary vertices.  If not then hopefully you can build it by looping through the MFEM mesh and using GetVertex and comparing these coordinates with your LBM boundary coordinates.  Clearly this could be expensive so you should do it once and store the result if possible.

Once you have this mapping you can rely on the fact that the order of the GridFunction degrees of freedom for a first order H1 basis in serial is only determined by the vertex number and the dimension of the space.  Specifically, the dof index is "dim*node+d" where 'd' is 0, 1, or 2 corresponding to the 'x', 'y', or 'z' component of the field.

The other option is to write a Coefficient object for each component of the force and incorporate the above mapping into these coefficients so that you can look up force values given nodal coordinates.  You can then call GridFunction::ProjectBdrCoefficient(Coefficient*coeff[], Array<int> &attr).  This method will look cleaner and it has the potential to work in parallel but it would probably be less efficient.

I'd be happy to give more details if any of this is unclear.

Best wishes,
Mark

**Comment by JianhuaQin** [comment]
Hi @mlstowell ,

Thank you so much for the discussion! Your suggestions help me a lot!

By using a first order H1 basis, I constructed a GridFunction `force` by
```
   ifstream ifilef("../../Turek/force.data");
   GridFunction force(mesh, ifilef);
   ifilef.close();
```
This gridfunciton contains values of the whole domain, not only boundary values.
Then I can easily construct the linear form by
```
   LinearForm *bb = new LinearForm(&fespace);
   VectorGridFunctionCoefficient forcec(&force);
   bb->AddDomainIntegrator(new VectorDomainLFIntegrator(forcec));
   bb->Assemble();
```
Is anything wrong by doing like this?

Thank you again for your help!

Best regards,
Jianhua

**Comment by mlstowell** [comment]
Hello, @JianhuaQin ,

The first approach you showed will impose a force throughout the entire volume of the mesh.  If the grid function is equal to zero in most of the mesh then this force will also be zero so that may be ok.  You should be warned though that the LinearForm object in this case is performing a volume integral and not a surface integral so, even if the GridFunction is only nonzero on the boundary, the effective force is acting on the outermost layer of elements and not on the surface of those elements.  The difference will depend on the thickness of the outer layer of elements and this could easily lead to bad results.

Regarding the time to write the file `force.data`.  I presume you are mostly writing zeros to this file because, if I understand correctly, the force is only nonzero on the boundary.  You could speed this up by only writing the non-zero values and their coordinates or vertex indices.  You could then read this much smaller file and use a suitable mapping from LBM indices to MFEM indices to place the values in the GridFunction one by one.

The matrix-vector multiplication scheme has some problems as you've written it.  The vectors used in finite element schemes come in two flavors; primal and dual.  This is a subtle distinction and MFEM's class documentation does not help to clarify this distinction so it's easily missed.  MFEM's `GridFunction` class is used to store *primal vectors*.  These store the degrees of freedom that we solve for, they are the expansion coefficients in a finite element representation of a function e.g. they are the `a_i` in `\sum_{i=0}^n a_i \phi_i(x)`.  MFEM's `LinearForm` class is used to store *dual vectors*.  These are linear functionals which store the values of integrals of the basis functions e.g. they are the `b_i` in `b_i = \int_\Omega f(x)\phi_i(x)dx` for some function `f(x)`.  If you wanted to compute the integral of the product of two functions `f(x)` and `g(x)`,  MFEM provides two ways to accomplish this:
1) Project `f(x)` and `g(x)` onto two `Gridfunctions`s called `fPrimal` and `gPrimal`, compute a mass matrix, `M`, using a `BilinearForm`  and compute `fPrimal^T * M * gPrimal`.
2) Project `g(x)` onto a `GridFunction` and build a `LinearForm` called `fDual` with `f(x)` and compute `fDual^T * gPrimal`.
These two methods should produce exactly the same answer as long as the `BilinearForm` and `LinearForm` use the same integration rule.  In other words `fDual = M * fPrimal`.  With this in mind your scheme becomes the following where `*bb` is the dual vector associated with the primal vector stored in `force`.
```
   ifstream ifilef("../../Turek/force.data");
   GridFunction force(mesh, ifilef);
   ifilef.close();
   LinearForm *bb = new LinearForm(&fespace);
   BilinearForm m(&fespace);
   const double ref_density = 1.0*dr; // density in the reference configuration
   ConstantCoefficient rho0(ref_density);
   m.AddBoundaryIntegrator(new MassIntegrator(rho0));
   m.Assemble();
   m.Mult(force, *bb);  //matrix-vector multiplication
```

Best wishes,
Mark

**Comment by JianhuaQin** [comment]
Hello, @mlstowell ,

Thank you so much for the thorough explanation. I will keep learning how to use MFEM! 
Of course the thickness of the element has a significant influence on the results.

Yours sincerely,
Jianhua
