### ISSUE TITLE
Orientation in periodic meshes

### ISSUE THREAD

**Issue by gsosajones** [mfem/mfem#577]
Hello,

I have a question about the orientation of the boundary elements when using periodic meshes. I am trying to create a 3D mesh in [0,1]x[-1,1]x[-1,0] that is periodic only in _y_ and I think that I am having some issues with the orientation of the boundary elements. Do I have to order the boundary so that the normal is always an outward normal? As far as I can see in the periodic-cube.mesh example, the boundary elements do not follow any particular ordering, so I am not sure about what I should be doing.
Also, I see that for the periodic cube mesh the boundary elements are still listed in the file even though this mesh seems to be periodic in every direction. On the other hand, in the periodic square and segment meshes, the boundary elements are not listed since the meshes are periodic in every direction.

Thank you.
Giselle

**Comment by gsosajones** [comment]
Hello,

If it helps, here is the mesh that I am using. I changed the extension to txt because that is the only way I could upload it.

Thank you!
Giselle

[periodic3D.txt](https://github.com/mfem/mfem/files/2290999/periodic3D.txt)

**Comment by v-dobrev** [comment]
When defining a hex element through its vertex indices, the expected ordering is the one on the *left* in the following diagram:
```
      7-----6         6-----7
     /|    /|	     /|    /|
    / |   / |	    / |   / |
   /  |  /  |	   /  |  /  |
  /   3-/---2	  /   2-/---3
 /   / /   /	 /   / /   /
4-----5   /	4-----5   /
|  /  |  /	|  /  |  /
| /   | /	| /   | /
|/    |/	|/    |/
0-----1      	0-----1
```
When defining the coordinates of the hex (using a linear DG collection, "L2_T1_3D_P1") the vertex coordinates should be given in the Cartesian ordering, as shown on the *right* in the above diagram.

It was not obvious to me, just by looking at the file you posted, what ordering you used there. 

Hopefully, the above diagram makes things clearer.

**Comment by tzanio** [comment]
Hi @gsosajones, can you update us on the status of this issue?

**Comment by mlstowell** [comment]
Hi, Giselle,
I took the liberty of modifying the mesh file you uploaded a few weeks ago [periodic3D_MLS.txt](https://github.com/mfem/mfem/files/2420702/periodic3D_MLS.txt).  The vertex orderings contained in your original file did not agree with the orderings described by @v-dobrev but the coordinate orderings did agree.  I made a few small changes to the element to node connectivity and the mesh seemed valid.

To display the surfaces at the ends of the mesh GLVis needs boundary elements defined there.  On periodic surfaces the trick is to include each face twice with opposite orderings.  The ordering determines the vector normal to the face and GLVis uses this normal to determine which end of the box the face belongs to.  If you provide faces with both normals then GLVis will draw faces on each end of the box.

Best wishes,
Mark

**Comment by gsosajones** [comment]
Hi Mark,

Thank you so much for your response. I made some modifications to the mesh I uploaded here and my code seems to be working fine. However, I have been testing my code with the mesh you provided and I get bad results. I am not sure if there is an error on my side or if there is something off about the mesh. Would you mind taking a look at my mesh file to see if this would be a valid mesh too? Note that I am omitting the periodic boundaries since they are only important for visualization.

Thank you for all the help.

Best,
Giselle

[periodic3D_v2.txt](https://github.com/mfem/mfem/files/2428315/periodic3D_v2.txt)

**Comment by mlstowell** [comment]
Hi, Giselle,

It looks as if your periodic3D_v2.txt is using incorrect orientations.  If we use the node arrangement that you provided earlier then the first four vertices of the first element in this mesh are "3 4 16 15".  This describes a face parallel to the xy plane with a normal pointed in the positive z direction.  According to @v-dobrev 's diagrams this face should be the base of a hexahedron with the opposite face above it. Specifically, the opposite face should be "6 7 19 18" but your file shows "0 1 13 12" which is below the first face.

The node coordinates in your file are consistent with the vertex ordering used to define your elements but they also don't agree with @v-dobrev 's diagrams.    In fact your node ordering defines a left-handed coordinate system.  If only one of these orderings was switched then your elements would have negative Jacobians and your results would probably be obviously incorrect.  Since your orderings are internally consistent, although not what MFEM expects, your Jacobians are positive and some results might look reasonable.  However, it's difficult to say what types of problems to expect.

When I run `ex1p` on `periodic3D_MLS.txt` I get a solution with the following cross section:
![periodic3d_mls_ex1p](https://user-images.githubusercontent.com/6109571/46223147-64e95200-c307-11e8-823b-85693107b998.png)
This result is typical of this example which solves `Laplacian(u)=1`.

When I run the same example on `periodic3D_v2.txt` I get this:
![periodic3d_v2_ex1p](https://user-images.githubusercontent.com/6109571/46223240-ada10b00-c307-11e8-8412-4c05147718f3.png)
This solution is negative everywhere but has a very small magnitude (~1e-6).  This is clearly incorrect although it's not clear to me why it looks exactly like this.

I believe you need to alter both your element-to-node connectivity (the "elements" section of the mesh file) and also your node orderings (the "nodes" section).  Changing either one by itself would probably lead to worse results but changing both them together should be the correct path.

By the way, I'm curious about your test code.  The fact that my mesh file lead to bad results suggests that this code may have an error which is somehow consistent with your orderings but not what MFEM expects.  What type of code is this?  What operators does it use?

Best wishes,
Mark

**Comment by mlstowell** [comment]
Hi, @gsosajones,

I'll close this issue for now but feel free to reopen it if you have further concerns.

Best wishes,
Mark
