### ISSUE TITLE
Evaluating surface integrals of a grid function

### ISSUE THREAD

**Issue by izaid** [mfem/mfem#599]
Hello all,

I've been using MFEM for the last couple of weeks, and I've been very impressed by it. Thanks for making it available!

I'm working on an electromagnetic problem, but my question is much more general. Basically, I need to evaluate surface integrals of things like intensity of the electric field, i.e. |E|^2 = E dot E, where E is a 3D vector field that is solved for. This is a post-processing step to get certain quantities of interest. My understanding is that one simple way to do this is define a bilinear form such as

```c++
  Array<int> bdr_marker(1);
  bdr_marker[0] = 1;

  BilinearForm *bi = new BilinearForm(m_ptr->fes);
  bi->AddBoundaryIntegrator(new VectorFEMassIntegrator(), bdr_marker);
  bi->Assemble();
```

and then use that via `bi->InnerProduct(x, x)` on an appropriately-defined grid function x. I tried this, but I couldn't get it working for *boundary integrals*.

As such, I have created a minimal example that replicates my issue. In this example, I'm simply trying to use a `BilinearForm` to compute the volume and surface area of a meshed unit sphere (the mesh file is attached). I'm using scalar functions here, so I simply set the grid function to be 1 and integrate over the entire volume or what I think should be the spherical boundary. The volume comes out fine, the surface area comes out very wrong. Am I missing something here? How can I use a bilinear form to compute a surface integral with a grid function?

```c++
int main(int argc, char *argv[]) {
  Mesh *mesh = new Mesh("sphere.vtk");

  // Set the space for the high-order mesh nodes.
  H1_FECollection fec(2, mesh->Dimension());
  FiniteElementSpace nodal_fes(mesh, &fec, mesh->SpaceDimension());
  mesh->SetNodalFESpace(&nodal_fes);

  FiniteElementSpace *fespace = new FiniteElementSpace(mesh, &fec);

  GridFunction x(fespace);
  x = 1.0;

  BilinearForm *vol = new BilinearForm(fespace);
  vol->AddDomainIntegrator(new MassIntegrator());
  vol->Assemble();

  Array<int> bdr_markers(1);
  bdr_markers[0] = 1;

  BilinearForm *area = new BilinearForm(fespace);
  area->AddBoundaryIntegrator(new MassIntegrator(), bdr_markers);
  area->Assemble();

  cout << "Volume of the meshed unit sphere is " << vol->InnerProduct(x, x) << endl;
  cout << "Should be " << (4 * M_PI / 3) << endl;
  cout << "----" << endl;
  cout << "Area of the meshed unit sphere is " << area->InnerProduct(x, x) << endl;
  cout << "Should be " << (4 * M_PI) << endl;

//  ofstream mesh_ofs("sphere_refined.vtk");
//  mesh->PrintVTK(mesh_ofs);

  return 0;
}
```

[sphere.vtk.zip](https://github.com/mfem/mfem/files/2346467/sphere.vtk.zip)

**Comment by sshiraiwa** [comment]
Hi, 

Just reading this reminded me my question. I was wondering how does MFEM handle 
the surface normal vector direction.

—
Syun'ichi

**Comment by izaid** [comment]
@mlstowell Thanks for the quick and detailed reply!

First, thanks for seeing the errors in that mesh. I'm generating my mesh externally with some other programs, it is just a tetrahedralization of the unit sphere. However, the file I gave you was written with MFEM's own VTK writer. I found that using the signature with the `ref` argument saved the mesh correctly, leading to the correct surface area and volume. (I also found saving it as a `.mesh` file was also fine.)

This brings back to my original question. @mlstowell, did you happen to try my example with different finite element collections, for instance an `ND_FECollection`? I find this does not work. This was actually the original problem I was struggling with today.

I've updated my example program to demonstrate this, and attached a new `.mesh` file. Using this program with this mesh will produce the correct surface area and volume for the `H1_FECollection`, but not for the `ND_FECollection`. Am I missing something here? The code is almost identical.

```
#include "mfem.hpp"
#include <fstream>
#include <iostream>

using namespace std;
using namespace mfem;

void do_h1() {
  Mesh *mesh = new Mesh("sphere.mesh");
  mesh->ReorientTetMesh();

  // Set the space for the high-order mesh nodes.
  FiniteElementCollection *fec = new H1_FECollection(2, mesh->Dimension());
  FiniteElementSpace nodal_fes(mesh, fec, mesh->SpaceDimension());

  FiniteElementSpace *fespace = new FiniteElementSpace(mesh, fec);

  FunctionCoefficient func([](const Vector &x) { return 1.0; });

  GridFunction x(fespace);
  x.ProjectCoefficient(func);

  BilinearForm *vol = new BilinearForm(fespace);
  vol->AddDomainIntegrator(new MassIntegrator());
  vol->Assemble();

  Array<int> bdr_markers(1);
  bdr_markers[0] = 1;

  BilinearForm *area = new BilinearForm(fespace);
  area->AddBoundaryIntegrator(new MassIntegrator(), bdr_markers);
  area->Assemble();

  cout << "Volume of the meshed unit sphere is " << vol->InnerProduct(x, x) << endl;
  cout << "Should be " << (4 * M_PI / 3) << endl;
  cout << "----" << endl;
  cout << "Area of the meshed unit sphere is " << area->InnerProduct(x, x) << endl;
  cout << "Should be " << (4 * M_PI) << endl;

  //  ofstream mesh_ofs("sphere_refined.vtk");
  //  mesh->PrintVTK(mesh_ofs);
}

void do_nd() {
  Mesh *mesh = new Mesh("sphere.mesh");
  mesh->ReorientTetMesh();

  // Set the space for the high-order mesh nodes.
  FiniteElementCollection *fec = new ND_FECollection(2, mesh->Dimension());
  FiniteElementSpace nodal_fes(mesh, fec, mesh->SpaceDimension());

  FiniteElementSpace *fespace = new FiniteElementSpace(mesh, fec);

  VectorFunctionCoefficient func(3, [](const Vector &x, Vector &v) {
    v(0) = 1;
    v(1) = 0;
    v(2) = 0;
  });

  GridFunction x(fespace);
  x.ProjectCoefficient(func);

  BilinearForm *vol = new BilinearForm(fespace);
  vol->AddDomainIntegrator(new VectorFEMassIntegrator());
  vol->Assemble();

  Array<int> bdr_markers(1);
  bdr_markers[0] = 1;

  BilinearForm *area = new BilinearForm(fespace);
  area->AddBoundaryIntegrator(new VectorFEMassIntegrator(), bdr_markers);
  area->Assemble();

  cout << "Volume of the meshed unit sphere is " << vol->InnerProduct(x, x) << endl;
  cout << "Should be " << (4 * M_PI / 3) << endl;
  cout << "----" << endl;
  cout << "Area of the meshed unit sphere is " << area->InnerProduct(x, x) << endl;
  cout << "Should be " << (4 * M_PI) << endl;
}

int main(int argc, char *argv[]) {
  do_h1();
  cout << "-----" << endl;
  do_nd();

  return 0;
}
```

[sphere.mesh.zip](https://github.com/mfem/mfem/files/2346697/sphere.mesh.zip)

**Comment by mlstowell** [comment]
HI, @izaid ,
I'm glad you were able to sort out the issue with the mesh.  The problem with the ND space is perhaps more subtle.  You may think that if your vector field is v=(1,0,0) then v.v would equal 1 so your surface integral would integrate 1 over the surface of the mesh.  This is not the case.  What happens is that the surface integral first restricts the ND basis to the surface then takes the inner product and computes the surface integral.  Restriction to the surface means that the vector field becomes s=nx(vxn).  In this case n=(Cos[\[Phi]] Sin[\[Theta]], Sin[\[Phi]] Sin[\[Theta]], Cos[\[Theta]]) which leads to a more complicated function to be integrated.  The answer turns out to be 8pi/3=8.37758...  Your new code computes 8.20508 which is close.

The ND basis is suitable for computing the tangential part of a vector field at a surface (this is what nx(vxn) gives you).  So, you could accurately compute surface currents, for example.  You could also use ND spaces to accurately compute the normal component of the curl of a vector field at the surface.  Other quantities will be difficult to compute at the surface using this basis.

If you need to compute the normal component of a vector field on a surface it is better to use RT spaces.  For example, you could convert an electric field E (using the ND basis) into D=epsilon E (using the RT basis).  The normal component of D in the RT basis would give you an accurate representation of the surface charge density.  Similar tricks apply to B and H where B is usually expressed using RT bases and H with ND.

I am curious why you need |E|^2 integrated on a surface.  Typically terms quadratic in E are related to energy density which is a volumetric quantity so a surface integral would not be appropriate.  Perhaps this is related to energy deposition in a very thin layer which cannot be resolved by the mesh?  If so, it might make sense to treat the components of E which are tangent to or parallel to this layer differently.

Best wishes,
Mark

**Comment by izaid** [comment]
@mlstowell Thanks for this, I now understand what is going on. Your explanations have been very helpful.

So, I'm working on a scattering problem and I want to compute the cross sections, which are basically power flux. These are defined as surface integrals either in terms of the Poynting vector S = E cross H, where H = curl(E), or in terms of E dot E. I'd be happy computing either of them -- I assumed the E dot E form was easier here, but maybe that's wrong.

I guess my question now is, can I compute either of these integrals in the ND basis easily? Or do I need to use an interpolator? The integrands are:

- E dot E
- S dot n = (E cross H) dot n, where H ~ curl(E)

Thanks again for your help!

**Comment by mlstowell** [comment]
Hi, @izaid ,
Yes, this should be easy as long as your surface is sufficiently far from your scatterer.  The trick is to use the Silver-Muller (a.k.a Sommerfeld) radiation condition which states that the outgoing waves must satisfy lim_{r->infty} [r(Hxn-E)]=0 where n is the unit vector in the radial direction.  This means that E will be tangential to the surface of the sphere and that the tangential part of H is a rotated copy of E.  If you follow through the nasty vector identities you end up with a surface integral of E_perp.E_perp which is, luckily, the most natural surface integral for ND bases.  The code from your original question should work perfectly:
```
  Array<int> bdr_marker(1);
  bdr_marker[0] = 1;

  BilinearForm *bi = new BilinearForm(m_ptr->fes);
  bi->AddBoundaryIntegrator(new VectorFEMassIntegrator(), bdr_marker);
  bi->Assemble();
```

If a sufficiently large spherical surface is impractical then you may need to integrate over a surface inside the sphere.  This is because you cannot accurately estimate the tangential portion of H on the outer boundary unless you know something more about it (like the Silver-Muller condition).  Using an interior surface allows you to approximate H as a ND field from CurlE, which is a RT field, in the least-squares-best-fit sense.  I doubt you want to do this but it should be possible.

Best wishes,
Mark
