### ISSUE TITLE
Better random number generation in HypreLOBPCG and in general

### ISSUE THREAD

**Issue by v-dobrev** [mfem/mfem#610]
The convergence of `HypreLOBPCG` seems to be severely affected by the initial random vectors which are initialized from a single seed value.

It would be great if we can improve on this, maybe by using a more sophisticated random number generator.

**Comment by mlstowell** [comment]
It looks like the randomization occurring on line [3396](https://github.com/mfem/mfem/blob/bbac26bffe986f9f4d0cee480dcdd1924ce699d9/linalg/hypre.cpp#L3396) is poorly chosen.  We should use something like `seed+i` otherwise all of the vectors will be the same.  But I expect that code is rarely called.

Random number generation may not be the best solution for LOBPCG in any case.  These random vectors will have a greatly deal of high frequency randomness but LOBPCG locates low frequency solutions so most of the "energy" in a random vector should be removed by LOBPCG.

When using LOBPCG for electromagnetic applications I've found that initializing these vectors with products of low frequency trigonometric functions tends to work best.  Unfortunately, this requires knowledge of the geometry of the problem domain (dimension, bounding box, etc.).  It might be interesting to try setting the vectors to `v[i]=cos(2*pi*n*i/length)` and/or `v[i]=sin(2*pi*n*i/length)`.  Where each vector is given a different value for `n`.

**Comment by mlstowell** [comment]
Sorry about the `close`.  I hit the wrong button.

**Comment by v-dobrev** [comment]
This is a good point - that we use the same seed on all processors - that definitely contributes to the issue.

My thinking was that if we have a "good random number generator", it will create initial guesses covering the whole spectrum of frequencies. It may not be 100% reliable but still might be a significant improvement over the current status.

I'm certain this is really possible or easy to do - just something to consider.

**Comment by v-dobrev** [comment]
Correction above, I meant: "I'm NOT certain this is ..."

**Comment by lobpcg** [comment]
Using poor random number generators or the same seed on different processors creates a special structure in the initial approximations of LOBPCG that is known to make LOBPCG randomly crash after some iterations for no obvious reasons, especially for large size matrices and with large block sizes. Using a high quality Gaussian with zero mean random number generator is a must for better stability of LOBPCG.

**Comment by uvilla** [comment]
Does `MFEM` still need to support compilers that do not implement the C++11 standard?

If C++11 is a requirement, I can easily adapt this class to work with `MFEM`:
https://github.com/hippylib/hippylib/tree/master/hippylib/utils/cpp_rand

Other options are to use external libraries for parallel RNG, such as [Tina's RNG](https://www.numbercrunch.de/trng/). This was used in [ParElagMG](https://github.com/LLNL/parelagmc)

**Comment by tzanio** [comment]
We will likely switch to C++11 before the next release. Better random number generation can be another reason for that.

**Comment by uvilla** [comment]
Thanks @tzanio,

I’ll start a PR in the next week or so, so that we can start the discussion.

**Comment by v-dobrev** [comment]
@williamfgc, MFEM builds fine with C++11 and optional dependencies can use C++11 if they need that. This is already done in MFEM - for example, when building MFEM with STRUMPACK support, we enable C++11 because STRUMPACK requires it.

**Comment by williamfgc** [comment]
@v-dobrev thanks for the answer, sounds great. It would be helpful to update the developer-guidelines to reflect this: https://github.com/mfem/mfem/blob/master/CONTRIBUTING.md#developer-guidelines `We prefer basic C++ and the C++03 standard, to keep the code readable by a large audience and to make sure it compiles anywhere.` I was afraid to violate this principle. Thanks!
