### ISSUE TITLE
Question about assigning section current density for calculating induction voltage by coil

### ISSUE THREAD

**Issue by TangLaoya** [mfem/mfem#647]
Dear all,
I am trying to calculating induction voltage by coil in ground, as I described on issue #621.  After Mark's help on issue #632, I found the example tesla can calculate the 3D magnetostatic problem by 'a ring of current in a metal sphere', since in my problem I need to calculate the right hand side--the integral term
b=-i * omega * int(dot(N__i, J), V)

I need to know how to fill the element of right hand side after domain is discreted into tetrahedral elements. But I still didn't find any clue on how to fill elements. Could anyone give me some step-by-step instruction on how to fill the element of right hand side?

After solved the electric field, I need to calculate the induction voltage on some received coils, the induction voltage can be calculated by loop integration on the loop of received coils:
V=int(E, l)
furthermore, this integration can be calculated by Gauss integration, therefore, I need to calculate the electric field of some given points. How to do this?

Thanks,
Tang Laoya

**Comment by mlstowell** [comment]
Hi, @TangLaoya ,

In MFEM you do not need to "fill the elements" because the `LinearForm` object does this for you unless I'm misunderstanding your question.
```
LinearForm J(fespace);
J.AddDomainIntegrator(new VectorFEDomainLFIntegrator(JCoef));
J.Assemble(); /// This step performs the integration you mentioned
```
The `LinearForm` object, `J` in the above code, is a vector that contains the integrals of `JFunc`.  Precisely which integrals of `JFunc` is determined by which finite element space you're working in.

It's usually best to work from the physics equations you're trying to discretize.  For example when you write `b=-i * omega * int(dot(N__i, J), V)`, where does this come from?  What is `N_i`?  What is `V`?

Best wishes,
Mark

**Comment by TangLaoya** [comment]
Dear Mark,
Thank you very much for your kindly reply. The expression I mention is from the attached document I studied, do you think is there any problem?

Thanks,
Tang Laoya
[vector finite element stiff.docx](https://github.com/mfem/mfem/files/2512818/vector.finite.element.stiff.docx)

**Comment by tzanio** [comment]
See #648

**Comment by liuzg-23** [comment]
Hi,@TangLaoya:
I am also studying how to use MFEM to load the current source, could you add your WeChat to discuss together, and my wechat number is: 16639638224

Best wishes,
Liuzg
