### ISSUE TITLE
Question about boundary conditions for ex3

### ISSUE THREAD

**Issue by skarden86** [mfem/mfem#649]
Dear developers,

could you please comment how to specify real boundary conditions for ex3.
I don't understand what happened in this lines,

```c++
GridFunction x(fespace);
VectorFunctionCoefficient E(sdim, E_exact);
x.ProjectCoefficient(E);
```

thank you.

**Comment by tzanio** [comment]
Hi @skarden86,

The last line takes the boundary conditions specified in the C-function `E_exact` (see https://github.com/mfem/mfem/blob/master/examples/ex3.cpp#L212-L226) and interpolates them in the finite element function `x`.

Since `fespace` is a Nedelec space, its degrees of freedom (entries in `x`) correspond to dot products with tangential vectors, so the above corresponds to imposing conditions on `E.n`.

Hope this helps,
Tzanio

**Comment by skarden86** [comment]
Hi Tzanio,

thank you.
1)
I still don't understand, if I need to specify for example periodic or tangential conditions what shoul I do?
2)
Am I right that  x.ProjectCoefficient(E)   calculate E_exact on every point from x?

Denis
