### ISSUE TITLE
infinite loop in GeometryRefiner::Refine

### ISSUE THREAD

**Issue by barker29** [mfem/mfem#66]
If GeometryRefiner::Refine() is called on a mesh with quadrilaterals and with Times=0, ETimes=1, then lines 625 and 634 in geom.cpp lead to loops that do not increment and so go on infinitely. 

The call to GeometryRefiner::Refine() with Times=0, ETimes=1 happens if you call SaveVTK() with ref=0, see gridfunc.cpp line 2148. This seems like a reasonable way to call SaveVTK().

**Comment by v-dobrev** [comment]
In `SaveVTK` the parameter `ref` is meant to represent a number of intervals for subdividing in one direction (i.e. along edges), not number of refinement levels, so `ref=0` does not make sense. Probably the name is confusing. What name would be better? How about `subdiv`?

**Comment by barker29** [comment]
Veselin - what is the appropriate ref parameter to use in `SaveVTK()` if you have called `mesh.PrintVTK()` with no ref parameter, using the one-argument version of `mesh.PrintVTK(`) ? Seems to me it should be `SaveVTK(ref=0)`.

**Comment by v-dobrev** [comment]
Oh, I think see what the issue is: are you calling
```c++
Mesh::PrintVTK(std::ostream &out);
```
and then
```c++
GridFunction::SaveVTK(std::ostream &out, const std::string &field_name, int ref);
```
with `ref=0`? If that is the case, then the issue is that instead of the above `Mesh::PrintVTK` method, `GridFunction::SaveVTK` expects you to call the other `Mesh::PrintVTK` method that has a `ref` parameter:
```c++
Mesh::PrintVTK(std::ostream &out, int ref, int field_data=0);
```
and use the same value for `ref` which should be positive.
The two `PrintVTK` methods do different things: the first one saves a linear or quadratic mesh in native VTK format preserving all element connectivity; the second one writes each (curved) mesh element as a separate subdivided linear mesh. The `SaveVTK` method writes data corresponding to the GridFunction subdivided in the same manner as the mesh. This functionality was used just for visualization in VisIt before VisIt had native support for mfem meshes and solutions.

**Comment by barker29** [comment]
Yes, that's what I'm doing. After some more digging I think `VisItDataCollection` is what I want and will solve my problem. (Arguably you should improve documentation for PrintVTK, SaveVTK and/or assert ref > 0, but I don't think issue will effect me anymore.) Thanks.
