### ISSUE TITLE
Getting boundary face details

### ISSUE THREAD

**Issue by vikramsg** [mfem/mfem#666]
I need to get the location of a point in an element which is farthest in the normal direction of a boundary element. Let me try to explain.

If we take the reference element as a square on the boundary, any of the 4 edges can be the boundary element. So what I want is to identify which one of the faces is at the boundary, is it ( (0, 0), (0, 1) ) or ( (0, 1), (1, 1) ), ( (1, 1), (1, 0) ) or ( (1, 0), (0, 0) ). Once I know this, for any point on the edge, I need to get the location of the corresponding point on the opposite edge.

What would be the best way of doing this?

**Comment by tzanio** [comment]
To clarify, is this the problem you are trying to solve:

"Given a face of the reference element and a point on that face, find the intersection of the boundary of the reference element with the ray defined by the point and the interior face normal at it."

Are you interested in doing this in reference of physical space? Can you provide more details about what it will be used for?

**Comment by vikramsg** [comment]
I think that is correct. I would actually want to do it in physical space but I think doing it in reference space would be easier and will serve as an approximation for physical space. 

![wmles_pts](https://user-images.githubusercontent.com/13407380/48255332-12767780-e415-11e8-97a4-ae2a7d40b5b1.png)

Let me try to illustrate what I am trying to do with the above picture. The bottom line is the boundary, and the bottom element is the boundary element. Now, I am trying to impose a wall function based boundary condition. So at the boundary points, to impose such a condition I want to impose the values taken from the red points normal to the point on the boundary. 

This was much easier in simple boundaries like in the figure, but now I want to generalize it and so have to deal with arbitrary normals. In addition I generated this figure for Gauss points but am now using Gauss Lobatto points, so both points on boundary and opposite face points are on the boundary and interior face. 

I hope this is clearer.

**Comment by v-dobrev** [comment]
Hi @vikramsg,

Is this type of b.c. imposed as a constraint to the system? For example, if `i` is the index of a boundary dof and `j1` and `j2` are the indices of the two red dofs between which dof `i` falls when extended into the domain in normal direction, then you want to impose the constraint `sol(i) = a1*sol(j1) + a2*sol(j2)` where `a1` and `a2` are some weights. If this is the case, MFEM currently does not offer support for imposing such constraints, however, we are planning on adding support for that in the near future. One possible solution in the meantime can be to manually modify the matrix and rhs of your system (if your problem is linear). Let's say that the original system can be written in the form
``` 
| A_ii  A_ib | | u_i | = | f_i |
| A_bi  A_bb | | u_b |   | f_b |
```
and you want to impose the constraint
```
u_b = C_bi u_i
```
then the modified system that you need to solve is
```
A_ii u_i + A_ib C_bi u_i = f_i
```
or extending the system to preserve its original size
```
| (A_ii + A_ib C_bi)  0 | | u_i | = | f_i |
|       0             I | | z_b |   |  0  |
```
This seems like one reasonable approach.

If I understand correctly, your main question is about finding the indices `j1` and `j2`, given the index `i`, as in the example above. For general quad elements, e.g. high-order quads, this procedure will not be straightforward. If, however, you can assume that the elements are parallelograms, then the procedure will be relatively simple.

Alternatively, is there a way to formulate this type of b.c. on continuous level, i.e. can the constraints be written as `c(u,v)=d(v)` where `u` is the solution, `v` is a test function, and `c(.,.)` and `d(.)` are a bilinear and linear forms, respectively, which are defined as integrals over a strip of elements adjacent to a subset of the boundary? If such formulation is possible, then constructing the constraint matrix may be easier, even for general meshes.

**Comment by tzanio** [comment]
Hi Vikram,

I have also been trying to think about this, and I also have struggled to find a natural way to describe these conditions.

If you really are OK with imposing them on the reference element, then that is certainly doable and just a question of handling all the cases of which face is the boundary and constructing the corresponding dof map, using the fixed reference element numbering.

For general elements, it seems to me what you are asking is to solve an advection equation, transporting the values on the red face with a "velocity" vector that is the mapped normal vector field from the reference element. While doable, this will certainly be expensive and I wonder if it is really what you want.

**Comment by vikramsg** [comment]
Hi @v-dobrev,

I am not completely sure I understand what you are saying but one thing is that the boundary condition is not a linear function, but depends non-linearly both on the values on the red dofs as well as its distance from the boundary dof. 

@tzanio Right now all I have come up with is determining the normal direction at the boundary in the reference element, say at eip. I checked and this normal always points away from the boundary element as I just reverse this, get (eip2 = eip+nor) and then u.Eval(eip2). 

Right now, getting the values like this in physical space seems a bit too complicated to me. I may probably have to use the FindPoints and InverseTransform to do this, but as I understand that is not guaranteed to be stable.

**Comment by v-dobrev** [comment]
Hi Vikram,

As an example how the physical normal vector can be computed in a DG-type integrator, take a look at this:
https://github.com/mfem/mfem/blob/4cb8d2cbc19aac5528df650b4a41c54158d1d2c2/fem/lininteg.cpp#L498-L505
With this computation, the vector `nor` is orthogonal to the face described by `Tr.Face` but it is not unit (in 2D/3D). The length of `nor` is actually the weight in the change of variables formula, from the physical face, say `F`, to the reference face `\hat{F}` (`Tr.Face` represents the mapping from `\hat{F}` to `F`):
```
\int_F f = \int_{\hat{F}} f |nor|
```

Since your b.c. is non-linear, then I guess it has to be evaluated as part of the evaluation of your non-linear operator, so my considerations about the linear case do not apply.

What type of elements (near the wall boundary) are you interested in? Are parallelogram elements sufficient, or do need general quads and/or hexes? Do you want to be able to use high-order mesh elements as well?

The general case (high-order curved elements) will require a ray-tracing algorithm: given a point on the boundary of an element and a direction (in your case, the inward normal at that point), find the point on the boundary of the element where the ray exits the element (in terms of which face is the exit face and what is the reference face coordinate of the exit point). Is this the type of algorithm you are interested in?

**Comment by vikramsg** [comment]
Hi @v-dobrev ,

Yes, now that you have put it this way, I think a ray-tracing algorithm is exactly what I want.  In this case all I would want is the reference element coordinate of the place where the ray exits the element.

**Comment by tzanio** [comment]
@vikramsg, were you able to come up with a solution, or is this still an open issue for you?

**Comment by vikramsg** [comment]
Hi @tzanio ,

Sorry for not replying. I did not actually figure out a better solution. I will close this for now, but hopefully some kind of feature for raytracing is introduced.
