### ISSUE TITLE
Outflow and Inflow Boundary conditions

### ISSUE THREAD

**Issue by nickwhitman1993** [mfem/mfem#668]
Hello,

I have a test problem in which I have a boundary driven source, i.e. a Dirichlet boundary condition on the left side and right side (inflow). This is defined using the boundary flow integrator, which should be just fine. 

However, on the outflow directions (i.e. the exiting faces of the problem defined by the direction of particle travel dot normal > 0), I need a robin boundary condition (the equation is second order so I need to make sure I impose this). Do you have any idea how I could implement this or point me to a previous thread?

**Comment by jandrej** [comment]
A robin type boundary condition
```
u \cdot n = g + a u
```
will have a contribution to the left hand side and right hand side of your resulting equation. From the replacement of a boundary term in a continuous galerkin formulation in the weak form you replace `u \cdot n` and end up with
```
\int g * v + \int a * u * v
```
when v is the test function. Therefore you have a linear term
```
\int g * v
```
where you can just use `BoundaryLFIntegrator`. For the other part containing both a trial and test function you have a contribution by a boundary mass matrix
```
\int a * u * v
```
for which you can use `BoundaryMassIntegrator`.

I hope I got your question right.

**Comment by nickwhitman1993** [comment]
The form of my boundary condition looks like:

\lambda\cdot\grad u + a u = f

where lambda is my VectorFunctionCoefficient, a is a constant, and f is a constant.

Is the derivative portion excluded in the portion or am I overlooking something?

Thanks again, your explanation definitely puts me on the correct track.

**Comment by jandrej** [comment]
I made a typo in the first equation, it should be
```
\nabla u \cdot n = g + a u
```
where `n` is the outward unit normal.

**Comment by nickwhitman1993** [comment]
@jandrej - my thoughts are the following:

I can not assert that I only use this treatment on faces such that my direction vector, lambda, dotted into the face normal vector is > 0. Maybe I can loop over the boundary faces and test for if that case is true? 

Additionally, it looks like my robin condition is a tad different, whereas I need to do:

lambda dot grad u + a u = constant 

So really, it would end up looking like:

(lambda_x du/dx + lambda_y du/dy + lambda_z du/dz) + a u = constant if vec(lambda) dot n > 0 on the boundary faces.

Do you have any thoughts?

Apologies for my lack of knowledge - I am still trying to grasp the MFEM concepts in more detail. 

Thanks again for your time!

Nick

**Comment by jandrej** [comment]
> I can not assert that I only use this treatment on faces such that my direction vector, lambda, dotted into the face normal vector is > 0. Maybe I can loop over the boundary faces and test for if that case is true?

Sorry I don't understand that.

> lambda dot grad u + a u = constant

Maybe it can help if you explain what the physical meaning is for your problem that you want this boundary condition for.

**Comment by nickwhitman1993** [comment]
Sorry - so the physical problem I am solving is a neutron transport equation. This particular form is called the Self-Adjoint Form, which is a second order (spatially) equation and is derived from the first order equation. In the first order transport equation and in the second form, the incoming source from the boundary is the defined the same way. I already have this in the form of a BoundaryFlowIntegrator. Additionally, in the second order equation however, we have to enforce that the first order transport equation is met on the outflow surfaces, i.e. that the direction vector we are currently using dotted into the face normal is > 0. 

I can refer you to some previous threads that I opened #520, #592, but the weak galerkin forms are as follows:

![44884403-15fcbe00-ac70-11e8-9071-02b8bc69ed10](https://user-images.githubusercontent.com/23174133/48645093-752dbd00-e999-11e8-9f1b-f1bc81894a44.png)

At this point, I have run a 1-D benchmark against two other solutions, one of which being the first order in MFEM. I am trying to figure out what might be going on at the boundaries or in any other part of my code that is rising to the discrepancies between the two. My solution should be very close to the others.

These are the results I am getting: 
![image](https://user-images.githubusercontent.com/23174133/48645208-d5246380-e999-11e8-9a81-4cac93cf0aa0.png)

**Comment by v-dobrev** [comment]
Hi @nickwhitman1993,

Are you asking about implementing the last term in (17) and the last term in (18)?

**Comment by nickwhitman1993** [comment]
@v-dobrev Before I continue, I want to make sure I mention that I have a verified version of the first-order transport equation in MFEM which is the gray solution above. The derivation of the second order Galerkin weak form uses many of the same terms as the first order equation.

With that being said, I believe the term in (17) is taken care of with two DGTraceIntegrators (at least this was the way it was coded for the first order equation and it should not change between the two) unless I am mistaken.

    // Upwind fluxes between zones on each face interior to mesh
    // For surface, we need a boundary geometry integration rule and order
    mfem::BilinearFormIntegrator *traceInterior =
        new mfem::DGTraceIntegrator(omega, -1.0, +0.5);
    traceInterior->SetIntRule(&elIntRule);
    mfem::BilinearFormIntegrator *transInterior =
        new mfem::TransposeIntegrator(traceInterior);
    L.AddInteriorFaceIntegrator(transInterior);

    //Now add the inflow boundary conditions to the matrix and RHSs
    // need to SetIntRule on the DGTraceIntegrator rather than the
    // TransposeIntegrator
    mfem::BilinearFormIntegrator *traceBdr =
        new mfem::DGTraceIntegrator(omega, -1.0, +0.5);
    traceBdr->SetIntRule(&bdrIntRule);
    mfem::BilinearFormIntegrator *transBdr =
        new mfem::TransposeIntegrator(traceBdr);
    L.AddBdrFaceIntegrator(transBdr);

The term in (18) - now this is _possibly_ one source of error. I split the domain source term in (18) into a DomainLFIntegrator and had to create a custom class for the \Omega \cdot \nabla \psi portion. My custom class could definitely be causing an issue. I received help creating it from @mlstowell and it _seemed_ to look correct but when I started testing it, it caused non-convergence (I am using source iteration), but that may be also due to the BC I might be missing. 

Only the first of the other two surface terms is needed (no reflective BC) and is taken care of with a BoundaryFlowIntegrator (same as in the first order equation).

The additional BC needed for uniqueness on the outflow boundaries is as follows:

![untitled](https://user-images.githubusercontent.com/23174133/48655054-61994b00-e9c7-11e8-8a54-26a50b7684bb.jpg)

and (5) is shown for the above reference. 

![1](https://user-images.githubusercontent.com/23174133/48655060-783fa200-e9c7-11e8-984c-3326a7b00a4c.jpg)

Again, I may be incorrect and missing something huge that you may see. 
Please let me know if anything I said does not make sense and I can try to clear it up; I realize I am not always great at being thorough in explaining things.

I appreciate your time in helping me look into this!

Nick

**Comment by v-dobrev** [comment]
@nickwhitman1993,

I'm sorry to be blunt here, but do you know what linear and/or bilinear forms you need in order to discretize your problem?

If you are not certain and that is what you are trying to figure out, then it is unfair to expect MFEM developers to help you figure it out. We try to help people with simple PDE discretization questions, however your questions are quite long and require understanding of your area of research.

Once you figure out what linear and/or bilinear forms you need for your discretization scheme, I will be happy to provide guidance on how to implement them in MFEM.

Just to clarify: what I said above is my own opinion - other may feel differently.

**Comment by nickwhitman1993** [comment]
@v-dobrev 

Yes, I do know what linear and bilinear forms I need and have done my best to avoid asking for help. I don't expect anyone to help me figure it out. I apologize if I come across that way, as that is not my intention.

I have already received assistance on the custom linear form integrator that I needed for <\Omega\cdot\nabla\psi*, _____>, which was greatly appreciated. My questions above were asking about if the implementation of that custom class might have been incorrect, and if there were any leads/thoughts on how to implement a boundary condition that I can't seem to find information about on the website or anywhere on the forum.

Again, I sincerely apologize if there was miscommunication on my part.

Nick

**Comment by jandrej** [comment]
I guess I won't be able to help to derive your form needs, but regarding
> Before I continue, I want to make sure I mention that I have a verified version of the first-order transport equation in MFEM which is the gray solution above.

If I understand correctly, you don't know if your implementation is solving the equation that you defined on paper, so you should read up on the Method of Manufactured Soltutions in [https://www.osti.gov/biblio/759450](https://www.osti.gov/biblio/759450).

**Comment by v-dobrev** [comment]
Hi @nickwhitman1993,

Imposing boundary conditions can be done using 2 approaches:
* essential b.c. - in this case values of a discretized field are plugged directly into the discritized system
* weakly imposed b.c. - in this case the linear form (rhs) and/or the bilinear form (the matrix of the system) are modified by adding additional terms.

In standard diffusion discretization (using continuous elements) Robin b.c. are imposed using the second approach. That is why I assumed (maybe incorrectly?) that with your discretization scheme, one needs to use the second approach as well. So I asked what are the additional terms you need to add to you linear and bilinear forms in order to impose the boundary condition you are asking about.

Which category does your b.c. fall into?

Note that the answer does not depend just on the physical type of the b.c. (like Dirichlet, Neumann, etc) but also depends on the discretization scheme. For example, in standard diffusion discretization, Neumann b.c. are imposed weakly (category 2 above), however in mixed diffusion discretizations, the Neumann b.c. become essential b.c. (category 1 above).

**Comment by nickwhitman1993** [comment]
@v-dobrev It might be a better idea if I look at the custom integrator and see if there are any issues there before we go any deeper. 

I have done some manufactured solution tests and the tests that are uniform solutions are solved within 1e-15 if I omit my custom integrator (which is 0 if the solution is uniform). This leads me to believe that _may_ be the source.

I do have some ideas on what you asked, but I keep reading some conflicting things in the papers I have been looking at. 

Would you be willing to take a glance at that portion to see if anything jumps out?

**Comment by v-dobrev** [comment]
@nickwhitman1993, I can take a look at your custom integrator implementation. To do that, I'll need to know the precise definition of the bilinear (or linear) form that you are implementing.

**Comment by nickwhitman1993** [comment]
@v-dobrev, I appreciate it.

The linear form I am implementing is as shown above in (18), but in more general terms that are the convention:

(u* + \alpha \vec{\lambda} \cdot \nabla u* , f)

Where alpha is a FunctionCoefficient, Lambda is a VectorFunctionCoefficient, and f is a GridFunctionCoefficient. 

I currently split this Linear term into (u*, f) and ( \alpha \vec{\lambda} \cdot \nabla u* , f), since (u*, f) can be handled using a DomainLFIntegrator and do so. 

My current version of the ( \alpha \vec{\lambda} \cdot \nabla u* , f) term looks like this. I pass in (lambda, alpha, f) as arguments.

      class DomainConvectionIntegrator : public LinearFormIntegrator
        {
        private:
          DenseMatrix dshape;
          Vector shape, Q_ir;
          VectorCoefficient &Q;
          Coefficient &S, &F;
          int oa, ob;
        public:
          /// Constructs a domain integrator with a given Coefficient
          DomainConvectionIntegrator(VectorCoefficient &q, Coefficient &s, Coefficient &f,
            int a = 1, int b = 1)
             : Q(q), S(s), F(f), oa(a), ob(b) { }

              virtual void AssembleRHSElementVect(const FiniteElement &el,
                                                  ElementTransformation &Tr,
                                                  Vector &elvect);

              using LinearFormIntegrator::AssembleRHSElementVect;
        };


      void DomainConvectionIntegrator::AssembleRHSElementVect(const FiniteElement &el,
                                                      ElementTransformation &Tr,
                                                      Vector &elvect)
      {
        int nd = el.GetDof();
        int dim = el.GetDim();

        elvect.SetSize(nd);
        dshape.SetSize(nd,dim);
        shape.SetSize(nd);


        const IntegrationRule *ir = IntRule;
        if (ir == NULL)
        {
          ir = &IntRules.Get(el.GetGeomType(),
                             oa * el.GetOrder() + ob + Tr.OrderW());
          // ir = &IntRules.Get(el.GetGeomType(), oa * el.GetOrder() + ob);
        }

        elvect = 0.0;


        for (int i = 0; i < ir->GetNPoints(); i++)
        {
           // Grab the current integration point and pass it to the element transformation
           const IntegrationPoint &ip = ir->IntPoint(i);
           Tr.SetIntPoint(&ip);

           // Calculate the gradient of the basis functions at this point in physical space
           el.CalcPhysDShape(Tr, dshape);

           // Compute vector coefficient at this point
           Q.Eval(Q_ir, Tr, ip); //VectorCoefficient omega

           // Compute the dot product of Q with each basis function
           // and accumulate the results into the output vector with appropriate weight
           dshape.AddMult_a(ip.weight * Tr.Weight() * F.Eval(Tr, ip) * S.Eval(Tr, ip), Q_ir, elvect);
         }
      }

**Comment by v-dobrev** [comment]
@nickwhitman1993,

Your implementation looks correct to me. One minor thing: the vector `shape` is not really used, so you can remove it from your class.

One potential issue could be the choice of the order of the quadrature rule. For this linear form, it is probably more appropriate to use order similar to the one in `ConvectionIntegrator::AssembleElementMatrix`: https://github.com/mfem/mfem/blob/4cb8d2cbc19aac5528df650b4a41c54158d1d2c2/fem/bilininteg.cpp#L877-L878

This choice may be an overkill though (the drawback for higher quadrature orders is slower execution due to larger number of quadrature points). Probably the lowest quadrature order that makes sense is `order = el.GetOrder() + 1` or even just `order = el.GetOrder()`.

**Comment by nickwhitman1993** [comment]
@v-dobrev 

Thank you very much for the feedback. I made some minor changes to the quadrature rule. Not much changed, as I assumed would probably happen unfortunately.

I had a chat with my adviser and we both agreed that a mixed boundary condition is what we are needing. 

The term is < [\vec{\alpha} \cdot \nabla v + \beta v - \gamma], u>.  
Similar to BoundaryFlowIntegrator, we would need to test for direction (outgoing) \vec{\alpha} \cdot \hat{n} > 0, i.e. alpha = 1.0 and beta = 0.5. 

I am thinking that we could simply add another BoundaryFlowIntegrator to handle < \gamma, u> for outgoing directions, \alpha = 1.0 and \beta = 0.5. 
The other part < [\vec{\alpha} \cdot \nabla v + \beta v] , u > would require an extra Bilinear term that tests for direction similarly to BoundaryFlowIntegrator, or in another fashion perhaps.

Do you have any thoughts on how to proceed? If anything I said above needs clarification or seems wrong please let me know.

Thank you again for looking over this.

**Comment by v-dobrev** [comment]
In the term `< [\vec{\alpha} \cdot \nabla v + \beta v - \gamma], u>`, is the integration over all boundary faces where `\vec{alpha}.n > 0`?

In the same term, I see two separate terms: 1) a bilinear term involving both `v` (trial function) and `u` (test function) which I assume needs to be added to a `BilinearForm`, and 2) the term `<\gamma, u>` that involves only the test function `u` (`\gamma` is a given coefficient) and which I assume will need to be added to a `LinearForm`. Do I understand this correctly?

**Comment by nickwhitman1993** [comment]
@v-dobrev 

Yes, these are on all boundary faces such that `\vec{alpha}.n > 0.`

I believe that your understanding is correct.

**Comment by nickwhitman1993** [comment]
@v-dobrev 

Just checking back in to see if you have had a chance to think about this.

**Comment by v-dobrev** [comment]
Here are some general directions:
* For the term `< [\vec{\alpha} \cdot \nabla v + \beta v, u>`, create a new class derived from `BilinearFormIntegrator` and implement its method `AssembleFaceMatrix`. For examples of this type of integrators, see the classes `DGTraceIntegrator` and `DGDiffusionIntegrator` - they should have all the components you need. Since you are only interested to use this form on the boundary, you can assume that there is no second element, i.e. that `(Trans.Elem2No >= 0)` is false. When you use this integrator, add it to the `BilinearForm` with the method `AddBdrFaceIntegrator`.
* For the term `<\gamma, u>`, create a new class derived from `LinearFormIntegrator` and implement its method `AssembleRHSElementVect(const FiniteElement &el, FaceElementTransformations &Tr, Vector &elvect)`. This class will need the coefficient `\vec{\alpha}` (in addition to `\gamma`) so that you can determine if, at a quadrature point, `\vec{alpha}.n > 0` is true. This should be very similar to the class `BoundaryFlowIntegrator`. When you use this integrator, add it to the `LinearForm` using the method `AddBdrFaceIntegrator`.

Does this make sense?

Let me know if you have more specific questions about the implementations.
