### ISSUE TITLE
Derefinement and nodal finite element spaces

### ISSUE THREAD

**Issue by junkudo** [mfem/mfem#671]
Hey,
I have some code that performs derefinement on a mesh and tries to update a non-nodal finite element space.  Here's a small working example of what I'm trying to do:
```c++
mfem::Mesh mesh(5, 5, mfem::Element::QUADRILATERAL, 1,
                          1.0, 1.0);
mesh.EnsureNCMesh();
mesh.UniformRefinement();

mfem::RT_FECollection fec(1, mesh.Dimension());
mfem::FiniteElementSpace fes(&mesh, &fec);

mfem::Vector elem_error(mesh.GetNE());
elem_error = 0.0;
mesh.DerefineByError(elem_error, 1.0);

fes.Update();
```

This code fails an assert statement at:
https://github.com/mfem/mfem/blob/73a4ddfb619fbb05f357c66b0998edca8456a4b2/fem/fespace.cpp#L1036

It looks like I can't currently perform derefinement and update non-nodal finite element spaces. If so, is this a feature that's going to be implemented soon?  Otherwise, am I doing something wrong? 
CC @Dan2997925 
Thanks for your help!

**Comment by v-dobrev** [comment]
Hi @junkudo,

You should be able to update the space using `fes.Update(false)`. However, using `want_transform = false` (the parameter of `Update()`) means that you will not be able to update (coarsen) any `GridFunction`s which may or may not be an issue, depending on your use case. For example, if you are going to solve the problem again on the coarse mesh then you do not need to update/coarsen a solution from the finer mesh. On the other hand, if you coarsen the mesh after a time step, you will need to update/coarsen the solution in order to continue the time stepping on the coarser mesh.

In any case, adding support for coarsening of non-nodal `GridFunction`s should not be too difficult. I'll make a branch for that soon and I'll let you know when it is ready for you to test.

**Comment by junkudo** [comment]
Hey @v-dobrev - is this functionality in a branch somewhere?

**Comment by tzanio** [comment]
My apologies -- I closed this before realizing that there is an outstanding TODO item. Feel free to reopen the issue.

**Comment by v-dobrev** [comment]
Hi @junkudo,

I have not had time to work on this yet. I'll try to do it this week.

**Comment by v-dobrev** [comment]
Hi @junkudo,

I just created a branch where I added support for derefinement of RT spaces - it is called [derefine-vector-spaces](https://github.com/mfem/mfem/tree/derefine-vector-spaces). Give it a try and let me know if you run into any issues.

**Comment by junkudo** [comment]
Okay.  Will let you know.

**Comment by junkudo** [comment]
Yeah.  This seems to work properly for my application now.  Let me know when the branch is merged into master!

**Comment by v-dobrev** [comment]
I just created one - see above - thanks for reminding us.
