### ISSUE TITLE
Constructing a mfem::HypreParVector

### ISSUE THREAD

**Issue by junkudo** [mfem/mfem#690]
Hey,
I'm trying to create a mfem::HypreParVector using the constructor:
https://github.com/mfem/mfem/blob/87f86d45c927ad5fa001a82c96ec29ca0def37ff/linalg/hypre.hpp#L87-L89

Following the comment, I tried the following with two processors : 
```c++
   HYPRE_Int glob_size = 10;
   HYPRE_Int * col = new HYPRE_Int[3];

   // Create a column specification of 3 numbers on proc 0 and 7 on proc 1
   col[0] = 0;
   col[1] = 3;
   col[2] = 10;
   mfem::HypreParVector x(MPI_COMM_WORLD, glob_size, col);
   std::cout << myrank << ": x size is " << x.Size() << std::endl;
```

I expected processor 0 to have a vector of size 3 and processor 1 to have a vector of size 7.  Instead I saw:
```bash
0: x size is 3
1: x size is 3
```

When I dug into an example that uses this constructor : 
https://github.com/mfem/mfem/blob/87f86d45c927ad5fa001a82c96ec29ca0def37ff/examples/ex5p.cpp#L221-L222

I saw that it was passing in a pointer to an array that had column definitions that was not consistent with the constructor comments.  For example, when I turned off refinement and ran with three processors, I saw: 
```bash
0: M->GetGlobalNumRows() 2640
0: M->GetRowStarts()[0] 0
0: M->GetRowStarts()[1] 552
0: M->GetRowStarts()[2] 2640
0: M->GetRowStarts()[3] 0
0: Md->Size() 552
1: M->GetGlobalNumRows() 2640
1: M->GetRowStarts()[0] 552
1: M->GetRowStarts()[1] 2016
1: M->GetRowStarts()[2] 2640
1: M->GetRowStarts()[3] 0
1: Md->Size() 1464
2: M->GetGlobalNumRows() 2640
2: M->GetRowStarts()[0] 2016
2: M->GetRowStarts()[1] 2640
2: M->GetRowStarts()[2] 2640
2: M->GetRowStarts()[3] 0
2: Md->Size() 624
```
It's very possible I'm stepping past the bounds of `M->GetRowStarts()` as I don't actually know the size here.

Regardless, I don't think I understand what the input should be for the column specification.  It almost looks like only the first two numbers are important...?  What should be the proper input into this constructor?  Thanks!

CC @chldkdtn @Dan2997925

**Comment by mlstowell** [comment]
Hi, @junkudo ,

Originally, Hypre defined this array to have a length equal to the number of processors plus one and they filled it just as you tried to do.  However, this approach is not scalable so at some point they redefined how this array should be filled.  Hypre still supports both methods and so does MFEM.  I believe the choice must be made when compiling the Hypre library.

The new scheme defines these arrays to be of length two regardless of the number of processors.  The first entry is the global offset for the first row of the local processor.  The second entry is the global offset for the first row of the next processor.  This seems to be consistent with the three processor output that you show if, as you surmised, you ignore the last two entries.

You should be able to assume that Hypre is using the length two scheme, because this is the current default, but if you want to support both schemes there is a way to tell which scheme is being used.  The boolean function `HYPRE_AssumedPartitionCheck()` returns true if the length two scheme is in use.

I'll make the necessary changes to the header file comments.

Best wishes,
Mark

**Comment by junkudo** [comment]
Thanks Mark.  I figured it was something like this and really just wanted confirmation that I wasn't silently creating an improper `mfem::HyperParVector`!

**Comment by mlstowell** [comment]
Just created a pull request #691 to address this issue.  @junkudo , feel free to close this issue if you're satisfied.
