### ISSUE TITLE
parallel building METIS error

### ISSUE THREAD

**Issue by skarden86** [mfem/mfem#698]
Dear developer,

following parallel building instruction, after command
make parallel -j MFEM_USE_METIS_5=YES METIS_DIR=@MFEM_DIR@/../metis-5.1.0

I got next make an error, probably from metis-5.1.0/include/metis.h

c fem/staticcond.cpp -o fem/staticcond.o
mpicxx   -O3 -I./../hypre-2.11.2/src/hypre/include -I./../metis-5.1.0/include  -c fem/tmop.cpp -o fem/tmop.o
mesh/mesh.cpp: In member function ‘int* mfem::Mesh::GeneratePartitioning(int, int)’:
mesh/mesh.cpp:4676:38: error: cannot convert ‘int*’ to ‘idx_t* {aka long int*}’ for argument ‘1’ to ‘int METIS_SetDefaultOptions(idx_t*)’
       METIS_SetDefaultOptions(options);
                                      ^
mesh/mesh.cpp:4722:53: error: cannot convert ‘int*’ to ‘idx_t* {aka long int*}’ for argument ‘1’ to ‘int METIS_PartGraphRecursive(idx_t*, idx_t*, idx_t*, idx_t*, idx_t*, idx_t*, idx_t*, idx_t*, real_t*, real_t*, idx_t*, idx_t*, idx_t*)’
                                         partitioning);
                                                     ^
mesh/mesh.cpp:4758:48: error: cannot convert ‘int*’ to ‘idx_t* {aka long int*}’ for argument ‘1’ to ‘int METIS_PartGraphKway(idx_t*, idx_t*, idx_t*, idx_t*, idx_t*, idx_t*, idx_t*, idx_t*, real_t*, real_t*, idx_t*, idx_t*, idx_t*)’
                                    partitioning);
                                                ^
mesh/mesh.cpp:4795:48: error: cannot convert ‘int*’ to ‘idx_t* {aka long int*}’ for argument ‘1’ to ‘int METIS_PartGraphKway(idx_t*, idx_t*, idx_t*, idx_t*, idx_t*, idx_t*, idx_t*, idx_t*, real_t*, real_t*, idx_t*, idx_t*, idx_t*)’
                                    partitioning);
                                                ^
make[1]: *** [mesh/mesh.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory `/home/oem/workspace/mfem/mfem-3.4'
make: *** [parallel] Error 2

**Comment by tzanio** [comment]
Thanks for reporting this @skarden86.

It looks like we need to add explicit conversion to `(idx_t *)` to more of the arguments in our METIS calls in `Mesh::GeneratePartitioning`.

Usually this is not an issue because `idx_t` is just `int`, but in your build it is `long int`. (Probably because you set `IDXTYPEWIDTH` to 64?)

If this is not critical, you can just rebuild METIS with `IDXTYPEWIDTH  32` and MFEM should build. .

**Comment by tzanio** [comment]
Thanks @skarden86

**Comment by nourgaliev** [comment]
Tzanio, I am upgrading Metis/Parmetis from their GitHub repo. Getting related error:

In file included from /Users/nourgaliev1/Robert/CODES/TELOS/dev1/librepos/mfem/mesh/mesh.cpp:38:
/Users/nourgaliev1/Robert/CODES/TELOS/libraries/osx_gcc11.3.0/debug/metis/5.1.1-94c03a6e2d-b/mpi-openmpi-4.1.1/gklib-gklib-sha-a7f8172703-a/cmake-3.22.4/BLT-develop-49971b88e6/include/metis.h:115:4: error: #error "Incorrect user-supplied value fo IDXTYPEWIDTH"
  115 |   #error "Incorrect user-supplied value fo IDXTYPEWIDTH"
      |    ^~~~~
/Users/nourgaliev1/Robert/CODES/TELOS/libraries/osx_gcc11.3.0/debug/metis/5.1.1-94c03a6e2d-b/mpi-openmpi-4.1.1/gklib-gklib-sha-a7f8172703-a/cmake-3.22.4/BLT-develop-49971b88e6/include/metis.h:150:4: error: #error "Incorrect user-supplied value for REALTYPEWIDTH"
  150 |   #error "Incorrect user-supplied value for REALTYPEWIDTH"
      |    ^~~~~
 
Do you have fix for that now? (May be some CMake flag???) I am at the latest MFEM version right now. My old Metis repo was from their old (~2015) tarball. There are quite a few changes in their new (github https://github.com/KarypisLab/METIS) version. In any case - I would appreciate any hint how to fix this.

**Comment by nourgaliev** [comment]
Tzanio: I am re-opening this issue - as I am having similar problem.

**Comment by nourgaliev** [comment]
I am building MeTiS with 32 bit.

**Comment by nourgaliev** [comment]
Tzanio: I fixed this by adding to MFEM CMakeList.txt:

#=======================
# METIS' custom options:
#=======================
option(METIS_IDX64 "enable 64 bit ints" OFF)
option(METIS_REAL64 "enable 64 bit floats (i.e., double)" OFF)
if(METIS_IDX64)
  set(METIS_COPTIONS "${METIS_COPTIONS} -DIDXTYPEWIDTH=64")
  message(STATUS "METIS with IDX64")
else()
  set(METIS_COPTIONS "${METIS_COPTIONS} -DIDXTYPEWIDTH=32")
  message(STATUS "METIS with IDX32")
endif(METIS_IDX64)

if(METIS_REAL64)
  set(METIS_COPTIONS "${METIS_COPTIONS} -DREALTYPEWIDTH=64")
  message(STATUS "METIS with REAL64")
else()
  set(METIS_COPTIONS "${METIS_COPTIONS} -DREALTYPEWIDTH=32")
  message(STATUS "METIS with REAL32")
endif(METIS_REAL64)

if (MFEM_USE_METIS)
  find_package(METIS REQUIRED)
  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${METIS_COPTIONS}")
endif()

**Comment by nourgaliev** [comment]
Then you would need to pass something like:

" -DMETIS_IDX64=OFF"
" -DMETIS_REAL64=OFF"

To explicitly activate/force Metis use 32 or 64 bit.

**Comment by v-dobrev** [comment]
Hi @nourgaliev,

I didn't even know METIS had GitHub repo (and I've searched for it before). It is also not mentioned on their original website.

Anyway, any METIS build options and configuration should be done by the METIS cmake files -- I don't understand why you modify MFEM's cmake files.

When configuring MFEM, you just need to specify where METIS is installed with the flag `-DMETIS_DIR=/path/to/metis`. MFEM will work with both 32bit and 64bit builds of METIS. At least it does with METIS v5.1.0 from the original website http://glaros.dtc.umn.edu/gkhome/metis/metis/download.

In any case, we can take a look at the new (?) version 5.1.1 of METIS and the main branch from the GitHub repo to see how we can support these.

**Comment by nourgaliev** [comment]
Hi Veselin,

I did not know they had github either, until recently. Turns out they commented out in their latest version of metis.h

//#define IDXTYPEWIDTH 32
//#define REALTYPEWIDTH 32

So these are undefined. You could either manually uncomment it in their source, or define it in your cmake build system. I actually ended up doing both, as the same problem happen iwhen building PETSc with MeTiS. Their build system is more complex, so I could not figure out how to pass IDXTYPEWIDTH and REALTYPEWIDTH. In any case – up to you if want to use something like I suggested. This way – you could flip between 32/64 bits.

There are a few other problems with their repo, like they moved gklib out of MeTiS into separate repo, which caused problem for PETSC; and they have a couple of compilation bugs causing problems on some systems. I figured all these out, but not sure if this all worthwhile – as it does not look they update this repo actively, and if it has any major upgrade from PETSc’s repo which I was using previously. I chatted with Barry Smith about this – he did not sound enthusiastic to upgrade. I also reported these issues to MeTiS. For now, I would suggest simply replace the above commented out lines with something like:


//#define IDXTYPEWIDTH 32
#ifndef IDXTYPEWIDTH
#define IDXTYPEWIDTH 32
#endif // IDXTYPEWIDTH

//#define REALTYPEWIDTH 32
#ifndef REALTYPEWIDTH
#define REALTYPEWIDTH 32
#endif // REALTYPEWIDTH

in metis.h

and this will take care of the problem.

Robert.

==========================================
Nourgaliev, Robert
Lawrence Livermore National Laboratory (LLNL)
P.O. Box 808, L-170, Livermore CA 94551
Email: ***@***.***
Phone: (925) 423-2905
Mobile: (805) 451-8825

From: Veselin Dobrev ***@***.***>
Reply-To: mfem/mfem ***@***.***>
Date: Tuesday, May 24, 2022 at 9:03 PM
To: mfem/mfem ***@***.***>
Cc: "Nourgaliev, Robert Nr" ***@***.***>, Mention ***@***.***>
Subject: Re: [mfem/mfem] parallel building METIS error (#698)


Hi @nourgaliev<https://urldefense.us/v3/__https:/github.com/nourgaliev__;!!G2kpM7uM-TzIFchu!hspSl9riMkiTRcce0DyLXLDABrgvbkZ2G3w7hjE-60cmsTOB4FlII2iQ6zGowui4GaHS$>,

I didn't even know METIS had GitHub repo (and I've searched for it before). It is also not mentioned on their original website.

Anyway, any METIS build options and configuration should be done by the METIS cmake files -- I don't understand why you modify MFEM's cmake files.

When configuring MFEM, you just need to specify where METIS is installed with the flag -DMETIS_DIR=/path/to/metis. MFEM will work with both 32bit and 64bit builds of METIS. At least it does with METIS v5.1.0 from the original website http://glaros.dtc.umn.edu/gkhome/metis/metis/download<https://urldefense.us/v3/__http:/glaros.dtc.umn.edu/gkhome/metis/metis/download__;!!G2kpM7uM-TzIFchu!hspSl9riMkiTRcce0DyLXLDABrgvbkZ2G3w7hjE-60cmsTOB4FlII2iQ6zGowltRureR$>.

In any case, we can take a look at the new (?) version 5.1.1 of METIS and the main branch from the GitHub repo to see how we can support these.

**Comment by nourgaliev** [comment]
When configuring MFEM, you just need to specify where METIS is installed with the flag -DMETIS_DIR=/path/to/metis. MFEM will work with both 32bit and 64bit builds of METIS. At least it does with METIS v5.1.0 from the original website http://glaros.dtc.umn.edu/gkhome/metis/metis/download<https://urldefense.us/v3/__http:/glaros.dtc.umn.edu/gkhome/metis/metis/download__;!!G2kpM7uM-TzIFchu!hspSl9riMkiTRcce0DyLXLDABrgvbkZ2G3w7hjE-60cmsTOB4FlII2iQ6zGowltRureR$>.
BTW, the only way you could flip to 64 bit version of metis was to go manually edit their metis.h header file from

#define IDXTYPEWIDTH 32
#define REALTYPEWIDTH 32

to

#define IDXTYPEWIDTH 64
#define REALTYPEWIDTH 64

I suspect this is why they commented these out in their 5.1.1 version – to allow outside install script to control this, w/o editing their source (I think this is reasonable). What I suggested for your cmake system will do that.

Robert.

==========================================
Nourgaliev, Robert
Lawrence Livermore National Laboratory (LLNL)
P.O. Box 808, L-170, Livermore CA 94551
Email: ***@***.***
Phone: (925) 423-2905
Mobile: (805) 451-8825

From: Veselin Dobrev ***@***.***>
Reply-To: mfem/mfem ***@***.***>
Date: Tuesday, May 24, 2022 at 9:03 PM
To: mfem/mfem ***@***.***>
Cc: "Nourgaliev, Robert Nr" ***@***.***>, Mention ***@***.***>
Subject: Re: [mfem/mfem] parallel building METIS error (#698)


Hi @nourgaliev<https://urldefense.us/v3/__https:/github.com/nourgaliev__;!!G2kpM7uM-TzIFchu!hspSl9riMkiTRcce0DyLXLDABrgvbkZ2G3w7hjE-60cmsTOB4FlII2iQ6zGowui4GaHS$>,

I didn't even know METIS had GitHub repo (and I've searched for it before). It is also not mentioned on their original website.

Anyway, any METIS build options and configuration should be done by the METIS cmake files -- I don't understand why you modify MFEM's cmake files.

When configuring MFEM, you just need to specify where METIS is installed with the flag -DMETIS_DIR=/path/to/metis. MFEM will work with both 32bit and 64bit builds of METIS. At least it does with METIS v5.1.0 from the original website http://glaros.dtc.umn.edu/gkhome/metis/metis/download<https://urldefense.us/v3/__http:/glaros.dtc.umn.edu/gkhome/metis/metis/download__;!!G2kpM7uM-TzIFchu!hspSl9riMkiTRcce0DyLXLDABrgvbkZ2G3w7hjE-60cmsTOB4FlII2iQ6zGowltRureR$>.

In any case, we can take a look at the new (?) version 5.1.1 of METIS and the main branch from the GitHub repo to see how we can support these.

**Comment by nourgaliev** [comment]
BTW, I think currently PETSC will work with only 32-bit version, as they check for this in their configure script.

==========================================
Nourgaliev, Robert
Lawrence Livermore National Laboratory (LLNL)
P.O. Box 808, L-170, Livermore CA 94551
Email: ***@***.***
Phone: (925) 423-2905
Mobile: (805) 451-8825

From: "Nourgaliev, Robert Nr" ***@***.***>
Date: Wednesday, May 25, 2022 at 7:30 AM
To: mfem/mfem ***@***.***>, mfem/mfem ***@***.***>
Cc: Mention ***@***.***>
Subject: Re: [mfem/mfem] parallel building METIS error (#698)

Hi Veselin,

I did not know they had github either, until recently. Turns out they commented out in their latest version of metis.h

//#define IDXTYPEWIDTH 32
//#define REALTYPEWIDTH 32

So these are undefined. You could either manually uncomment it in their source, or define it in your cmake build system. I actually ended up doing both, as the same problem happen iwhen building PETSc with MeTiS. Their build system is more complex, so I could not figure out how to pass IDXTYPEWIDTH and REALTYPEWIDTH. In any case – up to you if want to use something like I suggested. This way – you could flip between 32/64 bits.

There are a few other problems with their repo, like they moved gklib out of MeTiS into separate repo, which caused problem for PETSC; and they have a couple of compilation bugs causing problems on some systems. I figured all these out, but not sure if this all worthwhile – as it does not look they update this repo actively, and if it has any major upgrade from PETSc’s repo which I was using previously. I chatted with Barry Smith about this – he did not sound enthusiastic to upgrade. I also reported these issues to MeTiS. For now, I would suggest simply replace the above commented out lines with something like:


//#define IDXTYPEWIDTH 32
#ifndef IDXTYPEWIDTH
#define IDXTYPEWIDTH 32
#endif // IDXTYPEWIDTH

//#define REALTYPEWIDTH 32
#ifndef REALTYPEWIDTH
#define REALTYPEWIDTH 32
#endif // REALTYPEWIDTH

in metis.h

and this will take care of the problem.

Robert.

==========================================
Nourgaliev, Robert
Lawrence Livermore National Laboratory (LLNL)
P.O. Box 808, L-170, Livermore CA 94551
Email: ***@***.***
Phone: (925) 423-2905
Mobile: (805) 451-8825

From: Veselin Dobrev ***@***.***>
Reply-To: mfem/mfem ***@***.***>
Date: Tuesday, May 24, 2022 at 9:03 PM
To: mfem/mfem ***@***.***>
Cc: "Nourgaliev, Robert Nr" ***@***.***>, Mention ***@***.***>
Subject: Re: [mfem/mfem] parallel building METIS error (#698)


Hi @nourgaliev<https://urldefense.us/v3/__https:/github.com/nourgaliev__;!!G2kpM7uM-TzIFchu!hspSl9riMkiTRcce0DyLXLDABrgvbkZ2G3w7hjE-60cmsTOB4FlII2iQ6zGowui4GaHS$>,

I didn't even know METIS had GitHub repo (and I've searched for it before). It is also not mentioned on their original website.

Anyway, any METIS build options and configuration should be done by the METIS cmake files -- I don't understand why you modify MFEM's cmake files.

When configuring MFEM, you just need to specify where METIS is installed with the flag -DMETIS_DIR=/path/to/metis. MFEM will work with both 32bit and 64bit builds of METIS. At least it does with METIS v5.1.0 from the original website http://glaros.dtc.umn.edu/gkhome/metis/metis/download<https://urldefense.us/v3/__http:/glaros.dtc.umn.edu/gkhome/metis/metis/download__;!!G2kpM7uM-TzIFchu!hspSl9riMkiTRcce0DyLXLDABrgvbkZ2G3w7hjE-60cmsTOB4FlII2iQ6zGowltRureR$>.

In any case, we can take a look at the new (?) version 5.1.1 of METIS and the main branch from the GitHub repo to see how we can support these.

**Comment by v-dobrev** [comment]
Okay, I see what they did. That is not a good solution. Setting these parameters really needs to be part of their configuration step. Users should not need to set these manually after METIS is configured, built, and installed.

**Comment by nourgaliev** [comment]
Agree. They should have configuration flag to set 32 or 64 bit version, when you build their library, if they don't want anyone editing their source code. Now we have to dance around to make this working...

**Comment by jiapei-nexera** [comment]
> Okay, I see what they did. That is not a good solution. Setting these parameters really needs to be part of their configuration step. Users should not need to set these manually after METIS is configured, built, and installed.

Therefore, you are suggesting: it's better to build metis with other packages, as a submodule, rather than build metis independently ??

**Comment by tzanio** [comment]
For now we recommend using MFEM's mirror of METIS, see #3196 and https://mfem.org/building/#parallel-mpi-version-of-mfem
