### ISSUE TITLE
Behaviour of BlockOperator when blocks are not set explicitly

### ISSUE THREAD

**Issue by enjoh** [mfem/mfem#704]
I have a question about the BlockOperator class.
In the header file it says  'If a block is not set, it is assumed to be a zero block' and my understanding of this sentence would be that said block is set to all zeros , but it seems that when a block is not set explicitly, it is just NULL.
Is this a bug or a wrong understanding of the description?

Thanks in advance!

**Comment by mlstowell** [comment]
Hi, @enjoh ,

We generally think in terms of sparse operators which only store data for non-zero entries.  Therefore, if an entire block is zero there's no reason to explicitly set its entries to zero because those entries simply don't exist in the sparsity pattern.  When the block operator is applied, either via `Mult` or `MultTranspose`, any NULL blocks are skipped which has the same effect as multiplying by zero but is much more efficient.

I suppose a more accurate comment would be "Any blocks which are not explicitly set are treated as being equal to zero when the block operator is applied."

Best wishes,
Mark

**Comment by enjoh** [comment]
Hello Mar,

thanks a lot for your answer, this makes sense.

Regards,
Johannes
