### ISSUE TITLE
DiagonalPolicy in ParBilinearForm

### ISSUE THREAD

**Issue by barker29** [mfem/mfem#737]
I want to assemble a parallel matrix using the diagonal policy `Matrix::DIAG_ZERO`. All of the parallel elimination routines (`ParBilinearForm::FormLinearSystem`, `ParallelEliminateEssentialBC`, `ParallelAssembleElim`, etc.) implicitly use the policy `Matrix::DIAG_ONE` (regardless of what policy is actually set in the bilinear form).

Following #181, you can `EliminateEssentialBC` in the local matrix, and then call `ParallelAssemble`, but this only works for the policy `DIAG_KEEP`. I have not found a way to correctly assemble the parallel matrix using the `DIAG_ZERO` policy.

Below is an example demonstrating this issue. The hard coded `policy` and `serial_elimination` variables let you choose six possibilities, and it prints the diagonal.

```c++
int main(int argc, char * argv[])
{
   const Matrix::DiagonalPolicy policy = Matrix::DIAG_ZERO;
   const bool serial_elimination = true;

   MPI_Init(&argc, &argv);
   int rank, size;
   MPI_Comm_rank(MPI_COMM_WORLD, &rank);
   MPI_Comm_size(MPI_COMM_WORLD, &size);

   Mesh * mesh = new Mesh(2, 2, Element::QUADRILATERAL, 1);
   ParMesh pmesh(MPI_COMM_WORLD, *mesh);
   delete mesh;

   H1_FECollection fec(1, 2);
   ParFiniteElementSpace fespace_lor(&pmesh, &fec);
   ParBilinearForm a_form(&fespace_lor);

   Array<int> ess_bdr(pmesh.bdr_attributes.Max());
   ess_bdr = 1;
   Array<int> ess_tdof_list;
   fespace_lor.GetEssentialTrueDofs(ess_bdr, ess_tdof_list);

   a_form.SetDiagonalPolicy(policy);
   a_form.AddDomainIntegrator(new DiffusionIntegrator);

   HypreParMatrix * hmatrix;
   a_form.Assemble();
   if (serial_elimination)
   {
      a_form.EliminateVDofs(ess_tdof_list, policy);
      a_form.Finalize();
      hmatrix = a_form.ParallelAssemble();
   }
   else
   {
      Vector X, B;
      Vector x(fespace_lor.GetVSize()), b(fespace_lor.GetVSize());
      hmatrix = new HypreParMatrix;
      a_form.FormLinearSystem(ess_tdof_list, x, b, *hmatrix, X, B);
   }

   Vector diag;
   hmatrix->GetDiag(diag);
   for (int i = 0; i < size; ++i)
   {
      if (rank == i)
         diag.Print(std::cout, 1);
      MPI_Barrier(MPI_COMM_WORLD);
   }   
   delete hmatrix;
   MPI_Finalize();
}
```

Example output (serial output is correct, parallel output is not):

```
[barker29@tux411:element-tensor(master)]$ ./issue
0
0
0
0
2.66667
0
0
0
0
[barker29@tux411:element-tensor(master)]$ mpirun -np 2 ./issue
2
0.666667
2.66667
0.666667
0
0
0
0
0
0
[barker29@tux411:element-tensor(master)]$
```

**Comment by v-dobrev** [comment]
You are right: the diagonal policy is completely ignored right now in `ParBilinearForm::FormLinearSystem()` and `ParBilinearForm::FormSystemMatrix()` (the former simply calls the latter).

In the `serial_elimination == true` case, I think the `HypreParMatrix` is correct. I did not test this but I think you get the wrong output because the matrix has empty rows and `HypreParMatrix::GetDiag(Vector &)` returns the wrong values - it assumes that the first entry in each row is the diagonal one (which should be true if the row is not empty). The empty rows are due to `a_form.Finalize()` using the default value of its optional parameter `skip_zeros == 1`. If you call `a_form.Finalize(1)`, you should get the correct output but that is just a workaround for the test code. The right solution is to fix `HypreParMatrix::GetDiag(Vector &)` to support the case of empty rows.

**Comment by barker29** [comment]
I get the same output with `a_form.Finalize(1)`. As an additional check, I've dumped the matrices with `hmatrix->Print()` and the diagonals reported above are the actual diagonals of the `HypreParMatrix`.

**Comment by v-dobrev** [comment]
Can you try building mfem with debug enabled? Just to see if any asserts will trigger.

**Comment by barker29** [comment]
Yes, the results above are all from a debug build. No asserts were triggered.

**Comment by v-dobrev** [comment]
Okay, I'll need to debug it then to see what is going wrong. I'll let you know when I figure it out.

**Comment by v-dobrev** [comment]
@barker29, the issue is that `a_form.EliminateVDofs()` expects a list of "vdofs" and you are giving it a list of "tdofs". Essentially, on more than 1 processors, `ess_tdof_list` should only be used when `serial_elimination == false`.

Anyway, the simplest solution is to call `a_form.EliminateEssentialBC(ess_bdr, policy)` instead of `a_form.EliminateVDofs(ess_tdof_list, policy)`.

**Comment by barker29** [comment]
Thanks @v-dobrev , that fixes it.
