### ISSUE TITLE
Assembling a different operator on RT_TriangleElement

### ISSUE THREAD

**Issue by pratyuksh** [mfem/mfem#769]
Hello,
I am working with Raviart-Thomas spaces, RT_Element. Given a ParGridFunction _**g**_, I want to assemble the following:
A = \int_{\Omega} (_**g**_ \cdot \grad{ **u** } ) \cdot **v** dx.

The new component here is the matrix \grad { **u** }, which I think I will need to write.
But while looking at the _CalcVShape_ and _CalcDivShape_, I did not understand clearly what the role of matrix _T_ or _Ti_ is. A brief explanation about these routines or other tips about assembling the above expression will be very helpful. Thanks.

**Comment by mlstowell** [comment]
Hello, @pratyuksh ,

Unfortunately, \grad{u} cannot easily be computed in RT spaces.  The trouble is not T or Ti but rather that the gradient will depend on derivatives of the Jacobian.  Typically if \grad{u} is required for a vector field u then you must have u in a vector-valued H1 space (as in example 2).

Best wishes,
Mark

**Comment by pratyuksh** [comment]
@mlstowell can you please share a good reference about this issue and RT spaces in general? It is unclear to me how the derivatives of the Jacobian enter the computation. Thanks a lot.

**Comment by mlstowell** [comment]
Hi, @pratyuksh ,
The reference I use for RT spaces is Nedelec's 1986 paper titled "A New Family of Mixed Finite Elements in R^3".  Unfortunately, it's a difficult read and I'm not sure it even explains this issue.

The issue stems from how vector fields behave under coordinate transformations.  We can only take derivatives of our basis functions in a reference coordinate system.  However, what we need is derivatives in the physical coordinate system where our reference elements appear distorted.  To perform these transformations we rely on specific transformation properties of the various spaces of basis functions.  These properties ensure that we can transform the derivatives using only the Jacobian (or its inverse, its determinant, etc.) but not its derivatives.

The Wikipedia page  https://en.wikipedia.org/wiki/Euclidean_vector#Vectors,_pseudovectors,_and_transformations discusses this a little.  Our ND spaces (also called H(Curl) spaces) are contra variant vector fields, the RT spaces (also called H(Div) spaces) are pseudovector fields.  Because these vector fields have a very different nature they transform differently and this also impacts how their derivatives transform.  The vector-valued H1 space that I recommended is yet another thing which doesn't transform at all.  This would be a simple triple of scalar fields like the length, width, and height of a rectangular box that is mentioned on this wikipedia page.

Best wishes,
Mark

**Comment by pratyuksh** [comment]
@mlstowell Thank you for the explanation. I also looked up some other references, and have deduced the following:
Given the affine transformation T : \hat{K}  -> K,  T(\hat{x}) = B \hat{x} + b, where B is invertible.
Then, from the inverse Piola transformation for the Raviart-Thomas spaces, we have
\phi = |det(B)|^{-1} B \hat{ \phi } ( T^{-1}(\hat{x}) )

So, we compute the derivatives (after some simplifications):
\grad { \phi } =  |det(B)|^{-1} B \hat{\grad} { \hat{\phi} } B^{-1}.

If there is no error in the computation above, it should not be too difficult to implement this or am I missing something here?

**Comment by aasivas** [comment]
Hi @pratyuksh ,

A while ago I was working on something similar and I asked the following question

https://github.com/mfem/mfem/issues/566

Veselin's answer there is awesome and it helped me understand the idea very well. Then I started implementing the function I needed here

https://github.com/mfem/mfem/tree/mfem-rt

However, there is a bug somewhere I can not find and my research took a different direction so I have not worked on it for a while. But it might be helpful to you take a look at the function CalcJShape which calculates the Jacobian of a given vector test functions which is exactly what you need.

@mlstowell I needed the \grad{u} term for the Stokes equations, since RT fespace is H(div) conforming and possibly RT solutions are pressure-robust. So it might actually be useful to many people. 

Whenever, I am done with my current work, I will take another look at it to find the bug. But I am pretty sure it is not in the function CalcJShape.

**Comment by pratyuksh** [comment]
Hello @aasivas Thank you for the reference to the pointing out the previous question, it has been very helpful in trying to understand how RT basis is computed in mfem.

In case it still helps you, the bug in your implementation is during assembly, you are not using the Piola transformations.

**Comment by aasivas** [comment]
Oh my, that is embarrassing. I thought I did. Is it only `VectorFEDiffusionIntegrator` or also in `VectorFEDGDiffusionIntegrator`?

**Comment by pratyuksh** [comment]
I noticed it for VectorFEDiffusionIntegrator, did not check the other one.

**Comment by aasivas** [comment]
Awesome. Thanks for letting me know. I will try to find some time and fix it.

**Comment by vikramsg** [comment]
Hi @pratyuksh,

I would be very interested in the operator that you refer to in the original post. Have you implemented it. If so, can I have a look at it?

**Comment by pratyuksh** [comment]
Hi @vikramsg 

Sorry for the very late reply. I have implemented the operator. If you still need it, let me know. I will put together the functions needed for it and post it here.

**Comment by issabass** [comment]
Hi there!
Dear @pratyuksh, I second vikramsg's request... 
I do need that operator ($A = \int_{\Omega} (g \cdot \grad{ u } ) \cdot v dx.$) being implemented.
Thank you,
zaq

**Comment by pratyuksh** [comment]
Hello,

I have attached the files you would need to assemble this operator. Brief info:

1) You would need to use CalcGradVShape routine in the fe.hpp/.cpp, add it from my files to your mfem library.

2) The routines for assembling the convection tri-linear form is in assembly.hpp/.cpp

Best,
Pratyuksh

[mfem_convection.zip](https://github.com/mfem/mfem/files/4213226/mfem_convection.zip)

**Comment by tzanio** [comment]
Thank you @pratyuksh.
