### ISSUE TITLE
MFEM features

### ISSUE THREAD

**Issue by gabrielerovi** [mfem/mfem#789]
Dear all,

I am totally new to MFEM and, before I start using it, it would be nice to know if some features are actually available. 

1) I am solving a least-square problem, thus a mixed problem of the form:
                                                      A        B^T
                                                      B^T    C
which I call (-), and I want to do a geometric multigrain on this. I wonder if this is actually the structure of the matrix or if we can rearrange it, based on the mesh topology, to make it sparser and obtain what I can call <->. 

2) Are parallel interpolation operators between nested mesh (uniform refinement) available? If so, do we have them for both (-) and <-> or just for one of the two?

3) For a smoother a I want to implement, I need to know which are the face-degrees of freedom related to a given vertex. On the internal boundaries of a distributed mesh, this means knowing also the face-dofs of other processors. Even nicer would be knowing the ghost-elements.
Are such a functionalities implemented?

4) Can we save .vtk files for viewing the result in Paraview?

5) Is parallel vertex-colouring of the mesh implemented?

Thank you for you time.

Best regards,

Gabriele Rovi

**Comment by tzanio** [comment]
Hi Gabriele,

Here are some answers to your questions:

>  I wonder if this is actually the structure of the matrix or if we can rearrange it, based on the mesh topology, to make it sparser and obtain what I can call <->.

Most likely, what you want to assemble is A, B and C separately and apply their actions to form the action of the 2x2 block operator. You can reorder these sparse matrices, but we don't usually do that.

> Are parallel interpolation operators between nested mesh (uniform refinement) available?

Yes, for each of the row/columns of A and B.

> For a smoother a I want to implement, I need to know which are the face-degrees of freedom related to a given vertex. On the internal boundaries of a distributed mesh, this means knowing also the face-dofs of other processors. Even nicer would be knowing the ghost-elements. Are such a functionalities implemented?

The face-neighbor element ghost layer is available when using DG discretizations. With some creativity, the vertex-to-face table can also be obtained. That being said, we have many smoother options via *hypre*, and you may consider using one of them instead of implementing your own. 

> Can we save .vtk files for viewing the result in Paraview?

Yes, see #797. You can also visualize in VisIt, or MFEM's own [GLVIs](https://glvis.org/).

> Is parallel vertex-colouring of the mesh implemented?

There are no parallel coloring algorithms in MFEM. Obtaining the parallel vertex-to-vertex and similar tables is easy though.

**Comment by tzanio** [comment]
I am closing this now, but please let us know if you have any further questions.

**Comment by gabrielerovi** [comment]
Ok, thank you Tzanio.

________________________________
Da: Tzanio Kolev <notifications@github.com>
Inviato: mercoledì 10 aprile 2019 09:05:01
A: mfem/mfem
Cc: Rovi Gabriele; Author
Oggetto: Re: [mfem/mfem] MFEM features (#789)


I am closing this now, but please let us know if you have any further questions.
