### ISSUE TITLE
Question: Linker error

### ISSUE THREAD

**Issue by carlos-pereyra** [mfem/mfem#835]
On mac, I've set my PATH environment variables to the directory where I've built mfem.
`/Users/Revolver/Install/mfem/mfem-3.4`

I've copied example 1 into a new directory. Yet when I try 
`g++ -o ex1.cpp -o ex1`

`clang: error: no input files`

I've also added the 'data' directory for the mesh settings.

However,
`g++  -O3 -I /Users/Revolver/Install/mfem/mfem-3.4  ex1.cpp -o expoop -L /Users/Revolver/Install/mfem/mfem-3.4 -l mfem`

works for me. I am new to linux and confused about why I need to use -I and -L even after I've set my PATH variable to where I built mfem. Thanks.

**Comment by tzanio** [comment]
Hi @carlos-pereyra,

It should be `g++ ex1.cpp -o ex1` not `g++ -o ex1.cpp -o ex1`.

You need to provide the include and library path, because the compiler does not use your `PATH` variable for that. These could be relative, e.g.

```
g++ -O3 -I ../mfem-3.4 ex1.cpp -o expoop -L ../mfem-3.4 -l mfem
```

Hope this helps,
Tzanio

**Comment by carlos-pereyra** [comment]
Is there a way to set a environment variable so the compiler doesn't always need -I and -L specified? 

Additionally, when I try to `make install ~/Install/mfem/glvis-3.4` while in the GLVIS directory (in the same directory as mfem-3.4) the following error occurs: `makefile:192: *** The MFEM library is not built.  Stop.`

I figured I wouldn't have to go through the process of building once I invoke `make serial -j` while in the mfem directory. Thanks. Sorry for the confusion.

**Comment by mlstowell** [comment]
Hello, @carlos-pereyra ,

In Linux (and other Unix variants) the `PATH` variable is used to search for executable programs.  For example when you type `g++ ex1.cpp -o ex1` the operating system locates `g++` by searching through the directories in your `PATH` variable and other standard locations.

A similar variable for locating library files is `LD_LIBRARY_PATH` and for include files its `CPATH`, `C_INCLUDE_PATH`, or `CPLUS_INCLUDE_PATH`.  The include file paths are rarely used and might lead to problems.  Two potential issues would be slowing down the build process and locating incorrect files that happen to have the same filename.  Use these with caution.

The error that you mention regarding the MFEM library not being built usually comes up when the GLVis build system cannot find `libmfem.a`.  By default GLVis expects this file to be found in `../mfem`.  If you're using the directory name `mfem-3.4` rather than `mfem` that may be the problem.  First verify that `libmfem.a` was built and then we can figure out why GLVis cannot find it.

As a side note, since you're not very comfortable with linux it might be best to build MFEM and GLVis using the instructions in the INSTALL files and avoid moving files to nonstandard locations at least initially.

Best wishes,
Mark
