### ISSUE TITLE
Printing (x, y, z, solution) for AMR ParMesh

### ISSUE THREAD

**Issue by jwp3** [mfem/mfem#861]
I am solving the 3D Laplace equation in a cube using hexahedral elements.  Zero Dirichlet B.C.s are imposed on one wall, and Neumann on all other walls.  When I run the code in serial with no AMR, I am able to use the code #104 to print (x,y,z,solution) correctly, but when using AMR and/or more than one MPI process, the solution is printed incorrectly.   Is there a "standard" way to print the (x, y, z, solution) quadruple after exiting the AMR loop and/or when using more than one MPI process?  Does METIS and the AMR  process reorder the nodes in a way that using the code in #104 is no longer viable?

Edit: my code is adapted from ex6p.cpp and I am using the MFEM 3.4.

Thank you in advance for the help!

**Comment by mlstowell** [comment]
Hi, @jwp3 ,
The code you refer to is not written to support parallel simulations so it would require some modifications.  It should be possible to make this work (without AMR).  What type of incorrect output do you see?  I don't know the AMR code as well as I should but I believe the same scheme should be able to output the vertex coordinates correctly.

The solution data is another matter, particularly when using AMR.  The trouble is that the solution data is probably not stored in the same manner as the vertex data.  A more standard method is to loop over the elements rather than the vertices.  This is a finite element code after all so it's more natural to think in terms of elements.  The idea is to loop over the elements and call `ParGridFunction::GetValue()` at multiple locations within each element to collect the solution data you need.  This call uses an `IntegrationPoint` object which specifies the location in terms of a local coordinate system.  To get the vertex coordinates in this scheme you need to use `Element::GetVertices()` to get the vertex indices and then call `Mesh::GetVertex()` for each vertex connected to this element.  The trick is to relate the sequence of vertices to the correct `IntegrationPoints` within the element.  This is done by knowing the numbering convention used for each element type.  I believe hexahedra use a tensor product ordering scheme but I cannot seem to find where we describe this.

I'd be happy to offer more specific advice but first I want to make sure this strategy will be useful to you.

Best wishes,
Mark

**Comment by jwp3** [comment]
Hi Mark,

Yes, I think this strategy is what I am looking for.  To start us off, here is a simple loop over the elements.  What's missing is a call to `ParGridFunction::GetValue()`, which I am a bit confused by.

```C++
int NE = pmesh->GetNE(); /* get number of elements */
for (int i = 0; i < NE; i++){ /* loop over elements */
   Element *e = pmesh->GetElement(i); /* get element i */
   int *v = e->GetVertices(); /* get list of vertices */
   int nv = e->GetNVertices(); /* get number of vertices */
   for (int j = 0; j < nv; j++){ /* loop over vertices for element i */
      double *coords = pmesh->GetVertex(v[j]); /* get global coordinates of vertex j of element i */
      /* TODO: get solution value at this vertex using ParGridFunction::GetValue()*/
   }
}
```

**Comment by mlstowell** [comment]
Hi, @jwp3 ,
That's an excellent start.  Inside the vertex loop you need to call `ParGridFunction::GetValue` like this:
```
double val = sol->GetValue(i, ip[j]);
```
Where `ip` is a your favorite container filled with `IntegrationPoint` objects.  Unless I'm mistaken the ordering you want for hexahedra could be achieved like this:
```
ip[0].Set3(0,0,0);
ip[1].Set3(1,0,0);
ip[2].Set3(1,1,0);
ip[3].Set3(0,1,0);
ip[4].Set3(0,0,1);
ip[5].Set3(1,0,1);
ip[6].Set3(1,1,1);
ip[7].Set3(0,1,1);
```
We may have a routine somewhere that could set these for arbitrary element types (or at least we should) but I cannot remember where that might be.

Best wishes,
Mark

**Comment by jwp3** [comment]
Hi Mark,

Everything works now, both in parallel and/or when using AMR!  For those who are interested, here is the complete code.

```C++
int NE = pmesh->GetNE(); /* get number of elements */
for (int i = 0; i < NE; i++){ /* loop over elements */
   Element *e = pmesh->GetElement(i); /* get element i */
   int *v = e->GetVertices(); /* get list of vertices */
   int nv = e->GetNVertices(); /* get number of vertices */
   Array<IntegrationPoint> ip(8); /* set integration points in local coordinates */
   ip[0].Set3(0,0,0);
   ip[1].Set3(1,0,0);
   ip[2].Set3(1,1,0);
   ip[3].Set3(0,1,0);
   ip[4].Set3(0,0,1);
   ip[5].Set3(1,0,1);
   ip[6].Set3(1,1,1);
   ip[7].Set3(0,1,1);
   for (int j = 0; j < nv; j++){ /* loop over vertices for element i */
      double *coords = pmesh->GetVertex(v[j]); /* get global coordinates of vertex j of element i */
      double val = x.GetValue(i, ip[j]);  /* get solution at vertex */
      printf("%e %e %e %e\n", coords[0], coords[1], coords[2], val); /* print x,y,z,solution */
   }
}
```

Note that `x` is of type `ParGridFunction`, and `pmesh` is of type `ParMesh`.

Thank you @mlstowell for the speedy replies and great instructions!

**Comment by v-dobrev** [comment]
In general, the vertices for any reference element type can be obtained with:
```c++
   const IntegrationRule &ir = *Geometries.GetVertices(e->GetGeometryType());
```
This variable can then be used inside the vertex loop like this:
```c++
   double val = x.GetValue(i, ir.IntPoint(j));
```
In some cases (e.g. when using a high-order curvilinear mesh) the coordinates returned by `pmesh->GetVertex(v[j])` may be incorrect. In that case you can compute the vertex coordinates and the values with a single call per element:
```c++
   // Define outside the element loop:
   Vector vert_vals;
   DenseMatrix vert_coords;
   // ...
   // Inside the element loop use:
   x.GetValues(i, ir, vert_vals, vert_coords);
   // the vertex values are: vert_vals(j), 0 <= j < nv
   // the vertex coordinates are: vert_coords(i,j), 0 <= i < dim, 0 <= j < nv,
   // where dim = vert_coords.Height() is the mesh dimension (= pmesh->Dimension())
```
