### ISSUE TITLE
absorbing boundary for electromagnetic scattering problem: BoundaryIntegrator query

### ISSUE THREAD

**Issue by tomathew** [mfem/mfem#869]
Hello, I am trying an electromagnetic scattering problem (in complex alg and time harmonic) using Nedelec finite elements. I use first-order absorbing boundary conditions for truncation, which in the weak form turns to be like: (n x V, n x E) on the boundary. V , E are the test and trial functions respectively, and n the normal vector. Are there any examples where this has been dealt before ?
Or can anyone suggest me with how to implement this in MFEM.
Thanks in advance

**Comment by mlstowell** [comment]
Hi, @tomathew ,
I don't think we have an example of this in the master branch of MFEM yet but we have been working on this.  Have a look at [hertz_solver](https://github.com/mfem/mfem/blob/1770b6c63693a3414b0551030e64b1b5178dde9b/miniapps/electromagnetics/hertz_solver.cpp#L212) in the `hertz-dev` branch.  It's surprisingly simple.  You just need to add a mass matrix, with an appropriate coefficient, to the imaginary part of your system matrix.

Best wishes,
Mark

**Comment by tomathew** [comment]
Thank you very much. I should say with regrets, that I am new to this platform (in fact I came across this website yesterday). I am really flattered by the fact that you have seamless Hypre integration, (especially the AMS). I can see from your last reply (thanks !) the impedance matching type applied to the 'transient' case, but as I said I am working with the time-harmonic form, where the weak form (shown in complex alg, but I will be working with 2x2 block real form) here.
![varf](https://user-images.githubusercontent.com/22793567/56342552-96007580-61b8-11e9-908a-ef4e1296fa14.png)
As you can see, there is a bilinear contribution from (n x V, n x E) on the boundary \Gamma. As similar to CurlCurlIntegrator which takes care of (\nabla x V, \nabla x E) in mfem, I was looking for the former's equivalent one (with unit normal boundary vector). Do I need to make a new integrator for this ?
Thanks again,very much looking forward to try this platform
Best

**Comment by mlstowell** [comment]
Hi, @tomathew ,
Our transient solver is called `maxwell` but I was in fact referring to our time-harmonic solver named `hertz`.   The time-harmonic solver should be available at the link I sent.  If that's not working the answer is simple enough.  The bilinear form (n x V, n x E)_Gamma is equivalent to (V, E)_Gamma because Nedelec basis functions which are not tangent to the boundary integrate to zero on the boundary by construction.  Consequently we can use a `VectorFEMassIntegrator` to integrate this term on the boundary by adding it to the `BilinearForm` like this:
```
ParBilinearForm ai(fes); \\ bilinear form for the imaginary portion of the operator
ai.AddBoundaryIntegrator(new VectorFEMassIntegrator(impedCoef));
``` 
Adding this integrator as a "boundary" integrator rather than a "domain" integrator essentially plays the same role as using "n x" in each slot of the bilinear form.

Best wishes,
Mark

**Comment by tomathew** [comment]
Thank you very much. Sorry, my bad to think of hertz in time domain (out of bed :), and I was also looking for ABC in your examples/miniapp/electromagnetics page, and got carried away). So, the basis functions takes care of everything, nice !. Now, this is clear ! ( the current platform I am working doesn't have these robust Nedelec basis meanings at boundary). Thank you very much ! Looks like I'll be back with another query soon !
