### ISSUE TITLE
Operators change size after FormSystemMatrix

### ISSUE THREAD

**Issue by tangqi** [mfem/mfem#888]
I have been trying to parallelize my code. The good news is my code works for np=1. But it has a minor issue for np>1. For an operator appear at both sides of a system, for instance, the mass matrix, it gives me some troubles. Here is what I found:
```c++
   M = new ParBilinearForm(&fespace);
   M->AddDomainIntegrator(new MassIntegrator);
   M->Assemble();
   M->FormSystemMatrix(ess_tdof_list, Mmat);
```
In parallel, `M->FormSystemMatrix(ess_tdof_list, Mmat)` will destroy `M->mat`, so there is no operator of size `fespace.GetVSize()`. However, based on the discussion with @mlstowell in https://github.com/mfem/mfem/issues/818, he seems to think there is an operator of correct size in `M`. But I cannot find it. 

In serial, `M->FormSystemMatrix(ess_tdof_list, Mmat)` will not destroy `M->mat`. But I believe the size of the operator will change.

I can probably still get away with defining another mass matrix and never call `FormSystemMatrix`. Maybe that is always the right way to implement?

**Comment by mlstowell** [comment]
Hi, @tangqi ,
During our last discussion I made a couple small changes to `ex6` and `ex6p` so that I could see the sizes of the `BilinearForm` and `ParBilinearForm` objects before and after calls to `FormLinearSystem`.  If I remember correctly I saw that `BilinearForm` objects change size but `ParBilinearForm` objects do not.  This is an unfortunate inconsistency and I don't see any mention of a size change in the documentation of the relevant methods.  It sounds like you've found that `BilinearForm::Mult` and `ParBilinearForm::Mult` stop working after calls to `FormSystemMatrix` or presumably `FormLinearSystem`.  This sounds like a problem to me.  I think we need to hear from @v-dobrev and/or @jakubcerveny about the intended behavior of these methods.  Using the same bilinear form operator with a solver and to build a RHS is a bit unusual so perhaps its just a simple oversight.

Best wishes,
Mark

**Comment by tzanio** [comment]
Hi @tangqi,

In general `M` and `Mmat` indeed have different sizes.

The bilinear form `M` is a *finite element* object of the size of the finite element space. There is some locality / duplication though -- e.g. on each MPI task we have a self-contained mesh and function and with AMR the degrees of freedom on each element are well-defined. 

The matrix `Mmat` is a *linear algebra* object of the size of the linear system you actually solve for. All parallel and/or AMR duplicate dofs have been eliminated from it, and in fact there could be additional modifications when using static condensation or hybridization.

In serial, without AMR, the two objects are the same so we just reuse `M->mat` for `Mmat`. In all other cases though, `M->mat` is decoupled and the true `Mmat` is smaller.

Most likely you want to use `Mmat` on both sides of the equations. See e.g. Example 16.

What is the problem with doing that? 

Tzanio

**Comment by tangqi** [comment]
@tzanio 
> In serial, without AMR, the two objects are the same so we just reuse M->mat for Mmat. 

Yes, that is how I implemented in serial. 

>In all other cases though, M->mat is decoupled and the true Mmat is smaller.

In parallel, I found after calling `FormSystemMatrix`, `M->mat` is destroyed. I think I can see @mlstowell 's point that `M->mat` is typically not needed after the matrix is formed.


>Most likely you want to use Mmat on both sides of the equations. See e.g. Example 16. What is the problem with doing that?

I started by following example 16. But for AMR, it gave me some problems when I define my block operator by `TimeDependentOperator(4*f.GetTrueVSize(), 0.0)`. So I follow amr/laghos.cpp and defined my operator by `TimeDependentOperator(4*f.GetVSize(), 0.0)`. @mlstowell also suggested me to work with RHS of size `f.GetVSize()`. However, I only have `Mmat` in RHS when I want to apply it to a vector of size `f.GetVSize()`.

As suggested by @mlstowell , I got around by keeping another mass matrix operator. It works well for both AMR and parallel. I asked for my own understanding. I think I understand what happened now, thanks to all your suggestions.

Thanks again for all your help!
Qi
