### ISSUE TITLE
Rebalance with AMR

### ISSUE THREAD

**Issue by tangqi** [mfem/mfem#897]
Hi, I got some strange reblanced partitioning results in dynamic AMR. Here are some pictures.

It looks okay initially.  
![grid0](https://user-images.githubusercontent.com/1406660/57188548-f8968880-6ebd-11e9-804c-e50e6eeb49e5.png)

Then the grid is changed slightly on the fly. 
![grid0p1](https://user-images.githubusercontent.com/1406660/57188558-0fd57600-6ebe-11e9-818b-2acba1a78388.png)

But its rebalanced partitioning looks funny:
![partition0p1](https://user-images.githubusercontent.com/1406660/57188575-372c4300-6ebe-11e9-878a-d0552e61e802.png)
For instance
![onePart](https://user-images.githubusercontent.com/1406660/57188576-385d7000-6ebe-11e9-9543-8c45dfd59517.png)

However, even with the strange partitioning, the code seems to be okay and produce solutions consistent with my serial AMR code.

My code looks like this:
```c++
     //---Update fespace and interpolation---
     AMRUpdate(vx, vx_old, fe_offset, phi, psi, w, j);

     pmesh->Rebalance();

     //---Update fespace and interpolation---
     AMRUpdate(vx, vx_old, fe_offset, phi, psi, w, j);
     //Update time dependent operator and update/assemble bilinear forms
     oper.UpdateProblem();
```
Let me know what I am missing.

Thanks,
Qi

**Comment by jakubcerveny** [comment]
Hi @tangqi, I'm not sure what exactly you are referring to, but here are two comments:

1. The funny "hook"-shaped protrusions are an artifact of the Hilbert space-filling curve partitioning algorithm and cannot be easily avoided.

2. The partitions are not continuous. This happens when the initial (coarse) mesh is not ordered along a space-filling curve. To avoid disconnected partitions, the elements of the coarse mesh should be ordered as a sequence of face-neighbors (you also need a recent (master) version of MFEM). In your case the coarse mesh could also be just a single quad, which would also make the partitions continuous.

Hope that helps,
Jakub

**Comment by tangqi** [comment]
Hi @jakubcerveny, thanks for your very helpful comments. Indeed, I was wrongly expecting a continuous partitioning, which was observed in my code on uniform meshes. Since this is expected, I am less worried. The parallel AMR code is very robust with those discontinuous partitions. Thanks again for your impressive work. --Qi
