### ISSUE TITLE
Implementation of collocation-like scheme in sbp-dev

### ISSUE THREAD

**Issue by jehicken** [mfem/mfem#900]
Hi,

We are implementing a discretization that uses collocation, specifically summation-by-parts operators.  Before we invest too much time, we wanted to get your opinion on the possible software design for these collocation elements in MFEM.

**Design Motivation:** The collocation operators are `NodalFiniteElement`s that store the values of the shape function derivative as an array, because the elements do not, in general, have an explicit basis.  When calling `el.CalcDShape(ip, dshape)`, we would like to access rows in the derivative array using the nodal index.  However, the information passed to `CalcDShape` does not know about the nodal index.

We have two possible solutions:
1. Store an integer index in `IntegrationPoint`.  This is easy to implement, but it means there is an integer member in the `IntegrationPoint` class that is unnecessary for most element types.
2. Create an `unordered_map<IntegrationPoint*, int>` that maps `IntegrationPoint` addresses to an index.  We can store this `unordered_map` inside our collocation element class.

Thanks in advance for your thoughts.

**Comment by jehicken** [comment]
@tuckerbabcock did some benchmark tests, and we did not see a significant difference in time between the two choices.  (although, the number of nodes in 2d up to degree p=4 was perhaps too small to begin to see differences).  For now we are going with the `unordered_map` approach, since it avoids changes to `IntegrationPoint`.  Please let us know if you want us to do it differently.

I will leave the issue open for you guys to close at your discretion.

**Comment by tzanio** [comment]
Sorry for the delayed response @jehicken and @tuckerbabcock . We are in the final stretch of the next major release of the library, and should have more time for the design discussion next week, after mfem-4.0 comes out.

If I understand correctly you want to define a space where the basis functions and their derivatives are known only at the degrees of freedom, and then use this space in regular integrators?

If that's the case, then the approach above is OK for now, but longer term it could be improved as follows: 

1. You check that the integration rule used in an integrator and the space are compatible and directly return the array of values/derivatives in all degrees of freedom, we call this dof-to-quad-point matrix `B`, see https://codedocs.xyz/CEED/libCEED/md_doc_libCEEDapi.html. 

2. If `D` is the (block-)diagonal matrix of coefficient values and element Jacobian metric terms in the quadrature points, you can assemble the local element matrix (or apply its action) with `B^T D B` instead of the loop in current integrators. 

3. The `B` formulation is preferable from GPU perspective (as well as from the perspective of computing the finite element operator Jacobian).

Cheers,
Tzanio

**Comment by jehicken** [comment]
Thanks @tzanio.  No rush reading/answering the following.

Yes, your interpretation is correct, but just to clarify: we want to define a space where the basis functions and their derivatives are known only at the nodal degrees of freedom, _and the nodes correspond to quadrature points_ (the quadrature rules we need may or may not be available as existing `IntegrationRules`, but that is a separate issue).

I think I understand your suggestion.  This would require us to add new code to every existing `Assemble*` that we might want to use, is that correct?

**Comment by ataber** [comment]
My team is also in need of some quadrature point indexing scheme, but for a different use. We have a `FunctionCoefficient` that involves looking up pre-computed values at quadrature points. Since the only data we get during the invocation of the `Eval` function is the vector position of the quadrature point, we would have to do some extra geometric lookup to find the corresponding value. It would make it much simpler to just have access to a linear index into the pre-computed data.

**Comment by v-dobrev** [comment]
One possible solution will be to add a local index into the `IntegrationPoint` class -- it can be set once when constructing `IntegrationRule`s. Then inside your `Eval` method (defining your own class derived from `Coefficient`) you will have the element index from the `ElementTrasnsormation` and the local quadrature point index from the `IntegrationPoint`.

**Comment by ataber** [comment]
Right - I agree this is the cleanest way forward. Would a PR be welcome to add a local index to `IntegrationPoint`?

**Comment by v-dobrev** [comment]
> Would a PR be welcome to add a local index to `IntegrationPoint`?

Yes.

**Comment by IdoAkkerman** [comment]
How would this collocation approach work for NURBS based discretisation? Given the possible smoothness there is a lot of opportunity for the NURBS/ collocation combo.

**Comment by tzanio** [comment]
The original issues is more than a year old now and very likely out of date.

@jehicken, I'll close it now but feel free to reopen and/or post additional questions in new issues.
