### ISSUE TITLE
FormSystemMatrix with PetscParMatrix

### ISSUE THREAD

**Issue by stefanozampini** [mfem/mfem#966]
@v-dobrev 
I don't understand why we can do

```
HypreParMatrix A;
a->FormSystemMatrix(ess_tdof_list, A);

```
But we cannot do

```
PetscParMatrix A;
a->FormSystemMatrix(ess_tdof_list, A);
```

**Comment by v-dobrev** [comment]
The `ParBilinearForm` class has an associated operator type which defaults to `Operator::Hypre_ParCSR`. To get the petsc version working you currently need to call `a->SetOperatorType(Operator::PETSC_MATAIJ)` or another suitable petsc format. This makes sense for petsc because there are multiple options for the internal type used by the class `PetscParMatrix`. We can fix a specific petsc sub-format inside the implementation:

https://github.com/mfem/mfem/blob/3320cb796c0d862bbf025d0bdc4f6cbcb6fde40d/fem/bilinearform.hpp#L392-L400

e.g. by calling `SetOperatorType(A.GetType())` but then only that petsc sub-format will be available. Actually, for `PetscParMatrix` the type returned by the `GetType()` method is not fixed, so this may work with all sub-formats as long as one sets the desired sub-format when creating/initializing the `PetscParMatrix`. One issue is that calling `PetscParMatrix::GetType()` after the default constructor will result in an error since the `PetscParMatrix` object has no associated `Mat` object and `GetType()` will generate an error.

What do you think?

**Comment by tzanio** [comment]
I don't have a strong feeling about this one. @stefanozampini, what do you think?

**Comment by tzanio** [comment]
ping: @stefanozampini, @v-dobrev

**Comment by stefanozampini** [comment]
It was more of a curiosity than a proper issue. Nevertheless, it would be nice to be able to assemble in AIJ format if no type is specified.

**Comment by tzanio** [comment]
Feel free to propose a PR that either fixes a default type or allows us to query that a type has not been set in `FormSystemMatrix`.

Given that there are multiple storage options, the current state of having to call `SetOperatorType` also seem acceptable to me.
