### ISSUE TITLE
Update mfem's Spack package

### ISSUE THREAD

**Issue by tzanio** [mfem/mfem#970]
We need to update the MFEM [Spack package](https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/mfem/package.py) for the mfem-4.0 release.

The minimal requirement for that is:

- [x] Add version 4.0 with `url='https://bit.ly/mfem-4-0'`

It will be even better to support the new device backends

- [ ] Add `cuda` variant, see `MFEM_USE_CUDA`
- [x] Add `occa` variant, see `MFEM_USE_OCCA`
- [x] Add `raja` variant, see `MFEM_USE_RAJA`
- [ ] Add `hpc` variant, see `make hpc`

**Comment by goxberry** [comment]
See https://github.com/spack/spack/pull/11880.

I suspect dependency conflicts need updating. See https://github.com/mfem/mfem/issues/989.

**Comment by goxberry** [comment]
@tzanio @v-dobrev @acfisher I added a couple lower bounds on dependencies, and I also added a conflict when using hypre 2.16.0 and SuperLU 6.1.1 due to issue https://github.com/mfem/mfem/issues/983.

**Comment by goxberry** [comment]
How should `spack install mfem@4.0+cuda+occa+raja+openmp` be distinct from `spack install mfem@4.0+hpc`?

**Comment by goxberry** [comment]
(Paraphrasing from https://github.com/spack/spack/pull/11880)

I have what looks to be a working `mfem@4.0.0` package with `+occa` and `+raja` variants. Due to OS/compiler configuration (macOS 10.14.6/Apple Clang), I can't test CUDA on my laptop at all, and can't test OpenMP easily (would require rebuilding a lot of packages with, e.g., LLVM Clang 8.0.1). I think the current PR is mergeable, except possibly for version requirements of variants I don't typically use (e.g., MPFR, Sundials). Would someone on the MFEM team be willing to review https://github.com/spack/spack/pull/11880? The only thing I need checked are that the version ranges in the `depends_on` statements are correct -- other feedback is welcome, of course, but not essential.

**Comment by goxberry** [comment]
Also, https://github.com/spack/spack/pull/11880 includes a patch from #1043 to fix a Makefile bug I found in #1042.

**Comment by tzanio** [comment]
> How should spack install mfem@4.0+cuda+occa+raja+openmp be distinct from spack install mfem@4.0+hpc?

Currently it should be the same, but the idea is that `+hpc` will enable all possible backends so the users don't need to remember them all.

**Comment by tzanio** [comment]
ping: @acfisher

**Comment by tzanio** [comment]
This is being addressed on an ongoing basis, and in particular will be updated with the next release of the [CEED software distribution](https://ceed.exascaleproject.org/ceed-2.0/)
