### ISSUE TITLE
How to compute integral using BoundaryNormalLFIntegrator

### ISSUE THREAD

**Issue by QikLiang** [mfem/mfem#993]
Hi,

I am following the Volta miniapp and trying to compute the integral of the electric field normal to a surface. To clarify, I have a vector grid function (e_ in volta_solver.cpp), and I want to take the dot product with the vector normal to a boundary, and then integrate it across the boundary. I am trying to do this using the BoundaryNormalLFIntegrator and is confused by what is the QG parameter that it's supposed to take? Is it the electric field? Should I be using another integrator?

My attempt so far below:
```
double VoltaSolver::ComputeCharge(){
      LinearForm lf_bdr(e_->FESpace());
      VectorGridFunctionCoefficient egridfunc(e_);
      lf_bdr.AddBoundaryIntegrator(new BoundaryNormalLFIntegrator(egridfunc));
      lf_bdr.Assemble();
      return lf_bdr(*e_);
   }
```

**Comment by v-dobrev** [comment]
I see two issues:
1. In the definition of `lf_bdr`, instead of `e_->FESpace()` you should use the scalar H1 space, `H1FESpace_`.
2. At the end instead of `lf_bdr(*e_)` you want to return `lf_bdr(ones)` where `ones` can be defined like this:
```c++
      ParGridFunction ones(H1FESpace_);
      ones = 1.0;
```

**Comment by mlstowell** [comment]
Hi, @QikLiang ,

There are a few different ways to accomplish this and I think @v-dobrev 's suggestions are a good choice.  This computation would be a useful addition to `volta` so I wanted to thank you for the idea.  I may try to add this computation starting from `d_` rather than `e_` since we have both fields available.

Thanks again for the idea!

Best wishes,
Mark

**Comment by mlstowell** [comment]
Hi, @QikLiang ,

I just created a pull request #994 which incorporates a charge calculation into the `volta` miniapp.  As I mentioned above, I used `d_` rather than `e_` although I did experiment with both schemes.  Using `d_`, as in the modified miniapp, produces much better results than integrating the normal component of `e_`.  I'm not entirely sure why this is the case but you may want to carefully test your scheme if you decide to use `e_`.

Incidentally, the modified `volta` computes the total charge in two ways which produce essentially the same result.  This redundancy is there for demonstration purposes.  If you decide to reproduce this calculation in your own application you could just choose which ever approach seems most efficient.

Best wishes,
Mark

**Comment by QikLiang** [comment]
Thank you for both of your replies.

@mlstowell For my application, I don't actually need `d_`, so I would prefer using either `e_` or even only using`phi_` if possible to avoid redundant computation.

For the record, the following version seems to work (still testing the output):
```
double VoltaSolver::ComputeCharge(){
   LinearForm lf_bdr(H1FESpace_);
   VectorGridFunctionCoefficient egridfunc(e_);
   Array<int> bdr_attr(pmesh_->bdr_attributes.Max());
   bdr_attr = 0;
   bdr_attr[1] = 1;
   lf_bdr.AddBoundaryIntegrator(new BoundaryNormalLFIntegrator(egridfunc), bdr_attr);
   lf_bdr.Assemble();
   GridFunction ones(H1FESpace_);
   ones = 1.;
   return lf_bdr(ones);
}
```

However, another problem I having is trying to directly compute charge from `phi_` using `GradientGridFunctionCoefficient`. The code is as follows:
```
double VoltaSolver::ComputeCharge2(){
   LinearForm lf_bdr(H1FESpace_);
   GradientGridFunctionCoefficient egridfunc(phi_);
   Array<int> bdr_attr(pmesh_->bdr_attributes.Max());
   bdr_attr = 0;
   bdr_attr[1] = 1;
   lf_bdr.AddBoundaryIntegrator(new BoundaryNormalLFIntegrator(egridfunc), bdr_attr);
   lf_bdr.Assemble();
   GridFunction ones(H1FESpace_);
   ones = -1.;
   return lf_bdr(ones);
}
```
The only difference between the two pieces of code is `VectorGridFunctionCoefficient` of `e_` being replaced by `GradientGridFunctionCoefficient` of `phi_` and a factor of negative one at the bottom. Since `E = - \nabla \phi`, the two functions should have the same output. I projected the second coefficient into a grid function and visualized it with GLVis, and it looks identical to `e_`. Nevertheless, `ComputeCharge2()` returns 0. What is the difference?

**Comment by mlstowell** [comment]
Hi, @QikLiang ,

The trouble here is not obvious.  It is due to the fact that you're trying to integrate over one face of an element so the `GridFunction` is being given a boundary element.  Unfortunately the normal component of the gradient only makes sense if you have access to the volume element.

Best wishes,
Mark

**Comment by mlstowell** [comment]
Hi, @QikLiang ,

I am still concerned about computing the charge from E directly.  To test the charge computation I used one of the sample runs which specifies a charged sphere of a particular total charge, in this case `q=2.0e-11`.  I ran this using first order and second order basis functions (`p=1` and `p=2`):

mpirun -np 4 ./volta -dbcs 1 -cs '0.0 0.5 0.0 0.2 2.0e-11' -o 2

I then plotted the charge as computed by the two methods with the AMR iteration on the horizontal axis:
![image](https://user-images.githubusercontent.com/6109571/60760735-63b02880-9fef-11e9-91cc-ee7b21360001.png)

Note that the `n.D` calculation is poor initially because the mesh is so coarse that the source is not captured well.  As the mesh is refined the `n.D` calculations converge to values with errors on the order of 5% for the p=1 case and less than 1% for the p=2 case.  The `n.E` calculation, on the other hand, shows no sign of converging either as the mesh is refined or when the basis function order is increased.  `n.E` might converge at some point but I wouldn't trust these values until we understand this very poor accuracy.

Best wishes,
Mark

**Comment by QikLiang** [comment]
@mlstowell 

I found out the reason why the value is not converging for my version of the code. 

The call stack when assembling the linear form looks like the following:
`LinearForm::Assemble` tries to assemble the element vector for the ith boundary element
`BoundaryNormalLFIntegrator::AssembleRHSElementVector` evaluates the coefficient at the ith boundary element
`VectorGridFunctionCoefficient::Eval` passes the call to the grid function
`VectorGridFunctionCoefficient::Eval` treats i as the element index instead of boundary index

It seems like `VectorGridFunctionCoefficient` is not expecting to see a boundary element. This boils down to the same problem as the `GradientGridFunctionCoefficient` where a boundary integrator deals with boundaries but the coefficient deals with elements.

What is the right way to fix this? Are there coefficients that work with boundaries correctly? Looking at the parameters it takes, there doesn't seem to be a way to distinguish boundaries and elements. The best way I can think of is to use the mesh to find the element that the boundary is connected to. Is there a built-in way to do that without me looping over the entire boundaries and elements lists?

I see that your PR #994 seems to be solving this by using `VectorFEBoundaryLFIntegrator`, but I couldn't find that constructor in the code or documentation.

**Comment by mlstowell** [comment]
Hi, @QikLiang ,

Sorry about that, we should have seen this coming.  This bug has bitten us before.  It's not exactly a bug in MFEM but it is easy to write seemingly valid code that produces invalid results.  Therefore, it certainly resembles a bug.

 I don't believe our `GridFunction` class offers a way to get a value from a boundary element index.  Consequently, I don't think we can write a `GridFunctionCoefficient` which will work as expected on the boundary.  Part of the problem with this is that for H(Curl) basis functions the degrees of freedom associated with the boundary are, by construction, associated with the tangential part of the vector field.  Therefore, in a sense the portion of the field which is normal to the boundary is not actually associated with the boundary.

The `VectorFEBoundaryLFIntegrator` is a new class added in PR #994 at line 276 of `fem/lining.hpp`.

Please let me know if you still have trouble.

Best wishes,
Mark

**Comment by v-dobrev** [comment]
Hi @QikLiang,

You are right, currently `VectorGridFunctionCoefficient` does not handle the boundary case correctly -- I forgot about that. There is a relatively easy way to fix this -- one can compare the dimensions returned by `ElementTransformation::GetDimension` and `ElementTransformation::GetSpaceDim` and treat the boundary case (when the first dimension, the reference space dimension, is smaller than the second dimension, the physical space dimension). I think @jandrej had this implemented but I'm not sure if it is in any branch at the moment.

In the mean time you should be able to use Mark's code instead -- it is a better solution anyway.


@mlstowell,

How do you compute `n.E`? I do not see code for that in #994. Did you use the approach with the `VectorGridFunctionCoefficient`?

**Comment by mlstowell** [comment]
Hi, @v-dobrev ,

When using the H(Div) field D rather than E the dot product with the normal vector does not show up explicitly.  This is because when integrating over the boundary the `RT_FECollection` gives us an `L2_FiniteElement` which is, by definition, the normal component of the RT basis projected onto the face of the 3D element (or onto the edge between two 2D elements).

Best wishes,
Mark

**Comment by v-dobrev** [comment]
Mark,

I was asking about the plot above where `n.D` converges to the expected value but `n.E` does not. I was wondering how you computed `n.E` there -- just trying to figure out what the issue is.

**Comment by mlstowell** [comment]
Oh, I see.  I computed that using a slightly modified version of @QikLiang 's function which I didn't commit to GitHub:
```
double VoltaSolver::ComputeCharge()
{
   ParLinearForm lf_bdr(H1FESpace_);
   VectorGridFunctionCoefficient egridfunc(e_);
   Array<int> bdr_attr(pmesh_->bdr_attributes.Max());
   bdr_attr = 1;
   lf_bdr.AddBoundaryIntegrator(new BoundaryNormalLFIntegrator(egridfunc), bdr_attr);
   lf_bdr.Assemble();
   ParGridFunction ones(H1FESpace_);
   ones = 1.;
   return epsilon0_ * lf_bdr(ones);
}
```

**Comment by v-dobrev** [comment]
OK, I see. This method has the issue that @QikLiang noticed -- the class `VectorGridFunctionCoefficient` does not work currently with boundary integrators. We can fix this and double check the results again. I'll make a branch with the fix I mentioned above.

**Comment by v-dobrev** [comment]
Hi @mlstowell,

Here is the branch that adds support for using a `VectorGridFunctionCoefficient` in a boundary integrator: https://github.com/mfem/mfem/tree/grid-func-coeffs-on-bdr. Can you re-run your convergence test with it?

**Comment by mlstowell** [comment]
That did fix the problem!  I didn't run the p=2 case beyond 10 AMR iterations but the error was already down to 1% by that point.
![image](https://user-images.githubusercontent.com/6109571/60945004-430dfa00-a29f-11e9-95aa-8151ec993e54.png)
The two charge calculations now track each other quite closely.  For p=1 the `n.D` calculation tends to be better by about 1.5%.  For p=2 the two results differ by less than 0.05%.

Thanks, @v-dobrev !

**Comment by QikLiang** [comment]
@v-dobrev 
I can also confirm that `VectorGridFunctionCoefficient` now converges to the same value as the approach in #994. However, perhaps there should be a new layer of abstraction that solves this systematically? For example, `GridientGridFunctionCoefficient` has a similar problem as well. One approach might be to add a function `Coefficient::EvalBdr` which performs the boundary to element transformation and then calls `Coefficient::Eval`, and all the boundary integrators would call `EvalBdr` instead.

@mlstowell 
Adding to your performance metrics, it seems that the `n.D` computation is about 4~6 times faster than the `n.E` computation.

Since my original problem is solved, I am fine if this issue is closed.

**Comment by mlstowell** [comment]
@QikLiang ,
I'm surprised `n.D` is faster.  This probably didn't include the time needed to compute `D` from `E`, did it?  Incidentally, I was thinking that `volta` is computing two sparse matrices, one for computing `epsilon E` in this process, that are not really necessary.  I'm thinking of replacing these with `ParLinearForm` objects that use `GridFunctionCoefficient`s.  This should be a little faster and much less memory intensive.

Thanks for your interest in this miniapp.  This has been a very useful exchange.
 
Mark

**Comment by QikLiang** [comment]
@mlstowell 
Yes, that didn't include the time to compute `D` from `E`. I went back and computed the run time difference for `VoltaSolver::Solve` with and without `D`, and that exactly made up the difference between the `n.D` and `n.E` calculations. The fastest approach I see is still using `GradientGridFunctionCoefficient` on `phi_` because it avoids creating both `E` or `D`, which I don't need.

Thanks for all your help as well.

**Comment by tzanio** [comment]
@mlstowell, @v-dobrev and @QikLiang -- can we close this issue?

**Comment by QikLiang** [comment]
@tzanio
Yes, this issue can be closed.
